### ISSUE TITLE
JSON error with New-HPOVServerProfile using -ServerProfileTemplate option

### ISSUE THREAD

**Issue by tknightblc** [HewlettPackard/POSH-HPOneView#101]
Seem to be on a roll today. Trying to create a server profile from one of my templates but getting a unrecognized JSON field error. Almost looks liek earlier error where Applianceconnection property is not being removed...

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> Get-HPOVVersion

PowerShell Library Version : 2.0.312.0
Library Path               : C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $PSVersionTable

Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : BuildVersion
Value : 6.3.9600.16406

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $sbl460gen8spt = Get-HPOVServerProfileTemplate "A BL460 Gen8 ESX Template No SAN" -ApplianceConnection $Connection1

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $svr = Get-HPOVServer "Encl1, Bay 3" -ApplianceConnection $Connection1

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $sbl460gen8spt

Name                             Status Server Hardware Type Enclosure Group Affinity Server Profiles
----                             ------ -------------------- --------------- -------- ---------------
A BL460 Gen8 ESX Template No SAN OK     BL460c Gen8 1        ESX-Enclosure   Bay                     

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $svr

Name         Status Power Serial Number Model       ROM            iLO       Server Profile License
----         ------ ----- ------------- -----       ---            ---       -------------- -------
Encl1, bay 3 OK     Off   SGH100X8RN    BL460c Gen8 I31 09/30/2011 iLO4 2.20 No Profile     OneView

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> New-HPOVServerProfile -name "test" -server $svr -ServerProfileTemplate $sbl460gen8spt -ApplianceConnection $Connection1 | Wait-HPOVTaskComplete
New-HPOVServerProfile : Unrecognized JSON field. The field named ApplianceConnection near line 1, column 2,986 is not a valid field in this JSON object.
At line:1 char:1
+ New-HPOVServerProfile -name "test" -server $svr -ServerProfileTemplate $sbl460ge ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [New-HPOVServerProfile], InvalidOperationException
    + FullyQualifiedErrorId : InvalidAuthOperation,New-HPOVServerProfile
 

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $error | % { Format-List -InputObject $_ * } 

PSMessageDetails      : 
Exception             : System.InvalidOperationException: Unrecognized JSON field. The field named ApplianceConnection near line 1, column 2,986 is not a valid field in 
                        this JSON object.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : Send-HPOVRequest
CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationException
FullyQualifiedErrorId : InvalidAuthOperation,Send-HPOVRequest
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5486
                        at New-HPOVServerProfile<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 38447
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "GetResponse" with "0" argument(s): "The remote server returned an 
                        error: (400) Bad Request." ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
                           at System.Net.HttpWebRequest.GetResponse()
                           at CallSite.Target(Closure , CallSite , HttpWebRequest )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : WebException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5085
                        at New-HPOVServerProfile<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 38447
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $error | % { $_.ScriptStackTrace } 
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5486
at New-HPOVServerProfile<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 38447
at <ScriptBlock>, <No file>: line 1
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5085
at New-HPOVServerProfile<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 38447
at <ScriptBlock>, <No file>: line 1

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy>

**Comment by ChrisLynchHPE** [comment]
That should be working.  I fixed an issue where objects that contained the ApplianceConnection property in the root would be removed prior to submitting to the API.  Can you do your call again, but capture the output from it when you include the -Verbose switch to the New-HPOVServerProfile call?

**Comment by tknightblc** [comment]
Will do right now

**Comment by tknightblc** [comment]
Here you go:

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> Import-Module HPOneView.200

         Welcome to the HP OneView POSH Library, v2.0.312.0
         -----------------------------------------------------

To get a list of available CMDLETs in this library, type :  Get-Command -module HPOneView.200
To get help for a specific command, type:                   get-help [verb]-HPOV[noun]
To get extended help for a specific command, type:          get-help [verb]-HPOV[noun] -full
To update the offline help for this module, type:           Update-Help -module HPOneView.200

Module sample scripts are located at: C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\Samples

If you need further help, please consult one of the following:

  • Get-Help about_HPOneView.200
  • Get-Help about_Appliance_Connections
  • Online documentation at https://github.com/HewlettPackard/POSH-HPOneView/wiki
  • Online Issues Tracker at https://github.com/HewlettPackard/POSH-HPOneView/issues

(C) Copyright 2013-2015 Hewlett Packard Enterprise Development LP

Note: Set your PowerShell console width to 150 to properly view report output. (Current Max Width: )


PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $myAppliance = "tk1-ov200-dcsdemo.advizex.net"
$myPassword = "hpinvent"

# this is prompted method
#
#$myAppliance = Read-Host "HP OneView hostname or IP address"
#$myPassword = Read-Host "HP OneView Admin password"
#
# end of prompted method

Write-Host "Connecting to" $myAppliance

$Connection1 = Connect-HPOVMgmt -appliance $myAppliance -User Administrator -password $myPassword

$ConnectedSessions
Connecting to tk1-ov200-dcsdemo.advizex.net
This management appliance is a company owned asset and provided for the exclusive use of authorized personnel. Unauthorized use or abuse of this system may lead to correc
tive action including termination, civil and/or criminal penalties.


ConnectionID Name                          UserName      AuthLoginDomain
------------ ----                          --------      ---------------
1            tk1-ov200-dcsdemo.advizex.net Administrator LOCAL



PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $sbl460gen8spt = Get-HPOVServerProfileTemplate "A BL460 Gen8 ESX Template No SAN" -ApplianceConnection $Connection1

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $svr = Get-HPOVServer "Encl1, Bay 3" -ApplianceConnection $Connection1

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> New-HPOVServerProfile -name "test" -server $svr -ServerProfileTemplate $sbl460gen8spt -Verbose -ApplianceConnection $Connection1 | Wait-HPOVTaskComplete
VERBOSE: [NEW-HPOVSERVERPROFILE] Bound PS Parameters:

Key   : Name
Value : test

Key   : Server
Value : @{type=server-hardware-4; name=Encl1, bay 3; state=NoProfileApplied; stateReason=NotApplicable; assetTag=[Unknown]; category=server-hardware;
        created=2016-03-29T22:44:47.962Z; description=; eTag=1459291659368; formFactor=HalfHeight; intelligentProvisioningVersion=Unknown; licensingIntent=OneView;
        locationUri=/rest/enclosures/09SGH100X6J1; memoryMb=32768; model=ProLiant BL460c Gen8; modified=2016-03-29T22:47:39.368Z; mpFirmwareVersion=2.20 Nov 01 2014;
        mpHostInfo=; mpModel=iLO4; mpState=OK; partNumber=603718-C21; portMap=; position=3; powerLock=False; powerState=Off; processorCoreCount=4; processorCount=2;
        processorSpeedMhz=2400; processorType=Intel(R) Xeon(R) Processor E5620 @ 2.4GHz; refreshState=NotRefreshing; romVersion=I31 09/30/2011; serialNumber=SGH100X8RN;
        serverGroupUri=/rest/enclosure-groups/78dec4f7-c6c2-4def-a612-2c7891ed6a45;
        serverHardwareTypeUri=/rest/server-hardware-types/36F6F819-59A2-4EF7-B3F5-FE99114AA8DF; serverProfileUri=; serverSettings=; shortModel=BL460c Gen8; signature=;
        status=OK; uidState=Unsupported; uri=/rest/server-hardware/37333036-3831-4753-4831-30305838524E; uuid=37333036-3831-4753-4831-30305838524E;
        virtualSerialNumber=; virtualUuid=; ApplianceConnection=}

Key   : ServerProfileTemplate
Value : @{type=ServerProfileTemplateV1; uri=/rest/server-profile-templates/0dee2ad5-7b8f-4ba0-a022-fc24f20fd0c3; name=A BL460 Gen8 ESX Template No SAN;
        description=Template for ESX host-BL460 Gen8 with no SAN storage definitions; serverProfileDescription=;
        serverHardwareTypeUri=/rest/server-hardware-types/36F6F819-59A2-4EF7-B3F5-FE99114AA8DF;
        enclosureGroupUri=/rest/enclosure-groups/78dec4f7-c6c2-4def-a612-2c7891ed6a45; affinity=Bay; hideUnusedFlexNics=True; macType=Virtual; wwnType=Virtual;
        serialNumberType=Virtual; firmware=; connections=System.Object[]; bootMode=; boot=; bios=; localStorage=; sanStorage=; category=server-profile-templates;
        created=2016-04-19T17:34:15.280Z; modified=2016-04-19T17:34:15.299Z; status=OK; state=; eTag=1461087255299/1; ApplianceConnection=}

Key   : Verbose
Value : True

Key   : ApplianceConnection
Value : {tk1-ov200-dcsdemo.advizex.net}




VERBOSE: [NEW-HPOVSERVERPROFILE] Called from: <ScriptBlock>
VERBOSE: [NEW-HPOVSERVERPROFILE] Verify auth
VERBOSE: [TEST-HPOVAUTH] Caller: New-HPOVServerProfile
VERBOSE: [TEST-HPOVAUTH] Verify Auth for HPOneView.Appliance.Connection
VERBOSE: [TEST-HPOVAUTH] $Appliance is [HPOneView.Appliance.Connection]
VERBOSE: [TEST-HPOVAUTH] Recieved HPOneView.Appliance.Connection Object:
ConnectionID Name                          UserName      AuthLoginDomain
------------ ----                          --------      ---------------
1            tk1-ov200-dcsdemo.advizex.net Administrator LOCAL



VERBOSE: [NEW-HPOVSERVERPROFILE] Recieved PSCustomObject for ServerProfileTemplate.
VERBOSE: [NEW-HPOVSERVERPROFILE] Recource Name: A BL460 Gen8 ESX Template No SAN
VERBOSE: [NEW-HPOVSERVERPROFILE] Recource Category: server-profile-templates
VERBOSE: [NEW-HPOVSERVERPROFILE] Processing Server Profile Template: A BL460 Gen8 ESX Template No SAN.
VERBOSE: [NEW-HPOVSERVERPROFILE] Requesting new Server Profile from API.
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:

Key   : Hostname
Value : tk1-ov200-dcsdemo.advizex.net

Key   : uri
Value : /rest/server-profile-templates/0dee2ad5-7b8f-4ba0-a022-fc24f20fd0c3/new-profile




VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [SEND-HPOVREQUEST] Processing 'tk1-ov200-dcsdemo.advizex.net' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/server-profile-templates/0dee2ad5-7b8f-4ba0-a022-fc24f20fd0c3/new-profile' to 'tk1-ov200-dcsdemo.advizex.net'
VERBOSE: [RESTCLIENT] Bound PS Parameters:

Key   : method
Value : GET

Key   : uri
Value : /rest/server-profile-templates/0dee2ad5-7b8f-4ba0-a022-fc24f20fd0c3/new-profile

Key   : Appliance
Value : tk1-ov200-dcsdemo.advizex.net




VERBOSE: [RESTCLIENT] Called from: Send-HPOVRequest
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET https://tk1-ov200-dcsdemo.advizex.net/rest/server-profile-templates/0dee2ad5-7b8f-4ba0-a022-
fc24f20fd0c3/new-profile
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://tk1-ov200-dcsdemo.advizex.net/rest/server-profile-templates/0dee2ad5-7b8f-4ba0-a022-fc24f20fd0c3/new-profile
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 200
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = NzMxNjgyMjE4MTA3QSGeyH2m1qEEhfRrwFr9UE8n39tNRVzw
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 {OK}
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Content-Language = en-us
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Pragma = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Content-Type = application/json;charset=UTF-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 6: Date = Tue, 19 Apr 2016 20:43:17 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 7: Expires = Thu, 01 Jan 1970 00:00:00 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 8: Server = Apache
VERBOSE: [SEND-HPOVREQUEST] Response Header 9: Via = 1.1 example.com
VERBOSE: [SEND-HPOVREQUEST] Response:

type                     : ServerProfileV5
uri                      :
name                     :
description              :
serialNumber             :
uuid                     :
serverProfileTemplateUri : /rest/server-profile-templates/0dee2ad5-7b8f-4ba0-a022-fc24f20fd0c3
templateCompliance       : Unknown
serverHardwareUri        :
serverHardwareTypeUri    : /rest/server-hardware-types/36F6F819-59A2-4EF7-B3F5-FE99114AA8DF
enclosureGroupUri        : /rest/enclosure-groups/78dec4f7-c6c2-4def-a612-2c7891ed6a45
enclosureUri             :
enclosureBay             :
affinity                 : Bay
associatedServer         :
hideUnusedFlexNics       : True
firmware                 : @{firmwareInstallType=FirmwareAndOSDrivers; forceInstallFirmware=False;
                           firmwareBaselineUri=/rest/firmware-drivers/843216_001_spp_2015_10_0-SPP2015100_2015_0921_6; manageFirmware=True}
macType                  : Virtual
wwnType                  : Virtual
serialNumberType         : Virtual
category                 : server-profiles
created                  :
modified                 :
status                   : OK
state                    : Creating
inProgress               : False
taskUri                  :
connections              : {@{id=1; name=; functionType=Ethernet; deploymentStatus=; networkUri=/rest/ethernet-networks/341d18c4-fb07-43ac-a46d-cfd0ff7fe1af; portId=Flb
                           1:1-a; requestedVFs=Auto; allocatedVFs=; interconnectUri=; macType=; wwpnType=; mac=; wwnn=; wwpn=; requestedMbps=1000; allocatedMbps=0;
                           maximumMbps=0; boot=}, @{id=2; name=; functionType=Ethernet; deploymentStatus=;
                           networkUri=/rest/ethernet-networks/229adda7-cedc-4c74-ab5d-03152be01a40; portId=Flb 1:2-a; requestedVFs=Auto; allocatedVFs=;
                           interconnectUri=; macType=; wwpnType=; mac=; wwnn=; wwpn=; requestedMbps=1000; allocatedMbps=0; maximumMbps=0; boot=}, @{id=3; name=;
                           functionType=FibreChannel; deploymentStatus=; networkUri=/rest/fc-networks/12e0d358-e587-4d5a-ab81-da5cec33a950; portId=Flb 1:1-b;
                           requestedVFs=; allocatedVFs=; interconnectUri=; macType=; wwpnType=; mac=; wwnn=; wwpn=; requestedMbps=4000; allocatedMbps=0; maximumMbps=0;
                           boot=}, @{id=4; name=; functionType=FibreChannel; deploymentStatus=; networkUri=/rest/fc-networks/133e89d2-4a37-4144-b55d-cfa054227c53;
                           portId=Flb 1:2-b; requestedVFs=; allocatedVFs=; interconnectUri=; macType=; wwpnType=; mac=; wwnn=; wwpn=; requestedMbps=4000;
                           allocatedMbps=0; maximumMbps=0; boot=}...}
bootMode                 :
boot                     : @{order=System.Object[]; manageBoot=True}
bios                     : @{manageBios=True; overriddenSettings=System.Object[]}
localStorage             : @{controllers=System.Object[]}
sanStorage               : @{volumeAttachments=System.Object[]; manageSanStorage=False}
eTag                     :




VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] Response object, no paging needed.
VERBOSE: [SEND-HPOVREQUEST] Does nextPageUri member exist: False
VERBOSE: [SEND-HPOVREQUEST] Is nextPageUri Null or Empty: True
VERBOSE: [SEND-HPOVREQUEST] Stopping Do/Until loop because nextPageUri doesn't exist and have received all objects.
VERBOSE: [SEND-HPOVREQUEST] END
VERBOSE: [NEW-HPOVSERVERPROFILE] Processing Server parameter.
VERBOSE: [NEW-HPOVSERVERPROFILE] Server is type PSCustomObject.
VERBOSE: [NEW-HPOVSERVERPROFILE] Server Name: Encl1, bay 3
VERBOSE: [NEW-HPOVSERVERPROFILE] Server Uri: /rest/server-hardware/37333036-3831-4753-4831-30305838524E
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:

Key   : Hostname
Value : tk1-ov200-dcsdemo.advizex.net

Key   : uri
Value : /rest/server-profiles

Key   : method
Value : POST

Key   : body
Value : @{type=ServerProfileV5; name=test; description=; serverProfileTemplateUri=/rest/server-profile-templates/0dee2ad5-7b8f-4ba0-a022-fc24f20fd0c3;
        serverHardwareUri=/rest/server-hardware/37333036-3831-4753-4831-30305838524E;
        serverHardwareTypeUri=/rest/server-hardware-types/36F6F819-59A2-4EF7-B3F5-FE99114AA8DF;
        enclosureGroupUri=/rest/enclosure-groups/78dec4f7-c6c2-4def-a612-2c7891ed6a45; enclosureUri=; enclosureBay=; affinity=Bay; hideUnusedFlexNics=True; firmware=;
        macType=Virtual; wwnType=Virtual; serialNumberType=Virtual; connections=System.Object[]; bootMode=; boot=; bios=; localStorage=; sanStorage=;
        ApplianceConnection=}




VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [SEND-HPOVREQUEST] Processing 'tk1-ov200-dcsdemo.advizex.net' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/server-profiles' to 'tk1-ov200-dcsdemo.advizex.net'
VERBOSE: [RESTCLIENT] Bound PS Parameters:

Key   : method
Value : POST

Key   : uri
Value : /rest/server-profiles

Key   : Appliance
Value : tk1-ov200-dcsdemo.advizex.net




VERBOSE: [RESTCLIENT] Called from: Send-HPOVRequest
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for POST https://tk1-ov200-dcsdemo.advizex.net/rest/server-profiles
VERBOSE: [SEND-HPOVREQUEST] Body object found. Converting to JSON.
VERBOSE: [SEND-HPOVREQUEST] Request Body: {"type":"ServerProfileV5","name":"test","description":"","serverProfileTemplateUri":"/rest/server-profile-templates/0dee2ad5-7b8
f-4ba0-a022-fc24f20fd0c3","serverHardwareUri":"/rest/server-hardware/37333036-3831-4753-4831-30305838524E","serverHardwareTypeUri":"/rest/server-hardware-types/36F6F819-5
9A2-4EF7-B3F5-FE99114AA8DF","enclosureGroupUri":"/rest/enclosure-groups/78dec4f7-c6c2-4def-a612-2c7891ed6a45","enclosureUri":null,"enclosureBay":null,"affinity":"Bay","hi
deUnusedFlexNics":true,"firmware":{"firmwareInstallType":"FirmwareAndOSDrivers","forceInstallFirmware":false,"firmwareBaselineUri":"/rest/firmware-drivers/843216_001_spp_
2015_10_0-SPP2015100_2015_0921_6","manageFirmware":true},"macType":"Virtual","wwnType":"Virtual","serialNumberType":"Virtual","connections":[{"id":1,"name":"","functionTy
pe":"Ethernet","networkUri":"/rest/ethernet-networks/341d18c4-fb07-43ac-a46d-cfd0ff7fe1af","portId":"Flb 1:1-a","requestedMbps":"1000","boot":{"priority":"NotBootable"}},
{"id":2,"name":"","functionType":"Ethernet","networkUri":"/rest/ethernet-networks/229adda7-cedc-4c74-ab5d-03152be01a40","portId":"Flb 1:2-a","requestedMbps":"1000","boot"
:{"priority":"NotBootable"}},{"id":3,"name":"","functionType":"FibreChannel","networkUri":"/rest/fc-networks/12e0d358-e587-4d5a-ab81-da5cec33a950","portId":"Flb 1:1-b","r
equestedMbps":"4000","boot":{"priority":"NotBootable"}},{"id":4,"name":"","functionType":"FibreChannel","networkUri":"/rest/fc-networks/133e89d2-4a37-4144-b55d-cfa054227c
53","portId":"Flb 1:2-b","requestedMbps":"4000","boot":{"priority":"NotBootable"}},{"id":5,"name":"","functionType":"Ethernet","networkUri":"/rest/network-sets/3318e854-8
04f-4d2a-bd6b-c94a43885f3c","portId":"Flb 1:1-c","requestedMbps":"3000","boot":{"priority":"NotBootable"}},{"id":6,"name":"","functionType":"Ethernet","networkUri":"/rest
/network-sets/b6d7c640-6e88-4968-a975-2a6dd3572974","portId":"Flb 1:2-c","requestedMbps":"3000","boot":{"priority":"NotBootable"}},{"id":7,"name":"","functionType":"Ether
net","networkUri":"/rest/ethernet-networks/719a645c-6331-4c9f-9240-ada5f0007b44","portId":"Flb 1:1-d","requestedMbps":"2000","boot":{"priority":"NotBootable"}},{"id":8,"n
ame":"","functionType":"Ethernet","networkUri":"/rest/ethernet-networks/43234b10-4ade-439a-bad4-91aa60c8b5f3","portId":"Flb 1:2-d","requestedMbps":"2000","boot":{"priorit
y":"NotBootable"}}],"bootMode":null,"boot":{"order":["CD","Floppy","USB","HardDisk","PXE"],"manageBoot":true},"bios":{"manageBios":true,"overriddenSettings":[{"id":"210",
"value":"3"},{"id":"110","value":"585-451-6254"},{"id":"108","value":"Thomas Knight"},{"id":"140","value":"3"}]},"localStorage":{"controllers":[{"slotNumber":"0","managed
":true,"mode":"RAID","initialize":true,"importConfiguration":false,"logicalDrives":[{"driveNumber":null,"raidLevel":"RAID1","numPhysicalDrives":2,"driveTechnology":"SasHd
d","bootable":false,"driveName":"My local disk"}]}]},"sanStorage":{"volumeAttachments":[],"manageSanStorage":false},"ApplianceConnection":{"ConnectionId":1,"Name":"tk1-ov
200-dcsdemo.advizex.net"}}
VERBOSE: [SEND-HPOVREQUEST] Request: POST https://tk1-ov200-dcsdemo.advizex.net/rest/server-profiles
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 200
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = NzMxNjgyMjE4MTA3QSGeyH2m1qEEhfRrwFr9UE8n39tNRVzw
VERBOSE: [SEND-HPOVREQUEST] Request Header 7: Host = tk1-ov200-dcsdemo.advizex.net
VERBOSE: [SEND-HPOVREQUEST] Net.WebException Error caught
VERBOSE: [SEND-HPOVREQUEST] The remote server returned an error: (400) Bad Request.
VERBOSE: [SEND-HPOVREQUEST] Exception
VERBOSE: [SEND-HPOVREQUEST] Getting Error Response.
VERBOSE: [SEND-HPOVREQUEST] ERROR RESPONSE: {
    "nestedErrors":  [

                     ],
    "details":  "The field named ApplianceConnection near line 1, column 2,986 is not a valid field in this JSON object.",
    "errorSource":  null,
    "recommendedActions":  [
                               "Check the valid fields for this JSON object and remove or correct the unrecognized field."
                           ],
    "data":  {

             },
    "errorCode":  "UNRECOGNIZED_JSON_FIELD",
    "message":  "Unrecognized JSON field."
}

VERBOSE: [SEND-HPOVREQUEST] Response Status: HTTP 400 [Bad Request]
VERBOSE: [SEND-HPOVREQUEST] Response Header: Connection =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Transfer-Encoding =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Cache-Control =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Content-Type =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Date =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Server =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Via =
VERBOSE: [SEND-HPOVREQUEST] HTTP 400 error caught.
VERBOSE: [NEW-ERRORRECORD] Building ErrorRecord object
New-HPOVServerProfile : Unrecognized JSON field. The field named ApplianceConnection near line 1, column 2,986 is not a valid field in this JSON object.
At line:1 char:1
+ New-HPOVServerProfile -name "test" -server $svr -ServerProfileTemplate $sbl460ge ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [New-HPOVServerProfile], InvalidOperationException
    + FullyQualifiedErrorId : InvalidAuthOperation,New-HPOVServerProfile

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy>

**Comment by ChrisLynchHPE** [comment]
Thanks.  I have implemented a more robust method of making sure the `ApplianceConnection` property is removed from objects before submitting to the API.  I have tested it using your Server Profile JSON object you provided, and it works.  I'll be finalizing some other fixes, and will release an update within the next day.

**Comment by tknightblc** [comment]
Thanks very much Chris!

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.368.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.368.0).

Closing.
