### ISSUE TITLE
New-HPOVServerProfileTemplate for DL server returning The value specified for the profile template mac assignment type is not valid or not supported error

### ISSUE THREAD

**Issue by tknightblc** [HewlettPackard/POSH-HPOneView#109]
Trying to create a DL360 Gen9 (or Gen8) server profile template, but status return indicates "The value specified for the profile template mac assignment type is not valid or not supported" and template is not created. Not sure why I am getting this as not doing anything network related in template creation. Verbose output below also in attached word file. 

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> Get-HPOVVersion

PowerShell Library Version : 2.0.404.0
Library Path               : C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $PSVersionTable

Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : BuildVersion
Value : 6.3.9600.16406

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $conListA

id                  : 1
functionType        : Ethernet
name                : 
portId              : Auto
networkUri          : /rest/ethernet-networks/068c4af9-bfe0-4965-b2b9-738dce24eeac
requestedMbps       : 1000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 2
functionType        : Ethernet
name                : 
portId              : Auto
networkUri          : /rest/ethernet-networks/f454b786-57e0-43c9-8311-e5654008e0ed
requestedMbps       : 1000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 3
functionType        : FibreChannel
name                : 
portId              : Auto
networkUri          : /rest/fc-networks/be11adcf-8c5e-4df0-90ba-af1501a1016f
requestedMbps       : 4000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 4
functionType        : FibreChannel
name                : 
portId              : Auto
networkUri          : /rest/fc-networks/89ba9e67-e84d-495d-8d87-ebb2e56ba2ad
requestedMbps       : 4000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 5
functionType        : Ethernet
name                : 
portId              : Auto
networkUri          : /rest/network-sets/6ed8259d-fa3a-483d-86d6-0d47bcc6b40e
requestedMbps       : 3000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 6
functionType        : Ethernet
name                : 
portId              : Auto
networkUri          : /rest/network-sets/6620daab-d64b-4521-bffe-638a344f17a8
requestedMbps       : 3000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 7
functionType        : Ethernet
name                : 
portId              : Auto
networkUri          : /rest/ethernet-networks/cb25f3cc-d1ac-4d3a-9e3a-74627dde51c6
requestedMbps       : 2000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 8
functionType        : Ethernet
name                : 
portId              : Auto
networkUri          : /rest/ethernet-networks/cf46c111-1f38-4720-931d-ffd4179a7a18
requestedMbps       : 2000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $attachVolumesshared

id                     : 2
lun                    : 1
volumeUri              : /rest/storage-volumes/987FD9B9-FF97-41C5-A9DF-F3D49297567B
volumeStoragePoolUri   : /rest/storage-pools/FF9A173E-DAA2-4279-9FF9-D9B571500946
volumeStorageSystemUri : /rest/storage-systems/TXQ1000307
lunType                : Manual
storagePaths           : {}

id                     : 3
lun                    : 2
volumeUri              : /rest/storage-volumes/C32C5335-6F4E-4D51-B4F7-AA96F7E04AB1
volumeStoragePoolUri   : /rest/storage-pools/FF9A173E-DAA2-4279-9FF9-D9B571500946
volumeStorageSystemUri : /rest/storage-systems/TXQ1000307
lunType                : Manual
storagePaths           : {}

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $Gen9BiosSettings

Name  : id
Value : PowerProfile

Name  : value
Value : MaxPerf

Name  : id
Value : AdminName

Name  : value
Value : Thomas Knight

Name  : id
Value : AdminPhone

Name  : value
Value : 585-451-6254

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $eg

Name          Logical Interconnect Group Used By
----          -------------------------- -------
ESX-Enclosure ESX-LIG                    Encl1  

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $bl460Gen9SHT

Name          Model                Form Factor Adapters                                        
----          -----                ----------- --------                                        
BL460c Gen9 1 ProLiant BL460c Gen9 HalfHeight  Flb 1 - HP FlexFabric 10Gb 2-port 536FLB Adapter

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $dl360Gen9SHT

Name         Model               Form Factor Adapters
----         -----               ----------- --------
DL360 Gen9 1 ProLiant DL360 Gen9 1U                  

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> New-HPOVServerProfileTemplate -name "DL360 Gen9 Template" -description "Template for DL360 Gen9" -firmware -baseline "HP Service Pack For ProLiant" -serverHardwareType $dl360Gen8SHT -bios -biossettings $Gen9BiosSettings -ApplianceConnection $Connection1 | Wait-HPOVTaskComplete

Appliance       : tk1-ov200-dcsdemo.advizex.net
Name            : Create 
Owner           : Administrator
Created         : 2016-05-04T20:22:29.909Z
Duratuon        : 00:00:00
TaskState       : Error
Complete        : 100
ProgressUpdates : {}
TaskErrors      : {@{errorSource=; details=; nestedErrors=System.Object[]; recommendedActions=System.Object[]; data=; errorCode=InvalidParameterForTemplateMacType; 
                  message=The value specified for the profile template mac assignment type is not valid or not supported.}}
ParentTaskUri   : 

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> New-HPOVServerProfileTemplate -verbose -name "DL360 Gen9 Template" -description "Template for DL360 Gen9" -firmware -baseline "HP Service Pack For ProLiant" -serverHardwareType $dl360Gen8SHT -bios -biossettings $Gen9BiosSettings -ApplianceConnection $Connection1 | Wait-HPOVTaskComplete

VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] Bound PS Parameters: 

Key   : Verbose
Value : True

Key   : Name
Value : DL360 Gen9 Template

Key   : Description
Value : Template for DL360 Gen9

Key   : Firmware
Value : True

Key   : Baseline
Value : HP Service Pack For ProLiant

Key   : ServerHardwareType
Value : {@{type=server-hardware-type-4; category=server-hardware-types; name=DL360p Gen8 1; description=; 
        uri=/rest/server-hardware-types/D06ED929-07B7-4A5D-B216-7B91E4A78B96; eTag=1462391115499; created=2016-05-04T19:45:15.499Z; modified=2016-05-04T19:45:15.499Z; 
        model=ProLiant DL360p Gen8; formFactor=1U; storageCapabilities=; biosSettings=System.Object[]; bootModes=System.Object[]; pxeBootPolicies=System.Object[]; 
        adapters=System.Object[]; bootCapabilities=System.Object[]; capabilities=System.Object[]; ApplianceConnection=}}

Key   : Bios
Value : True

Key   : BiosSettings
Value : {System.Collections.Hashtable, System.Collections.Hashtable, System.Collections.Hashtable}

Key   : ApplianceConnection
Value : {tk1-ov200-dcsdemo.advizex.net}

VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] Called from: <ScriptBlock>
VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] Verify auth
VERBOSE: [TEST-HPOVAUTH] Caller: New-HPOVServerProfileTemplate
VERBOSE: [TEST-HPOVAUTH] Verify Auth for HPOneView.Appliance.Connection
VERBOSE: [TEST-HPOVAUTH] $Appliance is [HPOneView.Appliance.Connection]
VERBOSE: [TEST-HPOVAUTH] Recieved HPOneView.Appliance.Connection Object: 
ConnectionID Name                          UserName      AuthLoginDomain
------------ ----                          --------      ---------------
1            tk1-ov200-dcsdemo.advizex.net Administrator LOCAL          

VERBOSE: [NEWOBJECT] Bound PS Parameters: 

Key   : ServerProfileTemplate
Value : True

VERBOSE: [NEWOBJECT] Called from: New-HPOVServerProfileTemplate
VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] ServerHardwareType object provided
VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] ServerHardwareType Name: DL360p Gen8 1
VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] ServerHardwareType Uri: /rest/server-hardware-types/D06ED929-07B7-4A5D-B216-7B91E4A78B96
VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] Server is a ProLiant DL model. Enclosure Group not required.
VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] Server Hardware Type is a DL, setting 'macType', 'wwnType', 'serialNumberType', 'affinity' and 'hideUnusedFlexNics' to Null.
VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] 
VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] Firmware Baseline HP Service Pack For ProLiant
VERBOSE: [GET-HPOVBASELINE] Bound PS Parameters: 

Key   : SppName
Value : HP Service Pack For ProLiant

Key   : ApplianceConnection
Value : {tk1-ov200-dcsdemo.advizex.net}

VERBOSE: [GET-HPOVBASELINE] Called from: New-HPOVServerProfileTemplate
VERBOSE: [GET-HPOVBASELINE] Verify auth
VERBOSE: [TEST-HPOVAUTH] Caller: Get-HPOVBaseline
VERBOSE: [TEST-HPOVAUTH] Verify Auth for HPOneView.Appliance.Connection
VERBOSE: [TEST-HPOVAUTH] $Appliance is [HPOneView.Appliance.Connection]
VERBOSE: [TEST-HPOVAUTH] Recieved HPOneView.Appliance.Connection Object: 
ConnectionID Name                          UserName      AuthLoginDomain
------------ ----                          --------      ---------------
1            tk1-ov200-dcsdemo.advizex.net Administrator LOCAL          

VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters: 

Key   : Hostname
Value : HPOneView.Appliance.Connection

Key   : uri
Value : /rest/firmware-drivers

VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [SEND-HPOVREQUEST] Processing 'tk1-ov200-dcsdemo.advizex.net' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/firmware-drivers' to 'tk1-ov200-dcsdemo.advizex.net'
VERBOSE: [RESTCLIENT] Bound PS Parameters: 

Key   : method
Value : GET

Key   : uri
Value : /rest/firmware-drivers

Key   : Appliance
Value : tk1-ov200-dcsdemo.advizex.net

VERBOSE: [RESTCLIENT] Called from: Send-HPOVRequest
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET https://tk1-ov200-dcsdemo.advizex.net/rest/firmware-drivers
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://tk1-ov200-dcsdemo.advizex.net/rest/firmware-drivers
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 200
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = [*****REDACTED******]
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 {OK}
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Content-Type = application/json;charset=UTF-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Date = Wed, 04 May 2016 20:22:53 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Server = Apache
VERBOSE: [SEND-HPOVREQUEST] Response Header 6: Via = 1.1 example.com
VERBOSE: [SEND-HPOVREQUEST] Response: 

type        : firmware-baseline-list
members     : {@{bundleType=SPP; resourceId=843216_001_spp_2015_10_0-SPP2015100_2015_0921_6; uuid=843216_001_spp_2015_10_0-SPP2015100_2015_0921_6; xmlKeyName=bp002598; 
              isoFileName=843216_001_spp_2015_10_0-SPP2015100_2015_0921_6.iso; baselineShortName=SPP 2015.10.0; bundleSize=5502076928; version=2015.10.0; 
              releaseDate=2015-09-27T11:35:34.779Z; supportedOSList=System.Object[]; supportedLanguages=English (US), Japanese, Chinese (Simplified); 
              fwComponents=System.Object[]; swPackagesFullPath=/mnt/fwbundles/843216_001_spp_2015_10_0-SPP2015100_2015_0921_6/hp/swpackages/; state=Created; 
              lastTaskUri=/rest/tasks/DEB67F4C-EFDB-48FC-9C7A-2C5614A229B8; hpsumVersion=740_b41; description=HP Service Pack for ProLiant (SPP) is a comprehensive 
              systems software and firmware update solution, which is delivered as a single ISO image. This solution uses HP Smart Update Manager (HP SUM) as the 
              deployment tool and is tested on all HP ProLiant Gen9, Gen8 and earlier servers as defined in the Service Pack for ProLiant Server Support Guide found at 
              www.hp.com/go/spp/documentation.; status=OK; name=HP Service Pack for ProLiant; category=firmware-drivers; created=2015-12-28T14:32:03.000Z; 
              modified=2015-12-28T14:35:02.196Z; eTag=2015-12-28T14:35:02.196Z; uri=/rest/firmware-drivers/843216_001_spp_2015_10_0-SPP2015100_2015_0921_6}}
count       : 1
total       : 1
nextPageUri : 
start       : 0
prevPageUri : 
category    : firmware-drivers
created     : 2016-05-04T20:22:53.230Z
modified    : 2016-05-04T20:22:53.230Z
eTag        : 2016-05-04T20:22:53.230Z
uri         : /rest/firmware-drivers?start=0&count=1

VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] Response members and automatic pagination
VERBOSE: total stored '1'
VERBOSE: nextPageURI: ''
VERBOSE: [SEND-HPOVREQUEST] Reached end of pagination. Building AllResults
VERBOSE: [SEND-HPOVREQUEST] Does nextPageUri member exist: True
VERBOSE: [SEND-HPOVREQUEST] Is nextPageUri Null or Empty: True
VERBOSE: [SEND-HPOVREQUEST] Stopping Do/Until loop because nextPageUri is null/empty and have received all objects.
VERBOSE: [SEND-HPOVREQUEST] END
VERBOSE: [GET-HPOVBASELINE] SppName parameter provided: HP Service Pack For ProLiant
VERBOSE: [GET-HPOVBASELINE] Version parameter provided: 
VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] Profile JSON Object: {
    "type":  "ServerProfileTemplateV1",
    "name":  "DL360 Gen9 Template",
    "description":  "Template for DL360 Gen9",
    "serverProfileDescription":  null,
    "affinity":  null,
    "hideUnusedFlexNics":  null,
    "bios":  {
                 "manageBios":  true,
                 "overriddenSettings":  [
                                            {
                                                "id":  "PowerProfile",
                                                "value":  "MaxPerf"
                                            },
                                            {
                                                "id":  "AdminName",
                                                "value":  "Thomas Knight"
                                            },
                                            {
                                                "id":  "AdminPhone",
                                                "value":  "585-451-6254"
                                            }
                                        ]
             },
    "firmware":  {
                     "manageFirmware":  true,
                     "firmwareBaselineUri":  "/rest/firmware-drivers/843216_001_spp_2015_10_0-SPP2015100_2015_0921_6",
                     "forceInstallFirmware":  false,
                     "firmwareInstallType":  "FirmwareAndOSDrivers"
                 },
    "boot":  {
                 "manageBoot":  false,
                 "order":  [

                           ]
             },
    "bootMode":  null,
    "localStorage":  {
                         "controllers":  [

                                         ]
                     },
    "serialNumberType":  null,
    "macType":  null,
    "wwnType":  null,
    "connections":  [

                    ],
    "serverHardwareTypeUri":  "/rest/server-hardware-types/D06ED929-07B7-4A5D-B216-7B91E4A78B96",
    "enclosureGroupUri":  null,
    "sanStorage":  null
}
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters: 

Key   : uri
Value : /rest/server-profile-templates

Key   : Hostname
Value : tk1-ov200-dcsdemo.advizex.net

Key   : method
Value : POST

Key   : body
Value : @{type=ServerProfileTemplateV1; name=DL360 Gen9 Template; description=Template for DL360 Gen9; serverProfileDescription=; affinity=; hideUnusedFlexNics=; bios=; 
        firmware=; boot=; bootMode=; localStorage=; serialNumberType=; macType=; wwnType=; connections=System.Collections.ArrayList; 
        serverHardwareTypeUri=/rest/server-hardware-types/D06ED929-07B7-4A5D-B216-7B91E4A78B96; enclosureGroupUri=; sanStorage=}

VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [SEND-HPOVREQUEST] Processing 'tk1-ov200-dcsdemo.advizex.net' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/server-profile-templates' to 'tk1-ov200-dcsdemo.advizex.net'
VERBOSE: [RESTCLIENT] Bound PS Parameters: 

Key   : method
Value : POST

Key   : uri
Value : /rest/server-profile-templates

Key   : Appliance
Value : tk1-ov200-dcsdemo.advizex.net

VERBOSE: [RESTCLIENT] Called from: Send-HPOVRequest
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for POST https://tk1-ov200-dcsdemo.advizex.net/rest/server-profile-templates
VERBOSE: [SEND-HPOVREQUEST] Body object found. Converting to JSON.
VERBOSE: [SEND-HPOVREQUEST] HTTP Method is POST. Removing 'ApplianceConnection' NoteProperty from object(s).
VERBOSE: InputObject is [PSCustomObject]. Copying...
VERBOSE: InputObject is [PSCustomObject]. Copying...
VERBOSE: Property is IEnumerable
VERBOSE: InputObject is [PSCustomObject]. Copying...
VERBOSE: InputObject is [PSCustomObject]. Copying...
VERBOSE: Property is IEnumerable
VERBOSE: InputObject is [PSCustomObject]. Copying...
VERBOSE: Property is IEnumerable
VERBOSE: Property is IEnumerable
VERBOSE: [SEND-HPOVREQUEST] Request Body: {"type":"ServerProfileTemplateV1","name":"DL360 Gen9 Template","description":"Template for DL360 Gen9","serverProfileDescription
":null,"affinity":null,"hideUnusedFlexNics":null,"bios":{"manageBios":true,"overriddenSettings":[{"id":"PowerProfile","value":"MaxPerf"},{"id":"AdminName","value":"Thomas
 Knight"},{"id":"AdminPhone","value":"585-451-6254"}]},"firmware":{"manageFirmware":true,"firmwareBaselineUri":"/rest/firmware-drivers/843216_001_spp_2015_10_0-SPP2015100
_2015_0921_6","forceInstallFirmware":false,"firmwareInstallType":"FirmwareAndOSDrivers"},"boot":{"manageBoot":false,"order":[]},"bootMode":null,"localStorage":{"controlle
rs":[]},"serialNumberType":null,"macType":null,"wwnType":null,"connections":[],"serverHardwareTypeUri":"/rest/server-hardware-types/D06ED929-07B7-4A5D-B216-7B91E4A78B96",
"enclosureGroupUri":null,"sanStorage":null}
VERBOSE: [SEND-HPOVREQUEST] Request: POST https://tk1-ov200-dcsdemo.advizex.net/rest/server-profile-templates
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 200
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = [*****REDACTED******]
VERBOSE: [SEND-HPOVREQUEST] Request Header 7: Host = tk1-ov200-dcsdemo.advizex.net
VERBOSE: [SEND-HPOVREQUEST] Response Status: 202 {Accepted}
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Content-Length = 0
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Date = Wed, 04 May 2016 20:22:53 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Location = /rest/tasks/C962341E-6416-41AF-B945-E75FE83D5006
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Server = Apache
VERBOSE: [SEND-HPOVREQUEST] Response Header 6: Via = 1.1 example.com
VERBOSE: [SEND-HPOVREQUEST] Response: 
VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] Async Task (HTTP 202) received
VERBOSE: [SEND-HPOVREQUEST] Async Task Location found in HTTP headers: /rest/tasks/C962341E-6416-41AF-B945-E75FE83D5006
VERBOSE: [SEND-HPOVREQUEST] Getting Task Resource Object to return to caller.
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters: 

Key   : Hostname
Value : tk1-ov200-dcsdemo.advizex.net

Key   : uri
Value : /rest/tasks/C962341E-6416-41AF-B945-E75FE83D5006

Key   : method
Value : GET

VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [SEND-HPOVREQUEST] Processing 'tk1-ov200-dcsdemo.advizex.net' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/tasks/C962341E-6416-41AF-B945-E75FE83D5006' to 'tk1-ov200-dcsdemo.advizex.net'
VERBOSE: [RESTCLIENT] Bound PS Parameters: 

Key   : method
Value : GET

Key   : uri
Value : /rest/tasks/C962341E-6416-41AF-B945-E75FE83D5006

Key   : Appliance
Value : tk1-ov200-dcsdemo.advizex.net

VERBOSE: [RESTCLIENT] Called from: Send-HPOVRequest
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET https://tk1-ov200-dcsdemo.advizex.net/rest/tasks/C962341E-6416-41AF-B945-E75FE83D5006
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://tk1-ov200-dcsdemo.advizex.net/rest/tasks/C962341E-6416-41AF-B945-E75FE83D5006
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 200
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = [*****REDACTED******]
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 {OK}
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Content-Language = en-us
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Pragma = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Content-Type = application/json;charset=UTF-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 6: Date = Wed, 04 May 2016 20:22:53 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 7: Expires = Thu, 01 Jan 1970 00:00:00 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 8: ETag = 1
VERBOSE: [SEND-HPOVREQUEST] Response Header 9: Server = Apache
VERBOSE: [SEND-HPOVREQUEST] Response Header 10: Via = 1.1 example.com
VERBOSE: [SEND-HPOVREQUEST] Response: 

type                    : TaskResourceV2
taskType                : User
stateReason             : Starting
associatedResource      : @{resourceUri=; resourceCategory=server-profile-templates; associationType=MANAGED_BY; resourceName=}
hidden                  : False
category                : tasks
data                    : 
taskErrors              : {}
taskOutput              : {}
percentComplete         : 0
taskState               : Starting
taskStatus              : Creating server profile template
parentTaskUri           : 
associatedTaskUri       : 
completedSteps          : 0
computedPercentComplete : 0
expectedDuration        : 0
progressUpdates         : {}
totalSteps              : 0
userInitiated           : False
name                    : Create 
owner                   : Administrator
eTag                    : 1
created                 : 2016-05-04T20:22:53.370Z
modified                : 2016-05-04T20:22:53.389Z
uri                     : /rest/tasks/C962341E-6416-41AF-B945-E75FE83D5006

VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] Response object, no paging needed.
VERBOSE: [SEND-HPOVREQUEST] Does nextPageUri member exist: False
VERBOSE: [SEND-HPOVREQUEST] Is nextPageUri Null or Empty: True
VERBOSE: [SEND-HPOVREQUEST] Stopping Do/Until loop because nextPageUri doesn't exist and have received all objects.
VERBOSE: [SEND-HPOVREQUEST] END
VERBOSE: [SEND-HPOVREQUEST] Adding 'HPOneView.Appliance.TaskResource' to PSObject TypeNames for task object
VERBOSE: [SEND-HPOVREQUEST] Response object, no paging needed.
VERBOSE: [SEND-HPOVREQUEST] Does nextPageUri member exist: False
VERBOSE: [SEND-HPOVREQUEST] Is nextPageUri Null or Empty: True
VERBOSE: [SEND-HPOVREQUEST] Stopping Do/Until loop because nextPageUri doesn't exist and have received all objects.
VERBOSE: [SEND-HPOVREQUEST] END

Appliance       : tk1-ov200-dcsdemo.advizex.net
Name            : Create 
Owner           : Administrator
Created         : 2016-05-04T20:22:53.370Z
Duratuon        : 00:00:00
TaskState       : Error
Complete        : 100
ProgressUpdates : {}
TaskErrors      : {@{errorSource=; details=; nestedErrors=System.Object[]; recommendedActions=System.Object[]; data=; errorCode=InvalidParameterForTemplateMacType; 
                  message=The value specified for the profile template mac assignment type is not valid or not supported.}}
ParentTaskUri   : 

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $error | % { Format-List -InputObject $_ * } 

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $error | % { $_.ScriptStackTrace } 

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> 
[OV Issue with DL server Profile Template.docx](https://github.com/HewlettPackard/POSH-HPOneView/files/249519/OV.Issue.with.DL.server.Profile.Template.docx)
[OV Issue with DL server Profile Template.docx](https://github.com/HewlettPackard/POSH-HPOneView/files/249520/OV.Issue.with.DL.server.Profile.Template.docx)

**Comment by ChrisLynchHPE** [comment]
This is already fixed in a release I'm pushing out later tonight.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.414.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.414.0).

Closing.
