### ISSUE TITLE
POSH 1.20.0050 issue with New-HPOVNetwork command

### ISSUE THREAD

**Issue by huberm001** [HewlettPackard/POSH-HPOneView#11]
Hi,

the 'New-HPOVNetwork' command doesn't work in the latest POSH-Library!

Try 'get-help New-HPOVNetwork' and you will see the error that is also returned when I tried to create
a network:

"Property 'Position' cannot be found for type 'System.Management.Automation.ValidateSetAttribute'"

BR

**Comment by ChrisLynchHP** [comment]
Unfortunately, this is a known issue that was found yesterday.  I have it fixed, and will be in an update I'll get out later today.  Just adding some other fixes to the library.

**Comment by ChrisLynchHP** [comment]
This was fixed in the 1.20.0077 release.
