### ISSUE TITLE
Add-HPOVSanManager cannot add HPN5930

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#112]
Please fill in as much information as possible to help resolve your issue.

### Description
I cannot add an HPN 5930 switch using Add-HPOVSanManager.  It appears that you are failing to correctly pass "SnmpAuthLevel"  in the JSON.  As you can see in my command line (see Steps to reproduce), I am passing an SnmpAuthLevel of AuthAndPriv.  However, as shown in the verbose output, the JSON you are passing contains the following:

{"name":"SnmpAuthLevel","Value":null}

### Expected Behavior
Successfully add an HPN 5930 switch as a SAN Manager

### Actual Behavior
**Device fails to add with:**
Cannot convert argument "errorRecord", with value: "System.InvalidOperationException: SNMPv3 security level is empty. 
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)", for "ThrowTerminatingError" to type "System.Management.Automation.ErrorRecord": "Cannot convert the 
"System.InvalidOperationException: SNMPv3 security level is empty. 
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)" value of type "System.InvalidOperationException" to type "System.Management.Automation.ErrorRecord"."
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:24935 char:8
+                 $PsCmdlet.ThrowTerminatingError($errorRecord)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument 

### Steps to reproduce
Add-HPOVSanManager -Type HP -Hostname <HPN5930 IP> -Username <HPN5930 admin username> -Password <HPN5930 admin password> -SnmpUserName <SNMP username> -SnmpAuthLevel AuthAndPriv -SnmpAuthProtocol sha -SnmpAuthPassword <SNMP Auth password> -SnmpPrivProtocol aes-128 -SnmpPrivPassword <SNMP Priv password> -ApplianceConnection $OVConnection –Verbose

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.414.0
HPE OneView Appliance Version:   2.00.06-0241397 
Output from `$PSVersionTable` on your Windows Host:
Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : BuildVersion
Value : 6.3.9600.17400

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

**Comment by ChrisLynchHPE** [comment]
Issue identified and will be fixed in the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.430.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.430.0).
