### ISSUE TITLE
New-HPOVNetwork has an incomplete parameter set for FCOE networks

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#113]
### Expected Behavior
New-HPOVNetwork should be able to configure all applicable parameters for an FCOE network

### Actual Behavior
The affiliated parameter set is missing [at least] the following parameters:
[-typicalBandwidth [<Int32>]]
[-maximumBandwidth [<Int32>]]

### Steps to reproduce
Get-Help New-HPOVNetwork
**New-HPOVNetwork [-Name] <Name> [[-Type] [<Type>]] [-VlanId] <VlanId> [[-ManagedSan] [<ManagedSan>]] [-ApplianceConnection [<ApplianceConnection>]] [<CommonParameters>]**

### Version Information
HPE OneView PowerShell Library Version ( Get-HPOVVersion ): 2.0.414.0
 HPE OneView Appliance Version: 2.00.06-0241397 
 Output from  $PSVersionTable  on your Windows Host:
 Name : PSVersion
 Value : 4.0

Name : WSManStackVersion
 Value : 3.0

Name : SerializationVersion
 Value : 1.1.0.1

Name : CLRVersion
 Value : 4.0.30319.42000

Name : BuildVersion
 Value : 6.3.9600.17400

Name : PSCompatibleVersions
 Value : {1.0, 2.0, 3.0, 4.0}

Name : PSRemotingProtocolVersion
 Value : 2.2

**Comment by ChrisLynchHPE** [comment]
Issue identified and will be fixed in the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.430.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.430.0).
