### ISSUE TITLE
New-HPOVServerProfileAttachVolume cannot attach existing volume to existing server profile

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#114]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Existing volume can be attached to existing server profile that is currently unassigned

### Actual Behavior
New-HPOVServerProfileAttachVolume : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg.
/rest/server-hardware) in its value. Please correct the value and try again.
At line:1 char:1
+ New-HPOVServerProfileAttachVolume -ServerProfile $MyProfile -Volume $MyVolume -V ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-HPOVServerProfileAttachVolume], ParameterBindingValidationExceptio
   n
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-HPOVServerProfileAttachVolume

### Steps to reproduce
New-HPOVServerProfileAttachVolume -ServerProfile $MyProfile -Volume $MyVolume -VolumeID 0

### Version Information
HPE OneView PowerShell Library Version ( Get-HPOVVersion ): 2.0.414.0
 HPE OneView Appliance Version: 2.00.06-0241397 
 Output from $PSVersionTable on your Windows Host:
 Name : PSVersion
 Value : 4.0

Name : WSManStackVersion
 Value : 3.0

Name : SerializationVersion
 Value : 1.1.0.1

Name : CLRVersion
 Value : 4.0.30319.42000

Name : BuildVersion
 Value : 6.3.9600.17400

Name : PSCompatibleVersions
 Value : {1.0, 2.0, 3.0, 4.0}

Name : PSRemotingProtocolVersion
 Value : 2.2

### Verbose Output
VERBOSE: [NEW-HPOVSERVERPROFILEATTACHVOLUME] Bound PS Parameters:

Key   : ServerProfile
Value : @{type=ServerProfileV5; uri=/rest/server-profiles/f66c40f7-ed22-45c1-bc0b-dd30453fafab; name=TEST;
        description=; serialNumber=VCGGLZB00U; uuid=f66c40f7-ed22-45c1-bc0b-dd30453fafab; serverProfileTemplateUri=;
        templateCompliance=Unknown; serverHardwareUri=;
        serverHardwareTypeUri=/rest/server-hardware-types/57F5EAB1-FF6D-49DF-8A5A-123BC48E72FD;
        enclosureGroupUri=/rest/enclosure-groups/9e29f708-73c5-47a4-980e-96e4beae1149; enclosureUri=; enclosureBay=;
        affinity=Bay; associatedServer=; hideUnusedFlexNics=True; firmware=; macType=Virtual; wwnType=Virtual;
        serialNumberType=Virtual; category=server-profiles; created=20160510T201007.384Z;
        modified=20160510T201009.133Z; status=OK; state=Normal; inProgress=False;
        taskUri=/rest/tasks/91B7AEBC-F7B8-4DD6-9CFF-547D8F7C3B4B; connections=System.Object[]; bootMode=; boot=;
        bios=; localStorage=; sanStorage=; eTag=1462911007795/3; ApplianceConnection=}

Key   : Volume
Value : @{type=StorageVolumeV3; snapshots=; isPermanent=True;
        storagePoolUri=/rest/storage-pools/35966D02-E191-4D08-8AF2-36A48CC31688; provisionType=Thin; shareable=True;
        snapshotPoolUri=; provisionedCapacity=1073741824; deviceVolumeName=MyTestSharedVolume;
        allocatedCapacity=671088640; revertToSnapshotUri=; deviceType=FC; raidLevel=RAID5;
        wwn=60:00:2A:C0:00:00:00:00:00:00:01:5A:00:00:2F:FD; storageSystemUri=/rest/storage-systems/1612285;
        stateReason=None; refreshState=NotRefreshing; name=MyTestSharedVolume; state=Configured; description=This is a

        test shareed volume; status=OK; created=2016-05-10T20:41:21.055Z; modified=2016-05-10T20:41:21.920Z;
        eTag=2016-05-10T20:41:21.920Z; category=storage-volumes;
        uri=/rest/storage-volumes/83451D92-E124-477B-B808-BE0017AA54F3; ApplianceConnection=}

Key   : VolumeID
Value : 0

Key   : Verbose
Value : True

VERBOSE: [NEW-HPOVSERVERPROFILEATTACHVOLUME] Called from: <ScriptBlock>
VERBOSE: [NEW-HPOVSERVERPROFILEATTACHVOLUME] Verify auth
VERBOSE: [TEST-HPOVAUTH] Caller: New-HPOVServerProfileAttachVolume
VERBOSE: [TEST-HPOVAUTH] Verify Auth for HPOneView.Appliance.Connection
VERBOSE: [TEST-HPOVAUTH] $Appliance is [HPOneView.Appliance.Connection]
VERBOSE: [TEST-HPOVAUTH] Recieved HPOneView.Appliance.Connection Object:
ConnectionID Name        UserName      AuthLoginDomain
------------ ----        --------      ---------------
1            172.28.10.1 Administrator LOCAL

VERBOSE: [NEWOBJECT] Bound PS Parameters:

Key   : ServerProfileStorageVolume
Value : True

VERBOSE: [NEWOBJECT] Called from: New-HPOVServerProfileAttachVolume
VERBOSE: [NEW-HPOVSERVERPROFILEATTACHVOLUME] No VolumeID value provided.  Getting next volume id value.

**Comment by ChrisLynchHPE** [comment]
Issue identified and will be fixed in the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.430.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.430.0).
