### ISSUE TITLE
New-HPOVQosConfig

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#116]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
An object would be returned without 12 errors being generated prior to the object being returned:

### Actual Behavior
The following 12 errors are output:
The property 'uplinkClassificationType' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:36558 char:5
+                 $_QosConfigurationObject.uplinkClassificationType   = $UplinkClassificationT ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

The property 'downlinkClassificationType' cannot be found on this object. Verify that the property exists and can be
set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:36559 char:5
+                 $_QosConfigurationObject.downlinkClassificationType = $DownlinkClassificatio ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

The property 'qosTrafficClassifiers' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:36618 char:6
+                     $_QosConfigurationObject.qosTrafficClassifiers = NewObject -DefaultFCoELoss ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

You cannot call a method on a null-valued expression.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:36636 char:5
+                 $_.PSObject.TypeNames.Insert(0,'HPOneView.Networking.Qos.TrafficClassifier')
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:36636 char:5
+                 $_.PSObject.TypeNames.Insert(0,'HPOneView.Networking.Qos.TrafficClassifier')
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:36636 char:5
+                 $_.PSObject.TypeNames.Insert(0,'HPOneView.Networking.Qos.TrafficClassifier')
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:36636 char:5
+                 $_.PSObject.TypeNames.Insert(0,'HPOneView.Networking.Qos.TrafficClassifier')
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:36636 char:5
+                 $_.PSObject.TypeNames.Insert(0,'HPOneView.Networking.Qos.TrafficClassifier')
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:36636 char:5
+                 $_.PSObject.TypeNames.Insert(0,'HPOneView.Networking.Qos.TrafficClassifier')
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:36636 char:5
+                 $_.PSObject.TypeNames.Insert(0,'HPOneView.Networking.Qos.TrafficClassifier')
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:36636 char:5
+                 $_.PSObject.TypeNames.Insert(0,'HPOneView.Networking.Qos.TrafficClassifier')
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

### Steps to reproduce
 New-HPOVQosConfig -ConfigType CustomWithFCoE -UplinkClassificationType DOT1P -DownlinkClassificationType DOT1P_AND_DSCP

**Comment by ChrisLynchHPE** [comment]
Thanks.  Looking into this.

**Comment by ChrisLynchHPE** [comment]
This is fixed, and will be in the next 2.00 release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.435.1](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.435.1).

Closing.
