### ISSUE TITLE
Recreation of FC connection without rezoning SAN

### ISSUE THREAD

**Issue by 5truja** [HewlettPackard/POSH-HPOneView#117]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Hi Chris,
I would like to change my serverprofiles having existing zoning etc since I need two tunnels instead of one that I have now.
I have 8 connections (ETH: 4 SUS and 2 Tunnel, SAN FC: 2 connections).
However I need to change server profiles but would like to recreate FC connections (Mezzanine HBA non-FLEX) by keeping the very same wwpn and wwnn in order to avoid rezoning of SAN. I thought to use the following command for that:

PS C:\> $con41 =  Get-HPOVNetwork 'Fabric A' | New-HPOVServerProfileConnection -connectionId 3 -connectionType FibreChannel -userdefined -mac 11:22:33:44:55:66 -wwpn 10:00:00:00:a1:55:1b:8f -wwnn 20:00:00:00:a1:55:1b:8f -name "VC FF Fabric A Connection"

The thing is that above mentioned wwpn and wwnn are not "userdefined" and I am wondering if this command could be used to recreate wwpn and wwnn from the same "range"?

I am not sure if virtual and oneview-generated range for wwpn and wwnn could be recreated "manually" (-userdefined) or if "userdefined" has its own "specific" range (which basically means that I need to ask for rezoning of all disks.

### Actual Behavior
According to this I am assume that recreation of existing wwpn and wwnn is possible:
http://h17007.www1.hpe.com/docs/enterprise/servers/oneview2.0/cic-rest/en/content/s_create-server_profile_userids-sdk.html

but I don't get this part: "then copy the virtual IDs that you need from that profile"

### Steps to reproduce
Is it possible to keep profile, delete connections and than add connections with same wwpn and wwnn?

Or delete profile and than use New-HPOVServerProfileConnection command with -userdefined switch?

Or if I delete one profile and wwpn and wwnn are released, are very same released wwpn and wwnn assigned to me by default.

Trying to compare with VCM/VCEM behaviour...

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
If you specify a valid address that is within a defined Address Pool, OneView will mark that address as consumed.

**Comment by 5truja** [comment]
But if I delete that profile and create it from scratch? Is it possible to assign the very same MAC, wwpn and wwnn even when using -userdefined switch?

Med v?nlig h?lsning,
Mladen Brekalo


14 juni 2016 kl. 18:43 skrev Chris Lynch <notifications@github.com<mailto:notifications@github.com>>:


If you specify a valid address that is within a defined Address Pool, OneView will mark that address as consumed.

-

**Comment by ChrisLynchHPE** [comment]
Yes.

**Comment by 5truja** [comment]
Great!

Med v?nlig h?lsning,
Mladen Brekalo


14 juni 2016 kl. 18:48 skrev Chris Lynch <notifications@github.com<mailto:notifications@github.com>>:


Yes.

-

**Comment by ChrisLynchHPE** [comment]
Closing this issue.  If you feel that it isn't resolved, please open a new issue.
