### ISSUE TITLE
POSH 1.20.0077 issue New-HPOVNetwork

### ISSUE THREAD

**Issue by huberm001** [HewlettPackard/POSH-HPOneView#12]
Hi,

there is a issue with the New-HPOVNetwork cmdlet.

Adding Ethernet Networks returns an error - the network gets although created.

Command (from get-help):
New-HPOVNetwork -type Ethernet -name MyNetwork1 -vlanid 100

Error:
New-Object : Cannot find type [[HPOneView.EthernetNetwork]]: make sure the assembly containing this type is loaded.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.120\HPOneView.120.psm1:11764 char:32

BR

**Comment by ChrisLynchHP** [comment]
Unfortunately, this is a known error.  A fix for this will be released within the next 24hrs.

**Comment by ChrisLynchHP** [comment]
This is fixed in [Release 1.10.0078](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v1.20.0078.0).
