### ISSUE TITLE
Set-HPOVLdapDefaultDirectory (2.0.436.0) -- Error with JSON/Legacy Get-HPOVLdapDirectory Parameter

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#120]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Default directory should change from LOCAL to an LDAP/AD directory or vice versa.

### Actual Behavior
Set-HPOVLdapDefaultDirectory complains:
Get-HPOVLdapDirectory: A parameter cannot be found that matches parameter name 'Hostname'

I changed this in HPOneView.200.psm1 from -Hostname to -ApplianceConnection, line 49949.

However, another error is produced:

Set-HPOVLdapDefaultDirectory: Invalid JSON type. The type field content, "LoginDomainConfigVersion200", included in this request is invalid.

### Steps to reproduce
Connect to HPOVMGmt

Add an AD/LDAP Directory.

Set-HPOVLdapDefaultDirectory -Directory <directory> -ApplianceConnection $ApplianceConnection -Confirm:$False

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.436.0
HPE OneView Appliance Version: 2.00.07-0250853
Output from `$PSVersionTable` on your Windows Host: 
PSVersion 4.0
WSAnStackVersion 3.0
SerializationVersion 1.1.0.1
CLRVersion 4.0.30319.42000
Buildversion 6.3.9600.17400

**Comment by ChrisLynchHPE** [comment]
Looks like the 2.00.07 patch may have caused an API change.  I'm investigating this.

**Comment by ChrisLynchHPE** [comment]
As I stated in my prior comment, I added API support for the 2.00.07 patch.  However, the LDAP API also changed, which caused this issue.  I have tested a fix and will be in the next library update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.474.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.474.0).

Closing.
