### ISSUE TITLE
New-HPOVLdapGroup (2.0.436.0) -- Error regarding userName and password parameters/properties

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#121]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Being able to connect an AD/LDAP group to one or more roles in OneView.

### Actual Behavior
Doesn't seem to process properties "username" or "Password".

VERBOSE: [NewObject] Called from NEW-HPOVLdapGroup
The property "userName" cannot be found on this object. Verify that the property exists and can be set.

The property "password" cannot be found on this object. Verify that the property exists and can be set.

New-HPOVLdapGroup: No roles provided for enterprise group to role assignment. No roles provided for enterprise group to role assignment.

### Steps to reproduce

Connect to HPOVMgmt

Add a directory.

New-HPOVLdapGroup -AuthProvider <Directory> -UserName <domainuser> -Password <domainuserpassword> -Groupname <Directorygroupname> -Roles "Infrastructure administrator" -ApplianceConnection $ApplianceConnection -Verbose

### Version Information
HPE OneView PowerShell Library Version (Get-HPOVVersion): 2.0.436.0
HPE OneView Appliance Version: 2.00.07-0250853
Output from $PSVersionTable on your Windows Host: 
PSVersion 4.0
WSAnStackVersion 3.0
SerializationVersion 1.1.0.1
CLRVersion 4.0.30319.42000
Buildversion 6.3.9600.17400

**Comment by ChrisLynchHPE** [comment]
I found the source of the issue.  Will be fixed in a 2.00 library update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.474.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.474.0).

Closing.
