### ISSUE TITLE
Set-HPOVApplianceDateTime (2.0.436.0) -- Not exported in .psm1

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#123]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Set-HPOVApplianceDateTime

### Actual Behavior
Set-HPOVApplianceDateTime has not been exported in 2.0.436.0

"Export-ModuleMember -Function Set-HPOVApplianceDateTime" needs to be added to HPOneView.200.psm1.

### Steps to reproduce
Try using Set-HPOVApplianceDateTime. It will throw an error that the function doesn't exist.

### Version Information
HPE OneView PowerShell Library Version (Get-HPOVVersion): 2.0.436.0
HPE OneView Appliance Version: 2.00.07-0250853
Output from $PSVersionTable on your Windows Host: 
PSVersion 4.0
WSAnStackVersion 3.0
SerializationVersion 1.1.0.1
CLRVersion 4.0.30319.42000
Buildversion 6.3.9600.17400

**Comment by ChrisLynchHPE** [comment]
Sorry about that.  It was exported, not sure what happened to the statement.  Will be fixed in the next update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.474.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.474.0).

Closing.
