### ISSUE TITLE
Get-HPOVAuditLog (2.0.436.0) -- Cannot download appliance audit log as in version 110/120

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#124]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Being able to download the audit log to a -Location

### Actual Behavior
There is no -Location parameter as there were in the 110 and 120 versions.

### Steps to reproduce
Get-HPOVAuditLog

### Version Information
HPE OneView PowerShell Library Version (Get-HPOVVersion): 2.0.436.0
HPE OneView Appliance Version: 2.00.07-0250853
Output from $PSVersionTable on your Windows Host: 
PSVersion 4.0
WSAnStackVersion 3.0
SerializationVersion 1.1.0.1
CLRVersion 4.0.30319.42000
Buildversion 6.3.9600.17400

**Comment by ChrisLynchHPE** [comment]
The Cmdlet changed.  `Get-HPOVAuditLog` is meant to obtain individual audit log entries.  The functionaltiy you are looking for is in the `Download-HPOVAuditLog` Cmdlet.  I have updated the user documentation to add the `Download-HPOVAuditLog` as a linked Cmdlet for discovery purposes.  User documentation will be updated soon.

**Comment by ChrisLynchHPE** [comment]
I was supposed to be exported already, and apparently it is not.  So yes, it will in the next update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.474.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.474.0).

Just a note, The Cmdlet to download the audit log ZIP is [Get-HPOVAuditLogArchive](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Get-HPOVAuditLogArchive).

Closing.
