### ISSUE TITLE
Importing HPOneView.200.psd1 (2.0.436.0) -- Requires FormatPX to successfully import

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#125]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Importing module successfully. I read earlier that CLRVersion 4.0.30319.42000 was necessary, and I have that on my system (Windows Server 2012 R2).

### Actual Behavior
"The required module 'FormatPX' is not loaded. Load the module or remove the module from 'RequiredModules' in the file HPOneView.200.psd1.

### Steps to reproduce
Importing module on a system with similar PowerShell/.NET/CLRVersion.

### Version Information
HPE OneView PowerShell Library Version (Get-HPOVVersion): 2.0.436.0
HPE OneView Appliance Version: 2.00.07-0250853
Output from $PSVersionTable on your Windows Host: 
PSVersion 4.0
WSAnStackVersion 3.0
SerializationVersion 1.1.0.1
CLRVersion 4.0.30319.42000
Buildversion 6.3.9600.17400

**Comment by ChrisLynchHPE** [comment]
How did you get the library on your Windows 2012 R2 system?  Did you just copy the files over, or did you use the installer?  FormatPX is a required module for fixing a number of Microsoft Format-* issues.

**Comment by erikgraa** [comment]
Which library?

The HP OneView library was copied over to my computer, yes.

.NET 4.6.1 was installed on the Windows Server system to up the CLRVersion.

Unsure what actually installs FormatPX, I saw in an earlier thread that the only thing you recommended installing was a new version of .NET.

**Comment by ChrisLynchHPE** [comment]
We bundle FormatPX as part of the HPE OneView PowerShell library.  If you simply copied over the `HPOneView.xxx` directory to another Windows system, you are going to be missing the FormatPX and SnippetPX modules.  Please use the installer we provide.  The other thread you are referring to was a condition where FormatPX was present but couldn't load due to another issue.  My suggestion was to make sure they had a supported version of the .Net framework.  But your case, the .Net Framework isn't the source of the problem.

**Comment by erikgraa** [comment]
Currently working in an environment where installing is frowned upon, but if it's the only way, alright.

I appreciate learning that FormatPX and SnippetPX are included in the .exe.

Doesn't seem like SnippetPX is a RequiredModule in the HPOneView.200.psd1 though. Perhaps there's a relation with FormatPX?

**Comment by ChrisLynchHPE** [comment]
The EXE is the only method to obtain the digitally signed library assets.  SnippetPX is a dependency for FormatPX.  I have added SnippetPX to the psd1 file, but that still wouldn't resolve your issue.

**Comment by erikgraa** [comment]
True, it wouldn't solve it. :)

I'll figure out a way to include the .exe.

Related issue: can the .exe be silently installed?

**Comment by ChrisLynchHPE** [comment]
We use InnoSetup, which offers silent installation support.  I haven't tested it myself, as it is a low priority feature at this point.  If you run into an issue using it, please submit another issue.

**Comment by erikgraa** [comment]
For future reference: http://www.silentinstall.org/inno_setup

HPE.OneView.2.00.PowerShell.Library.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART

Worked perfectly.

**Comment by ChrisLynchHPE** [comment]
Fantastic!  Thanks for helping to test that for us.
