### ISSUE TITLE
New-HPOVLdapDirectory (2.0.436.0) -- Invalid credentials to connect to the directory X

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#126]
##Please fill in as much information as possible to help resolve your issue.
This can be labeled as a question as I'm unsure if it's an issue or just my environment.

I'd like to know what format the username input should be in.

### Expected Behavior
Being able to create a new directory for the appliance.

### Actual Behavior
Credentials are rejected time and again. I had it working at one point, but when I recreated the appliance it doesn't work again.

errorcode: AUTHN_LOGINDOMAIN_SERVER_CREDENTIALS_INCORRECT
message: Invalid credentials to connect to the directory X

HTTP 400 bad request.

When I look at the request using -Verbose, the username and password are 100% correct. I've tried multiple users and multiple ways of setting up the username:

netbios\username
username
username@fqdn

The password is a SecureString object.

When I input the exact same values in the UI everything goes right through.

### Steps to reproduce
New-HPOVLdapDirectory

### Version Information
HPE OneView PowerShell Library Version (Get-HPOVVersion): 2.0.436.0
HPE OneView Appliance Version: 2.00.07-0250853
Output from $PSVersionTable on your Windows Host: 
PSVersion 4.0
WSAnStackVersion 3.0
SerializationVersion 1.1.0.1
CLRVersion 4.0.30319.42000
Buildversion 6.3.9600.17400

**Comment by ChrisLynchHPE** [comment]
The API is rejecting your credentials.  You can use the UPN (user@fqdn.com) of the account that has permissions to authenticate to the LDAP Directory.  You are providing a `SecureString` for the Cmdlet.  Can you validate you are using the correct password?  You can decrypt your `SecureString` password with the following PowerShell code (which is exactly the same as what the Cmdlet is doing):

```PowerShell
[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($Password))
```

**Comment by erikgraa** [comment]
Yeah, the password is correct, and it's the same for every account.

I've based my script on the sample applianceconfig.ps1 script and tried various ways of making the securestring object.

Both UPN and just the user name should be OK right? When in the UI I always just use the username without NETBIOS\ or @FQDN.

I'm at a loss regarding why it's not working and why I got it to work once.

Firewall on DCs is not rejecting anything, there are no audit failures in the eventlog.

**Comment by ChrisLynchHPE** [comment]
Please use the `Start-HPOVLibraryTrace` ad then `Stop-HPOVLibraryTrace` Cmdlet to capture the verbose output of your call.  Do know that I have not fully implemented a method to redact account passwords.  You may need to edit the file to redact them in the REQUEST BODY prior to replying.

**Comment by erikgraa** [comment]
If I specify a wrong username I get a different error, ie. AUTHN_LOGINDOMAIN_VALIDATION_ERROR, AUTHN_AUTH_FAIL, "Enter correct credentials and try again. To obtain a username or password, contact your administrator".

I've tried several usernames who all have search context rights (which you get from Domain User privileges I guess), and also Domain Admins users. I've reset the password and I'm 100% sure it is typed correctly as it is a very easy password.

I've made the SecureString in various ways,

$password = ConvertTo-SecureString -AsPlaintext "Password" -Force
$password = Read-Host "Password" -AsSecureString

I've tried decrypting it to plaintext to see if it truly is the same password, and it is.

The LibraryTrace doesn't seem to provide any more info and I can't upload it without redacting most of the data.

I don't need to apply a certificate to the appliance or provide the New-HPOVLdapServer -Certificate parameter with a file with the full BASE64 certificate chain of the domain controller? This has nothing to do with eachother right?

**Comment by ChrisLynchHPE** [comment]
Without a Library trace, I can't see what is causing your issue.  You can email it to me if you can, chris [dot] lynch {A_T} hpe (dot) com.

**Comment by ChrisLynchHPE** [comment]
Were you ever able to find the source to your auth issue?

**Comment by erikgraa** [comment]
I haven't been able to figure it out, which is annoying as I had hopes of fully automating the install.

**Comment by ChrisLynchHPE** [comment]
I think I was able to reproduce this.  In comparing the API call the UI uses to what the Cmdlet generates, it looks like one of the properties was changed slightly.  I'm going to submit an update later today.  Let's see if that fixes it for you as well.

**Comment by ChrisLynchHPE** [comment]
I uploaded [Release 2.0.500.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.500.0).  Can you please verify it fixes your issue?  If so, I will then close this issue.

**Comment by erikgraa** [comment]
I'll look at it first thing in the morning Chris!

**Comment by erikgraa** [comment]
And on reinstall when I try again it suddenly acts similar to before, invalid credentials.

I do not get this at all.

**Comment by ChrisLynchHPE** [comment]
Please know that we do not support restoring appliances from Snapshots that were taking while the appliance is online.  Quiescing the file system and RAM is not enough to make sure the appliance can restore to a good known state.

As for the timeout, you may be running into an issue that I have never been able to figure out what happens.  There are some cases where the HTTP connection times out, even though the appliance is running.  As the library uses C# managed code, it is difficult to reproduce, let alone trace when it happens.

As for your re-install, are you sure you installed the correct version?  Ever since making the small change to the API call, I have not once reproduced the invalid credentials again, unless the credentials were indeed invalid.

**Comment by erikgraa** [comment]
It was a snapshot from a new deployment that had never been powered on.

Tried deploying again nevertheless. I cannot get past this error.

errorcode AUTHN_LOGINDOMAIN_SERVER_CREDENTIALS_INCORRECT
details "Invalid credentials to connect to the directory {0}"

Looking at the parameters passed to the API everything looks completely correct.

Could be an environmental issue too, so I might just drop this for now and do ad integration/rbac/default directory as a manual setup.

**Comment by erikgraa** [comment]
By the way, certificates that have a different Cryptographic Service Provider than RSA, e.g. ECDH_P256, will give the error "The certificate does not seem to be valid" when trying to add a directory server.

**Comment by erikgraa** [comment]
Have tried in two different environments, brand new 2.00.07 appliances with 2.0.500.0 POSH and I simply cannot get this to work. No idea why or how I got it intermittently working yesterday.

**Comment by ChrisLynchHPE** [comment]
@erikgraa As I can't reproduce this, I'm going to close this issue.  If you feel that this issue still exists, feel free to re-open it or submit a new issue.

**Comment by erikgraa** [comment]
I have done some more investigating.

New-HPOVLdapGroup in 2.0.530.0 works perfectly against my domain using a domain user with search context as the Username and a SecureString as the Password.

I still cannot get New-HPOVLdapDirectory to work properly.

Today I was experimenting. I sent a New-HPOVLdapDirectory request and it timed out. I checked Settings in the WebUI to check whether it had been added. It had not. I sent the New-HPOVLdapDirectory command again and I got that the Enterprise Domain already was added.

I deleted the domain and tried again, this time waiting a while. It took around 1.5 minutes before the domain was visible from the UI. This is consistent with how long it takes to add the domain when you do it through the UI, actually. Maybe my test environment is slow somehow, but still.

However, it's not possible to automate this with any accuracy if I can't be certain that the domain is there when I start to change the default domain and want to add groups. What about Wait-HPOVTaskComplete for this Cmdlet?

**Comment by erikgraa** [comment]
I guess I could do a While(-Not(Get-HPOVLdapDirectory) { Start-Sleep 30 } until it is added as a last resort.

**Comment by erikgraa** [comment]
Haha. I have no idea what is going on.

Reinstalled the appliance to test a final time with my script. I got the usual invalid credentials error.

HOWEVER. After I add the domain with the UI and remove it, I'm able to do it through Cmdlets. Not before. Completely weird.

This explains why I've sometimes gotten it to work, though, since I've been alternating between trying through UI and with Cmdlets.

1) First add through Cmdlets -- does not work

1) Add through UI and then remove through Cmdlet
2) Add with Cmdlet -- works. I can now remove and re-add at will without any whining about credentials.

Makes no sense right?
