### ISSUE TITLE
Feature request: Cmdlet to Set HP Public Key

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#129]
Please fill in as much information as possible to help resolve your issue.

Feature request: Cmdlet to Set HP Public Key
### Expected Behavior

Cmdlet to Set HP Public Key in the Security Settings of the Appliance. Can't seem to find anything that fits in the Cmdlet reference.
### Actual Behavior

N/A
### Steps to reproduce

N/A
### Version Information

HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.436.0
HPE OneView Appliance Version:  2.0

**Comment by ChrisLynchHPE** [comment]
We don't have a Cmdlet for this yet.  Updating the GPG Public Key on the appliance is only necessary IF the GPG private key was ever compromised, or for environments that need to validate signed Linux components are from HPE.  Updating it on an appliance at this time is unnecessary.  If you absolutely need to do this, then you can take a look at the REST API spec for `PUT /rest/appliance/firmware/verificationKey`.  However, after looking at that particular API call, we aren't documenting it fully, and needs an update.  I'll put this as an enhancement, but unfortunately will be a low priority at this time.

**Comment by erikgraa** [comment]
In my case it's important to ensure that updates are coming from HPE.

So basically http://h17007.www1.hp.com/docs/enterprise/servers/oneviewhelp/oneviewRESTAPI/content/images/api/#rest/login-sessions and then http://h17007.www1.hp.com/docs/enterprise/servers/oneviewhelp/oneviewRESTAPI/content/images/api/#rest/appliance/firmware?

I'll look into it, I've never worked with REST before, particularly not in POSH :)

**Comment by ChrisLynchHPE** [comment]
They are digitally signed, and the appliance already verifies the contents have valid HPE signatures.  If not, they are rejected.

**Comment by erikgraa** [comment]
Soooo all current keys are already in the internals of the black box appliance?

There's something I'm not getting, I thought I was making stuff more ironclad by adding the latest key.

**Comment by ChrisLynchHPE** [comment]
All of the required GPG keys to validate patches and updates are already included with each release.  If we need to update the GPG keys, it could be included within a patch.  We haven't had a need to do this, but the mechanism is in place.  Yes, we provide all public GPG keys for customers to validate components on their own.  HPE added a company wide policy that all components must provide a digital signature to validate the origin.  This included Firmware and Drivers, along with software.

**Comment by erikgraa** [comment]
Great. I suppose this can be closed then, unless you're gonna keep it open for the potential API enhancement.

**Comment by ChrisLynchHPE** [comment]
You need to provide the key as is.  It is a GPG key, not Base64 Binary.

**Comment by erikgraa** [comment]
OK. Got it working, but like you said, it's an unnecessary or even detrimental procedure as the keys are already in place.

**Comment by ChrisLynchHPE** [comment]
Closing as this enhancement is not necessary or needed.
