### ISSUE TITLE
POSH 1.20.0078 New-HPOVProfileConnection issue

### ISSUE THREAD

**Issue by huberm001** [HewlettPackard/POSH-HPOneView#13]
creating a Profile with a Ethernet-Connection returns the following error:

Unable to create server profile: Template-BL460
Error Code --> BOOT_ATTRIBUTE_NOT_ALLOWED
Error Message --> The boot attribute specified for connection 1 is not valid

VERBOSE: ParameterSet: Ethernet
VERBOSE: [NEW-HPOVPROFILECONNECTION] Network resource provided via parameter
VERBOSE: [NEW-HPOVPROFILECONNECTION] Network Name:  VLAN-30
VERBOSE: [NEW-HPOVPROFILECONNECTION] Network Category:  ethernet-networks
VERBOSE: [NEW-HPOVPROFILECONNECTION] User specified 'Ethernet' ConnectionType
VERBOSE: [NEW-HPOVPROFILECONNECTION] Network Type: Ethernet
VERBOSE: [NEW-HPOVPROFILECONNECTION] Connection object: {
    "id":  1,
    "functionType":  "Ethernet",
    "name":  "Conn-1",
    "portId":  "Auto",
    "networkUri":  "/rest/ethernet-networks/3fdb60e7-04f7-45f4-ac7c-9d98a83b56b8",
    "requestedMbps":  2500,
    "boot":  {
                 "priority":  "NotBootable"
             }
}

**Comment by ChrisLynchHP** [comment]
Did You by chance disable Boot Management in your Server Profile?

**Comment by huberm001** [comment]
no, I did not change -bootable or -priority

here is how you can produce the error:
$pname = "Template-BL460"
$net1 = Get-HPOVNetwork "VLAN-10"
$con1 = New-HPOVProfileConnection -network $net1 -connectionType Ethernet -connectionId 1
$conList = @($con1)
$SHWT = Get-HPOVServerHardwareTypes -name "BL460c Gen9 1"
$eg = Get-HPOVEnclosureGroup "EncGRP-1"
$params = @{
 name = $pname;
server = "unassigned";
serverHardwareType = $SHWT;
enclosureGroup = $eg;
connections = $conList
}

New-HPOVProfile @params | Wait-HPOVTaskComplete

Name            : Create
Owner           : administrator
TaskState       : Error
PercentComplete : 100
ProgressUpdates : {}
TaskErrors      : {@{data=; errorCode=BOOT_ATTRIBUTE_NOT_ALLOWED; nestedErrors=System.Object[]; details=; errorSource=; recommendedActions=System.Object[];
                  message=The boot attribute specified for connection 1 is not valid.}}
Created         : 2015-03-02T18:27:12.258Z
Nodified        : 2015-03-02T18:27:12.761Z

**Comment by ChrisLynchHP** [comment]
Add manageboot = $true to your params and try again.

Sent from my Windows Phone
________________________________

**Comment by huberm001** [comment]
thanks, that works.

there must have been a change in the posh because that has been the default.
so it's manageboot = $false that returns the error

**Comment by ChrisLynchHP** [comment]
That parameter was supposed to e a switch, not a Boolean type. I had updated it to match prior versions

Sent from my Windows Phone
________________________________

**Comment by ChrisLynchHP** [comment]
Closing issue.
