### ISSUE TITLE
Remove-HPOVServerProfile - Error while removing the Server profile

### ISSUE THREAD

**Issue by pramodreddysareddy** [HewlettPackard/POSH-HPOneView#130]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Remove the Server Profile

### Actual Behavior
N/A

### Steps to reproduce
PS C:\> $profile = Get-HPOVServerProfile -name "Profile2"
PS C:\> Remove-HPOVServerProfile $profile -confirm:$false

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.474.0
HPE OneView Appliance Version:  2.0
Output from `$PSVersionTable` on your Windows Host:Name  : 
PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : BuildVersion
Value : 6.3.9600.16406

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

![removeserverprofile](https://cloud.githubusercontent.com/assets/20171809/16390493/ad48526c-3c68-11e6-9e13-796dffa3bb5b.png)

**Comment by ChrisLynchHPE** [comment]
Thanks.  The Cmdlet will need a be of refactoring, but will be fixed in the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.480.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.480.0).

Closing.
