### ISSUE TITLE
New-HPOVServerProfile - Issue while setting Custom BIOS Settings

### ISSUE THREAD

**Issue by pramodreddysareddy** [HewlettPackard/POSH-HPOneView#131]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Create a Server Profile with BIOS settings

### Actual Behavior
N/A

### Steps to reproduce
Please find below command to create a new server profile with BIOS settings.

$profileName = 'Subbu'

$server = Get-HPOVServer "Encl1, Bay 16" 

$bl460bios = @(@{id=210;value=4},@{id=140;value=3},@{id=176;value=1})

PS C:\OneView1> New-HPOVServerProfile -name $profileName -assignmentType 'server' -server $server -manageboot -bootorder @(“PXE”) -bios –biossettings $bl460bios | Wait-HPOVTaskComplete

I’m able to create a server profile but the BIOS settings are getting set to default instead of custom ($bl460bios = @(@{id=210;value=4},@{id=140;value=3},@{id=176;value=1})) . Please find  screenshots for the same.

![bios1](https://cloud.githubusercontent.com/assets/20171809/16396092/ad2f97ee-3c82-11e6-88d8-8c09dc36a227.png)
![bios2](https://cloud.githubusercontent.com/assets/20171809/16396105/b68a52fc-3c82-11e6-8f4d-268825a3450d.png)

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):2.0.474.0
HPE OneView Appliance Version:  200
Output from `$PSVersionTable` on your Windows Host:

Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : BuildVersion
Value : 6.3.9600.16406

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting this issue.  It is a regression in a fix I implemented to validate BIOS Settings were unique in the request.  As a workaround, create a Server Profile Template, and deploy your Server Profile resource from it.  This will be fixed in the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.480.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.480.0).

Closing.
