### ISSUE TITLE
Get-HPOVSanManager cannot connect to an HPOV appliance

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#132]
### Expected Behavior
Get-HPOVSanManager should be able to execute a query against the default or an alternative connection.

### Actual Behavior
No appliance Hostname parameter provided and no valid appliance session(s) found.

### Steps to reproduce
1. Attach to an HPOV appliance
2a. Execute Get-HPOVSanManager
or
2b. Execute Get-HPOVSanManager -ApplianceConnection $MyConnection

### Version Information
Release 2.0.474.0 

### Output
PS C:\> $ConnectedSessions
ConnectionID Name        UserName      AuthLoginDomain Default Connection
------------ ----        --------      --------------- ------------------
1            172.28.10.1 Administrator LOCAL           True

PS C:\> Get-HPOVSanManager
Get-HPOVSanManager : No appliance Hostname parameter provided and no valid appliance session(s) found.
At line:1 char:1
+ Get-HPOVSanManager
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Hostname:String) [Get-HPOVSanManager], AuthSessionException
    + FullyQualifiedErrorId : NoAuthSession,Get-HPOVSanManager

[Trace.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/340478/Trace.txt)

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting this.  The Cmdlet was inadvertently missed in the Default ApplianceConnection handling logic I added in the last update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.480.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.480.0).

Closing.
