### ISSUE TITLE
New-HPOVServerProfile - Error creating new server profile from server profile template.

### ISSUE THREAD

**Issue by pramodreddysareddy** [HewlettPackard/POSH-HPOneView#133]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Create new server profile from the existing server profile template.

### Steps to reproduce
Create Server Profile Template:
PS C:\OneView> $templateName= 'Hypervisor Cluster Node Template v1.0'
PS C:\OneView> $bl460cGen9SHT = Get-HPOVServerHardwareTypes -name "BL460c Gen9 1"
PS C:\OneView> $bl460cGen9bios = @(@{id="PowerProfile";value="Custom"},@{id="PowerRegulator";value="StaticHighPerf"},@{id="ProcHyperthreading";value="Enabled"})
PS C:\OneView> $enclosuregroup = Get-HPOVEnclosureGroup "Group-HV01-HV08"
PS C:\OneView> New-HPOVServerProfileTemplate -name $templateName -sht $bl460cGen9SHT  –bootMode “UEFI” -bios –biossettings $bl460cGen9bios -eg $enclosuregroup | Wait-HPOVTaskComplete

Create Server Profile:
$profileName = 'MYSQL-Server';
$server = Get-HPOVServer "Encl1, Bay 16"; 
$templateName = 'Hypervisor Cluster Node Template v1.0';
New-HPOVServerProfile -Name $profileName –Server $server –Description 'Workload Demo' –ServerProfileTemplate $templateName –ApplianceConnection $Hostname | Wait-HPOVTaskComplete;
![srvrprffromtemplate](https://cloud.githubusercontent.com/assets/20171809/16491472/b2f75428-3ea3-11e6-9576-4b1b45c43ecd.PNG)

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):2.0.474.0
HPE OneView Appliance Version:  200
Output from `$PSVersionTable` on your Windows Host:
Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : BuildVersion
Value : 6.3.9600.16406

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting this.  Issue has been identified and fixed.  Will be in the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.480.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.480.0).

Closing.
