### ISSUE TITLE
Regression:Remove-HPOVServerProfile

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#134]
### Expected Behavior
The following command should succeed without issue:
Get-HPOVProfile | Remove-HPOVProfile -force -Confirm:$false | Wait-HPOVTaskComplete 

### Actual Behavior
Remove-HPOVServerProfile : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg.
/rest/server-hardware) in its value. Please correct the value and try again.
At line:1 char:25
+ Get-HPOVServerProfile | Remove-HPOVServerProfile
+                         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-HPOVServerProfile], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Remove-HPOVServerProfile

### Steps to reproduce
Execute command specified in the Expected Behavior section when an HPOVServerProfile exists on the appliance.

### Version Information
HPE OneView PowerShell Library Version 2.0.480.0

**Comment by ChrisLynchHPE** [comment]
Issue found and fixed.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.500.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.500.0).

Closing.
