### ISSUE TITLE
Misspelled variable '$PSBoundParamters'

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#135]
Mis-spelling in several lines of code: $PSBoundParamters instead of $PSBoundParameters
20252
20796
39352
39411
47043
50517

### Version Information
HPE OneView PowerShell Library Version 2.0.480.0

**Comment by ChrisLynchHPE** [comment]
Issue found and fixed.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.500.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.500.0).

Closing.
