### ISSUE TITLE
Get-HPOVApplianceGlobalSetting not working with name parameter

### ISSUE THREAD

**Issue by bramhc** [HewlettPackard/POSH-HPOneView#136]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
If you use -name parameter with a name of a global setting you know exists, I'd expect it to return the properties for that setting, but it does pull anything back. Not sure if rest command format has changed with newer version of HP OneView.

### Actual Behavior
Cant use Get-HPOVApplianceGlobalSetting -Name <Name>. I can however do Get-HPOVApplianceGlobalSetting | select name, so know the setting name I am entering exists. Doesn't work with Set-HPOVApplianceGlobalSetting either. Guessing syntax has changed somehow

### Steps to reproduce
I am using latest OneView Posh. Try entering Get-HPOVApplianceGlobalSetting -Name alertMax . Which is the first global setting. It should return nothing

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
HPE OneView Appliance Version:  v2.0.480.0
Output from `$PSVersionTable` on your Windows Host: N/A

**Comment by ChrisLynchHPE** [comment]
I will look into this.  Please know that any modifications not instructed by HPE Support to modify is not supported.

**Comment by bramhc** [comment]
Hi Chris,

Found issue. Was just a small typo round about line 11245. 

It had :- $_settings.members = $settings.members | Where-Object name -like $Name

I changed it to :- $_settings.members = $_settings.members | Where-Object name -eq $Name

Seems to work now

**Comment by ChrisLynchHPE** [comment]
The `-Like` operator is a simplified Regular Expression, which should have worked.  It is a standard PowerShell operation.

**Comment by ChrisLynchHPE** [comment]
I did find the issue, which was with a mistype of a variable.  I found and fixed this.

**Comment by bramhc** [comment]
Hi Chris,

Yeah, just put '-EQ' in cause alertMax was returning two global settings with '-Like' comparison. Thought it might have had a knock on affect if I used the Set-HPOVApplianceGlobalSetting

Thanks

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.500.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.500.0).

Closing.
