### ISSUE TITLE
Install-HPOVApplianceCertificate -- "Invalid parameter".

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#137]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Installation of cert for webui.

### Actual Behavior
Throws "invalid parameter".

By pasting the contents of the same certificate file into the webui the certificate will be installed.

Does the webui restructure the content, e.g. replacing `r`n with `n, making sure there's only 64 characters per line, etc? I am suspecting that if the certificate file content is slightly "off" in the way oneview expects it, it will be rejected?

### Steps to reproduce
My script has this.
$Certificate = C:\Temp\Certificate.pem
$C = Get-Content $Certificate
Install-HPOVApplianceCertificate -Certificate $C -ApplianceConnection $A | Wait-HPOVTaskComplete

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.500.0
HPE OneView Appliance Version: 2.00.07
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
I will need the exact exception thrown.

As for the certificate, it needs to be in Base64 format, which PEM files are not.

**Comment by erikgraa** [comment]
It's in Base64 but I tried a couple of things, I have one file where I concatenated the certificate for oneview (.cer), the issuing ca (.cer) and the root ca (.cer) into one file using cmd's "typ" command, and that output was Certificate.pem. I guess it's unnecessary to have the entire certificate chain in one file, yeah? It was necessary when I developed for vROps for VMware.

I also tried with just the oneview.cer file (not the entire chain in one file).

In both cases it works when I paste the certificate into the webui (certificate import), but get-content and install-hpovappliancecertificate gives an error. I'll get more details tomorrow.

**Comment by ChrisLynchHPE** [comment]
The cert needs to be in Base64 without cert chain.

**Comment by erikgraa** [comment]
That works in webui for me, not through POSH.

Does it matter if the request was made through webui or with POSH if the import is to be made with POSH?

**Comment by ChrisLynchHPE** [comment]
No.  The Cert is passed through in the same format as the UI.  There is an issue with the API where a final new line is needed, and there is code within the library to handle it.  IF the UI accepts Base64 with the cert chain, the API would accept it as well.

I need more information on the except before I can see if this is an issue with the Cmdlet or not.

**Comment by ChrisLynchHPE** [comment]
I also just created a new CSR (New-HPOVApplianceCsr), submitted it to my internal Windows CA, generated a cert.  I wasn't able to successfully import the Base64 with Cert Chain (.p7b).  The appliance rejected it saying it was an invalid cert.  The UI also rejected it saying it was an invalid X.509 certificate.  I was able to install the Base64 version (which has the .cer extension).

**Comment by erikgraa** [comment]
Not sure what went wrong yesterday, but I repeated the procedure and got it working today.

TaskState: Completed. :)

:+1:

**Comment by ChrisLynchHPE** [comment]
Awesome.  BTW, I'm adding an enhancement here to allow piping the results from `Get-ChildItem` to `Add-HPOVBaseline` to you can simplify your call.

Closing.
