### ISSUE TITLE
Get-HPOVBaseline -- throws an error when there are no baselines in the system

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#139]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Returning nothing if there are no baselines.

### Actual Behavior
Gives the error "The Baseline ISO '' was not found when there are no baselines in the appliance

### Steps to reproduce
On an appliance bereft of baseline ISOs, run Get-HPOVBaseline.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.500.0
HPE OneView Appliance Version:  2.00.07

**Comment by ChrisLynchHPE** [comment]
AH, this is just validation logic that is missing.  It shouldn't generate an exception if you didn't provide a name and there are no baselines.  It should only generate that exception if you did provide a name and it wasn't found.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.526.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.526.0).

Closing.
