### ISSUE TITLE
New-HPOVEnclosure: Fails with OneVIew 1.2.03 when fnew FW Iso is mentioned

### ISSUE THREAD

**Issue by skopp1974** [HewlettPackard/POSH-HPOneView#14]
###
Environment:
[HPONEVIEW]: Administrator@172.28.10.1 PS C:..\CI\Run> Get-HPOVVersion -ApplianceVer

Name                           Value
----                           -----
applMajorVersion               1
applMinorVersion               20
applVersionInfo                1.20.03-0027947
applXApiVersion                120
libraryLoadedPath              C:\SVN\CS700forVirt\branches\Release_1.1.1\HPCS\CI\Common\HPOneView.120
OneViewPowerShellLibrary       1.20.0078.0
###

I found 3 objects returned when I call Get-HPOVSppFile on OneView 1.2 with patch 03
The last object is having the correct version of FW that I need to update as shown below:
[HPONEVIEW]: Administrator@172.28.10.1 PS C:..\CI\Run> (Get-HPOVSppFile).isoFileName
SPP2014060_2014_0618_4.iso
bp-hp-service-pack-for-proliant-oneview-2014-11-30-05.iso

I constructed the below param array for splatting and called New-HPOVEnclosure. You can see the errob after calling ...
[HPONEVIEW]: Administrator@172.28.10.1 PS C:..\CI\Run> $params

Name                           Value
----                           -----
eg                             Solution Enclosure Group
u                              Administrator
p                              ToBeScanned
oa                             172.28.3.21
l                              OneView
fwBaselineIsoFilename          bp-hp-service-pack-for-proliant-oneview-2014-11-30-05.iso

$Task = New-HPOVEnclosure @Params

Get-hpovSppFile : The Baseline ISO 'bp-hp-service-pack-for-proliant-oneview-2014-11-30-05.iso' was not found.
At C:\SRINI-DEV\SVN\CS700forVirt\branches\Release_1.1.1\HPCS\CI\Common\HPOneView.120\HPOneView.120.psm1:6209 char:35
+                     $fwBaseLine = Get-hpovSppFile $fwBaselineIsoFilename
+                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-HPOVSspFile:String) [Get-HPOVSppFile], BaselineResourceException
    + FullyQualifiedErrorId : BaselineResourceNotFound,Get-HPOVSppFile

Please help us!

**Comment by ChrisLynchHP** [comment]
Remove the .iso from the name and it will work.

Sent from my Windows Phone
________________________________

**Comment by skopp1974** [comment]
Thanks Chris!
Now working without file extension.

However, ```New-HPOVProfile``` is failing to work either with or without extension.
>>>
New-HPOVProfile : The provided SPP Baseline 'bp-hp-service-pack-for-proliant-oneview-2014-11-30-05' was not found or an error ocurred during lookup.

**Comment by ChrisLynchHP** [comment]
Thanks.  I'll look at New-HPOVProfile to make sure the parameter syntax for specifying the SPP matches that of Add-HPOVEnclosure.  Can you open an issue with New-HPOVProfile so it is tracked?
