### ISSUE TITLE
New-HPOVAddressRange not working

### ISSUE THREAD

**Issue by BraendiAT** [HewlettPackard/POSH-HPOneView#141]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
New-HPOVAddressRange configures a new address range

### Actual Behavior
for example the following command New-HPOVAddressRange -PoolType vmac -RangeType Custom -Start 26:AE:85:55:00:00 -End 26:AE:85:55:FF:FF -ApplianceConnection $ApplianceConnection gives following output
NewOPbject : The term 'NewOPbject' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At C:\OVINST\OVPowershell\HPOneView.200.psm1:38461 char:25
+                     $_newRange = NewOPbject -IDPoolRange
+                                  ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (NewOPbject:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The property 'startAddress' cannot be found on this object. Verify that the property exists and can be set.
At C:\OVINST\OVPowershell\HPOneView.200.psm1:38463 char:6
+                     $_newRange.startAddress = $Start
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'endAddress' cannot be found on this object. Verify that the property exists and can be set.
At C:\OVINST\OVPowershell\HPOneView.200.psm1:38464 char:6
+                     $_newRange.endAddress   = $End
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

New-HPOVAddressRange : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try again.
At line:1 char:1
+ New-HPOVAddressRange -PoolType vmac -RangeType Custom -Start 26:AE:85 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-HPOVAddressRange], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-HPOVAddressRange

### Steps to reproduce
$ApplianceConnection = Connect-HPOVMgmt -Hostname $OVIP -UserName $OVUser -password $OVPass
New-HPOVAddressRange -PoolType vmac -RangeType Custom -Start 26:AE:85:55:00:00 -End 26:AE:85:55:FF:FF -ApplianceConnection $ApplianceConnection

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
2.0.526.0  C:\OVINST\OVPowershell
HPE OneView Appliance Version:  
2.00.02
Output from `$PSVersionTable` on your Windows Host:
Name                           Value
----                           -----
PSVersion                      5.0.10240.16384
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10240.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3

**Comment by ChrisLynchHPE** [comment]
This typo is fixed, and will be in the next update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.530.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.530.0).

Closing.

**Comment by BraendiAT** [comment]
I fixed the typo but I got still errormessage:
PS C:\OVINST\OVPowershell> New-HPOVAddressRange -PoolType vmac -RangeType Custom -Start DA:E5:DA:C0:00:00 -End DA:E5:DA:C0:FF:FF
New-HPOVAddressRange : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try again.
At line:1 char:1
+ New-HPOVAddressRange -PoolType vmac -RangeType Custom -Start DA:E5:DA ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-HPOVAddressRange], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-HPOVAddressRange

**Comment by ChrisLynchHPE** [comment]
RE-opening.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.530.1](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.530.1).

Closing.
