### ISSUE TITLE
Connect-HPOVMgmt -- SecureString Password Input

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#142]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Connect-HPOVMgmt -Password SecureString input

### Actual Behavior
Connect-HPOVMgmt expects plaintext password instead of SecureString like New-HPOVLdapGroup and New-HPOVLdapDirectory

### Steps to reproduce
Connect-HPOVMgmt

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version:  2.00.07

**Comment by ChrisLynchHPE** [comment]
Thanks for the suggestion.  I've tested an enhancement that will support the following with the `Password` parameter:

* Support `[SecureString]` input type (i.e. using `Read-Host -AsSecureString`).
* `[System.String]` value, which is clear text.
* No value, which user will be prompted (using the  `Read-Host -AsSecureString` method).

**Comment by erikgraa** [comment]
Superb Chris!

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.530.1](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.530.1).

Closing.
