### ISSUE TITLE
New-HPOVNetworkSet treats multiple network entries as string, instead of an array

### ISSUE THREAD

**Issue by bramhc** [HewlettPackard/POSH-HPOneView#143]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Going by example coded into POSH. Below command should create a 'Network Set' called 'Production Networks' with associated networks of blue, green, yellow.

New-HPOVNetworkSet -name "Production Networks" -untaggedNetwork yellow -networks blue, green, yellow -TypicalBandwidth 1000 -MaximumBandwidth 5000

Note: Cannot give my actual production example

### Actual Behavior

POSH

Treats (blue, green, yellow) as a string so script fails the New-HPOVNetworkSet command. 

I tested the following modifications on POSH module which fixed the issue. added '$Networks = $Networks -split "," ' and '$_net = $_net.trim()'. This at least allows me to continue what I was doing, but thought I'd better highlight the issue.

Taken from modified code>>>>>>>>>>>>>

        $Networks = $Networks -split "," 

		# Validate Networks if they are objects, and ApplianceConnection prop matches $_connection.Name value
		ForEach ($_net in $Networks)
		{
        
        $_net = $_net.trim()

			switch ($_net.GetType().Name)
			{

<<<<<<<<<<<<<<<<<<<<<<<

### Steps to reproduce

Try creating new Network Set with multiple networks

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): v2.0.500.0
HPE OneView Appliance Version:  2.00
Output from `$PSVersionTable` on your Windows Host: N/A

**Comment by ChrisLynchHPE** [comment]
I am unable to reproduce your issue.  When using the following, the `Networks` parameter is treated as an Array of String:

```PowerShell
New-HPOVNetworkSet -Name test -Networks blue,green,yellow
```

Did you put any single or double quote around `blue, green, yellow`?  If so, that's your problem.  Each `String` value must either be encapsulated with a single (to mean literal) or double quote marks, not the entire parameter value.

**Comment by bramhc** [comment]
It was tried in the following format

- New-HPOVNetworkSet -Name test -Networks blue,green,yellow
- New-HPOVNetworkSet -Name test -Networks blue, green, yellow
- New-HPOVNetworkSet -Name test -Networks 'blue','green','yellow'
- New-HPOVNetworkSet -Name test -Networks blue green yellow

all produced the same result. I added a Write-Host to foreach section, which I was expecting to see something like below

blue 
green 
yellow

but got 'blue, green, yellow' output. Unless you are running a version that has already resolved this. I am running version  2.0.500.0. What version was it tested on? I will try latest revision and see if that build replicates my issue

**Comment by ChrisLynchHPE** [comment]
The same version you have.  Nothing has been modified with New-HPOVNetworkSet Cmdlet.  I tested using Network Name values are you have used.  I also tested with Network Objects obtained from `Get-HPOVNetwork`.  I cannot reproduce your issue.

I just noticed in your original post that you put `N/A` for the request to include the output from `$PSVersionTable` variable on your Windows host PowerShell console.  Can you please provide that information?  It does not include any sensitive data.

**Comment by bramhc** [comment]
Hi Chris,

Info is as follows:

Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.34209

Name  : BuildVersion
Value : 6.3.9600.17400

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

I am still to try the  latest revision as well. Will try and sort some time out to test this. If it helps eliminate possible problems. 2.0.500.0 was installed into a newly created development environment, so no previous additions where installed

**Comment by ChrisLynchHPE** [comment]
Well, you are using a supported version of PowerShell.  The New-HPOVNetworkSet Cmdlet has not changed in quite a long time.  It supports an array (collection) of Ethernet Network Names or Objects.

**Comment by bramhc** [comment]
Hi Chris,

Sorry it has taken me so long to get back to you. Had to set out some time to test new version of POSH. I removed 2.0.500.0 completely from our Dev environment and installed version 2.0.530.0. I checked the .psm to ensure my lines where removed and re-tested. I don't seem to be able to replicate issue with new revision of POSH. I would say we can close this ticket down. Not sure what the root cause was why .500 bugged out, but happy enough current version works ok

Thanks for your time

**Comment by ChrisLynchHPE** [comment]
I just compared the Cmdlet from the 2.0.500.0 and 2.0.530.0 releases, and the only difference is some white space in the Begin code block.  How the Cmdlet process the `-Networks` parameter is unchanged, and should have worked just fine.
