### ISSUE TITLE
New-HPOVLdapDirectory (2.0.530.0) -- Invalid credentials to connect to the directory

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#144]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
New-HPOVLdapDirectory adds the directory without fault.

### Actual Behavior
Follow-up on #126 

New-HPOVLdapDirectory cannot add the directory.

If a directory is added through the WebUI and then removed, either through WebUI or POSH, a new directory can be added through New-HPOVLdapDirectory without fault.

Feels like it needs to be broken in using the WebUI first. Very strange. But this explains why it has worked intermittently for me, as I've been configuring new installs using cmdlet/UI alternatively. Whenever I've tried with the UI it'll work afterwards, and whenever I never use the UI (which is what I'm intending for my install script), it'll never work. Cannot wrap my head around why this is happening though.

### Steps to reproduce
1) Create a new appliance and do the basic config of password/hostname/IP. Nothing else.
2) Do Connect-HPOVMgmt
3) Do New-HPOVLdapDirectory. For me, this will give "invalid credentials"
4) Add a directory using the WebUI instead.
5) Remove the added directory using Get-HPOVLdapDirectory | Remove-HPOVLdapDirectory -Confirm:$False OR remove it using the WebUI
6) New-HPOVLdapDirectory works.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version: 2.00.07
Output from `$PSVersionTable` on your Windows Host:
PSVersion 4.0
BuildVersion 4.0.30319.34014

**Comment by ChrisLynchHPE** [comment]
Based on your input, this seems like a product defect with OneView, not the Cmdlet.  I'm deploying a new 2.00.07 appliance to validate.

**Comment by ChrisLynchHPE** [comment]
I have confirmed this is a defect in HPE OneView 2.00.07.  I have raised it as an issue internally.  I will reply back once I have more information.

**Comment by erikgraa** [comment]
Great! I'm just happy I was able to find a way for you to reproduce the issue in your lab. Took me a lot of tries though, hah.

It must have worked in (some) previous versions, because the sample script for appliance config uses New-HPOVLDAPDirectory.

**Comment by ChrisLynchHPE** [comment]
@erikgraa, can you email me at Chris <dot> lynch (a t ) hpe [com]? I need more information from you that would be sensitive to discuss further here.

**Comment by ChrisLynchHPE** [comment]
There is a . Between my first and last name.

**Comment by ChrisLynchHPE** [comment]
I have tested a workaround for this core product defect.  This will be in the next milestone update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.576.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.576.0).

Closing.
