### ISSUE TITLE
New-HPOVLdapDirectory (2.0.530.0) -- Other CSA than RSA will produce error "The certificate does not seem to be valid"

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#145]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
New-HPOVLdapDirectory adds the directory without error.

### Actual Behavior
New-HPOVLdapDirectory cannot add directory if the certificate of the DCs have other Cryptographic Service Providers than RSA, although I've only tried with ECDH_P256.

Seems to be an error with how the OneView API expects certificates to look like.

### Steps to reproduce
- Domain Controller certificate / Certificate Chain with Cryptographic Service Provider other than RSA, e.g. ECDH_P256.
- Connect-HPOVMgmt
- New-HPOVLDAPDirectory

Error thrown: "The certificate does not seem to be valid" when adding the directory.

Other tidbits:

For the WebUI to be able to fetch the domain controllers' certificates, the entire chain needs to be RSA, not just the personal certificates of the DCs.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version: 2.00.07
Output from `$PSVersionTable` on your Windows Host:
PSVersion 4.0
BuildVersion 4.0.30319.34014

**Comment by ChrisLynchHPE** [comment]
This isn't a defect with the Library.  If you are trying to use other cryptographic algorithms, and you can't use them, this is a limitation of the appliance.  This issue tracker is not meant for core OneView product defects.  You need to open a support case with the HPE Customer Support Center.

**Comment by erikgraa** [comment]
Will do!
