### ISSUE TITLE
HP OneView PowerShell Library .exe silent install for ALLUSERS

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#146]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Silently install either to local user (%USERPROFILE%\documents\windowspowershell\modules\) OR to ALLUSERS (C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules)

### Actual Behavior
No matter what parameters you give to HPE.OneView.2.00.PowerShell.Library.exe it won't silently install elsewhere than %USERPROFILE%\Documents.

Would be nice if the ALLUSERS option during install was the default choice.

### Steps to reproduce
.\HPE.OneView.2.00.PowerShell.Library.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /NOICONS /DIR="C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules" /GROUP="HPE OneView 2.00 POSH Library" /LANG="en" will still install to the local user's document folder.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version: N/A
Output from `$PSVersionTable` on your Windows Host: N/A

**Comment by erikgraa** [comment]
It's possible to save an .INF of an ALLUSERS install and the load that for other installs, but even that won't install to ALLUSERS.

.\HPE.OneView.2.00.PowerShell.Library.exe /SAVEINF="c:\temp\oneview.inf" 

Uninstall

.\HPE.OneView.2.00.PowerShell.Library.exe /LOADINF="c:\temp\oneview.inf"

**Comment by ChrisLynchHPE** [comment]
The Inno Setup script we use is customized.  I'll see what we can do to provide a method to silent install for All Users.

**Comment by erikgraa** [comment]
The HP iLO PowerShell Library is installable with an MSI, maybe this could be done for OneView POSH also?

**Comment by ChrisLynchHPE** [comment]
I will look into it, but when this project first started, we only had access to InnoSetup as the installer.

**Comment by ChrisLynchHPE** [comment]
So, I finally have a solution to this.  An INF file will need to be created with the following structure:

``` 
[Setup]
Lang=en
NoIcons=0
Users=1
```

To install to `AllUsers`, the `Users` key will need to be set to `0`.  Change it to `1` to install for `JustMe`.

Then, the following command line switches will be needed:

``` Cmd
"HPE OneView 2.00 PowerShell Library.exe" /loadinf="{FILENAME}.inf" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
```

Of course, I will have this documented on the Wiki.  Expect a 2.00 release later this week that includes this and other enhancements/fixes.

**Comment by ChrisLynchHPE** [comment]
This has been added in [Release 2.0.604.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.604.0).  Use is documented on the main [Wiki](https://github.com/HewlettPackard/POSH-HPOneView/wiki#silent-installation-of-library) page.  There is an `Unattended` directory contained in the installer that provides examples for both installation directory options.

Closing.

**Comment by erikgraa** [comment]
Great.

Something I noticed:

1) You can do the install for ALLUSERS by adding the /USERS=1 parameter, or USERS=0 for local user instead of the LoadINF.

2) Install folder for ALLUSERS is correct at %WinDir%\System32\WindowsPowerShell\v1.0\Modules, but the uninstaller (uins000.exe) and shortcut seem to get placed in Windir%\SysWow64\WindowsPowerShell\v1.0\Modules.
