### ISSUE TITLE
HPOV / SCORCH

### ISSUE THREAD

**Issue by c0c00n** [HewlettPackard/POSH-HPOneView#148]
Hi Chris,
I am running your Cmdlet in a Microsoft System Center Orchestrator environment. I have to suppress all outputs when i am running powershell. As soon i run this line in my script `            $ApplianceConnection = Connect-HPOVMgmt -appliance $global:myAppliance -UserName $HPOVuser -password $HPOVpass -AuthLoginDomain $HPOVdomain
` i got the out put as described above in actual behavior. Looks like there are some line breaks

### Expected Behavior
No extra lines in the shell between command and prompt

### Actual Behavior

PS C:\WINDOWS\system32> $ApplianceConnection = Connect-HPOVMgmt -appliance $HPOVurl -UserName $HPOVuser -password $HPOVpass -AuthLoginDomain $HPOVdomain -LoginAcknowledge

"Something is here...."

PS C:\WINDOWS\system32>

> A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do not support user interaction, such as Windows PowerShell workflows.

### Steps to reproduce
Run the Connect-HPOVMgmt command and check the lines on the shell between command and prompt.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):  2.0.530.0
HPE OneView Appliance Version:  200
Output from `$PSVersionTable` on your Windows Host:
Name  : PSVersion
Value : 4.0
Name  : WSManStackVersion
Value : 3.0
Name  : SerializationVersion
Value : 1.1.0.1
Name  : CLRVersion
Value : 4.0.30319.42000
Name  : BuildVersion
Value : 6.3.9600.17400
Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}
Name  : PSRemotingProtocolVersion
Value : 2.2

Thanks
Mike

**Comment by ChrisLynchHPE** [comment]
Please use the [Enable-HPOVMSDsc](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Enable-HPOVMSDSC) Cmdlet.  This Cmdlet will overload Write-Host, and use Write-Verbose, which is needed for MS System Center Orchestrator.

**Comment by c0c00n** [comment]
Thank you, as you proposed I placed [Enable-HPOVMSDsc](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Enable-HPOVMSDSC) in the script on MS Orchestrator. All works fine now as excepted. Thank you very much for your fast hint.

**Comment by ChrisLynchHPE** [comment]
That's why the Cmdlet was created.  Please know that the way this Cmdlet works is on a per user basis.  So, if you ever needed to run interactive scripts, you should use a MSSC Orchestrator service account where the script will execute from.  The specific registry location where the value is managed is documented in the help.  So you can always do a `Test-Path HKCU:\Software\Hewlett-Packard\HPOneView' to see if it exists.  If not, run the `Enable-HPOVMsDsc` Cmdlet.

**Comment by c0c00n** [comment]
Okay i well remember that and all i running with  a service account. Anyway I have to run HPOV cmdlets trough this [solution](https://automys.com/library/asset/powershell-system-center-orchestrator-practice-template#PowerShellBestPracticeExample-section), coz SCORH has lame PS version.
