### ISSUE TITLE
Set-HPOVSMTPConfig - Password parameter is not SecureString

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#149]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Set-HPOVSMTP Password parameter accepts SecureString object.

### Actual Behavior
Set-HPOVSMTP Password parameter is a String.

### Steps to reproduce
Get-Help Set-HPOVSMTPConfig

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version:  2.00.07

**Comment by ChrisLynchHPE** [comment]
This will be enhanced in the next release milestone.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.576.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.576.0).

Closing.
