### ISSUE TITLE
Copy-HPOVProfile always updates firmware

### ISSUE THREAD

**Issue by skopp1974** [HewlettPackard/POSH-HPOneView#15]
```Copy-HPOVProfile``` is always updating the Server firmware thought SPP's FW matches to Server FW and no ```-force``` option is specified.
* The source profile is a template without assigning to any Device Bay.and had no forceInstallFirmware flag.

**Comment by ChrisLynchHP** [comment]
If a Server Profile has a baseline set, and you copy it, or assign it to a new server, the firmware baseline is always ran.  This isn't controlled by the HP OneView PowerShell library, rather the OneView product.

**Comment by skopp1974** [comment]
Yes, I agree based on my observation. When I manually apply a profile from WebUI, it does same thing and again applies the FW though server is at Baseline FW level. Must be OV appliance issue.
Due to this each of the profile assignment is taking ~30+min!

**Comment by ChrisLynchHP** [comment]
This is by design and not a bug or issue with HP OneView. When you have the baseline set in a Server Profile, it will take longer to apply regardless due to the server booting into Intelligent Provisioning and executing HPSUM to apply needed firmware.

Sent from my Windows Phone
________________________________

**Comment by skopp1974** [comment]
Thanks for clarification.
Even if you apply same baseline for 5 times on the same BL, its reapplying same versions as if -Force is used!

If there is a smart way to detect that baseline has been applied previously, and bypass this process, it would speedup the entire process.

**Comment by ChrisLynchHP** [comment]
Then you should change your Server Profile Affinity setting.  The Server Profile will be locked to that server device and cannot be transferred to another server device.
