### ISSUE TITLE
Set-HPOVSMTPConfig - Parameters are not passed to the Send-HPOVRequest

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#150]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Set-HPOVSMTPConfig successfully configures email on the appliance.

### Actual Behavior
Set-HPOVSMTPConfig doesn't send the parameters to the Send-HPOVRequest it seems. Also, SMTPPort doesn't get populated in the object despite what you send.

### Steps to reproduce
Set-HPOVSMTPConfig <Parameters> -Verbose

The parameters in the Send-HPOVRequest (parameters senderEmailAddress, password, smtpServer and smtpPort) are empty despite passing them to the Set-HPOVSMTPConfig Cmdlet.

If you run the Cmdlet without -Verbose it doesn't throw any errors and you're none the wiser.

At the end the output is "recommendedactions: message=Email address is required".

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version: 2.00.07

**Comment by ChrisLynchHPE** [comment]
This will be enhanced in the next release milestone.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.576.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.576.0).

Closing.
