### ISSUE TITLE
Get-HPOVSmtpConfig - Not exported in .psm1

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#151]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Get-HPOVSMTPConfig Cmdlet available

### Actual Behavior
Get-HPOVSMTPConfig not available

Not exported in HPOneView.200.psm1

There's also no link to the Cmdlet in the Wiki Table of Contents

### Steps to reproduce
Get-HPOVSMTPConfig

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version:  2.00.07

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.530.1](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.530.1).

Closing.
