### ISSUE TITLE
Add-HPOVSmtpAlertEmailFilter - Unable to create alert

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#152]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Ability to create filter for email config.

### Actual Behavior
Throws an error no matter what parameters I input.

Error message: Could not read JSON: No content to map to Object due to end of input; nested exception is java.io.EOFException: No content to map to Object due to end of input.

### Steps to reproduce
Add-HPOVSmtpAlertEmailFilter -Filter "CPU status:warning" -Emails email@mail.com -Verbose

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version: 2.00.07

**Comment by ChrisLynchHPE** [comment]
This will be fixed in the next milestone update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.576.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.576.0).

Closing.
