### ISSUE TITLE
Add-HPOVSmtpAlertEmailFilter - Unable to create alert with a null-filter (catch-all)

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#153]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Add-HPOVSMTPAlertEmailFilter without a filter to catch any/all notifications

### Actual Behavior
Add-HPOVSMTPAlertEmailFilter doesn't allow the -Filter parameter to be $null / empty, like in the WebUI.

### Steps to reproduce
Add-HPOVSmtpAlertEmailFilter -Filter "" -Emails email@mail.com -Verbose

See #152 also

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version: 2.00.07

**Comment by ChrisLynchHPE** [comment]
I've added support for this in the next milestone release.  Please know that using such a filter is not recommended, especially in very large environments.  You will receive a high level of alerts, including those that are lifecycle events that OneView can automatically clear.

**Comment by erikgraa** [comment]
Great. It's probably unwise in large environments yes.

I've been looking for a reference for creating queries/filters, but the wiki only has one example.

**Comment by ChrisLynchHPE** [comment]
Look in the User Guide and Online help for OneView.  There are more examples there.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.576.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.576.0).

Closing.
