### ISSUE TITLE
Add-HPOVBaseline - Uploads file even if it exists

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#156]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Add-HPOVBaseline -File shouldn't start the upload process at all if a filename already exists in the repo

### Actual Behavior
Add-HPOVBaseline uploads whether the ISO filename exists in the repo or not. Wouldn't it be better to forego the upload part by first checking whether such a filename already exists with Get-HPOVBaseline? I can understand that a filename in itself is not a unique identifier and that maybe there's some logic to pull metadata from the file post-upload though.

### Steps to reproduce
Add-HPOVBaseline -File XX.iso
Add-HPOVBaseline -File XX.iso -- uploads, then throws error that it already exists. 

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version: 2.00.07

**Comment by ChrisLynchHPE** [comment]
You can work around this by using the `Get-HPOVBaseline` Cmdlet to first verify that the Baseline exists.  Of course, you will need to wrap the Cmdlet within a Try{} Catch{} block.

**Comment by erikgraa** [comment]
Yup I have that in my current script.

But maybe this can be the default behaviour of the Cmdlet?

**Comment by ChrisLynchHPE** [comment]
I've labeled this as an `Enhancement` with `Low Priority`.

**Comment by ChrisLynchHPE** [comment]
Question:  How would you like to receive the message?  As it stands, I'm looking to see if the baseline exists.  If it does, a Write-Warning message is what I'm looking to display.  Of course, that isn't trappable, nor actionable.

**Comment by erikgraa** [comment]
Write-Error is non-terminating, right? I haven't seen many Write-Warnings so far, so I suppose the latter (Write-Error) is more in line with the rest of the library's style.

**Comment by ChrisLynchHPE** [comment]
We don't use the `Write-Error` Cmdlet.  We use either the `WriteError()` or `ThrowTerminatingError()` methods that are part of the `$PSCmdlet` special variable.  Both will display errors, and are trappable within a `Try {} Catch {}` code block.  WriteError doesn't terminate the thread stack.  ThrowTerminatingError will terminate the immediate call in the stack.

**Comment by erikgraa** [comment]
Aha, I suppose this is why SilentlyContinue as the ErrorAction for my current script using Add-HPOVBaseline isn't working. Might as well remove that from other Cmdlet calls also.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.576.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.576.0).

Closing.
