### ISSUE TITLE
Remove-HPOVServerProfile fails to remove profile

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#157]
### Expected Behavior
Remove-HPOVServerProfile  removes a server profile

### Actual Behavior
Remove-HPOVServerProfile  does not removes a server profile

### Steps to reproduce
Remove-HPOVServerProfile -name "MyServerProfile" -force -Confirm:$false | Wait-HPOVTaskComplete

### Version Information
POSH Release 2.0.530.0
Appliance Release 2.00.07-0250853

**Comment by ChrisLynchHPE** [comment]
This is fixed in the re-release of 2.00.530.0, which will be 2.00.530.1.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.530.1](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.530.1).

Closing.
