### ISSUE TITLE
Missing Cmdlet to add/remove Directory Server from Directory

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#160]
Please fill in as much information as possible to help resolve your issue.
### Expected Behavior

Ability to add or remove a directory server from a directory like in the WebUI
### Actual Behavior

No such Cmdlet
### Steps to reproduce

N/A
### Version Information

HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.1
HPE OneView Appliance Version: 2.00.07

**Comment by ChrisLynchHPE** [comment]
I have added this to our backlog.  In the meantime, you can script this operation:

```PowerShell
[PS] C:\> $TestDirectory = Get-HPOVLdapDirectory -Name TestDirectory
[PS] C:\> [Array]$TestDirectory.directoryServers = $TestDirectory.directoryServers | ? directoryServerIpAddress -ne $DCtoRemove
[PS] C:\> $TestDirectory.credential = @{username = 'MyAdmin@domain.local'; password = 'MyPassword'}
[PS] C:\> Set-HPOVResource $TestDirectory
```

**Comment by ChrisLynchHPE** [comment]
I have added this to the [3.00 library] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1210.3013).  I'm working on porting these new Cmdlets to the 2.00 library.

**Comment by ChrisLynchHPE** [comment]
This has been added to [Release 2.0.700.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.700.0).

Closing.
