### ISSUE TITLE
Add-HPOVSmtpAlertEmailFilter - Null-filter creation raises alert in OneView (The alert index filter () could not be registered.)

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#162]
### Expected Behavior
Add-HPOVSMtpAlertEmaiLFilter without the -Filter parameter leads to a null-filter being created (similar to not specifying a filter when creating in the WebUI)

### Actual Behavior
Add-HPOVSMtpAlertEmaiLFilter -Emails "email1.." works, but creates an alert in OneView (see in WebUI): The alert index filter () could not be registered.

### Steps to reproduce
Add-HPOVSMtpAlertEmaiLFilter -Emails email@email.com
Without the -Filter parameter

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.576.0
HPE OneView Appliance Version: 2.00.7.0

**Comment by ChrisLynchHPE** [comment]
I have fixed and tested this.  Will be in the next milestone update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.604.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.604.0).

Closing.

**Comment by erikgraa** [comment]
Works fine in 2.0.604.0! Thanks
