### ISSUE TITLE
New-HPOVServerProfile -Connection requires EnclosureGroup, causing API lookup failure.

### ISSUE THREAD

**Issue by tkubica12** [HewlettPackard/POSH-HPOneView#164]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Documentation states EnclosureGroup is needed only when assignment is "undefined", but it is required even when assignment is server when connection is set (should be corrected in documentation).

-EnclosureGroup should accept URI, name or object. 

### Actual Behavior
-EnclosureGroup code seems to correctly handle this input for all cases - name, uri and object. But code to do network lookup does seem to expect object only.

$_AvailableNetworksUri = $ServerProfilesAvailableNetworksUri + '?serverHardwareTypeUri={0}&enclosureGroupUri={1}' -f $ServerHardwareType.uri,$EnclosureGroup.uri

Perhaps this might rather point to $serverProfile.enclosureUri which is correctly filled when -EnclosureGroup is specified by name or uri

### Steps to reproduce

Create server profile with server assignment and connection.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.576.0
HPE OneView Appliance Version:  2.00
Output from `$PSVersionTable` on your Windows Host: 5.0.10586.122

**Comment by tkubica12** [comment]
Correction:
Documentation states eg needs to be object. Code seems to accept also name and uri:

#Retrieve the enclosure group uri from passed in enclosure uri param
elseif($enclosure -is [string]) 

Not a bug.

**Comment by ChrisLynchHPE** [comment]
The `EnclosureGroup` Parameter is only needed when the Assignment type is `Unassigned`.  Why?  Because if you are modeling a Server Profile for a BladeServer, we need to know what Enclosure Group the target Server Hardware Type is associated with.  When you provide a Server resource object, we can see if there is an associated Enclosure Group, and will use that  information instead. This behavior is modeled after the UI.

As for Networks, the `New-HPOVServerProfile` Cmdlet doesn't accept or process Network resources.  They must be assigned to Network Connections, which can be created from `New-HPOVServerProfileConnection`.

We are transitioning support for associated resources to specify Objects, not names.  Names will be supported in select cases, say getting a resource like `Get-HPOVNetwork`.

**Comment by tkubica12** [comment]
Thanks!

But when you assign to server and specify Connection EG needs to be defined since module gets available networks first and that fails when no EG is specified. Might be worth documenting.

VERBOSE: [NEW-HPOVSERVERPROFILE] Getting available Network resources based on SHT and EG.
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:

Key   : Hostname
Value : 192.168.89.100

Key   : uri
Value :
/rest/server-profiles/available-networks?serverHardwareTypeUri=/rest/server-hardware-types/993EE3AD-44BB-42F5-8
        6BB-DCCCB4BE5CE6&enclosureGroupUri=

"message":  "The connectivity model requires serverHardwareUri or serverHardwareTypeUri and enclosureGroupUri."

Example where EG needs to be specified even it is not Unassigned assignment type is here:
https://github.com/tkubica12/oneview-demo/blob/master/powershell/createServer.ps1


If project is moving away from name/uri/object (for EG) to object only there is unecessary code present in code today, could be removed for clarity.

Thanks !

**Comment by ChrisLynchHPE** [comment]
> But when you assign to server and specify Connection EG needs to be defined since module gets available networks first and that fails when no EG is specified. Might be worth documenting.

Sorry, but that is incorrect.  The Assignment Type is interrogated first.  The SHT and EG parameters are validated, then the Cmdlet moves on to processing the `Connections` parameter value. 

> $_AvailableNetworksUri = $ServerProfilesAvailableNetworksUri + '?serverHardwareTypeUri={0}&enclosureGroupUri={1}' -f $ServerHardwareType.uri,$EnclosureGroup.uri

That internal call is to look for the available Networks based on the input parameters you have given.  So, if you provided a Server Hardware device, the `serverHardwareTypeUri` and `enclosureGroupUri` are taken form the Server Device, IF it is a BL server.  If the AssignmentType is `Unassigned`, and you are trying to create a Server Profile for a supported BL server, you need to provide the `ServerHardwareType` and `EnclosureGroup`.  A `SHT` is not associated with just a single Enclosure Group or Enclosure.  It can have associations to multiple EG and Enclosure resources, and you need to provide the specific EG resource.  The Server Hardware or SHT+EG tells OneView how you intend to model the Server Profile, and also informs OneView on the validation rules it needs to use when the request is submitted.

URI's will always be used within Cmdlets.  Objects allows the Cmdlet to be more efficient, by not making unnecessary API calls, adding to Cmdlet latency.  If you feel there is an issue with the documentation, please submit an issue to the tracker for that.

**Comment by ChrisLynchHPE** [comment]
It would also help to fully understand the exact issue you are running into.  Can you please provide output from your Cmdlet call?

**Comment by tkubica12** [comment]
Just learning, focused more on containers, OpenStack and network automation, sorry if missing some background here.

Attached verbose output with and without eg specified (without specified failing). Server object in my case does not have enclosureGroupUri attribute, but encloser uri is under locationUri key.

Also - playing on Oneview DCS 2.00, there might also be issue specific to that...

Thanks
[noeg.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/405643/noeg.txt)
[witheg.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/405644/witheg.txt)

**Comment by ChrisLynchHPE** [comment]
`locationUri` is the associated Enclosure property of a Server Hardware device.  It does not represent the Enclosure Group.  Have you claimed your Enclosure for Management?  Looks like I may not be handling a null property value of the Server Hardware.

**Comment by tkubica12** [comment]
I believe so. Not understanding PowerShell, but it seems serverGroupUri in server object it the same as enclosureGroupUri, correct? There seems to be just one reference to serverGroupUri in code:

#Handle Blade Server objects
                        if ($server.serverGroupUri) 
						{ 
							
							$serverProfile.enclosureGroupUri = $server.serverGroupUri 
						
						}

Code that do networks lookup seems to reference $EnclosureGroup.uri only and it seems this has not been populated from serverGroupUri, was it?

**Comment by ChrisLynchHPE** [comment]
The properties are not specific to Powershell. They are API object properties. You will see the same in the Python library.

No, serverGroupUri is not the same as the enclosureGroupUri.  ServerGroupUri is the Enclosure associated with the BL server.  The Enclosure the has an enclosureGroupUri property where it gets the parent config policy from.

**Comment by tkubica12** [comment]
Just trying to identify why my call is failing without eg explicitly defined. API documentation suggest serverGroupUri = enclosureGroupUri:

**serverGroupUri** For blade servers, this is the URI of the containing **enclosure's enclosure group**. This URI can be used to retrieve information about the enclosure group or to identify all the servers in the same group. This value is not set for rack mount servers.

The code seems to copy this to enclosureGroupUri of $serverProfile being created, but network lookup happends before profile is actualy created and reference $EnclosureGroup.uri which seem to me is not populated for case when eg is not explicitly set within a call AND assignment is server. Could this be it? Maybe there might be another elseif for not eg and assignment eq server and hardware eq BL where serverGroupUri is copied to $EnclosureGroup.uri?

**Comment by ChrisLynchHPE** [comment]
> Just trying to identify why my call is failing without eg explicitly defined. API documentation suggest serverGroupUri = enclosureGroupUri:

That's right.  I was mixing up `locationUri` with `serverGroupUri` in the Server Hardware resource.

Can you tell me what version of 2.00 your appliance is?  Is it 2.00.02 or 2.00.07?  I ask because the validation logic that handles the `Connection` parameter has been present for a very long time, and no one has ever reported this condition.  After looking at the information you have provided thus far, and investing further, this does appear to be a defect, and one that needs to be fixed.

**Comment by tkubica12** [comment]
2.00.02-0219211

**Comment by ChrisLynchHPE** [comment]
This has been fixed.  Please update to [Release 2.0.610.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.610.0).  Closing.
