### ISSUE TITLE
Unable to use Connect-HPOVMgmt via POSH scipts 

### ISSUE THREAD

**Issue by kbrocheler** [HewlettPackard/POSH-HPOneView#165]
I am trying to use Powershell POSH scripts supplied by HP to do an automated backup of the Oneview appliance. Unfortunately i am unable to connect with POSH to the oneview appliance. I keep getting the error:

Send-HPOVRequest : The operation has timed out
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:6724 char:34
+ $applianceVersion = (Send-HPOVRequest $script:ApplianceXApiVersionUr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Send-HPOVRequest

Connect-HPOVMgmt : The appliance you are connecting to supports an older version of this library. Please visit
https://github.com/HewlettPackard/POSH-HPOneView for a supported version of the library.
At line:1 char:1
+ Connect-HPOVMgmt scl-scm-pr045@scl.local -User xxxxxxx -password xxxxxxxx -Au ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : OperationStopped: (scl-scm-pr045@scl.local:String) [Connect-HPOVMgmt], NotImplementedExc
eption
+ FullyQualifiedErrorId : LibraryTooNew,Connect-HPOVMgmt

I have tried almost all POSH versions available:

2.0.4.0 Does not work
2.0.202.0 Does not work
2.0.296.0 Does not work
2.0.430.0 Does not work
2.0.474.0 Too new
2.0.436.0 Too new
2.0.435.0 Too new
2.0.604.0 Too new

Command used to connect:

Connect-HPOVMgmt scl-scm-pr045@scl.local -User xxxxx -password xxxxxxx -AuthProvider SCL

**Comment by ChrisLynchHPE** [comment]
Why are you trying to use a UPN or Email address for the `-Hostname` parameter?  Please use an IP Address or FQDN and try your call again.

**Comment by kbrocheler** [comment]
That's because when i try ip-address or hostname or FQDN i get the following error:

Send-HPOVRequest : {0} Authentication failed because of an internal error in the authentication service. The following
message was returned: {0}
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:6992 char:21
+             $resp = Send-HPOVRequest $loginSessionsUri POST $_authinfo -Hostname ...
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationExceptio
   n
    + FullyQualifiedErrorId : InvalidAuthOperation,Send-HPOVRequest

So i found an article that suggested using the hostname@domain.local option and indeed the script went on but gave the message listed before.

Even when i do not use any options in my connect line and enter them manually it will not let me connect:

PS C:\Users\usr_sim_karlb> Connect-HPOVMgmt

cmdlet Connect-HPOVMgmt at command pipeline position 1
Supply values for the following parameters:
Hostname: 10.10.0.144
UserName: svc_hpov
Password: **********
Connect-HPOVMgmt : Cannot process argument transformation on parameter 'Appliance'. Cannot convert value to type
System.String.
At line:1 char:1
+ Connect-HPOVMgmt
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Connect-HPOVMgmt], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Connect-HPOVMgmt

**Comment by ChrisLynchHPE** [comment]
The `Connect-HPOVMgmt` Cmdlet does not support using a UPN to connect to a remote server.  The `-Hostname` parameter value must be an IP Address, Hostname or FQDN.

```Powershell
Send-HPOVRequest : {0} Authentication failed because of an internal error in the authentication service. The following
message was returned: {0}
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:6992 char:21
$resp = Send-HPOVRequest $loginSessionsUri POST $_authinfo -Hostname ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
CategoryInfo : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationExceptio n
FullyQualifiedErrorId : InvalidAuthOperation,Send-HPOVRequest
```
This looks to be an issue with your appliance and the auth provider you are trying to use.  Although, I have not seen that particular error before myself.  Can you provide more information on what appliance version you are trying to use?  And are you trying to use an HPE OneView embedded or External Directory account?

**Comment by kbrocheler** [comment]
Hi Chris,

It’s a Oneview 2.00.07 appliance (we have two, both don’t work with the script). I have tried both the Local Administrator account as an Active Directory account. Both won’t work. I tried all kinds of combinations even just using the Connect-HPOVMgmt with no switches and just entering either local or domain account. But no result so far.

Best Regards,

Karl

Van: Chris Lynch [mailto:notifications@github.com]
Verzonden: dinsdag 16 augustus 2016 19:15
Aan: HewlettPackard/POSH-HPOneView <POSH-HPOneView@noreply.github.com>
CC: Karl Bröcheler <karl.brocheler@simac.com>; Author <author@noreply.github.com>
Onderwerp: Re: [HewlettPackard/POSH-HPOneView] Unable to use Connect-HPOVMgmt via POSH scipts (#165)


The Connect-HPOVMgmt Cmdlet does not support using a UPN to connect to a remote server. The -Hostname parameter value must be an IP Address, Hostname or FQDN.

Send-HPOVRequest : {0} Authentication failed because of an internal error in the authentication service. The following

message was returned: {0}

At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:6992 char:21

$resp = Send-HPOVRequest $loginSessionsUri POST $_authinfo -Hostname ...

CategoryInfo : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationExceptio n
FullyQualifiedErrorId : InvalidAuthOperation,Send-HPOVRequest

This looks to be an issue with your appliance and the auth provider you are trying to use.  Although, I have not seen that particular error before myself.  Can you provide more information on what appliance version you are trying to use?  And are you trying to use an HPE OneView embedded or External Directory account?

**Comment by ChrisLynchHPE** [comment]
As I am unable to reproduce your issue, I will need the output from $PSVerionTable on your Windows system and more information from the exception you are getting.  Please do the following, and attach the file that is generated:

```PowerShell
PS C:\> $Password = Read-Host -Prompt 'Password'
PS C:\> Start-HPOVTranscript $env:temp\connect_transcript.txt
PS C:\> Connect-HPOVMgmt -Hostname 10.10.0.144 -Username Administrator -Password $Password -verbose
PS C:\> $Error | % { Format-List -InputObject $_  * -force; Write-Host '------------------------------------' }
PS C:\> Stop-Transcript
```

The `connect-transcript.txt` file will be created in your users `%temp%` directory.  Report back with that file by attaching it.

**Comment by kbrocheler** [comment]
Hi Chris.

I tried running the script but it looks like the Start-HPOVTranscript is not a part of the library. I am unable to run the command and when i look at the commands included it is indeed not listed. Can you give me the correct command?

**Comment by ChrisLynchHPE** [comment]
You need to have a current version of the 2.00 library in order to use that Cmdlet.  It was added in a recent release.  So please use the 2.0.604 library and follow the steps above.

**Comment by kbrocheler** [comment]
I am using the 2.0.604 library, and it still comes with an error that the command is not found. But for whatever reason i skipped the transcript command and went on with the Connect-HPOVMgmt command it worked...

So i got the whole thing scripted & scheduled and working :-)

**Comment by ChrisLynchHPE** [comment]
Sorry, the Cmdlet name was a typo.  The `Start-Transcript` Cmdlet is a native one provided by Microsoft.  We have a `Start-HPOVLibraryTrace` that does a similar thing, and even invokes `Start-Transcript`.

Glad you have your issue fixed.  Can you kindly tell me what you did to fix your problem?  It would be helpful to know this so if someone else reports a similar issue, I can be more helpful in guidance other than asking for a debug trace.

**Comment by kbrocheler** [comment]
Good question, when using the faulty script (with the typo) the connect commandlet worked, in all other scenarios it did not. So could not tell you why or how. 

This is the powershell script we run at the moment:

import-module HPOneView.200
$Path = "D:\Reports\Oneview\PR045\"
Connect-HPOVMgmt -Hostname 10.10.0.145 -Username Administrator -Password xxxxxx
new-HPOVBackup -Location $Path
# Delete all Files in C:\temp older than 31 day(s)
$Daysback = "-31"
$CurrentDate = Get-Date
$DatetoDelete = $CurrentDate.AddDays($Daysback)
Get-ChildItem $Path | Where-Object { $_.LastWriteTime -lt $DatetoDelete } | Remove-Item
