### ISSUE TITLE
Get-HPOVEulaStatus -- Send-HPOVRequest : The Property 'SslChecked' cannot be found on this object. verify that the property exists and can be set.

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#166]
### Expected Behavior
Get-HPOVEulaStatus -appliance <hostname/ip>

### Actual Behavior
Send-HPOVRequest : The Property 'SslChecked' cannot be found on this object. verify that the property exists and can be set.
HPOneView.200.psm1:11074 char:19

### Steps to reproduce
Get-HPOVEulaStatus -appliance <hostname/ip>

Seems to encompass several cmdlets, e.g. Set-HPOVEulaStatus: HPOneView.200.psm1:11203 char:19

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.610.0
HPE OneView Appliance Version: 2.00.07

**Comment by ChrisLynchHPE** [comment]
Related to [167]. consolidating issues.
