### ISSUE TITLE
Unable to create Enclosure Group without Logical Interconnect Group

### ISSUE THREAD

**Issue by goelaa** [HewlettPackard/POSH-HPOneView#168]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Create new enclosure group without a logical interconnect group being created

### Actual Behavior
Creating a new enclosure group, requires logical internconnect group

### Steps to reproduce
Is documented in help file

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.620.0
HPE OneView Appliance Version:  2.00.07-0250853
Output from `$PSVersionTable` on your Windows Host:
Name                      Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by ChrisLynchHPE** [comment]
You cannot create an Enclosure Group without a Logical Interconnect Group.  This is enforced by the appliance.

In which documentation states that you can create an Enclosure Group without a Logical Interconnect Group?  The following is the `Description` of `New-HPOVEnclosureGroup`:

> Create a new Enclosure Group.  **An existing Logical Interconnect Group must be created prior to creating an Enclosure Group**.

**Comment by goelaa** [comment]
Sorry, the help file for Powershell says it is required, however, I can create enclosure groups without logical interconnect groups on the appliance.

Right now  I have 2 enclosure groups and 0 interconnect groups.
![enclosure_groups](https://cloud.githubusercontent.com/assets/20292361/17956996/a3e64c84-6ac0-11e6-9cc1-338b93eeded9.PNG)
![logical_interconnect](https://cloud.githubusercontent.com/assets/20292361/17956997/a40168d4-6ac0-11e6-8316-196f600dcbf5.PNG)

**Comment by ChrisLynchHPE** [comment]
Sorry, you're right.  We did enforce Logical Interconnect Groups with 1.20 and older appliances.  2.00 we relaxed that restriction.  I'll add this to the backlog as an enhancement.

**Comment by ChrisLynchHPE** [comment]
After looking at this, it was a rather easy enhancement.  I'll be including this within the release I'll publish today that addresses another issue reported.

**Comment by ChrisLynchHPE** [comment]
I added this enhancedment to the [Release 2.0.621.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.621.0) update.
