### ISSUE TITLE
Update NetworkSet with networks existing on SUS (UplinkSet)

### ISSUE THREAD

**Issue by 5truja** [HewlettPackard/POSH-HPOneView#170]
Please fill in as much information as possible to help resolve your issue.
I would like to script to add networks to NetworkSet by using Set-HPOVNetworkSet and networks as a parameters in list or something like that
### Actual Behavior

$Net1 = Get-HPOVNetwork 'Network-100-A'
$Net2 = Get-HPOVNetwork 'Network-101-A'
$NetList = @($Net1, $Net2)
Set-HPOVNetworkSet -netSet "NSet-A" -networks @($NetList)

### Steps to reproduce
2.00.07-0250853

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
2.0
HPE OneView Appliance Version:  

2.00.07-0250853

Output from `$PSVersionTable` on your Windows Host:
2.00.07-0250853

**Comment by ChrisLynchHPE** [comment]
I'm not sure what you are asking for. We already have a `Set-HPOVNeteorkSet` Cmdlet.

**Comment by 5truja** [comment]
I know but the only example I could see was to put all networks i a brackets. I would like to have them listed above and than use parameter like array "list" in order to have better overview. Is that possible?


1 sep. 2016 kl. 18:56 skrev Chris Lynch <notifications@github.com<mailto:notifications@github.com>>:


I'm not sure what you are asking for. We already have a Set-HPOVNeteorkSet Cmdlet.

-

**Comment by ChrisLynchHPE** [comment]
The -Networks paramete IS an Array type.  So if you wanted to do any of the following:
 
-Networks $net1,$net2,$net3
 
Or
 
-Networks @($net1,$net2,$net3)
 
Or
 
$Nets = $net1,$net2,$net3
-Networks $Nets
 
Or 
 
$Nets = @($net1,$net2,$net3)
-Networks $Nets
 
Are all perfectly valid.  The example shows one way.  What I have shown above is simply standard PowerShell capabilities.

**Comment by 5truja** [comment]
Hi,

OK. I will try that.

Thanks Chris.


1 sep. 2016 kl. 19:40 skrev Chris Lynch <notifications@github.com<mailto:notifications@github.com>>:


The -Networks paramete IS an Array type. So if you wanted to do any of the following:

-Networks $net1,$net2,$net3

Or

-Networks @($net1,$net2,$net3)

Or

$Nets = $net1,$net2,$net3
-Networks $Nets

Or

$Nets = @($net1,$net2,$net3)
-Networks $Nets

Are all perfectly valid. The example shows one way. What I have shown above is simply standard PowerShell capabilities.

-

**Comment by 5truja** [comment]
Hi Chris,

I was running this:

$Net501 = Get-HPOVNetwork 'LEG-LND-RDH-SERV1-501-A'
Set-HPOVNetworkSet -netSet "NSet-SHL-V-SUS-A" -networks @($Net501)

And it fails with this:

Send-HPOVRequest : A network set referenced in one or more server profiles may
only contain networks which are defined as internal networks or associated with
an uplink set on the logical interconnects associated with the enclosure conta
ining these server profiles.
At C:\Users\adm127856\Documents\WindowsPowerShell\Modules\HPOneView.120\HPOneVi
ew.120.psm1:2521 char:9
+         Send-HPOVRequest $uri PUT $resource
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (network-sets:String) [Send-HP
   OVRequest], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Send-HPOVRequest

What am I missing here?

I my scenario I would like to APPEND new additional networks (already created and  added to uplinkSets) to the existing NetSet (having some other networks that I would like keep).
So I tried a script having just 2 lines above and it fails.

Maybe it is not possible to alter (append new networks) the existing NetworkSet but only to create new NetworkSet from scratch listing ALL (new and “old) networks again.

Which is the correct way and do I need to point to LIG or uplink set in my command line? I believe not sinc NetworkSet itself is unique.

Kind regards

**Comment by 5truja** [comment]
While this command for creation of new NetworkSet works fine and I would like to be able to alter it and append new Networks to it:


# Now, create a "A-Side" Network Set, grouping 3 of these networks for convenience:
$network501A = Get-HPOVNetwork -name "VLAN-501-A" -type "Ethernet"
$network502A = Get-HPOVNetwork -name "VLAN-502-A" -type "Ethernet"
$network504A = Get-HPOVNetwork -name "VLAN-504-A" -type "Ethernet"
New-HPOVNetworkSet -name "Production Networks-A" -networkUris $network501A.uri,$network502A.uri,$network504A.uri

# Now, create a "B-Side" Network Set, grouping 3 of these networks for convenience:
$network501B = Get-HPOVNetwork -name "VLAN-501-B" -type "Ethernet"
$network502B = Get-HPOVNetwork -name "VLAN-502-B" -type "Ethernet"
$network504B = Get-HPOVNetwork -name "VLAN-504-B" -type "Ethernet"
New-HPOVNetworkSet -name "Production Networks-B" -networkUris $network501B.uri,$network502B.uri,$network504B.uri

Kind regards


From: Brekalo Mladen
Sent: den 5 september 2016 13:33
To: 'HewlettPackard/POSH-HPOneView' <reply@reply.github.com>; HewlettPackard/POSH-HPOneView <POSH-HPOneView@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [HewlettPackard/POSH-HPOneView] Update NetworkSet with networks existing on SUS (UplinkSet) (#170)

Hi Chris,

I was running this:

$Net501 = Get-HPOVNetwork 'LEG-LND-RDH-SERV1-501-A'
Set-HPOVNetworkSet -netSet "NSet-SHL-V-SUS-A" -networks @($Net501)

And it fails with this:

Send-HPOVRequest : A network set referenced in one or more server profiles may
only contain networks which are defined as internal networks or associated with
an uplink set on the logical interconnects associated with the enclosure conta
ining these server profiles.
At C:\Users\adm127856\Documents\WindowsPowerShell\Modules\HPOneView.120\HPOneVi
ew.120.psm1:2521 char:9
+         Send-HPOVRequest $uri PUT $resource
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (network-sets:String) [Send-HP
   OVRequest], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Send-HPOVRequest

What am I missing here?

I my scenario I would like to APPEND new additional networks (already created and  added to uplinkSets) to the existing NetSet (having some other networks that I would like keep).
So I tried a script having just 2 lines above and it fails.

Maybe it is not possible to alter (append new networks) the existing NetworkSet but only to create new NetworkSet from scratch listing ALL (new and “old) networks again.

Which is the correct way and do I need to point to LIG or uplink set in my command line? I believe not sinc NetworkSet itself is unique.

Kind regards

**Comment by ChrisLynchHPE** [comment]
> Send-HPOVRequest : A network set referenced in one or more server profiles may only contain networks which are defined as internal networks or associated with an uplink set on the logical interconnects associated with the enclosure containing these server profiles.

This message is stating that you have not added that network to an Uplink Set or Internal Network within a Logical Interconnect Group or Logical Interconnect.  The operation you are also trying to do is setting the complete list of Networks.  You are not adding that network TO the existing Network Set.  You need to provide the complete list of Networks that must be present within the Network Set.

So, if your Network Set contained the following networks:

* Red
* Blue
* Green

And you wanted to add Yellow, then you need to add all 4.  The `Set-HPOVNetworkSet` Cmdlet will replace the existing Networks with the list you provide.

**Comment by 5truja** [comment]
OK. The part with listing all networks (old and new) is cristal clear but the part regarding the networks defined in uplinkset is not since these networks were defined in uplinkset. I checked this after getting the message you were mentioned. However i will do some more tests with less networks. I am wondering if the opposite is possible, which means if i have 10 networks defined in uplinkset and i want to set 29 and it fails.
Best regards


5 sep. 2016 kl. 23:52 skrev Chris Lynch <notifications@github.com<mailto:notifications@github.com>>:


Send-HPOVRequest : A network set referenced in one or more server profiles may only contain networks which are defined as internal networks or associated with an uplink set on the logical interconnects associated with the enclosure containing these server profiles.

This message is stating that you have not added that network to an Uplink Set or Internal Network within a Logical Interconnect Group or Logical Interconnect. The operation you are also trying to do is setting the complete list of Networks. You are not adding that network TO the existing Network Set. You need to provide the complete list of Networks that must be present within the Network Set.

So, if your Network Set contained the following networks:

  *   Red
  *   Blue
  *   Green

And you wanted to add Yellow, then you need to add all 4. The Set-HPOVNetworkSet Cmdlet will replace the existing Networks with the list you provide.

-

**Comment by ChrisLynchHPE** [comment]
The `Uplink Set` defines what L2 Fabric(s)/Network(s) will be associated with what `Uplink Ports`.  It is the outer most resource in our resource model.  Network Sets, and even Network Connections, can only have Networks associated if the L2 Fabric/Network is assigned to a Logical Interconnect Groups Uplink Set or Internal Networks as of HPE OneView 2.0.  Prior to 2.0, any created Ethernet Network resource would be implicitly provisioned to all managed Virtual Connect Ethernet-capable resource. In 2.0 and newer, you have to explicitly add the Ethernet Network to either the Uplink Set or Internal Network. The same is said of the Logical Interconnect, and it is derived from the parent Logical Interconnect Group policy.

**Comment by 5truja** [comment]
Hi Chris,

Thanks for the explanation.

Kind regards


6 sep. 2016 kl. 18:34 skrev Chris Lynch <notifications@github.com<mailto:notifications@github.com>>:


The Uplink Set defines what L2 Fabric(s)/Network(s) will be associated with what Uplink Ports. It is the outer most resource in our resource model. Network Sets, and even Network Connections, can only have Networks associated if the L2 Fabric/Network is assigned to a Logical Interconnect Groups Uplink Set or Internal Networks as of HPE OneView 2.0. Prior to 2.0, any created Ethernet Network resource would be implicitly provisioned to all managed Virtual Connect Ethernet-capable resource. In 2.0 and newer, you have to explicitly add the Ethernet Network to either the Uplink Set or Internal Network. The same is said of the Logical Interconnect, and it is derived from the parent Logical Interconnect Group policy.

-

**Comment by ChrisLynchHPE** [comment]
Closing.
