### ISSUE TITLE
The "Welcome to .. POSH Library" says _BETA.

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#172]
Just to let you know that it says BETA when loading the module for 621.0

Import-Module HPOneView.200

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): v2.0.621.0_BETA

**Comment by ChrisLynchHPE** [comment]
DOH!  That obviously should not be in the welcome banner.  I have an update to release soon, so will have that fixed.

**Comment by erikgraa** [comment]
Cool. Do you have an ETA on that update?

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.630.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.630.0).

Closing
