### ISSUE TITLE
New-HPOVServerProfile Task not sent to Appliance

### ISSUE THREAD

**Issue by CermakPOI** [HewlettPackard/POSH-HPOneView#174]
The command in Actual Behavior does NOT create the Task in the One View Appliance.
The Task is not visible in the OneView Appliance GUI (i suppose it's not sent at all), there is no Error Message or reason.

### Actual Behavior
```

$task = New-HPOVServerProfile -Name $ProfileNameNow -connections $arrProfConn -Description "$ProfileNameNow" -AssignmentType unassigned -ServerHardwareType $MyHW -EnclosureGroup $
MyEncGroup -ManageBoot -BootOrder ("PXE","Harddisk","CD","USB","Floppy") -ApplianceConnection $objHPOV?Connection
$task

Appliance    Name   Owner         Created             Duration TaskState PercentComplete
---------    ----   -----         -------             -------- --------- ---------------
16.55.43.103 Create Administrator 29.09.2016 09:50:29 00:00:00 New       0
PS C:\> Wait-HPOVTaskStart -task $task

Appliance    Name   Owner         Created             Duration TaskState PercentComplete
---------    ----   -----         -------             -------- --------- ---------------
16.55.43.103 Create Administrator 29.09.2016 09:50:29 00:00:01 Error     100

```

### Version Information
HPE OneView PowerShell Library Version (Get-HPOVVersion): 2.0.621.0
HPE OneView Appliance Version: 2.00.02-0219211
Output from $PSVersionTable on your Windows Host:
Name : PSVersion
Value : 4.0

Name : WSManStackVersion
Value : 3.0

Name : SerializationVersion
Value : 1.1.0.1

Name : CLRVersion
Value : 4.0.30319.42000

Name : BuildVersion
Value : 6.3.9600.17400

Name : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name : PSRemotingProtocolVersion
Value : 2.2

**Comment by ChrisLynchHPE** [comment]
To see what the error reason was, either use Format-List (as an `[HPOneView.Appliance.TaskResource] object will default to a formatted table output), or use `$task.taskErrors` to see why the task failed.

**Comment by ChrisLynchHPE** [comment]
Closing issue.  We can re-open this if you still have an issue.
