### ISSUE TITLE
New-HPOVServerProfileConnection FibreChannel requires MAC

### ISSUE THREAD

**Issue by CermakPOI** [HewlettPackard/POSH-HPOneView#177]
Please fill in as much information as possible to help resolve your issue.
I want to import Data from a VCEM Export into OneView. 
Unfortunately the SAN Connection needs a MAC address which is not needed in the GUI (see screenshot) In the OneView GUI the mac is auto created if left empty. I need this behaviour in the Script to import my SAN WWNs without Mac.
I hope you can help me, it's quite urgent now.
### Expected Behavior

Like in GUI when no mac is provided
![28-10-2016 09-10-03](https://cloud.githubusercontent.com/assets/11089205/19797982/a5d23c3c-9cee-11e6-8d71-1ca4f5d8e02a.png)

```
$arrProfConn += New-HPOVServerProfileConnection -connectionId 9 -name SAN1 -connectionType FibreChannel -Network $MySan -userdefined -
WWNN 50:01:43:80:02:A3:00:01 -WWPN 50:01:43:80:02:A3:00:00 -MAC auto -RequestedBW 8000
```

SAN connection created successfully...
### Actual Behavior

```
$arrProfConn += New-HPOVServerProfileConnection -connectionId 9 -name SAN1 -connectionType FibreChannel -Network $MySan -userdefined -
WWNN 50:01:43:80:02:A3:00:01 -WWPN 50:01:43:80:02:A3:00:00 -MAC auto -RequestedBW 8000
New-HPOVServerProfileConnection : Cannot validate argument on parameter 'MAC'. The "$_ -match $script:macAddressPattern" validation script for the argument with value
"auto" did not return a result of True. Determine why the validation script failed, and then try the command again.
At line:1 char:199
+ ... :A3:00:00 -MAC auto -RequestedBW 8000
+                    ~~~~
    + CategoryInfo          : InvalidData: (:) [New-HPOVServerProfileConnection], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-HPOVServerProfileConnection

```

Without the Parameter -MAC

```
$arrProfConn += New-HPOVServerProfileConnection -connectionId 9 -name SAN1 -connectionType FibreChannel -Network $MySan -userdefined -
WWNN 50:01:43:80:02:A3:00:01 -WWPN 50:01:43:80:02:A3:00:00 -MAC auto -RequestedBW 8000
New-HPOVServerProfileConnection : Parameter set cannot be resolved using the specified named parameters.

```
### Version Information

HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.630.0
PE OneView Appliance Version: 2.00.02-0219211
Output from $PSVersionTable on your Windows Host:
Name : PSVersion
Value : 4.0

Name : WSManStackVersion
Value : 3.0

Name : SerializationVersion
Value : 1.1.0.1

Name : CLRVersion
Value : 4.0.30319.42000

Name : BuildVersion
Value : 6.3.9600.17400

Name : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name : PSRemotingProtocolVersion
Value : 2.2

**Comment by CermakPOI** [comment]
I modded HPOneView.200.psm1 Line 51847 to support  -mac auto
```
if ($connectionType -eq "FibreChannel")
{
	if($mac -eq "auto") {
		$_conn.macType  = "Virtual" 
		$_conn.mac      = "" 
	} else {
		$_conn.macType  = "UserDefined" 
		$_conn.mac      = $mac 
	}
	$_conn.wwpnType = "UserDefined" 
	$_conn.wwnn     = $wwnn
	$_conn.wwpn     = $wwpn 
}
```

**Comment by ChrisLynchHPE** [comment]
Looks like you have run into the sole corner case that is difficult to support in creating the Connection.  The Cmdlet has no knowledge of the potential hardware the Connection you are trying to create will be for.  What I could do is remove the requirement for the `-MAC` parameter by changing the `Mandatory` declaration to `$false`.  I could then document that the parameter is required for CNA adapters, but not for FC mezzanine adapters.

**Comment by ChrisLynchHPE** [comment]
Actually, if you change your IF statement slightly, it would work better, and you will not need to touch any of the parameter definitions:

```PowerShell
if ($connectionType -eq "FibreChannel")
{
    if($PSBoundParameters['mac'])
    {
        $_conn.macType  = "UserDefined" 
        $_conn.mac      = $mac 
    }
    $_conn.wwpnType = "UserDefined" 
    $_conn.wwnn     = $wwnn
    $_conn.wwpn     = $wwpn 
}
```

**Comment by ChrisLynchHPE** [comment]
I don't have hardware to fully test this, but my suggestion of checking if `-MAC` was provided generates a valid Server Profile Connection object.

**Comment by CermakPOI** [comment]
Unfortunately i have to modify the parameters, because of the validation pattern ... The validation pattern should support "auto" then it would work.
Alternatively you can validate the MAC when it's needed and not as parameter.

**Comment by ChrisLynchHPE** [comment]
No you don't.  If you omit the parameter, the value will be Auto.

**Comment by ChrisLynchHPE** [comment]
This enhancement has been added to both [Release 3.0.1128.2242](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1128.2242) and [Release 2.0.650.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/2.0.650.0) 

Closing.
