### ISSUE TITLE
New-HPOVLogicalInterconnectGroup produces trailing '0' 

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#178]
[HPOVLogicalInterconnectGroup_transcript.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/565397/HPOVLogicalInterconnectGroup_transcript.txt)
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
New-HPOVLogicalInterConnectGroup should not provide trailing "0"

### Actual Behavior
New-HPOVLogicalInterConnectGroup outputstrailing "0"

### Steps to reproduce
Use any example in New-HPOVLogicalInertconnectGroup
See result in Log file

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.01121.2161
HPE OneView Appliance Version:  3.0
Output from `$PSVersionTable` on your Windows Host:

Name  : PSVersion
Value : 5.1.14393.0

Name  : PSEdition
Value : Desktop

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}

Name  : BuildVersion
Value : 10.0.14393.0

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : WSManStackVersion
Value : 3.0

Name  : PSRemotingProtocolVersion
Value : 2.3

Name  : SerializationVersion
Value : 1.1.0.1

**Comment by ChrisLynchHPE** [comment]
Thanks.  This will be fixed in the 3.00 update being released today.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1128.2242](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1128.2242).

Closing.
