### ISSUE TITLE
New-HPOVNetwork creates network with bandwidth set to 2.5 Gbps and 10Gbps

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#179]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
When creating Ethernet networks, the cmdelt should take into account values specified in the parameters

### Actual Behavior
New-HPOVNetwork always creates Ethernet network with 2.5Gbps as minium and 10 Gbps as maximum

### Steps to reproduce
New-HPOVNetwork -type Ethernet -name MyNetwork1 -vlanid 100 -typicalbandwidth 5000 -maximumbandwidth 7500

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): See transcript file
HPE OneView Appliance Version:  3.0
Output from `$PSVersionTable` on your Windows Host:
Name  : PSVersion
Value : 5.1.14393.0

Name  : PSEdition
Value : Desktop

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}

Name  : BuildVersion
Value : 10.0.14393.0

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : WSManStackVersion
Value : 3.0

Name  : PSRemotingProtocolVersion
Value : 2.3

Name  : SerializationVersion
Value : 1.1.0.1
[New-HPOVnetwork_HPOV_transcript.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/565423/New-HPOVnetwork_HPOV_transcript.txt)

**Comment by valfr** [comment]
Hello,
Same issue here with : New-HPOVNetwork -Name "myvlan123456" -Type "Ethernet" -VLANType "Tagged" -VlanId "123456" -Purpose "General" -SmartLink $true -PrivateNetwork $false -TypicalBandwidth 6000 -MaximumBandwidth 10000

----
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

Get-HPOVVersion
PowerShell Library Version : 3.0.1121.2161
Library Path               : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting this.  This issue will be fixed in the 3.00 update later today.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1128.2242](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1128.2242).

Closing.
