### ISSUE TITLE
Non-Standard behaviour of -ErrorAction Silentlycontinue

### ISSUE THREAD

**Issue by CermakPOI** [HewlettPackard/POSH-HPOneView#180]
Please fill in as much information as possible to help resolve your issue.
Many HPOV cmdlet do NOT support -ErrorAction Silentlycontinue like all other standard cmdlets.
When  -ErrorAction Silentlycontinue no Error message should be displayed to the user. 
It's confusing for users if errors come up when i the scrips want to just check if a profile exists.

### Expected Behavior
```
$Myitem = get-childitem NotExistingItem -ErrorAction Silentlycontinue
$ProfileFound = Get-HPOVProfile -name NotExistingServerprofile -ErrorAction Silentlycontinue
```
$ProfileFound is just empty.

### Actual Behavior
```
$Myitem = get-childitem NotExistingItem -ErrorAction Silentlycontinue
$ProfileFound = Get-HPOVProfile -name NotExistingServerprofile  -ErrorAction Silentlycontinue

Get-HPOVProfile : The specified Server Profile 'NotExistingServerprofile  ' not found. Please check the name again, and try again.
At Z:\10_Powershell\02_Dev\03_HPE\POI-MigrateVCEM2HPEOV.ps1:143 char:18
+     $ProfileFound = Get-HPOVProfile -name NotExistingServerprofile  -ErrorAction Silentlycont ...
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Name:String) [Get-HPOVServerProfile], ServerProfileResourceException
    + FullyQualifiedErrorId : ServerProfileResourceNotFound,Get-HPOVServerProfile
```
### Version Information
HPE OneView PowerShell Library Version (Get-HPOVVersion): 2.0.630.0
PE OneView Appliance Version: 2.00.02-0219211
Output from $PSVersionTable on your Windows Host:
Name : PSVersion
Value : 4.0

Name : WSManStackVersion
Value : 3.0

Name : SerializationVersion
Value : 1.1.0.1

Name : CLRVersion
Value : 4.0.30319.42000

Name : BuildVersion
Value : 6.3.9600.17400

Name : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name : PSRemotingProtocolVersion
Value : 2.2

**Comment by ChrisLynchHPE** [comment]
It's not that the Cmdlets are supporting a "non-standard" way of trapping errors (which is really what `-ErrorAction` does BTW).  It's that we use the `ThrowTerminatingError()` method to generate exceptions.  Why?  Because it is needed to support multiple appliance connections.  In order to support `-ErrorAction`, we would have to change all `ThrowTerminatingError()` calls to `WriteError()`, which would not work with `Try{}Catch{}` blocks within the Cmdlets.  `-ErrorAction` is left over from when MS introduced PowerShell 1.0.  Microsoft added `Try{}Catch{}`/`Try{}Catch{}Finally{}` into PowerShell 2.0 but never deprecated `-ErrorAction`. 

So, in order to trap errors, you will need to surround your Cmdlet calls or code with a Try{}Catch{} block.  For instance:

```PowerShell
Try
{

	Get-HPOVServerProfile -name NotExistingServerprofile

}

Catch [HPOneView.ServerProfileException]
{

	#Server Profile doesn't exist
	#Do Something

}

Catch
{

	#Something else happened

}
```

**Comment by CermakPOI** [comment]
I'm soo happy test-path and zillions of other cmdlets do not behave like this and require a try catch!
Try-catch is a workaround for bad programming style.

**Comment by ChrisLynchHPE** [comment]
While I disagree with your opinion that `Try{} Catch{}` is "bad programming style", it is for interactive purposes.  I am actively working to add this functionality into the `Get-HPOV` Cmdlets.  Please know that this will break existing scripts for those that have implemented `Try{} Catch{}` blocks, and would only need to add `-ErrorAction Stop` to the `Get-HPOV` Cmdlet calls.

**Comment by ChrisLynchHPE** [comment]
I have added support for `-ErrorAction` on Get-HPOV Cmdlets where providing a resource name would generate a Terminating Error.  Now, they will generate a non-terminating error, which `-ErrorAction` can be used to suppress it with `-ErrorAction SilentlyContinue`.  Received API Errors, missing or unsupported parameters or values will still generate a terminating error.

So, your example:

```PowerShell
$ProfileFound = Get-HPOVProfile -name NotExistingServerprofile -ErrorAction Silentlycontinue
```

will no longer generate a terminating error, and `$ProfileFound` will be `null`.

**Comment by ChrisLynchHPE** [comment]
I'm closing this issue for now.  If you want to discuss this further, feel free to continue, or open a new issue.
