### ISSUE TITLE
Get-HPOVNetwork -Type FCOE does not return FCOE networks

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#182]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Create FCOE network and call Get-HPOVNetwork -Type FCOE.
The call returns no network

### Actual Behavior
Teh call should return FCOE network type

### Steps to reproduce
Create FCOE network
Get-HPOVNetwork -Type FCOE
or
Get-HPOVNetwork
[1611171010_HPOV_transcript.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/598125/1611171010_HPOV_transcript.txt)

### Version Information

HPE OneView PowerShell Library Version ( Get-HPOVVersion ): 3.0.1142.2291
 HPE OneView Appliance Version: 3.00.01-0268448
 Output from  $PSVersionTable  on your Windows Host:
 PSVersion 5.1.14393.0
 PSEdition Desktop
 PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
 BuildVersion 10.0.14393.0
 CLRVersion 4.0.30319.42000
 WSManStackVersion 3.0
 PSRemotingProtocolVersion 2.3
 SerializationVersion 1.1.0.1

**Comment by ChrisLynchHPE** [comment]
This issue has been identified and will be fixed in the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1144.2035 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1144.2035 ).

Closing.
