### ISSUE TITLE
Help Get-HPOV* produces error

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#183]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Produces list of Get-HPOV cmdlets

### Actual Behavior
Get error 

### Steps to reproduce
Help Get-HPOV*
[PowerShell_transcript.INF25.MSUMc4t7.20161123081523.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/609345/PowerShell_transcript.INF25.MSUMc4t7.20161123081523.txt)

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
I found and fixed the issue.  You can use `Update-Help -Module HPOneView.300` to grab the latest offline user documentation and get the fix.  You may also need to add the `-Force` option, as `Update-Help` will not execute more than once within a 24hr period.

**Comment by DungKHoang** [comment]
The help module is updated and it works now
Run this command: Update-Help -Module HPOneView.300 with admin rights
