### ISSUE TITLE
Alert informations

### ISSUE THREAD

**Issue by avneeshjain108** [HewlettPackard/POSH-HPOneView#184]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior

 Get-HPOVAlert -severity CRITICAL -AlertState Cleared
Hi , I am expecting that while pulling the alert information from the hp oneview we are getting all the cleared alerts. where the number is so huge because of which the script is taing so much of time.

I appreciate if you can provide us the option to put for timeline like a day or so , which can help us to reduce the time taken.

### Actual Behavior

 Get-HPOVAlert -severity CRITICAL -AlertState Cleared
till now i am getting around 72000 alerts which are cleared  for one run and as it will run in each 30 mins its not ven finishing within that time.

### Steps to reproduce

you will login on hponeview and run the below command for severity as critical and warning. 

 Get-HPOVAlert -severity CRITICAL -AlertState Cleared

you will come to know the pain.
### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):  2.0.630.0
HPE OneView Appliance Version:  2.0
Output from `$PSVersionTable` on your Windows Host
PS K:\> $PSVersionTable

Name                           Value                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                
PSVersion                      5.0.10586.117                                                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                              
BuildVersion                   10.0.10586.117                                                                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                  
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
For now, you can use the `-Count` parameter to reduce the number of returned alert objects.  You can even include the resource you want alerts for.  Both should be documented examples.

As for the request, we will look into adding support.

**Comment by avneeshjain108** [comment]
we want the alerts for all the resources so we can not retrieve the alerts based on the resources.  Number of cleared alerts are always very high because thats the total count of alerts which are arrived and closed.  Right now we have the limit of it to 78000 . But processing the 78000 alerts took more than 1 hour. by which even the cleared alerts which cam in the same time got missed.  
Let me know, how i can use the count to allow the below command to get only 50 alerts for max.  

Get-HPOVAlert -severity CRITICAL -AlertState Cleared 
 so that it will not take more than 10 mins. atleast.

Thanks in advance.
Avneesh Jain

**Comment by ChrisLynchHPE** [comment]
I'm sorry.  I was confusing `Get-HPOVTask` with `Get-HPOVAlert`.  Currently, there isn't a way to return only a certain number of alerts.  I'm currently looking to add the following parameters to `Get-HPOVAlert`:

* `-Count` This will return only a certain number of alerts.
* `-Timespan` This will return the alerts from now to the TimeSpan value (i.e. $TimeSpan = New-TimeSpan -Start '01 JAN 2016'
* `-Start` will accept a [DateTime] object to get from, and `-End` will also be a [DateTime[ object to end the search (i.e. -Start '01 JAN 2016 18:00' -End '31 JAN 2016 8:00'

**Comment by ChrisLynchHPE** [comment]
Just letting you know that I am almost finished with this work.  I'm working on some important bug fixes.  As soon as they finish testing, then an update will be released.

**Comment by avneeshjain108** [comment]
Thanks for the update chris, i appreciate if you can release the same as early as possible, as my release is still pending.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release v3.0.1170.1773](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1170.1773).

Closing.
