### ISSUE TITLE
Import-Module HPOneView.300

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#185]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Import succeeds with no unexpected errors dropped onto the error stack.

### Actual Behavior
After import the module the following errors are see in the error stack (note no known functionality defect as a result):

Get-Variable : Cannot find a variable with the name 'PesterTest'.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.300\HPOneView.300.psm1:79460 char:15
+ $PesterTest = Get-Variable -Name PesterTest -Scope Global -ErrorAction SilentlyC ...
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PesterTest:String) [Get-Variable], ItemNotFoundException
    + FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.GetVariableCommand

Get-PSSnapin : No Windows PowerShell snap-ins matching the pattern 'Microsoft.PowerShell.Utility' were found. Check
the pattern and then try the command again.
    + CategoryInfo          : InvalidArgument: (Microsoft.PowerShell.Utility:String) [Get-PSSnapin], PSArgumentExcepti
   on
    + FullyQualifiedErrorId : NoPSSnapInsFound,Microsoft.PowerShell.Commands.GetPSSnapinCommand

### Steps to reproduce
Import-Module HPOneView.300

### Version Information
HPE OneView PowerShell Library Version: 3.0.1144.2035
HPE OneView Appliance Version: 3.00.05-0271823 
Output from `$PSVersionTable` on your Windows Host:
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by ChrisLynchHPE** [comment]
This is not an issue. Closing.
