### ISSUE TITLE
Details in help of New-HPOVServerProfile need clarity

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#187]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
The help of new-hpovServerprofile provides the syntax as follow:
New-HPOVServerProfile -Name <String> -AssignmentType <String> -ServerProfileTemplate <Object> [-OSDeploymentPlan <>] [-OSDeploymentAttributes <>] -Enclosure <object>
-EnclosureBay <Int32> -Server <Object> -Description <String> -IscsiIPv4Address <Array> -ISCSIInitatorName <String> -ChapSecret <SecureString> -MutualChap
[-ApplianceConnection <Object>] [<CommonParameters>]

This syntax is used to create a server profile from a server profile template.
and the description of the parameters are
-AssignmentType: Possible values are : Bay , server, unassigned
-Enclosure : Enclosure object.... Only required when AssignementType is ' Bay' 

### Actual Behavior
1/ I notice the following:
if you use the syntax: New-HPOVServerProfile -Name A_Name -ServerProfileTemplate $ThisTemplate -AssignmentType xx
No matter the value of xx is : Server, Bay or unassigned, it always creates an unassigned server profile
as long as you omit the -server parameter
Also when AssignmentType is Bay, you don't need an enclosure object

2/ Also I'm wondering use of the following parameters when creating profile from template:
     a) -EnclosureBay and -Enclosure because you will specify it in -Server parameter
     b) -OSDeployemntPlan and -OSDeploymentAttributes  because you already specify It in profiletemplate

### Steps to reproduce
See description above

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1144.2035
HPE OneView Appliance Version:  
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
> 1/ I notice the following:
> if you use the syntax: New-HPOVServerProfile -Name A_Name -ServerProfileTemplate $ThisTemplate -AssignmentType xx
> No matter the value of xx is : Server, Bay or unassigned, it always creates an unassigned server profile
> as long as you omit the -server parameter
> Also when AssignmentType is Bay, you don't need an enclosure object

You are missing the `-Server` parameter, which is needed in order to assign the Profile to a Server Hardware resource.

> 2/ Also I'm wondering use of the following parameters when creating profile from template:
> a) -EnclosureBay and -Enclosure because you will specify it in -Server parameter
> b) -OSDeployemntPlan and -OSDeploymentAttributes because you already specify It in profiletemplate

No, neither of these parameters are part of `New-HPOVServerProfileTemplate`.  They will be used for HPE Synergy Image Streamer support.  They are not enabled for use yet.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  I can re-open this issue if there is work to be done.
