### ISSUE TITLE
New-HPOVServerProfileTemplate ignores BIOSSettings

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#188]
[SeverProfileTempalte-BIOS_transcript.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/644865/SeverProfileTempalte-BIOS_transcript.txt)
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
When creating a server profile, you can change the BIOS settings.
When creating a server profile template, BIOS settings are ignored 

### Actual Behavior
BIOS Settings are not modified

### Steps to reproduce
New-HPOVServerProfileTemplate -Name Dung-Test-SPT -ServerHardwareType $ThisDLSHT -Bios –BIOSSettings $ThisCustomBIOS

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1144.2035
HPE OneView Appliance Version:  3.05
Output from `$PSVersionTable` on your Windows Host:
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release v3.0.1170.1773](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1170.1773).

Closing.
