### ISSUE TITLE
New-HPOVAddressPoolRange for creating serial number pool range is throwing error

### ISSUE THREAD

**Issue by sivasura** [HewlettPackard/POSH-HPOneView#189]
Please fill in as much information as possible to help resolve your issue.

** I had got a confirmation that Issue number 177 is meant for this issue but seems not tagged correctly with this defect. Hence raising this to track again. Attaching the email conversation for your reference.

[RE  OV 3 0 Lib error  -- Github Issue#177.zip](https://github.com/HewlettPackard/POSH-HPOneView/files/649805/RE.OV.3.0.Lib.error.--.Github.Issue.177.zip)

New-HPOVAddressPoolRange for creating serial number pool range is throwing error

The error is being thrown because of this typo..(It should be "Startswith" instead of "startwith")
Actual in the OV3.0 module:  if (-not($Start.StartWith('VCU'))).
Instead it should be if (-not($Start._StartsWith_('VCU'))) at line number :46637 in HPOneView.300.psm1

### Expected 
The New-HPOVAddressPoolRange should not throw errors after creating the required serial number ranges in the Oneview.

### Actual Behavior
Throws error as below after performing the action which makes the try-catch block fail my script despite of performing the required action.

New-HPOVAddressPoolRange -PoolType vsn -RangeType  Custom -Start "VCUG0ZG9D0" -End "VCUG0ZG9K3"
Method invocation failed because [System.String] does not contain a method named 
'StartWith'.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.300\HPOneView.300.psm1:46627 
char:13
+                                 if (-not($Start.StartWith('VCU')))
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [System.String] does not contain a method named 
'StartWith'.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.300\HPOneView.300.psm1:46637 
char:13
+                                 if (-not($End.StartWith('VCU')))
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Appliance Name Enabled Category Total Allocated Available Reserved Start      End       
--------- ---- ------- -------- ----- --------- --------- -------- -----      ---       
oneview   VSN  True    Custom   256   0         256       0        VCUG0ZG9D0 VCUG0ZG9K3

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
This is a known issue and will be fixed in the next update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release v3.0.1170.1773](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1170.1773).

Closing.
