### ISSUE TITLE
New-HPOVServerProfileTemplate and Server Profile Description

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#192]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
When using the GUI to create a Server Profile Template, you can specify a description for server profile in addition to description of a template

There is no such corresponding parameter in the cmdlet

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):3.0.1170.1173
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
Is this really important?

**Comment by DungKHoang** [comment]
You want me to report any defect
So I do

**Comment by scriptengine** [comment]
>>Is this really important?
Yes I vote it is. (I'm working on creating servers profile templates as you may have gathered)   
Its really useful to have a field like description to drop information about who/ when and how it was created. AND any information the customer wants to put into the description to describe what the profile is for etcetc (the purpose of the description field)

AND If we are using scripting to automate existing manual GUI based processes we need to be able to do the same in PS as any GUI admin.

m(y2cents)

**Comment by ChrisLynchHPE** [comment]
My question wasn't to ask if the parameter should never be added.  I have a lot of other features that need to be added to the library.  So my ask was more about how critical is it?

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1210.3013](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1210.3013).

Closing.
