### ISSUE TITLE
 Get-HPOVServerHardwareType and wilcard in -name parameter

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#194]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
In general the Get-HPOV* cmdlets accepts wildcard for -name parameter
For example : Get-HPOVServer -name "BL*"
The cmdlet  Get-HPOVServerHardwareType does not accept wildcard for its -name parameter

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1170.1173
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
For now, omit the `*` character.  The Cmdlet isn't converting the `*` character to an acceptable HTML encoded value.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1191.2858](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1191.2858).

Closing.
