### ISSUE TITLE
Several examples in help file need to be updated

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#197]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Low priority

Several examples in the help file need to be updated to use -name parameter
Example 3 in help New-HPOVServerProfileLogicalDiskController -examples
$LogicalDisk1 = New-HPOVServerProfileLogicalDisk 'MyDisk'
should be:

$LogicalDisk1 = New-HPOVServerProfileLogicalDisk -name 'MyDisk' 

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1170.1773

HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1191.2858](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1191.2858).

Closing.
