### ISSUE TITLE
Active ICsp connection cause Connect-HPOVMgmt to fail

### ISSUE THREAD

**Issue by susan-ng** [HewlettPackard/POSH-HPOneView#20]
With OneView 1.20, attempt to connect to OneView using the Connect-HPOVMgmt call fails due to the "$global:cimgmtSessionId" variable contains the ICsp connection sessionId.  This results in the error "You are already logged into $Appliance. Please use Disconnect-HPOVMgmt to end your existing session, and then call Connect-HPOVMgmt again."  OneView should use a different global variable name to check for existing OneView connection.

**Comment by ChrisLynchHP** [comment]
ICsp built their library from the HP OneView library, so they need to change the variable and method it uses to check for connection to an appliance.  This is not an HP OneView PowerShell library issue.

**Comment by susan-ng** [comment]
Thank you for your response.  I don't see a project in github for the PowerShell HPICsp module.  Where can I enter an issue to the PowerShell HPICsp module?

Thanks,
Susan

**Comment by ChrisLynchHP** [comment]
Closing.
