### ISSUE TITLE
Set-HPOVAddressPoolSubnet missing subnet Parameter

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#200]
### Expected Behavior
**Using Set-HPOVAddressPoolSubnet  one should be able to update the subnet of a IPV4 Subnet**

The action is supported in the OneView GUI

### Actual Behavior
The -subnet parameters is an input parameter and alias for IPV4Subnet not the subnet mask

### Version Information
HPE OneView PowerShell Library Version:
PowerShell Library Version : 3.0.1121.2161
Library Path               : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:
Name                           Value
----                           -----
PSVersion                      5.1.14393.479
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.479
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by scriptengine** [comment]
UPDATE:
I've now realized that -Subnet (alias IPV4Subnet) is intended as a INPUT parameter.
What is missing **there is not a parameter to support the updating of the subnet MASK**

My OneView GUI allows the updating of the subnet Mask

**Comment by ChrisLynchHPE** [comment]
You can only edit the Subnet Mask when it is not associated with a Network Resource.  Once it is, you can't edit the Subnet Mask.  That is why it is not available.  If you made a mistake creating the Subnet, and have not assigned it to an Ethernet Network, just delete the Subnet and recreate it.

**Comment by scriptengine** [comment]
I can see your point but I can change the subnet in the GUI (when its not been assigned) so logically I should be able to do it  in the code.

However I can see that once in use (the majority of the time) it would not be much use

**Comment by ChrisLynchHPE** [comment]
The initial thought was that if you made a mistake, it would just be easy to delete and re-create it.  Once it is assigned, you can't modify the Subnet Mask value.  I'll mark this as an Enhancement request.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1210.3013](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1210.3013).

Closing.
