### ISSUE TITLE
Help for Set-HPOVAddressPoolSubnet

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#201]
Help for Set-HPOVAddressPoolSubnet needs to be rewritten. It appears to be lifted from New -HPOVAddressPoolSubnet

For Syntax I suggest:
SYNTAX
    Set-HPOVAddressPoolSubnet [-IPv4Subnet <Object>] [-Gateway <IPAddress>] [-Domain <String>] [-DNSServers <Array>] [-ApplianceConnection <Object>] [<CommonParameters>]

(Currently:
Set-HPOVAddressPoolSubnet -IPv4Subnet <Object> -Gateway <IPAddress> -Domain <String> -DNSServers <Array> -ApplianceConnection <Object> [<CommonParameters>]
Which implies all parameters are required)

The Description
DESCRIPTION
    This cmdlet will assist with creating a new IPv4 Address Pool.  When creating a new IPv4 Address Subnet, you must provide the Network ID, Subnet Mask (CIDR [e.g. 24] or IPv4 Address Value [e.g.
    255.255.255.0]), Gateway and Domain Name.  DNS Servers are optional.

Needs to refer to updating not creating new address pools

-IPV4Subnet parameters does not document the subnet alias

### Version Information
HPE OneView PowerShell Library Version
PowerShell Library Version : 3.0.1121.2161
Library Path               : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

**Comment by ChrisLynchHPE** [comment]
Thanks.  I'm working on an update to documentation now.

**Comment by ChrisLynchHPE** [comment]
Linking with #203

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1191.2858](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1191.2858).

Closing.
