### ISSUE TITLE
Documentation on New-HPOVServerProfileTemplate

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#202]
The following details on New_HPOVServerProfileTemplate are not clear

1/  -EnclosureGroup <Object>
    Aliases [-eg]
    The Enclosure Group resource the Server Profile will be bound to.  Only required when Server value is
    "Unassigned".
Feedback: There is no -Server parameter in New_HPOVServerProfileTemplate

2/ -ServerHardwareType <Object>

    The Server Hardware Type reource the Server Profile will be bound to.  Required when Server value is
    "Unassigned" or assigning to an empty device bay in an enclosure which must include the -enclosure and -enclosureBay parameters.

Feedback: There is no -enclosure and -enclosurebay parameter in New_HPOVServerProfileTemplate

3/ When creating a template with local Storage, please document that the LunID parameter of new-HPOVServerProfileLogicalDisk cannot be set to Auto 

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1170.1773
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
Thanks, linking with #203.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1191.2858](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1191.2858).

Closing.
