### ISSUE TITLE
#204 Server_Profile_Template_Multiconnection_Sample.ps1 continues

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#206]
Continuing Issue 204

In this line:
$con2              = Get-HPOVNetwork -Name "VLAN 1-B" | New-HPOVServerProfileConnection -ConnectionID 2 -Name 'VLAN 1-B Connection' -Network $Vlan1B

$Vlan1B has not been defined previously
This would throw an error if this sample was run

I'm guessing but I'd say the "-Network $Vlan1B" is not required as its an alternative to piping the network object into New-HPOVServerProfileConnection

**Comment by ChrisLynchHPE** [comment]
Closing as re-opened #204.
