### ISSUE TITLE
Get-HPOVServerHardwareTypes documentation

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#207]
The help for Get-HPOVServerHardwareTypes 
Is incorrect
The name and application connection are optional

Needs to be something like:
SYNTAX
    Get-HPOVServerHardwareType [-Name <String>] [-ApplianceConnection <Array>] [-exportFile <String>] [<CommonParameters>]

### Version Information
PowerShell Library Version : 3.0.1191.2858
Library Path               : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

**Comment by ChrisLynchHPE** [comment]
Linking with #223

**Comment by ChrisLynchHPE** [comment]
Closing.
