### ISSUE TITLE
Get-HPOVBaseline documentation

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#209]
### Expected Behavior
I'm guessing but I think this what I'm seeing:
    Get-HPOVBaseline [-ApplianceConnection <Array>] [<CommonParameters>]
    Get-HPOVBaseline -File <String> [-ApplianceConnection <Array>] [<CommonParameters>]
    Get-HPOVBaseline -SppName <String> [-Version <String>] [-ApplianceConnection <Array>] [<CommonParameters>]
    Get-HPOVBaseline -HotfixesOnly [<SwitchParameter>] [-ApplianceConnection <Array>] [<CommonParameters>]

### Actual Behavior
Current Help:
SYNTAX
    Get-HPOVBaseline -File <String> -ApplianceConnection <Array> [<CommonParameters>]
    Get-HPOVBaseline -SppName <String> -Version <String> -ApplianceConnection <Array> [<CommonParameters>]
    Get-HPOVBaseline [-HotfixesOnly <SwitchParameter>] -ApplianceConnection <Array> [<CommonParameters>]

### Steps to reproduce
Get-Help Get-HPOVBaseline
Get-HPOVBaseline

### Version Information
PowerShell Library Version : 3.0.1191.2858
Library Path               : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

**Comment by ChrisLynchHPE** [comment]
Actually, no.  This Cmdlet help is documented correctly.

**Comment by ChrisLynchHPE** [comment]
Closing.
