### ISSUE TITLE
New-HPOVServerProfileConnection help bootable and priority

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#210]
The help for New-HPOVServerProfileConnection does not tie -Bootable and -Priority together 

### Expected Behavior
SYNTAX
    New-HPOVServerProfileConnection -ConnectionID <Int32> ... [-Bootable <SwitchParameter> -Priority <String>] ...

### Actual Behavior
SYNTAX
    New-HPOVServerProfileConnection -ConnectionID <Int32> ... [-Bootable <SwitchParameter>] -Priority <String> [-ApplianceConnection <Object>] [<CommonParameters>]
....
    -Priority <String>
        Optional boot option for this connection, but **Required if -bootable is specified.**

### Steps to reproduce
get-help  New-HPOVServerProfileConnection - full

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
You are misunderstanding what `[]` means and how PowerShell help system works.  When developing Cmdlets/Advanced Functions, you group parameters together with what is called `ParameterSets`, which shows up under Syntax.  The `[]` characters mean the parameter would be optional in that ParameterSet.  If the parameter is not within the same group(s) within the Syntax display, then the parameter is not supported.  It gets very complex when you have multiple ParameterSets and parameters.  Just look at `New-HPOVServerProfile` or `New-HPOVServerProfileTemplate` and the parameters there.

**Comment by scriptengine** [comment]
I don't think I am confused and your comments make my point.
"The [] characters mean the parameter would be optional in that ParameterSet."
Using this principle and the help "-Priority Optional boot option for this connection, but Required if -bootable is specified."

As -Priority is optional it should [-Priority]
Further its required when "bootable is specified", hence:
[-bootable -priority <string>]
is the correct specification for the PowerShell help

It may be that this needs to be combined with the ParameterSets, I wasn't trying to rewrite the whole of the functions help but hoped to identify an improvement that should be made.

**Comment by ChrisLynchHPE** [comment]
Unfortunately, you are misunderstanding how PowerShell help works.  There isn't a way to do what you are asking.  Parameter Sets control the behavior or linking parameters together.

**Comment by scriptengine** [comment]
Chris I think I have just learnt a whole heap (I didn't know about Maml files for a start)

My key point is the help says -Priority is optional the help syntax shows it as required.
- In the code (HPOneView.300.psm1) its optional
- In the help (HPOneView.300.psm1-help.xml) its required

The code: 
		[Parameter (Mandatory = **$false**, ParameterSetName = "Ethernet")]
		[Parameter (Mandatory = **$false**, ParameterSetName = "FC")]
		[Parameter (Mandatory = **$false**, ParameterSetName = "ISCSI")]
		[ValidateNotNullOrEmpty()]
		[ValidateSet('NotBootable', 'Primary', 'Secondary', IgnoreCase)]
		[string]**$Priority** = "NotBootable",

Now looking in HPOneView.300.psm1-help.xml ~line 34339:
				<command:parameter **required="true"** globbing="False" pipelineInput="false" position="named" parameterSetName="ISCSI, FC, Ethernet">
					<maml:name>Priority</maml:name>
					<maml:description>
						<maml:para>Optional boot option for this connection, but Required if -bootable is specified.  Accepted values are NotBootable, UseBIOS, Primary or Secondary. When the Connection Type is Ethernet, this affects PXE boot.  If the Connection Type is FibreChannel, this enables BfS settings.         
Default: NotBootable</maml:para>
					</maml:description>
					<command:parameterValue required="true" variableLength="False">String</command:parameterValue>

I'm done. This is really not that important. If I still don't get it , in software that is built in an environment way more complex than I can imagine. Please just close the issue.

**Comment by ChrisLynchHPE** [comment]
MAML files are complex (really wish MS would change the help system to something easier to develop, like Markdown or heck even using JSON).  And trying to match the MAML file with Parameter Set definitions is complex.  There are times where you will see parameters marked as Required, yet it is associated with multiple ParameterSets that have different Requirement values (True or False).

There is nothing to do in this request.  I'll close this.  You can continue to add comments even though it is closed.
