### ISSUE TITLE
(Help) Remove-HPOVServerProfileTemplate examples use strings not objects

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#212]
The help examples for Remove-HPOVServerProfileTemplate name the templates by name [string] and not their object as documented in the Syntax section of the help

### Actual Behavior
SYNTAX
    Remove-HPOVServerProfileTemplate -ServerProfileTemplate <Object>

    -------------------------- EXAMPLE 1 --------------------------

    PS C:\> $task = Remove-HPOVServerProfileTemplate -ServerProfileTemplate "My Template Profile"
    PS C:\> Wait-HPOVTaskComplete $task.uri

    Remove the profile template specifed by name. Wait for remove to complete.

    -------------------------- EXAMPLE 2 --------------------------

    PS C:\> $spt = Get-HPOVServerProfileTemplate -name "My Template Profile"
    PS C:\> Remove-HPOVServerProfileTemplate $spt -confirm:$false

    Remove the profile template specifed by $spt. Disable confirmation prompt.

PS> Get-HPOVServerProfileTemplate -name "TestTemplate1"

Name          Status Server Hardware Type Enclosure Group Affinity Server Profiles
----          ------ -------------------- --------------- -------- ---------------
TestTemplate1 OK     SY 480 Gen9 1        EG1             Bay

PS> Remove-HPOVServerProfileTemplate -ServerProfileTemplate "TestTemplate1"
Remove-HPOVServerProfileTemplate : A positional parameter cannot be found that accepts argument 'TestTemplate1'.
At line:1 char:1
+ Remove-HPOVServerProfileTemplate -ServerProfileTemplate "TestTemplate ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-HPOVServerProfileTemplate], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Remove-HPOVServerProfileTemplate

### Steps to reproduce
Above

### Version Information
PowerShell Library Version : 3.0.1191.2858
Library Path               : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

**Comment by scriptengine** [comment]
Further you may want to remove **name(s)** from the help:
The Help:
    -ServerProfileTemplate <Object>
        Aliases [-spt, -name]
        The server profile tempalte object(s) **or name(s)** to be removed.

**Comment by ChrisLynchHPE** [comment]
Yes, Name should be removed.  However, the parameter alias within the Cmdlet will not be.  It is to maintain backwards compatibility with existing scripts.

**Comment by ChrisLynchHPE** [comment]
Linking with #223

**Comment by ChrisLynchHPE** [comment]
While this is a documentation defect, the error you are getting is also a defect.  The Cmdlet still does support providing a resource name, and the call to `Get-HPOVServerProfileTemplate` has a defect not using the `-Name` parameter.  So, I'll also have that fixed.

**Comment by ChrisLynchHPE** [comment]
And after I look at this a bit more, this isn't a documentation issue at all.  The exception you received is the real defect here.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1210.3013](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1210.3013).

Closing.
