### ISSUE TITLE
Get-HPOVTask with URI fails to return an object

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#214]
### Expected Behavior
get-help Get-HPOVTask:

DESCRIPTION
    Obtain a collection of task resources which have the specified name and/or state.  **The returned data will include the task name, owner, state and status.**
    -InputObject [<Object>]
        Related resource Name, **URI** or Object to the task. To be used for filtering tasks specific to a resource object (i.e. Server Profile).

### Actual Behavior
In the following example line 1 demonstrates that the command is not returning anything
Line 2 demonstrates the URI is valid and that the appliance has such a task object

1-PS> Get-HPOVTask -InputObject "/rest/tasks/4061EF75-17F4-40A1-8EFC-4C701C39156E"  | gm
gm : You must specify an object for the Get-Member cmdlet.
At line:1 char:81
-InputObject "/rest/tasks/4061EF75-17F4-40A1-8EFC-4C701C39156E"  | gm
bla bla bla
NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand

2-PS> Send-HPOVRequest "/rest/tasks/4061EF75-17F4-40A1-8EFC-4C701C39156E"
Appliance   Name    Owner         Created             Duration TaskState PercentComplete
172.16.1.52 Create  administrator 12/01/2017 16:57:13 00:00:00 Error     100

### Steps to reproduce
$ATaskURI = (Get-HPOVTask -State completed | select -first 1).uri 
Get-HPOVTask -InputObject $ATaskURI | gm 
Send-HPOVRequest $ATaskURI

### Version Information
PowerShell Library Version : 3.0.1191.2858
Library Path               : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

**Comment by ChrisLynchHPE** [comment]
URI support has slowly been deprecated in a number of Cmdlets.  Looks like documentation hasn't been updated to reflect that accurately.  Please use Send-HPOVRequest to interact via object URIs if you need to.

**Comment by scriptengine** [comment]
Further I don't believe that when using a HPOV task object  Get-HPOVTask returns a anything.

In the following example I can use Wait-HPOVTaskComplete to fetch the status of a task but Get-HPOVTask returns null:

Sample Code: 
    "1.."
    Wait-HPOVTaskComplete -InputObject $objOVTask
    "2.."
    Get-HPOVTask -InputObject $objOVTask
    "Type:"
    Wait-HPOVTaskComplete -InputObject $objOVTask

Sample Output (there is nothing between 2&3)
1..

Appliance   Name    Owner         Created             Duration TaskState PercentComplete
172.16.1.52 Create  administrator 12/01/2017 17:48:23 00:00:00 Error     100


2..
3..

Appliance   Name    Owner         Created             Duration TaskState PercentComplete
172.16.1.52 Create  administrator 12/01/2017 17:48:23 00:00:00 Error     100

**Comment by ChrisLynchHPE** [comment]
> Further I don't believe that when using a HPOV task object Get-HPOVTask returns a anything.

You are using the Cmdlet wrong.  `-InputObject` is used for resources that would or could have an Async task (aka job) and return only tasks for that resource, not a task resource object itself.  As it states in the help for `InputObject`

> Related resource Name, URI or Object to the task. To be used for filtering tasks specific to a resource object (i.e. Server Profile).

If you wanted to get the async task and its status, use the `Wait-HPOVTaskComplete` Cmdlet.

**Comment by scriptengine** [comment]
Help reread and understood. Script recoded. **THANK YOU**. 

>>If you wanted to get the async task and its status, use the Wait-HPOVTaskComplete Cmdlet

Any reason not to use (or to?):
$objTask = send-hpovrequest <OV Task URI>
And look in the properties of the returned  object?

**Comment by ChrisLynchHPE** [comment]
If you have a Task object, which is documented in the various Add, New, Set and Remove Cmdlets, you can use the Wait-HPOVTaskComplete Cmdlet to wait for the task to complete.  Yes, you can use `Send-HPOVRequest`, and I would classify that as an advanced use of the library.  I've tried to simplify behaviors and requirements, to conform more to PowerShell than our API.  But, there is nothing stopping you or anyone else from using Send-HPOVRequest and using RAW API objects.

Do know that at some point, the library will change to supporting strongly typed object classes. This won't happen with a bug fix or enhancement release for an existing version.  It will happen in a new major release of the library.

**Comment by ChrisLynchHPE** [comment]
Linking with #223

**Comment by ChrisLynchHPE** [comment]
Closing.
