### ISSUE TITLE
Questions about the default session and connect-hpovmgmt 

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#216]
QUESTION(s)

How should the default OneView connection be changed in the $ConnectedSessions object?
Is there a cmdlet or parameter to do this? Or should the $ConnectedSessions object be manipulated directly?

connect-hpovmgmt sets a new connection to default if a default connection does not exist
Would it be reasonable to ask for connect-hpovmgmt to have a parameter to set the new connection as default?

**Comment by ChrisLynchHPE** [comment]
Closing since there are no further comments.  Feel free to continue to add comments in this issue, as I can always re-open it if needed.
