### ISSUE TITLE
New-HPOVUplinkSet with FC on Synergy frame

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#217]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
When creating FC uplinkset on a Synergy frame, the syntax for UplinkPorts is not working
The documentation says: " Bay2:Q1:1" or "Bay2:Q1.1" but both scenarios do not work 

### Steps to reproduce
See HPOV Library Trace
- Scenario 1: Use syntax Bay2:Q1:1
- Scenario 2: Use syntax Bay2:Q1.1

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): See transcript
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:
[Uplinkset-with-ports-1.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/710775/Uplinkset-with-ports-1.txt)
[Uplinkset-with-ports-2.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/710774/Uplinkset-with-ports-2.txt)

**Comment by ChrisLynchHPE** [comment]
This is a regression in the Cmdlet where I wasn't handling normalizing the Uplink Port(s) requested to supporting both C-Class and Synergy type ports.  I have found and fixed the issue, which will be in the next update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1210.3013](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1210.3013).

Closing.
