### ISSUE TITLE
Error: New-Object : Cannot find type [HPOneView.Appliance.Connection]: verify that the assembly containing this type is loaded.

### ISSUE THREAD

**Issue by BraendiAT** [HewlettPackard/POSH-HPOneView#219]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Connect to Appliance with Connect-HPOVMgmt

### Actual Behavior
```PowerShell
Error: New-Object : Cannot find type [HPOneView.Appliance.Connection]: verify that the assembly containing this type is loaded.
At D:\Temp\POSH-HPOneView-3.00\HPOneView.300.psm1:5610 char:59
+ ... onnection = New-Object HPOneView.Appliance.Connection($tmpConnectionI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
```
### Steps to reproduce
```PowerShell
Connect-HPOVMgmt -Hostname 10.10.10.10 -UserName Administrator -password Password
```
### Version Information

HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
```PowerShell
OneViewPowerShellLibrary libraryLoadedPath
------------------------ -----------------
3.0.1191.2858            D:\Temp\POSH-HPOneView-3.00
```

HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:
```PowerShell
Name                           Value
----                           -----
PSVersion                      5.0.10586.672
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.672
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ChrisLynchHPE** [comment]
It looks like you downloaded the repository tar or zip and not the EXE.  The repo does not contain the core DLL that contains the needed classes.  Please download and use the installer.

**Comment by ChrisLynchHPE** [comment]
@BraendiAT Can you please confirm how you are attempting to load and use the module?

**Comment by BraendiAT** [comment]
I downloaded the installer which fixed my issue.

Thanks

**Comment by i3laze** [comment]
As Installer is currently deprecated, seems HPOneView.500 pre-requires:

> Install-Module FormatPx, SnippetPx

**Comment by ChrisLynchHPE** [comment]
@i3laze PowerShellGet will resolve that for you.  It will download and install the pre-requirements of the library before attempting to install the HPE OneView PowerShell library.
