### ISSUE TITLE
SNMP Access (restriction)

### ISSUE THREAD

**Issue by tlauder** [HewlettPackard/POSH-HPOneView#22]
Is it possible with HP OneView or POSH to restrict SNMP by subnet or IP? I know in the VC Modules themselves, it is possible to set SNMP access, but with OneView, I don't see a similar setting. Any information would be helpful!

Thanks,
Todd

**Comment by ChrisLynchHP** [comment]
As you likely found out, you can only:
* set the Appliance Read-Only Community String, which is the community string HP OneView uses to configure Managed and Monitored devices with
* Set Trap Forward Destinations, which will forward all received SNMP traps from Managed and Monitored devices to the destination(s) you specify.

The Appliance itself doesn't support SNMP access.

**Comment by tlauder** [comment]
Yep, I was looking for the VC mods, which you can set in the LIG's. Thanks for the response!

**Comment by tlauder** [comment]
Hi Chris,

I have a dumb question, not related to POSH, but related to the PowerShell
tools for HP OA's. Not sure if you could redirect me to the correct person,
or possibly know the answer yourself.

So I'm trying to totally script an c7000 setup from scratch using the PS OA
Tools, but there's one thing I am hung up on. Once I do the initial setup,
the "First Time Setup Wizard" still shows up when I try to login to the web
interface. Granted, I could just click cancel, and be off on my merry way,
but is there some way to disable (through PS tools, or OA command line) the
first time setup wizard?

Thanks,
Todd Lauder

**Comment by ChrisLynchHP** [comment]
That isn't a stupid question.  Unfortunately, there is no way to not display the FTS after configuring the OA via the CLI or PowerShell library.  You will have to do that via the UI.

Sent from my Windows Phone
________________________________

**Comment by tlauder** [comment]
Hi Chris,

Thanks for the quick response :)  I guess it's just "cancel" for now :)

Thanks again!
Todd

**Comment by ChrisLynchHP** [comment]
It has been asked plenty of times before by other customers.  That behavior isn't going to change unfortunately.

Sent from my Windows Phone
________________________________

**Comment by tlauder** [comment]
Ok, thanks!

**Comment by nealpeters86** [comment]
@ChrisLynchHPE we are trying to access Oneview via our SNMP monitoring appliance. Our OneView appliance has IP: 192.168.1.10. Our monitoring instance has 192.168.1.11. When we do an SNMPwalk against the oneview IP we get a connection refused. 

Are we supposed to connect to the oneview frontend ip?

**Comment by ChrisLynchHPE** [comment]
@nealpeters86, what you are trying to do is not possible. HPE OneView is only an SNMP receiver, and will not respond to an snmpwalk request. This is what I stated above in this discussion.
