### ISSUE TITLE
Help for New-HPOVServerProfileLogicalDiskController

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#220]
The help for New-HPOVServerProfileLogicalDiskController
Says:
PARAMETERS
    -ControllerID <Object>
        Specify the Controller ID location.  **The only supported option for this parameter is 'Embedded'.**

        Required?                    true
        Position?                    named
        **Default value                Embedded**
        Accept pipeline input?       false
        Accept wildcard characters?  false

### Actual Behavior
When I take a sneak peak into HPOneView.300.psm I find:
function New-HPOVServerProfileLogicalDiskController
{
	Param 
	(
		[Parameter (Mandatory = $false, ParameterSetName = "Default")]
		[Parameter (Mandatory = $false, ParameterSetName = "Import")]
		[ValidateSet('Embedded',**'Mezz 1','Mezz 2','Mezz 3**')]
		[Object]$ControllerID = 'Embedded',

Does this mean that Mezz 1|2|3 is supported on Synergy and just not documented/ The documentation is wrong about the only supported option?

### Version Information
PowerShell Library Version : 3.0.1191.2858

**Comment by ChrisLynchHPE** [comment]
Mezz location is only supported with Synergy.  I'll get that updated.

**Comment by ChrisLynchHPE** [comment]
Linking with #223

**Comment by ChrisLynchHPE** [comment]
Closing.
