### ISSUE TITLE
Documentation: Synergy and New-HPOVServerProfileLogicalDisk

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#221]
### Expected Behavior
The RAID options of:
'RAID0','RAID1','RAID1ADM','RAID10','RAID5','RAID6','NONE'
Are not documented in the help for New-HPOVServerProfileLogicalDisk

The help only mentions:
"Only RAID0 and RAID1 are supported for embedded BL disk policies.  RAID5, RAID6, RAID10 are supported with DL servers with SmartArray controller that supports the RAID type."

### Version Information
3.0.1191.2858

**Comment by ChrisLynchHPE** [comment]
Thanks.  I missed updating this one when I added HPE Synergy support.

**Comment by ChrisLynchHPE** [comment]
Linking with #223

**Comment by ChrisLynchHPE** [comment]
Closing.
