### ISSUE TITLE
Documentiation: Bigbird

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#224]
May I suggest that all references to Bigbird in the documentation are changed to D3940

Example: New-HPOVServerProfileLogicalDisk
-MaxDriveSize
-MinDriveSize

PowerShell Library Version : 3.0.1191.2858

**Comment by ChrisLynchHPE** [comment]
I have already taken care of this for the next update.

**Comment by ChrisLynchHPE** [comment]
Closing.
