### ISSUE TITLE
New-HPOVServerProfileLogicalDisk requires -bootbable for ParameterSetName = "SynergyJBOD"

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#226]
### Expected Behavior
In the OV GUI,
In a Server Profile Template 
A RAID drive on the "Mezz 1 Storage controller"  can be set bootable

Therefore, the HPOV PowerShell module should support setting a RAID drive a synergy Mezz as bootable

### Actual Behavior
The New-HPOVServerProfileLogicalDisk ParameterSetName "SynergyJBOD" (which has the required Min/MaxDriveSize) does not support -Bootable

HPOneView.300.psm1:
[Parameter (Mandatory = $false, ParameterSetName = "Default")]
[ValidateNotNullOrEmpty()]
[bool]$Bootable

### Steps to reproduce
Use OneView Synergy DCS and see function definition HPOneView.300

### Version Information
3.0.1191.2858

**Comment by ChrisLynchHPE** [comment]
Disks are what needs to be set as Bootable, which you can do today.  You cannot set a JBOD as bootable.

Sent from my Windows 10 phone

**Comment by scriptengine** [comment]
>>You cannot set a JBOD as bootable.
The JBOD is the parameter set name in the code. I want to use RAID on the Synergy Mezz Card (which is bootable in the GUI) see attached screen shot.
![2017-01-22_20-20-36](https://cloud.githubusercontent.com/assets/23039871/22185577/6011d078-e0e0-11e6-999a-0c4e96c101ab.png)


>> Bootable, which you can do today. 
No.

New-HPOVServerProfileLogicalDisk does not allow -bootable when specifying -MinDriveSize and/or -MaxDriveSize to create a synergy RAID set on the D3940 using the controller on Mezz 1

**Comment by ChrisLynchHPE** [comment]
That is NOT a JBOD. That is a RAID logical disk which is missing from the parameter set due to a mixup in functionality.

Sent from my Windows 10 phone

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1210.3013](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1210.3013).

Closing.
