### ISSUE TITLE
Add-Baseline with empty file

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#227]
### Actual Behavior
if add-baseline is called with a file that exists but is empty (ie 0 bytes in size) the command fails with a divide by zero error

The baseline then been created on the OneView appliance but is in a permanent state of "The firmware bundle is being added"
**That is the appliance then has a zombie baseline that can not be used or deleted**

### Steps to reproduce
new-item -Path empty.iso -ItemType file
PS> Add-HPOVBaseline -File empty.iso
Add-HPOVBaseline : Attempted to divide by zero.
At line:1 char:1

Get-HPOVBaseline | ft name,state, status,version
empty.iso      Adding Unknown unknown version
874609-001.iso Adding Unknown unknown version

### Version Information
3.0.1210.3013

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1221.2746](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1221.2746).

Closing.
