### ISSUE TITLE
Documentation New-HPOVServerProfileLogicalDisk Raid None

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#229]
The help for New-HPOVServerProfileLogicalDisk 
does not document the value of None for -RAID

IF it is valid to use the value NONE for raid then it would be good for the help to mention what hardware (BLs/ Synergy/ Embedded/Mezz) it is supported for

### Version Information
3.0.1210.3013

**Comment by ChrisLynchHPE** [comment]
As it states in the Help, you need to look at the Server Hardware Type object.  It calls out what RAID type is supported.  I cannot document every single possible value for every single server hardware OneView supports.
