### ISSUE TITLE
get-hpovserver -name name* fails on Synergy

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#230]
### Expected Behavior
To be able to find servers using wildcards from the name, ie:
get-hpovserver -name prod*

The help:
    -Name <String>
        The name of the server hardware resource to be returned.  All server hardware resources will be returned if omitted.  **Supports * wildcard character.**

### Actual Behavior
PS> Get-HPOVServer -name prod*
Get-HPOVServer : Server Hardware 'prod%25' not found on '172.16.1.54' appliance connection. Please check the name again, and try again.

PS> Get-HPOVServer -name "prod*"
Get-HPOVServer : Server Hardware 'prod%25' not found on '172.16.1.54' appliance connection. Please check the name again, and try again.

PS> Get-HPOVServer -name 'prod*'
Get-HPOVServer : Server Hardware 'prod%25' not found on '172.16.1.54' appliance connection. Please check the name again, and try again.

### Version Information
3.0.1210.3013

**Comment by scriptengine** [comment]
Is Get-HPOVServer only valid for rack mount servers? 
Is this the expected behavior on Synergy?

**Comment by ChrisLynchHPE** [comment]
No, the Cmdlet is for any monitored or managed server on an HPE OneView appliance or Synergy Composer.

**Comment by scriptengine** [comment]
>>this does not lookup servers via their Server Profile Name,
>>only the hardware name displayed in the OneView Server Hardware List.
Yes works fine when you understand that, My mistake, sorry.
