### ISSUE TITLE
 Get-HPOVDriveEnclosure -name fails

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#231]
### Expected Behavior
To be able to get D3940s by name

SYNTAX
    Get-HPOVDriveEnclosure -Name <String> [-ApplianceConnection <Array>] [<CommonParameters>]
    -Name <String>
        The name of the Synergy DAS enclosure.  Omitt to return all devices.
        Required?                    true

### Error
PS> (Get-HPOVDriveEnclosure | select -first 1).name | Tee-Object -Variable name
Frame1-0000A66101, bay 1
PS> Get-HPOVDriveEnclosure -name $name
Get-HPOVDriveEnclosure : The 'Frame1-0000A66101, bay 1' Drive Enclosure resource was not found on '172.16.1.54' Appliance. Please check the name and try again.
At line:1 char:1
Get-HPOVDriveEnclosure -name $name
CategoryInfo          : ObjectNotFound: (Name:String) [Get-HPOVDriveEnclosure], UnmanagedDeviceResourceException
FullyQualifiedErrorId : UnmangedDeviceResouceNotFound,Get-HPOVDriveEnclosure

### Further
Typo: Omitt to return all devices
(Omit)
(I only noticed because of github's spell checking)

The help says that -name is required but the example shows -name not being used
"        Required?                    true"

### Version Information
3.0.1210.3013

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1221.2746](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1221.2746).

Closing.
