### ISSUE TITLE
(minor) Get-HPOVDriveEnclosure drivebays.model does not report SSD or HDD

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#233]
### Expected Behavior
When examining the disks in a D3940 I expect one of:
SATA HDD 
SATA SDD 
SAS HDD 
SAS SDD
Similar to the OV GUI
 
### Actual Behavior
The model attribute loses the HD drive (HDD or SDD) so you can not tell the drive type with out digging much deeper into the drive attribute of the drivebay

### Steps to reproduce
PS>Get-HPOVDriveEnclosure | select -first 1 | select -ExpandProperty drivebays | sort model -Unique | ft model

model
-----
SAS 1200
SAS 1662
SAS 1864
SAS 1988
SAS 3276
SAS 600
SAS 800
SAS 900
SAS 971
SATA 100
SATA 200
SATA 2048
SATA 400
SATA 500

Its impossible from this list to tell which are HD and which are SSDs

### Version Information
3.0.1210.3013

**Comment by ChrisLynchHPE** [comment]
You are looking at the raw API object.  There is a `driveMedia` that you should be looking at.  You can't simply go based on the `Model`.  To get drives of a certain type (SSD versus HDD) and interfact (SATA versus SAS), you need to use the following:

```PowerShell
Get-HPOVDriveEnclosure | select -first 1 | select -ExpandProperty drivebays | sort model -Unique | ft model,driveMedia,deviceInterface
```

**Comment by scriptengine** [comment]
I think it needs a
select -expand drive
Which is my point. Why are the properties of the drive not surfaced as a property of the drivebay?

Get-HPOVDriveEnclosure | select -first 1 | select -ExpandProperty drivebays | select -expand drive |sort -Unique deviceInterface,driveMedia, capacity | ft deviceInterface,driveMedia, capacity

**Comment by ChrisLynchHPE** [comment]
Because all that is returned in the Cmdlet is the drive enclosure. You need to look at the individual properties for the available drives. We don’t have a Cmdlet to return drives from drive enclosures because the UI doesn’t.

Sent from my Windows 10 phone
