### ISSUE TITLE
Sample Server_Multiconnection_SAN_Storage_Sample.ps1 bug

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#234]
### Actual Behavior
In  the sample Server_Multiconnection_SAN_Storage_Sample.ps1

I think the following is incorrect
#Attach Volumes
$volume1 = Get-HPOVStorageVolume Volume1 | Get-HPOVProfileAttachVolume -volumeid 1
$volume2 = Get-HPOVStorageVolume SharedVolume1 | Get-HPOVProfileAttachVolume -volumeid 2

Should Get-HPOVProfileAttachVolume  not be **New**-HPOVProfileAttachVolume ?

### Steps to reproduce
get-command *HPOVProfileAttachVolume*
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           New-HPOVProfileAttachVolume                        3.0.121... HPOneView.300

### Version Information
3.0.1210.3013

**Comment by scriptengine** [comment]
$volume1 = Get-HPOVStorageVolume Volume1 ...
$volume2 = Get-HPOVStorageVolume SharedVolume1 ...

should be:
$volume1 = Get-HPOVStorageVolume **-name** Volume1 ...
$volume2 = Get-HPOVStorageVolume **-name** SharedVolume1 ...

**Comment by ChrisLynchHPE** [comment]
I will address this sample script in the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1293.3770 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1293.3770).

Closing.
