### ISSUE TITLE
Get-HPOVStorageVolumeTemplate internal error exposed when volume does not exist

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#235]
###Summary
There is a parameter missing on a New-ErrorRecord cmdlet  for Get-HPOVStorageVolumeTemplate

### Steps to reproduce
$volumeTemplateName="NobodyWouldCallATemplateThis" 
Get-HPOVStorageVolumeTemplate -Name $volumeTemplateName

###Error
19:02 PS> $volumeTemplateName="NobodyWouldCallATemplateThis" ; Get-HPOVStorageVolumeTemplate -Name $volumeTemplateName
New-ErrorRecord : Missing an argument for parameter 'Message'. Specify a parameter of type 'System.String' and try again.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.300\HPOneView.300.psm1:33033 char:114

### Version Information
3.0.1210.3013

**Comment by ChrisLynchHPE** [comment]
Thanks.  Will be fixed in the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1221.2746](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1221.2746).

Closing.
