### ISSUE TITLE
Get-HPOVStorageVolumeTemplate  has a blank value for "storage pool"

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#236]
### Expected Behavior
PowerShell's default output for format-table and format-list to have the same output

### Actual Behavior
Get-HPOVStorageVolumeTemplate  has a blank value for "storage pool"

### Steps to reproduce
PS> Get-HPOVStorageVolumeTemplate | select -first 1 | ft
Name              Capacity  ProvisionedType Sharing Storage System    Storage Pool Snapshot Pool
Prod-OSBootDrives 128.00 GB Thin            Private ThreePAR7200-6710 **CPG-SSD-AO**   CPG-SSD-AO

PS> Get-HPOVStorageVolumeTemplate | select -first 1 | fl
Name                       : Prod-OSBootDrives
State                      : Configured (None)
Description                :
ProvisioningType           : Thin
Provisioned capacity       : 0.00 GB
Sharing                    : Private
Storage System             : ThreePAR7200-6710
**Storage Pool**               :
Snapshot Pool              : CPG-SSD-AO
Storage System Volume Name :

### In addition
In FL should "Storage System Volume Name" have a value (I have no idea what it should be)

### Version Information
3.0.1210.3013

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1221.2746](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1221.2746).

Closing.
