### ISSUE TITLE
New-HPOVUplinkSet -Type FibreChannel fails on FC Modules

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#237]
### Expected Behavior
As for New-HPOVUplinkSet with converged "Virtual Connect SE 40Gb F8 Module for Synergy" to be able to create uplink sets

### Actual Behavior
PS>Get-HPOVLogicalInterconnectGroup -name $LIG_FC_Name | New-HPOVUplinkSet -Name "FC-X" -Type FibreChannel -Networks "FC-X" -UplinkPorts "Enclosure1:Bay2:1"
**Send-HPOVRequest : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try again.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.300\HPOneView.300.psm1:54311 char:46**

###Version
3.0.1210.3013

### Attachments
Script attached
Verbose output attached
[Demo-FC-Lig-Bug.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/747001/Demo-FC-Lig-Bug.txt)

### Steps to reproduce

<#
    .SYNOPSIS
        Demonstrate a bug in HPOV PS when creating FC ligs

        Jeremy Pack    1/Feb/2017
#>

[CmdletBinding(DefaultParametersetName="JustRun")]
param (
    [string]$HostName="172.16.1.52",
    [string]$UserName = "Administrator",
    [string]$Password = "Password1",
    [switch]$UseVerbose=$false
    )

#Error Handling
Set-PSDebug -Strict
Set-StrictMode -Version latest
$ErrorActionPreference = "Stop"

#Global Variables
#$EnclosureGroupName = "EG"
#$LEName = "LE"
$LIG_M_LAG_Name   = "LIG-MLAG"
$LIG_SAS_Name     = "LIG-SAS"
$LIG_FC_Name      = "LIG-FC"

Write-host "Connecting to Appliance"
Disconnect-HPOVMgmt -erroraction SilentlyContinue
Connect-HPOVMgmt -Hostname $HostName -UserName $UserName -Password $Password -ErrorAction stop

Write-host "Creating Ethernet Networks"
    New-HPOVNetwork -Name Management -type Ethernet -vlanId 5 -privateNetwork $False -purpose Management -smartLink $False -typicalBandwidth 2500 -VLANType Tagged
    New-HPOVNetwork -Name Vmotion -type Ethernet -vlanId 10 -privateNetwork $False -purpose VMMigration -smartLink $False -typicalBandwidth 2500 -VLANType Tagged
    New-HPOVNetworkSet -name "Production Networks" -Networks Vmotion

Write-host "Creating FC Networks"
   New-HPOVNetwork -Name FC-A -type FC -fabricType FabricAttach
   New-HPOVNetwork -Name FC-B -type FC -fabricType FabricAttach
   New-HPOVNetwork -Name FCOE-A -type FCoE -VlanId 10
   New-HPOVNetwork -Name FCOE-B -type FCoE -VlanId 11
   New-HPOVNetwork -Name FC-X -type FC -fabricType FabricAttach
   New-HPOVNetwork -Name FC-Y -type FC -fabricType FabricAttach

Write-host "Creating LIGs"
    $VCbays =  @{
        Frame1 = @{Bay3 = 'SEVC40f8' ; Bay6 = 'SE20ILM'};
        Frame2 = @{Bay3 = 'SE20ILM'  ; Bay6 = 'SEVC40f8' };
        Frame3 = @{Bay3 = 'SE20ILM'  ; Bay6 = 'SE20ILM'}}
    New-HPOVLogicalInterconnectGroup -Name $LIG_M_LAG_Name -frameCount 3 -InterconnectBaySet 3 -Bays $VCbays -FabricModuleType SEVC40F8 -FabricRedundancy HighlyAvailable

    $SASbays =  @{
        Frame1 = @{Bay1 = 'SE12SAS'  ; Bay4 = 'SE12SAS'} }
    New-HPOVLogicalInterconnectGroup -Name $LIG_SAS_Name -frameCount 1 -InterconnectBaySet 1 -Bays $SASbays -FabricModuleType SAS

    $FCbays =  @{
        Frame1 = @{Bay2 ='SEVC16GbFC'; Bay5 = 'SEVC16GbFC'} }
    New-HPOVLogicalInterconnectGroup -Name $LIG_FC_Name -frameCount 1 -InterconnectBaySet 2 -Bays  $FCbays -FabricModuleType SEVCFC

Write-host "Creating LIGs"
    $AllNetworks = "Management","Vmotion"

    # FC Uplink Sets
Write-host "Creating Converged, FC Uplinks"
    Get-HPOVLogicalInterconnectGroup -name $LIG_M_LAG_Name | New-HPOVUplinkSet -Name "FC-A" -Type FibreChannel -Networks "FC-A" -UplinkPorts "Enclosure1:Bay3:Q4.1" | Wait-HPOVTaskComplete
    Get-HPOVLogicalInterconnectGroup -name $LIG_M_LAG_Name | New-HPOVUplinkSet -Name "FC-B" -Type FibreChannel -Networks "FC-B" -UplinkPorts "Enclosure2:Bay6:Q4.1" | Wait-HPOVTaskComplete

    # MLAG Uplink Set
Write-host "Creating Converged, Ethernet Uplinks"
    Get-HPOVLogicalInterconnectGroup -name $LIG_M_LAG_Name | New-HPOVUplinkSet -Name "M-LAG" -Type Ethernet -Networks $AllNetworks -UplinkPorts "Enclosure1:Bay3:Q1:1","Enclosure1:Bay3:Q5:1","Enclosure2:Bay6:Q1:1","Enclosure2:Bay6:Q5:1" | Wait-HPOVTaskComplete

Read-Host -Prompt "Demonstration stopped.`nReview DCS/ Composer configuration and check for errors before continuing.`nPress RETURN to continue"

    #Bays 2 & 5
Write-host "Creating Pure, FC Uplinks - PREPARE for Errors"

Write-host "Simple syntax..." -NoNewline
try {
    Get-HPOVLogicalInterconnectGroup -name $LIG_FC_Name | New-HPOVUplinkSet -Name "FC-X" -Type FibreChannel -Networks "FC-X" -UplinkPorts "Enclosure1:Bay2:1" -Verbose:$UseVerbose
    }
catch {
    Write-host "ERROR"
    $Error[0]
    }

Write-host "Simple syntax, with Q1.1..." -NoNewline
try {
    Get-HPOVLogicalInterconnectGroup -name $LIG_FC_Name | New-HPOVUplinkSet -Name "FC-X" -Type FibreChannel -Networks "FC-X" -UplinkPorts "Enclosure1:Bay2:Q1:1" -Verbose:$UseVerbose
    }
catch {
    Write-host "ERROR"
    $Error[0]
    }

Write-host "`nPass Lig as object" -NoNewline
try {
    $objLIG = Get-HPOVLogicalInterconnectGroup -name $LIG_FC_Name
    New-HPOVUplinkSet -Name "FC-X-Uplink" -Type FibreChannel -Networks "FC-X" -UplinkPorts "Enclosure1:Bay2:1" -lig $objLIG  -Verbose:$UseVerbose
    }
catch {
    Write-host "ERROR"
    $Error[0]
    }

Write-host "`nPass Networks as array" -NoNewline
try {
    $arrFCNetwork = @("FC-Y")
    Get-HPOVLogicalInterconnectGroup -name $LIG_FC_Name | New-HPOVUplinkSet -Name "FC-Y-Uplink" -Type FibreChannel -Networks $arrFCNetwork -UplinkPorts "Enclosure1:Bay2:1"  -Verbose:$UseVerbose
    }
catch {
    Write-host "ERROR"
    $Error[0]
    }

Write-host -ForegroundColor Green "`nDemonstration Complete"

[Demo-FC-Lig-Bug.zip](https://github.com/HewlettPackard/POSH-HPOneView/files/746993/Demo-FC-Lig-Bug.zip)

**Comment by ChrisLynchHPE** [comment]
You are using the Cmdlet wrong again. You do not specify the Enclosure or Frame.  You simply specify the `Bay#:PortName`.

Sent from my Windows 10 phone

**Comment by ChrisLynchHPE** [comment]
You are using the Cmdlet wrong again. You do not specify the Enclosure or Frame.  You simply specify the `Bay#:PortName`.

**Comment by scriptengine** [comment]
**Thanks Chris**, I'll test that as soon as I have a free DCS

Given (from my example) this works:
New-HPOVUplinkSet -Name "FC-B" -Type FibreChannel -Networks "FC-B" -UplinkPorts "Enclosure2:Bay6:Q4.1"

And this does not
New-HPOVUplinkSet -Name "FC-X" -Type FibreChannel -Networks "FC-X" -UplinkPorts "Enclosure1:Bay2:1"

and the error message is:
Send-HPOVRequest : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try again.

I would argue that its not "entirely obvious" as we say in the UK that I'm using the command wrong.

Looking at the help though I can see the clues were there...

**Comment by scriptengine** [comment]
Thanks again Chris.
I can confirm I have this working. (And intend to turn the code into a sample at some point)
Valid Syntax:
-UplinkPorts "BAY2:1" 
-UplinkPorts "BAY5:1","BAY5:2”
-UplinkPorts "BAY2:Q4.1"
-UplinkPorts "BAY5:Q4.1","BAY5:Q4.1"
-UplinkPorts "BAY2:2","BAY2:Q3.1" 

Invalid Configurations
-UplinkPorts "BAY2:Q4.4","BAY5:Q4.4" 
-UplinkPorts "BAY2:3","BAY5:3"

I have doubts about: -UplinkPorts "BAY2:2","BAY2:Q3.1" 
but it works on the DCS

**Comment by ChrisLynchHPE** [comment]
All of the UplinkPort values are perfectly valid.  The success of using them will be dictated by the target VC platform you are trying to model or configure.
