### ISSUE TITLE
very minor New-HPOVUplinkSet dot in list of uplinks ports breaks errors

### ISSUE THREAD

**Issue by scriptengine** [HewlettPackard/POSH-HPOneView#238]
### Expected Behavior
An error message about incorrect input/ input format
The issue is that the error message says a valid port can not be found

### Actual Behavior
NOTE the period between "Enclosure2:Bay6:Q3.1"**.**"Enclosure2:Bay6:Q4.1" rather than a comma

... | New-HPOVUplinkSet ... -UplinkPorts "Enclosure2:Bay6:Q3.1"**.**"Enclosure2:Bay6:Q4.1"
select-step : **The property 'Enclosure2:Bay6:Q4.1' cannot be found on this object.** Verify that the property exists.
      1..$iLargestStep | %{select-step $_}
CategoryInfo          : NotSpecified: (:) [select-step], PropertyNotFoundException
FullyQualifiedErrorId : PropertyNotFoundStrict,select-step

### Steps to reproduce
Use a period between uplink names with 

### Version Information
3.0.1210.3013

**Comment by ChrisLynchHPE** [comment]
Not sure what you are trying to say here.  There isn't an example that shows this, and the error you are getting is a standard PowerShell error.  This has nothing to do with the Cmdlet itself.
