### ISSUE TITLE
Unable to connect to OneView appliance (connect-hpovmgmt)

### ISSUE THREAD

**Issue by jpsivori** [HewlettPackard/POSH-HPOneView#24]
I'm running POSH-HPOneView on a W2K12 R2 server and trying to connect to a OneView installation on IP address 10.156.40.162. Currently returning the following error. Any help would be gratefully received :

[HPONEVIEW]: [Not Connected] PS C:\Users\Administrator> connect-hpovmgmt
cmdlet Connect-HPOVMgmt at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)

appliance: 10.156.40.162
User: administrator
Password: **********

connect-hpovmgmt : Exception of type 'Microsoft.PowerShell.Commands.WriteErrorException' was thrown.
At line:1 char:1
+ connect-hpovmgmt
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Connect-HPOVMgmt:String) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-HPOVMgmt

[HPONEVIEW]: [Not Connected] PS C:\Users\Administrator>

**Comment by ChrisLynchHP** [comment]
Can you add the -verbose switch to your call and provide the output?  Do know the password of your VM will be shown in the output, so do a find and replace before providing it.

**Comment by jpsivori** [comment]
Thanks Chris. Pls see attached.

Regards,
JP

**Comment by ChrisLynchHP** [comment]
Github doesn't support attachments via email. Please paste the contents into a reply from the site or within your email.

Sent from my Windows Phone
________________________________

**Comment by jpsivori** [comment]
Hi Chris,

Thanks for your help but I sorted in the end. Some colleagues suggested I connect to the appliance from a Windows 7 machine. I had previously been trying to connect through PS on the host (W2K12 R2 HyperV) that the appliance VM is running on. When I installed the POSH library onto the W7 PC, it connected instantly.

Cheers &

Regards,
JP

**Comment by ChrisLynchHP** [comment]
Sounds like your Hyper-V host doesn't have access to the VLAN you set the appliance VM to.  But you have it resolved.  Closing issue.

**Comment by jpsivori** [comment]
Hi Chris,

Our unit have been tasked with providing OSS-type services to a number of converged systems customers. We have a history of providing these services using SIM to receive SNMP traps from managed devices plus our own, bespoke “Intelligent Paging System” (IPS) to which SIM forwards these traps for processing into text messages our on-call engineers receive.

I am trying to see whether OneView 1.10.08 is also able to forward traps (it appears to be able to) and also what format these traps are in so we can adapt IPS to accept OV traps as well as SIM traps.

I am struggling to find documentation on this among the OV technical literature. I was wondering whether you could point me in the right direction?

Thanks in advance for your time.

Regards,
JP
