### ISSUE TITLE
New-HPOVserverProfileAttachVolume - Not handling WS Blades environment

### ISSUE THREAD

**Issue by sivasura** [HewlettPackard/POSH-HPOneView#241]
Please fill in as much information as possible to help resolve your issue.

Hi Chris 
Raising this defect as discussed in the chat,Few function in the HPOneview3.0 libraries not handling the WS blades. It throws error when it finds a WS Blades in place.

Error We are getting for WS blades environment:
 New-HPOVProfileAttachVolume : The provided Server Profile <Bladename>is not assigned to a supported Server Hardware TYpe Resource, ProLiant WS460c Gen9.  Only BL Gen 8 
or newer are supported.
At line:8 char:9
+         New-HPOVProfileAttachVolume -ServerProfile $OV_ProfileInfo -V ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (ServerProfile:PSObject) [New-HPOVServerProfileAttachVolume], ServerProfileResourceException
    + FullyQualifiedErrorId : UnsupportedServerHardwareResource,New-HPOVServerProfileAttachVolume

### Expected Behavior
Should not fail for WS blades as the are also HP blades and having similar architecture except graphics features..

### Actual Behavior
Fails stating this error: 
New-HPOVProfileAttachVolume : The provided Server Profile <Bladename>is not assigned to a supported Server Hardware TYpe Resource, ProLiant WS460c Gen9.  Only BL Gen 8 
or newer are supported.

### Steps to reproduce
The the below commands after establishing a connection to the oneview appliance using (Connect-HPOVMgmt)
In this case this blade is a WS460c blade.
$OV_ProfileInfo = Get-HPOVServerprofile -name "sBL01"
 $OV_VolumeInfo = Get-HPOVStorageVolume -name "LUN_OS01"

   $AttachVolume = New-HPOVProfileAttachVolume -ServerProfile $OV_ProfileInfo -Volume $OV_VolumeInfo -LunIdType Manual -LUNID 1 | Wait-HPOVTaskComplete

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
Get-HPOVVersion

PowerShellLibraryVersion : 3.0.1221.2746
LibraryPath              : C:\Siva\HPCS\09Feb2017\cI\common\HPOneView.300
HPE OneView Appliance Version:   3.00.05-0271823
Output from `$PSVersionTable` on your Windows Host  : 5.0.10586.117

PS C:\Windows\system32> $PSVersionTable

Name                           Value                                                  
----                           -----                                                  
PSVersion                      5.0.10586.117                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                
BuildVersion                   10.0.10586.117                                         
CLRVersion                     4.0.30319.36373                                        
WSManStackVersion              3.0                                                    
PSRemotingProtocolVersion      2.3                                                    
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
Thanks.  Yes, this is a defect as the `New-HPOVServerProfile` and `New-HPOVServerProfileTemplate` Cmdlets validate if the compute is a BL or DL model.  I will add support for WS, but in the future will re-architect the internals of the Cmdlet, looking at SHT capabilities.

**Comment by sivasura** [comment]
Thanks Chris. Much appreciated.
. Please let us know once this fixed.. 

Regards
Sivakumar Gnanavelu

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1264.2772](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1264.2772).

**Comment by ChrisLynchHPE** [comment]
closing.
