### ISSUE TITLE
Not able to change DataCenterSupportSettings

### ISSUE THREAD

**Issue by woertz** [HewlettPackard/POSH-HPOneView#245]
### Expected Behavior
We want to change the DataCenterSupportSettings via PowerCLI or "Remote Support" as it is called in the OneView web interface as we have 300 data centers and can not change it "by hand".

### Actual Behavior
The request method PUT is not supported or not applicable for the requested resource. 

### Steps to reproduce

- Get the URI of the DC
PowerCLI> $DC_URI=(Search-HPOVIndex -Category datacenters -Search 998).uri

- Get the remoteSupportUri of the DC
PowerCLI> $DC_RS_URI=(Send-HPOVRequest $DC_URI).remoteSupportUri

- Get the remote support data
PowerCLI> $RS=Send-HPOVRequest $DC_RS_URI

- Change the city
PowerCLI> $RS.city
Kempten
PowerCLI> $RS.city="Cambodunum"
PowerCLI> $RS.city
Cambodunum

- Write it back
PowerCLI> Send-HPOVRequest $RS.uri "PUT" $RS
Send-HPOVRequest : [Send-HPOVRequest]: The requested HTTP method is not valid/supported.  The request method PUT is not supported or not applicable
for the requested resource. URI: /rest/support/datacenters/ea0e807e-0447-4a18-acca-c0f115a0028f
In Zeile:1 Zeichen:1
+ Send-HPOVRequest $RS.uri "PUT" $RS
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (PUT:/rest/suppo...ca-c0f115a0028f:String) [Send-HPOVRequest], InvalidOperationException
    + FullyQualifiedErrorId : HTTP_METHOD_NOT_ALLOWED,Send-HPOVRequest

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1210.3013
HPE OneView Appliance Version:  3.00.05-0271823
Output from `$PSVersionTable` on your Windows Host:
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
So, this is not an issue with the HPE OneView PowerShell library, but rather your attempt at using an unsupported method for a given resource.  `/rest/datacenters` does not support the PUT method, only GET and PATCH.

**Comment by woertz** [comment]
I think you mean `/rest/support/datacenters`, not `/rest/datacenters`.
But never the less, my fault. I found in the "HPE OneView API Reference" the "Data Center Support Settings" [http://h17007.www1.hpe.com/docs/enterprise/servers/oneview3.0/cic-api/en/api-docs/current/index.html#rest/support/datacenters](url) with GET and PATCH.

But if I use PATCH I get this error:
`PS> Send-HPOVRequest $RS.uri "PATCH" $RS`
`Send-HPOVRequest : The JSON in the request is invalid. There is an error on line 1 near column 628. Correct the invalid JSON and try the request again.`
`In Zeile:1 Zeichen:1`
`+ Send-HPOVRequest $RS.uri "PATCH" $RS`
`    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationException`
`    + FullyQualifiedErrorId : InvalidAuthOperation,Send-HPOVRequest`

So how do I write back my changed data?

**Comment by ChrisLynchHPE** [comment]
Well, sort of.  You need to place resources into a DataCenter first (`/rest/datacenters`).  Then, after Remote Support has been enabled on the appliance, you would then modify the DataCenters associated Remote Support settings (`/rest/support/datacenters/{GUID}`).  The Remote Support DC Setting only supports the PATCH operation.  Here is what a PATCH object would look like to set the Address for the DataCenter:

```PowerShell
$DCAddressPatch = (
	@{
		op = "replace",
		path = "/streetAddress1",
		value = "1 Main Street"
	},
	@{
		op = "replace",
		path = "/streetAddress2",
		value = "Suite 700"
	},
	@{
		op = "replace",
		path = "/city",
		value = "Irvine"
	},
	@{
		op = "replace",
		path = "/postalCode",
		value = "92612"
	}
)
```

I'm accelerating the work I had on my backlog to add support for managing DataCenters, which Cmdlets do not exist, and the associated Remote Support parameters to support what you are doing from native Cmdlets in the library.

**Comment by ChrisLynchHPE** [comment]
Remote Support Datacenter management has been added into [Release 3.0.1264.2772](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1264.2772).

**Comment by ChrisLynchHPE** [comment]
closing.
