### ISSUE TITLE
Failure on HPOVProfileVolumeAttach

### ISSUE THREAD

**Issue by sivasura** [HewlettPackard/POSH-HPOneView#247]
Perform automation of a server profile and a volume mapping using the following steps. "New-HPOVserverprofileAttachVolume"

### Expected Behavior
The "New-HPOVserverprofileAttachVolume" should pass successfully

### Actual Behavior
"New-HPOVserverprofileAttachVolume" is failing with errors. Our automation needs updating the server profile in multiple stages which is not working as expected even after

### Steps to reproduce
Using automation of a server profiel and a volume mapping using the following steps.

1. Create a serverprofile on a C7000 Enclosure
2. Create a volume on the storage
3. Install the OS/HV(ESXi) add to a cluster
4. Update the server profile with the OS type as "VMWare" for the Manage SAN storage option using "Send-HPOVResource" function
5. Attach the volume using "New-HPOVserverprofileAttachVolume"
6. That failed stating the below error.
First error: -HostOStype should be supplied along with the cmdlet
7. Fixed by adding it in the function, then got the below error.

"No available storage systems found for 'blade9' Server Hardware and 'EncGroup' Enclosure Group.  Please verify an available Storage System exists, and has connectivity to the destination server or Enclosure Group, or that the Server Profile has a FibreChannel Connection that matches an Expected/Actual Network to a Storage System Host Port(s)."

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1221.2746
HPE OneView Appliance Version:  Oneview 3.00.07-0283691
Output from `$PSVersionTable` on your Windows Host:
Name  : PSVersion
Value : 5.0.10586.117
Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : BuildVersion
Value : 10.0.10586.117
Name  : CLRVersion
Value : 4.0.30319.36373
Name  : WSManStackVersion
Value : 3.0
Name  : PSRemotingProtocolVersion
Value : 2.3
Name  : SerializationVersion
Value : 1.1.0.1

**Comment by ChrisLynchHPE** [comment]
The `New-HPOVserverprofileAttachVolume` Cmdlet will set the HostOSType for you, so there wasn't a need to do it outside of a Cmdlet.

As for the Exception, that is generated when the Server Profile you are trying to create and assign does not have access to a storage system.  This is dictated by OneView.  So you need to validate that your Storage System Host Ports are configured correctly (with the correct Expected and Actual Networks), your FC or FCoE Network is associated with the correct Managed SAN (either Fabric Attach or Direct Attach), and those same FC or FCoE Networks are assigned to a correct Uplink Set.

**Comment by ChrisLynchHPE** [comment]
Closing.
