### ISSUE TITLE
Unable to use AddServers_Monitored_Sample.ps1 sample script

### ISSUE THREAD

**Issue by bpeter01** [HewlettPackard/POSH-HPOneView#250]
I am using AddServers_Monitored_Sample.ps1 script to add multiple DL gen9. I created the csv file and run the script providing the OV server credential. The script ran without errors with "We are all done. 0 async tasks were created. Displaying final status of tasks." message but no server was added and no output report. What am I missing?

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
Please provide the CSV file and its contents.  You should change the iLO IP Address or Host name value to something that you can publically provide, and the same for the password.

Also, what version of the library are you using?

**Comment by bpeter01** [comment]
Hi Chris,

I am only using one server for now as a test.

Brian

**Comment by bpeter01** [comment]
Sorry I had attached the csv file.

I am using the script as is from the v3.0 library and providing the csv and OV server hostname and credentials input when requested.


Brian

**Comment by ChrisLynchHPE** [comment]
There is a slight defect when you are only trying to add just 1 server using the sample script.  It really is a wrapper for calling the `Add-HPOVServer` Cmdlet using the `-Monitored` parameter.  Can you also verify that your CSV file has the required headers `hostname,account,password`?

**Comment by bpeter01** [comment]
Do you mean that I has to enter headers in the csv.  My script is also using -LicensingIntent OneView

The library has a download date of 1/9/2017 not sure if that was from release 3.0.1221.2746

I will try adding the headers.

Brian

**Comment by ChrisLynchHPE** [comment]
Did you modify the sample script?  The `-Monitored` parameter would set the license intent to OneView anyhow, so you don't need to do that.

Yes, the Sample Script at line 68 contains a note that your CSV needs to have headers:

```
hostname,account.password
myilo1.domain.local,admin,mypassword
myilo2.domain.local,admin,mypassword
myilo3.domain.local,admin,mypassword
```

When you submit an issue, I state that you need to provide the output from `Get-HPOVVersion` and `$PSVersionTable` in the text of the issue you are submitting.

**Comment by bpeter01** [comment]
Ok so we don't need to set the Licenseintent if we need to manage the DLs?

Brian

**Comment by ChrisLynchHPE** [comment]
What are you trying to do? The sample script you referenced is for adding lots of non-BL servers to an appliance for Monitoring only, no management no license.

Sent from my Windows 10 phone

**Comment by bpeter01** [comment]
I am trying to add multiple DL Gen9 servers for management with OneView License. I add the header hostname,account,password and I am getting this error now and the server is not added. Do I have to have more than one servers in the csv file?

Attempted to divide by zero.
At C:\Work Data\HP-OneView\Scripting\OV\v3.0\collection\POSH-HPOneView-3.00\Samples\AddServers_Monitored_Sample.ps1:103 char:2
+     Write-Progress -ID 1 -Activity ("Adding Servers to {0}" -f $Appli ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException
Add-HPOVServer : Cannot validate argument on parameter 'Username'. The argument is null or empty. Provide an argument that is not
null or empty, and then try the command again.
At C:\Work Data\HP-OneView\Scripting\OV\v3.0\collection\POSH-HPOneView-3.00\Samples\AddServers_Monitored_Sample.ps1:105 char:57
+ ...  = Add-HPOVServer -hostname $_.hostname -username $_.username -passwo ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-HPOVServer], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Add-HPOVServer
We are all done.
1 async tasks were created.
Displaying final status of tasks.
Send-HPOVRequest : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware) in its
value. Please correct the value and try again.
At C:\Work Data\HP-OneView\Scripting\OV\v3.0\collection\POSH-HPOneView-3.00\Samples\AddServers_Monitored_Sample.ps1:119 char:45
+ $AsyncTaskCollection | % { Send-HPOVRequest $_.uri } | Sort status -D ...
+                                             ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Send-HPOVRequest], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Send-HPOVRequest

Brian

**Comment by ChrisLynchHPE** [comment]
As I said, there is a defect in the script that needs to be fixed.  Please look at Get-Help Add-HPOVServer -Full examples on how to use the Cmdlet to do what you are wanting to do.  The script will not add those servers as Managed resources, only Monitored.

Sent from my Windows 10 phone

**Comment by bpeter01** [comment]
Thanks.

But I changed the csv header from "hostname,account,password" to "hostname,username,password" and it added it with OneViewAdvance License.

But got this message although it was added without problem. Is that because I only have one server in the file?

Attempted to divide by zero.
At C:\Work Data\HP-OneView\Scripting\OV\v3.0\collection\POSH-HPOneView-3.00\Samples\AddServers_Monitored_Sample.ps1:103 char:2
+     Write-Progress -ID 1 -Activity ("Adding Servers to {0}" -f $Appli ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException

We are all done.
1 async tasks were created.
Displaying final status of tasks.
Appliance   Name Owner         Created              Duration TaskState PercentComplete
---------   ---- -----         -------              -------- --------- ---------------
10.10.70.16 Add  Administrator 3/11/2017 2:33:40 PM 00:00:57 Completed 100



Appliance   Name Owner         Created              Duration TaskState PercentComplete
---------   ---- -----         -------              -------- --------- ---------------
10.10.70.16 Add  Administrator 3/11/2017 2:33:40 PM 00:00:57 Completed 100



Thanks. I'll review the Get-Help Add-HPOVServer -Full examples.


Brian

**Comment by ChrisLynchHPE** [comment]
Yes.

Sent from my Windows 10 phone

**Comment by bpeter01** [comment]
Thanks.

Brian

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1264.2772](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1264.2772).

**Comment by bpeter01** [comment]
Thanks.

Brian

**Comment by ChrisLynchHPE** [comment]
closing.
