### ISSUE TITLE
Missing capability to query Facilities information

### ISSUE THREAD

**Issue by tibmeister** [HewlettPackard/POSH-HPOneView#252]
In OneView and the RESTful API there's the ability to get the Location data of enclosures and DL servers, which can be tied to a datacenter container.  I don't see this as readily available in the POSH implementation.

**Comment by ChrisLynchHPE** [comment]
Yes, this is a backlog item for the 3.00 library.  I am actually finishing up Facilities Cmdlets that will be in the next 3.00 release.

**Comment by ChrisLynchHPE** [comment]
This is added in [Release 3.0.1264.2772](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1264.2772).

**Comment by ChrisLynchHPE** [comment]
closing.
