### ISSUE TITLE
Get Server Hardware Type for a Specific Blade in an Enclosure

### ISSUE THREAD

**Issue by IslandMonkey72** [HewlettPackard/POSH-HPOneView#253]
Hi,
I have an issue regarding the roll-out of profiles to server HW in OneView 3.00.
 
I am writing a PowerShell script to automate the provisioning of the servers with profiles in OneView for several hundred C7000 enclosures.

I have a test enclosure with eight BL460c Gen 9 Blades and there are four different hardware types amongst the eight blades returned when I run the commandlet “get-HPOVServerHardwareTypes”, owing to the differing cards in the blades.

The commandlet “New-HPOVServerProfile” requires the parameter “-ServerHardwareType”. Naturally, I would like to be able to select the correct HW Type for the particular blade for which a server profile is being created. However, I can see no way to link server name, bay, SN etc… to the Server Hardware type.

 Is there a way to make the link to from a specific server to its hardware type using Powershell?

In the GUI it is possible to get this information.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):

PowerShell Library Version : 3.0.1121.2161
Library Path               : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

HPE OneView Appliance Version:  

3.00

Output from `$PSVersionTable` on your Windows Host:
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.36366
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by ChrisLynchHPE** [comment]
You don't need to associate the Server Hardware Type when you wanting to assign the Profile to a specific server resource.  The SHT, and Enclosure Group, would automatically be filled in for you.  Instead, you would want to do the following:

```PowerShell
$SHT = Get-HPOVServerHardwareType | Select -First 1
$Server - Get-HPOVServer -ServerHardwareType $SHT | Select -First 1
New-HPOVServerProfile -Name 'My Profile 1' -AssignmentType Server -Server $Server
```

Now, if you wanted to create a Server Profile without assigning it to a Server resource, then yes the SHT would be required.  This and other examples are called out in the help for [New-HPOVServerProfile](https://github.com/HewlettPackard/POSH-HPOneView/wiki/New-HPOVServerProfile).

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  Fell free to re-open the issue if you have more questions on this topic.
