### ISSUE TITLE
Missing iSCSI boot parameter in New-HPOVServerProfileConnection -priority

### ISSUE THREAD

**Issue by jullienl** [HewlettPackard/POSH-HPOneView#255]
With the Image Streamer, we have to create a server profile with two iSCSI boot connections using the Ethernet function like :

![image](https://cloud.githubusercontent.com/assets/13134334/24159497/7f52eda8-0e5f-11e7-879b-ce7f37e173be.png)

But the Priority parameter of New-HPOVServerProfileConnection does not provide any iSCSI Boot option, only PXE boot is available.

-Priority <String>  Optional boot option for this connection, but Required if -bootable is specified.  Accepted values are NotBootable, UseBIOS, Primary or Secondary.  When the Connection Type is Ethernet, this affects PXE boot.  If the Connection Type is FibreChannel, this enables BfS settings. 
 

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 
PowerShellLibraryVersion : 3.0.1264.2772
LibraryPath              : C:\Program Files\WindowsPowerShell\Modules\HPOneview.300

HPE OneView Appliance Version:  3.00.07
Output from `$PSVersionTable` on your Windows Host:
Name  : PSVersion
Value : 5.0.10586.117

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}

Name  : BuildVersion
Value : 10.0.10586.117

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : WSManStackVersion
Value : 3.0

Name  : PSRemotingProtocolVersion
Value : 2.3

Name  : SerializationVersion
Value : 1.1.0.1

**Comment by ChrisLynchHPE** [comment]
Thank you for reporting this.  The parameter validation set is indeed missing the `IscsiParimary` and `IscsiSecondary` values.  I'll get them added into the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1293.3770 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1293.3770).

Closing.
