### ISSUE TITLE
Connect-HPOVMgmt -- no longer prompts for username

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#256]
Connect-HPOVMgmt -appliance <fqdn>

Will prompt you for password, but not username. I think it prompted for both before. Same is true for Connect-HPOVmgmt -appliance <fqdn> -password <password>. No longer prompts for username. With -verbose, it seems to connect using a blank username string.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1264.2779
HPE OneView Appliance Version:  3.0
Output from `$PSVersionTable` on your Windows Host: POSH 4.0

**Comment by ChrisLynchHPE** [comment]
When I added `PSCredential` support to the Cmdlet, I inadvertently changed the `Username` parameter optional.  There isn't an automated method for me to test changes in that behavior, and was missed when I tested `PSCredential` support.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 3.0.1293.3770 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1293.3770).

Closing.
