### ISSUE TITLE
Set-HPOVAutomaticBackupConfig -- doesn't accept username prefixed with an underscore (_)

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#258]
Set-HPOVAutomaticBackupConfig -Username "_servicehpovbackup" -verbose

Errors:
Parameter userName is null or empty or invalid.
Enter a valid value for the parameter userName and then retry edit operation.
errorcode: BACKUP_CONFIG_REQUIRED_PARAMS_INVALID

Using e.g. servicehpovbackup without the underscore works fine. Using e.g. _servicehpovbackup works if you configure using GUI.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1264.2779
HPE OneView Appliance Version:   3.0
Output from `$PSVersionTable` on your Windows Host: 4.0

**Comment by ChrisLynchHPE** [comment]
This is not a defect with the HPE OneView PowerShell library.  The Cmdlet passes the literal String value you provide to the `-Username` parameter, directly to the API of the appliance.  The _ cannot be used as the leading character, even in the UI:
<img width="481" alt="ui" src="https://cloud.githubusercontent.com/assets/6956305/24226850/4d92cece-0f26-11e7-8efa-af80acae3715.png">

**Comment by erikgraa** [comment]
So the defect is with the API/backend/appliance?

**Comment by ChrisLynchHPE** [comment]
It is by design according to the team that owns this feature in our HPE OneView R&D team.

**Comment by erikgraa** [comment]
Doesn't it say that underscores are allowed though?

What if one has a particular naming policy?

I guess it's not easily fixed anyways.

**Comment by ChrisLynchHPE** [comment]
Yes, it does say that underscores are allowed.  Just that it should be treated in place of space.  For instance: `My_useraccount`, not `_Myuseraccount`.  I know plenty of folks who use the `_` as the prefix character to service account usernames.  There is nothing for me to fix with this Cmdlet.  I'll pass along the feedback that we should allow the `_` character to be the first in the username field.

**Comment by erikgraa** [comment]
Thank you! 👍

**Comment by ChrisLynchHPE** [comment]
Just letting you know that a defect has been filed internally to fix this.  I do not (and cannot comment publically) when this will be fixed or addressed.

**Comment by erikgraa** [comment]
Superb.
