### ISSUE TITLE
Assign a UUID and Serial with New-HPOVProfile?

### ISSUE THREAD

**Issue by NJBean** [HewlettPackard/POSH-HPOneView#26]
Is there a way to assign a UUID and a Serial with the New-HPOVProfile commandlet? I'm working on a script to import a VCEM profile from a CSV to OneView.

**Comment by ChrisLynchHP** [comment]
It looks like the parameters you need were not included within the cmdlet.  I will put this on the backlog to fix.

**Comment by ChrisLynchHP** [comment]
This is fixed in [Release 1.20.166.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v1.20.166.0)
