### ISSUE TITLE
About the Addservers_monitored_sample

### ISSUE THREAD

**Issue by TanganWu** [HewlettPackard/POSH-HPOneView#260]
How can this script include scopes and labels when adding a server?
and I can't find the New-HPOVScope and Add-HPOVResourceToScope.
thx
### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
HPE OneView Appliance Version:  3.0
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
The [New-HPOVScope](https://github.com/HewlettPackard/POSH-HPOneView/wiki/New-HPOVScope) and [Add-HPOVResourceToScope](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Add-HPOVResourceToScope) Cmdlets are available in the 3.00 PowerShell library, as Scopes is a specific feature to HPE OneView 3.00.  There currently is not a native Cmdlet to create and assign labels to resources yet.

**Comment by ChrisLynchHPE** [comment]
Label support has been added in [Release 3.0.1293.3770 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1293.3770).

Closing.
