### ISSUE TITLE
Oneview Configuration Backup

### ISSUE THREAD

**Issue by scottboyde** [HewlettPackard/POSH-HPOneView#261]
Please fill in as much information as possible to help resolve your issue.

My oneview server currentIy has an error Oops Restart the appliance and/or create a support dump. I have logged a call with HPE and just waiting on some feedback.  At the moment as this was in the process of bing installed and configure for a new datacenter I do not have a backup of the appliance.  I was attempting to run a powershell script to backup the configuration.  But this is not running as the services of the appliance appear not to have started correctly.

Is it possible to get the to command line to create a backup or make sure that the services are running correctly

Thanks

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1264.2772
HPE OneView Appliance Version:  3
Output from `$PSVersionTable` on your Windows Host: 
Name                           Value                                                                                                                         
----                           -----                                                                                                                         
PSVersion                      4.0                                                                                                                           
WSManStackVersion              3.0                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                       
CLRVersion                     4.0.30319.36366                                                                                                               
BuildVersion                   6.3.9600.17400                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                          
PSRemotingProtocolVersion      2.2

**Comment by ChrisLynchHPE** [comment]
Unfortunately, without the API services running, a backup cannot be created as it is a request that requires authentication.  Please work your issue through HPE Support to resolve your appliance issue.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.
