### ISSUE TITLE
Remove-HPOVStorageVolume fails if you pass it a volume name or URI

### ISSUE THREAD

**Issue by VincentBerger** [HewlettPackard/POSH-HPOneView#262]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Remove-HPOVStorageVolume -StorageVolume should work when you pass it a volume name or URI instead of a volume object 

### Actual Behavior

```  
> Remove-HPOVStorageVolume -uri $volumeURI -Confirm:$false
 Remove-HPOVStorageVolume : The Storage Volume resource is not an expected category type [].  Allowed 
resource category type is 'storage-volumes'.  Please check the object provided and try again.
At line:1 char:1
+ Remove-HPOVStorageVolume -uri $volumeURI -Confirm:$false
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (StorageVolume::PSObject) [Remove-HPOVStorageVolume], Invalid 
   OperationException
    + FullyQualifiedErrorId : InvalidArgumentValue,Remove-HPOVStorageVolume
 ```

### Steps to reproduce

The issue is that you do
```
    if (-not($PSBoundParameters['SourceVolume']))
    {
        $PipelineInput = $True
    }
```
but the actual parameter name is StorageVolume, not SourceVolume. So you always go through the block that processes pipelined input and it fails.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1264.2772
HPE OneView Appliance Version:  3.00.07
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
I'll look at the Begin block, but you should be updating your scripts to pass in objects, not names or URIs for other than Get Cmdlets.

Sent from my Windows 10 phone

**Comment by VincentBerger** [comment]
Well, that particular srcipt wants to delete a volume attached to a profile. All I have to start with is the profile which gives me a volumeAttachment, not a volume object. And the volumeAttachment gives me the volume URI, not its name. I don't know how to get the volume object from its URI other than something like Get-HPOVStorageVolume | where { $_.uri -eq $myVolumeUri }
which feels inefficient. Any suggestion for a better way ?

**Comment by ChrisLynchHPE** [comment]
I could extend `Get-HPOVStorageVolume` Cmdlet to allow a Server Profile or Server Profile Template to return all attached volume objects.  You can then do something with them at that point.  I also have a `Set-HPOVServerProfile` Cmdlet that I am about to start work on that would allow you modify settings of the Profile or Template.

Or, you can do use the following:

```PowerShell
$MyServerProfile = Get-HPOVServerProfile -Name 'My Profile Name' -ErrorAction Stop
$Volumes = $MyServerProfile.sanStorage.volumeAttachments | % { Send-HPOVRequest -Uri $_.volumeUri }
```

**Comment by ChrisLynchHPE** [comment]
I have extended `Get-HPOVStorageVolume` to allow a Server Profile resource to be passed.  The Cmdlet will then parse the `volumeAttachments` property and return the Storage Volume objects.  This will be in the next update.

**Comment by ChrisLynchHPE** [comment]
I just published an updated library, addressing this request.  Please update to [Release 3.0.1358.2596 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1358.2596 ).

**Comment by ChrisLynchHPE** [comment]
Closing due to further inactivity.
