### ISSUE TITLE
New-HPOVBackup brings error "Value was either too large or too small for an Int32."

### ISSUE THREAD

**Issue by MWalterDE** [HewlettPackard/POSH-HPOneView#263]
### Expected Behavior
Backup HPE OneView configuration to remote Windows Server 2012 R2 computer with "New-HPOVBackup -Location E:\" command.

### Actual Behavior
PS > New-HPOVBackup -Location E:\
New-HPOVBackup : Cannot convert value "2285803536" to type "System.Int32".
Error: "Value was either too large or too small for an Int32."
At line:1 char:1
+ New-HPOVBackup -Location E:\

    + CategoryInfo          : InvalidArgument: (:) [New-HPOVBackup], RuntimeEx
   ception
    + FullyQualifiedErrorId : InvalidCastFromStringToInteger,New-HPOVBackup

### Steps to reproduce
Error occurs every time a backup is created with the PowerShell modules.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1264.2772
HPE OneView Appliance Version:  3.00.05-0271823
Output from `$PSVersionTable` on your Windows Host:
Name                           Value
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34014
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by ChrisLynchHPE** [comment]
Can you confirm that the backup file you are trying to download is 2.2**GB** in size?  I have never seen a backup be that large.  Typically they are around 200**MB**.

**Comment by MWalterDE** [comment]
Yes, the backup file is indeed 2.2GB in size right now, but this seems to be an issue with our appliance environment.
We are currently working on that with the HPE support team, so this issue can be closed.

**Comment by ChrisLynchHPE** [comment]
Okay.  The error you are getting is when we identify the file size of the download.  I'll change it to support an `Int64` data type so not to run into this issue in the future.

**Comment by ChrisLynchHPE** [comment]
I added Int64 data type support for handling inadvertently large backup files in [Release 3.0.1293.3770 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1293.3770).

Closing.

**Comment by MWalterDE** [comment]
Although I updated to version 3.0.1293.3770, the error is still present but now comes up with even more messages in our logfile.

`TerminatingError(New-Object): "Cannot convert argument "0", with value: "2291773456", for "Byte[]" to type "System.Int32": "Cannot convert value "2291773456" to type "System.Int32". Error: "Value was either too large or too small for an Int32."""`
`TerminatingError(Download-File): "Cannot convert argument "0", with value: "2291773456", for "Byte[]" to type "System.Int32": "Cannot convert value "2291773456" to type "System.Int32". Error: "Value was either too large or too small for an Int32."""`
`TerminatingError(New-HPOVBackup): "Cannot convert argument "0", with value: "2291773456", for "Byte[]" to type "System.Int32": "Cannot convert value "2291773456" to type "System.Int32". Error: "Value was either too large or too small for an Int32."""`
`New-HPOVBackup : Cannot convert argument "0", with value: "2291773456", for "Byte[]" to type "System.Int32": "Cannot convert value "2291773456" to type "System.Int32". Error: "Value was either too large or too small for an Int32.""`

**Comment by ChrisLynchHPE** [comment]
Append the -Verbose switch to your call to New-HPOVBackup and send me your log file.

Sent from my Windows 10 phone
