### ISSUE TITLE
New-HPOVNetwork  ignore the bandwidth parameter

### ISSUE THREAD

**Issue by henwei** [HewlettPackard/POSH-HPOneView#266]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
The following documented sample should set the bandwidth parameters
PS C:\scripts> New-HPOVNetwork -type Ethernet -name MyNetwork1 -vlanid 100 -typicalbandwidth 5000 -maximumbandwidth 7500

### Actual Behavior
The command generates always the default parameters only
Name            Status Purpose Type     VlanID IPv4Subnet Smartlink PrivateNetwork PreferredBandwidth MaxBandwidth
----            ------ ------- ----     ------ ---------- --------- -------------- ------------------ ------------
192.168.20.0_24 OK     General Untagged 0      None       True      False          2500               10000
MyNetwork1      OK     General Tagged   100    None       True      False          2500               10000
vMotion 200 A   OK     General Tagged   200    None       True      False          2500               10000

### Steps to reproduce
try New-HPOVNetwork  with several bandwidth parameters

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1121.2161
HPE OneView Appliance Version:   3.00.07-0288219
Output from `$PSVersionTable` on your Windows Host:
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by henwei** [comment]
update to Release 3.0.1293.3770  - Solved  :-)  sorry for that

**Comment by ChrisLynchHPE** [comment]
Closing.
