### ISSUE TITLE
Set-HPOVNetworkSet throws an invalid JSON exception

### ISSUE THREAD

**Issue by jullienl** [HewlettPackard/POSH-HPOneView#268]
`$net = (Get-HPOVNetwork -Name Production-$VLAN).uri`
`$netset = Get-HPOVNetworkSet -Name "Production Networks"`
`$netset2uris = $netset.networkUris | where { $_ -ne $net }`  
`$netset.networkUris = $netset2uris`
`$remove = Set-HPOVNetworkSet -NetworkSet $netset | Wait-HPOVTaskComplete`

`$error | fl * -Force | select -first 1`

PSMessageDetails      : 
Exception             : System.InvalidOperationException: The JSON in the request is invalid. There is an error on line 1 near column 26. 
                        Correct the invalid JSON and try the request again. 
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : Send-HPOVRequest
CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationException
FullyQualifiedErrorId : InvalidOperation,Send-HPOVRequest
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Program Files\WindowsPowerShell\Modules\HPOneview.300\HPOneView.300.psm1: line 4655
                        at Set-HPOVNetworkSet<Process>, C:\Program Files\WindowsPowerShell\Modules\HPOneview.300\HPOneView.300.psm1: line 50908
                       at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
3.0.1293.3770

HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:
Name  : PSVersion
Value : 5.0.10586.117

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}

Name  : BuildVersion
Value : 10.0.10586.117

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : WSManStackVersion
Value : 3.0

Name  : PSRemotingProtocolVersion
Value : 2.3

Name  : SerializationVersion
Value : 1.1.0.1

**Comment by ChrisLynchHPE** [comment]
The `Set-HPOVNetworkSet` Cmdlet will already set the associated networks to what you declare.  So, what you should have done is this:

```PowerShell
$NetToRemove = (Get-HPOVNetwork -Name Production-$VLAN).uri
$NetSet = Get-HPOVNetworkSet -Name "Production Networks"
$NewNets = ( $NetSet.networkUris | where { $_ -ne $NetToRemove } ) | % { Send-HPOVRequest -Uri $_ }
Set-HPOVNetworkSet -NetworkSet $NetSet -Networks $NewNets | Wait-HPOVTaskComplete
```

The documentation for `-Networks` parameter in [`Set-HPOVNetworkSet`](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Set-HPOVNetworkSet) states:

`An array containing the updated list of networks`

**Comment by jullienl** [comment]
Thanks but doesn't it also states:

`May contain Network Names or URI's.`

My script was working some time ago so something got changed !
