### ISSUE TITLE
Community Request (Please read): Consider adding to PowerShell Gallery

### ISSUE THREAD

**Issue by cantrellj** [HewlettPackard/POSH-HPOneView#269]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
More a feature request/enhancement than issue. Please consider making this available via PowerShell Gallery. It appears that other HPE modules have recently been posted there and having all available from a single, trusted source would be most helpful.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
This has been under consideration for a while.  Until the process can be worked out, the PowerShell module installer is the official mechanism today from this GitHub trusted site.

**Comment by ChrisLynchHPE** [comment]
As of today, I have published the current 3.10 library to the PowerShell Gallery.  You can find it [here](https://www.powershellgallery.com/packages/HPOneView.310/3.10.1416.3042).  Of course, you can always use the native PowerShell Cmdlets:

```PowerShell
Install-Module HPOneView.310
```
![install-module and connect](https://user-images.githubusercontent.com/6956305/29479826-4f629bf8-8429-11e7-9502-227064005411.png)

I am looking to continue dual publishing with the 3.10 library and any newer release in the future.  There may be a time where I deprecate the installer hosted here.  If there are folks that have not upgraded to Windows Management Framework 5.0 or newer, and would still like the downloadable installer, please provide your comments here.  I will leave this thread open.

**Comment by DungKHoang** [comment]
I fully agree to move forward with PowerShell Gallery. However, we need to consider the fact that installing module from the gallery requirex the client to use Windows Management Framework (WMF) 5.0 which is included in Windows Server 2012R2 and Windows 10 with PowerShell v5.0
For down-level versions, administrator needs to manually upgrade to WMF5.0
I have seen instances where Windows Server 2012 and Windows 7 are still the standard of OS in enterprises and asking for an upgrade to WMF 5.0 can be a huge challenge ( especially in federal environment)
So I appreciate to have both options but will push for PowerShell Gallery :=)
/Dung

**Comment by ChrisLynchHPE** [comment]
The 3.10 library is now published in the [PowerShellGallery](https://www.powershellgallery.com/packages/HPOneView.310/).  Older libraries will not be published.  All future libraries will be published to the gallery.
