### ISSUE TITLE
Add-hpovserver

### ISSUE THREAD

**Issue by timbing26** [HewlettPackard/POSH-HPOneView#27]
When trying to add a server in monitored I enter licensingIntent: OneViewNoiLo

I get the following:
Enter licensing intent for the server being imported (OneView or OneViewNoiLO).
licensingIntent: OneViewNoiLO
Name            : Add
Owner           : Administrator
TaskState       : Error
PercentComplete : 100
ProgressUpdates : {}
TaskErrors      : {@{errorCode=MONITOR_ONLY_SERVER_MODEL; data=; message=Unable to add the server hardware as "Managed". HP OneView does not support
                  server profiles for this server hardware, so it can only be monitored.; nestedErrors=System.Object[]; errorSource=; details=;
                  recommendedActions=System.Object[]}}
Created         : 2015-07-09T07:46:42.990Z
Nodified        : 2015-07-09T07:46:43.065Z

I have a large number of servers to add into HP OV in monitored only and was hoping to script it.

What is the syntax to add server as monitored.

Thanks

Tim

**Comment by ejschulte** [comment]
get-help Add-HPOVServer -examples

It's example #2.  The licensingintent parameter is not required for adding a server in monitored mode.

**Comment by ChrisLynchHP** [comment]
Also, if you do "help Add-HPOVServer", then syntax is available there.  You will notice that the -Monitored SwitchParameter does not include the -LicenseIntent parameter in the syntax.  I have updated the help for LicenseIntent to make it more clear on its usage.

**Comment by timbing26** [comment]
Hi Chris,

Thanks for your quick reply.

Looking at using HP Oneview for monitoring all HP hardware Globally so was looking for a quick easy way to add multiple servers. The GUI was just a little slow and laborious.

HP SIM was easy with its discover feature.

Many thanks

Regards

Tim

**Comment by ChrisLynchHP** [comment]
The UI (and the PowerShell library) both wait for the Async task to be accepted.  The UI shouldn't be so slow that you can't select Add+ to continue adding your servers.  If you have 100's, completely understand, and the PowerShell library (or API for that matter) will help add a large collection of supported devices to OneView.
