### ISSUE TITLE
New-HPOVServerProfileTemplate fails when SAN storage requested

### ISSUE THREAD

**Issue by daveolker** [HewlettPackard/POSH-HPOneView#272]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior

Prior to the 3.0.1293.3770 release, creating a new Server Profile Template worked when requesting SAN-based storage.  I confirmed this works with the 3.0.1264.2772 version of the POSH-HPOneView library.  I also confirmed the template will create even with the 3.0.1293.3770 library if SANstorage is set to $false.  

### Actual Behavior

With the 3.0.1293.3770 library the `New-HPOVServerProfileTemplate` call fails when SAN storage is requested as part of the template.  I enabled Verbose logging and it appears to fail when attempting to instantiate the list of SAN storage systems:

```Powershell
VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] SAN Storage being requested
VERBOSE: [NEW-HPOVSERVERPROFILETEMPLATE] Getting list of available storage systems
New-HPOVServerProfileTemplate : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value
and try again.
At C:\Users\DFO\Documents\GitHub\Populate-HPE-Synergy\Populate_HPE_Synergy.ps1:351 char:5
+     New-HPOVServerProfileTemplate @params -Verbose | Wait-HPOVTaskCom ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-HPOVServerProfileTemplate], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-HPOVServerProfileTemplate
```

### Steps to reproduce
    $SY660Gen9SHT      = Get-HPOVServerHardwareTypes -name "SY 660 Gen9 1" -ErrorAction Stop
    $EnclGroup         = Get-HPOVEnclosureGroup -Name "EG-Synergy-Local"
    $FWBaseline        = Get-HPOVBaseline -SppName "Service Pack for ProLiant" -Version "2016.10.0" -ErrorAction Stop
    $Eth1              = Get-HPOVNetwork -Name "Prod_1101" | New-HPOVServerProfileConnection -ConnectionID 1 -Name 'Prod-1101' -Bootable -Priority Primary
    $Eth2              = Get-HPOVNetwork -Name "Prod_1102" | New-HPOVServerProfileConnection -ConnectionID 2 -Name 'Prod-1102'
    $FC1               = Get-HPOVNetwork -Name 'SAN A FC' | New-HPOVServerProfileConnection -connectionId 3
    $FC2               = Get-HPOVNetwork -Name 'SAN B FC' | New-HPOVServerProfileConnection -connectionId 4
    $LogicalDisk       = New-HPOVServerProfileLogicalDisk -Name "SAS RAID5 SSD" -RAID RAID5 -NumberofDrives 3 -DriveType SASSSD -Bootable $True
    $SANVol            = Get-HPOVStorageVolume -Name "Shared-Volume-2" | New-HPOVProfileAttachVolume -LunIdType Manual -LunID 0
    $StorageController = New-HPOVServerProfileLogicalDiskController -ControllerID Embedded -Mode RAID -Initialize -LogicalDisk $LogicalDisk

    $params = @{
        Affinity                 = "Bay";
        Baseline                 = $FWBaseline;
        BootMode                 = "UEFI";
        BootOrder                = "HardDisk";
        Connections              = $Eth1, $Eth2, $FC1, $FC2;
        Description              = "Server Profile Template for HPE Synergy 660 Gen9 Compute Module with Local and SAN Storage";
        EnclosureGroup           = $EnclGroup;
        Firmware                 = $True;
        FirmwareMode             = "FirmwareOnly";
        HideUnusedFlexNics       = $True;
        LocalStorage             = $True;
        HostOStype               = "Win2k12";
        ManageBoot               = $True;
        Name                     = "HPE Synergy 660 Gen9 Profile Template 2";
        PxeBootPolicy            = "IPv4ThenIPv6";
        SANStorage               = $True;
        ServerHardwareType       = $SY660Gen9SHT;
        ServerProfileDescription = "Server Profile for HPE Synergy 660 Gen9 Compute Module";
        StorageController        = $StorageController;
        StorageVolume            = $SANVol
    }

    New-HPOVServerProfileTemplate @params -Verbose | Wait-HPOVTaskComplete

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):

```PowerShell
PowerShellLibraryVersion : 3.0.1293.3770
LibraryPath              : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300


HPE OneView Appliance Version:  3.00.04-0269898 (Synergy DCS Appliance)
```

Output from `$PSVersionTable` on your Windows Host: 

```Powershell
Name                           Value
----                           -----
PSVersion                      5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ChrisLynchHPE** [comment]
Do you by chance have any storage volumes created yet?  There is an issue with one of the URI's we use to validate volume attachments and if a server profile can be attached to a storage system.  And if 1 volume has not been created yet, the API lookup will cause a failure.

**Comment by ChrisLynchHPE** [comment]
I found the issue, and will have it fixed for the next update.

**Comment by ChrisLynchHPE** [comment]
I just published an updated library, addressing this issue.  Please update to [Release 3.0.1358.2596 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1358.2596 ).

**Comment by ChrisLynchHPE** [comment]
Closing due to further inactivity.
