### ISSUE TITLE
Get-HPOVApplianceNetworkConfig returns nothing

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#273]
### Actual Behavior
Get-HPOVApplianceNetworkConfig -Verbose shows the expected details/output, but nothing is returned by the Cmdlet.

Also, using the -Location parameter just gives you a .json file in the specified folder with a bunch of "Microsoft.PowerShell.Commands.Internal.Format." strings.

Is there any other way to get the FQDN of the appliance?

### Steps to reproduce
Get-HPOVApplianceNetworkConfig

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0
HPE OneView Appliance Version: 3.0.1293.3770
Output from `$PSVersionTable` on your Windows Host: 4.0

**Comment by erikgraa** [comment]
Re. no object returned: Looks to be because the function expects $ApplianceNetworkConfiguration to be returned, whereas $_ApplianceNetworkConfiguration is the object in the function.

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting this.  It will be fixed in the next update.

**Comment by ChrisLynchHPE** [comment]
I just published an updated library, addressing this issue.  Please update to [Release 3.0.1358.2596 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1358.2596 ).

**Comment by ChrisLynchHPE** [comment]
Closing due to further inactivity.
