### ISSUE TITLE
Set-HPOVNetwork Behavior Change

### ISSUE THREAD

**Issue by daveolker** [HewlettPackard/POSH-HPOneView#274]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
With previous release, the following logic worked:
Set-HPOVNetwork -InputObject Deployment -IPv4Subnet $deploy_subnet

### Actual Behavior
Latest library requires the following:

$Deploy_AddrPool = Get-HPOVAddressPoolSubnet -NetworkId $deploy_subnet
Get-HPOVNetwork -Name Deployment | Set-HPOVNetwork -IPv4Subnet $Deploy_AddrPool

### Steps to reproduce
Test code with latest library and previous library

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): Release 3.0.1293.3770
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
I will need a bit more information from you on this issue.  Are you getting a specific error?  Is the result different?  The pipeline operation in the `Actual Behavior` is no different than if you were to use the `-InputObject` parameter based on the code of the Cmdlet you are reporting.

**Comment by daveolker** [comment]
With the 3.0.1264.2772 library this command completes without error:
Set-HPOVNetwork -InputObject Deployment -IPv4Subnet $deploy_subnet

After updating to version 3.0.1293.3770, the same cmdlet gives:
Get-HPOVNetwork : A positional parameter cannot be found that accepts argument 'Deployment'.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.300\HPOneView.300.psm1:48880 char:16
+ ...      $net = Get-HPOVNetwork $net -type $PSCmdlet.ParameterSetName -Ap ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-HPOVNetwork], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Get-HPOVNetwork
 
Set-HPOVNetwork : Cannot validate argument on parameter 'Hostname'. The argument is null or empty. Provide an argument that is not null or empty, 
and then try the command again.
At line:1 char:1
+ Set-HPOVNetwork -InputObject Deployment -IPv4Subnet $deploy_subnet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-HPOVNetwork], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Set-HPOVNetwork


The workaround was to change my code to:
$Deploy_AddrPool = Get-HPOVAddressPoolSubnet -NetworkId $deploy_subnet
Get-HPOVNetwork -Name Deployment | Set-HPOVNetwork -IPv4Subnet $Deploy_AddrPool

**Comment by ChrisLynchHPE** [comment]
So, are you passing in `Deployment` as a `String` value?  I do see a small defect in how `String` values are handled.  I would suggest you update your script to use Objects instead.

**Comment by ChrisLynchHPE** [comment]
And looking at the version you say works, it really shouldn't.  There is no difference between the two releases you have reported.  Either way, it is a small defect that I will get fixed.

**Comment by daveolker** [comment]
I was passing in a string value based on the Set-HPOVNetwork help page:

-InputObject <Object>
        Aliases [-net, -Network]
        **The Name or Resource object** of the network to be modified.

I'm fine modifying my code to pass in a resource object, but the previous version accepted a string value that matched the name of the network.  

By the way, the new library caused a similar change in behavior to other cmdlets, including: Set-HPOVEnclosure and New-HPOVUplinkSet.

**Comment by ChrisLynchHPE** [comment]
The library has been changing to accept Objects instead of resource names in order to support multiple appliance connections.  Docs should have be updated to reflect that.  I will look at those other Cmdlet help as well.

Again, the code is identical from the teo versions you have reported. Are you sure you don’t have multiple versions of the library installed on your system?

Sent from my Windows 10 phone

**Comment by daveolker** [comment]
Just to be sure, I uninstalled the POSH-HPOneView library using CCleaner, verified there were no remnants of the installation on my system, re-downloaded the current library and installed it.

PS C:\> Get-HPOVVersion

        Welcome to the HPE OneView POSH Library, v3.0.1293.3770

I get the same error.

**Comment by ChrisLynchHPE** [comment]
This will be fixed in the next update.

**Comment by ChrisLynchHPE** [comment]
I just published an updated library, addressing this issue.  Please update to [Release 3.0.1358.2596 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1358.2596 ).

**Comment by ChrisLynchHPE** [comment]
Closing due to further inactivity.
