### ISSUE TITLE
ConvertTo-HPOVImageStreamerConfiguration

### ISSUE THREAD

**Issue by Brandonk13** [HewlettPackard/POSH-HPOneView#275]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Reconfigure Logical Enclosure

### Actual Behavior
ConvertTo-HPOVImageStreamerConfiguration : The term 'else' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
+ ConvertTo-HPOVImageStreamerConfiguration -InputObject $le -UplinkSetN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (else:String) [ConvertTo-HPOVImageStreamerConfiguration], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,ConvertTo-HPOVImageStreamerConfiguration

### Steps to reproduce
ConvertTo-HPOVImageStreamerConfiguration -InputObject $le -UplinkSetName $UplinkSetName -UplinkPorts $UplinkPorts -DeploymentNetwork $DeploymentNetwork -IgnoreSasLogicalInterconnects

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
PowerShellLibraryVersion : 3.0.1293.3770
LibraryPath              : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300
HPE OneView Appliance Version:  
Model Synergy Composer
Firmware
Version 3.00.07-0288219
Date Mar 15, 2017
Output from `$PSVersionTable` on your Windows Host:
Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.15063.138                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.15063.138                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
Hmm..  I cannot seem to find where this error is coming from.  When you attempt to execute the Cmdlet, can you then get the output from $error | Ft * -force ?

Sent from my Windows 10 phone

**Comment by Brandonk13** [comment]
PSMessageDetails Exception                                                                                                                                                                    
---------------- ---------                                                                                                                                                                    
                 System.Management.Automation.CommandNotFoundException: The term 'else' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the sp...
                 System.Management.Automation.ItemNotFoundException: Cannot find a variable with the name 'PesterTest'.                                                                       
                 System.Management.Automation.ItemNotFoundException: Cannot find a variable with the name 'IsWindows'.

And here's my code if it helps

$LE = Get-HPOVLogicalEnclosure
$uplinkPorts = @("Enclosure1:Bay3:Q1.1")
$uplinkSetName = 'ImageStreamer UplinkSet'
$DeploymentNetwork = Get-HPOVNetwork -Name 'Deployment'
ConvertTo-HPOVImageStreamerConfiguration -InputObject $le -UplinkSetName $UplinkSetName -UplinkPorts $UplinkPorts -DeploymentNetwork $DeploymentNetwork -IgnoreSasLogicalInterconnects

**Comment by ChrisLynchHPE** [comment]
I need the entire exception, not a snippet that you provided.

Sent from my Windows 10 phone

**Comment by Brandonk13** [comment]
PS C:\Users\bkoenigsknecht\Desktop> $error
else : The term 'else' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.300\HPOneView.300.psm1:64622 char:6
+                     else
+                     ~~~~
    + CategoryInfo          : ObjectNotFound: (else:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Connect-HPOVMgmt : A positional parameter cannot be found that accepts argument 'optlab-synergy.ad.optiolab.us'.
At line:1 char:1
+ Connect-HPOVMgmt "optlab-synergy.ad.optiolab.us" -UserName optlab\bko ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-HPOVMgmt], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Connect-HPOVMgmt

Connect-HPOVMgmt : A positional parameter cannot be found that accepts argument 'optlab-synergy.ad.optiolab.us'.
At line:1 char:1
+ Connect-HPOVMgmt optlab-synergy.ad.optiolab.us -UserName optlab\bkoen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-HPOVMgmt], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Connect-HPOVMgmt

Get-Variable : Cannot find a variable with the name 'PesterTest'.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.300\HPOneView.300.psm1:88367 char:18
+ ... terRun    = Get-Variable -Name PesterTest -Scope Global -ErrorAction  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PesterTest:String) [Get-Variable], ItemNotFoundException
    + FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.GetVariableCommand

Get-Variable : Cannot find a variable with the name 'IsWindows'.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.300\HPOneView.300.psm1:88358 char:32
+ ... = if (-not (Get-Variable -Name IsWindows -ErrorAction SilentlyContinu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (IsWindows:String) [Get-Variable], ItemNotFoundException
    + FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.GetVariableCommand

**Comment by Brandonk13** [comment]
[PSerror.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/1064198/PSerror.txt)

**Comment by ChrisLynchHPE** [comment]
Thanks.  I actually have this fixed already for the upcoming update.

**Comment by Brandonk13** [comment]
Awesome. When is the next update coming? Before or after the 3.1 OV patch?

**Comment by ChrisLynchHPE** [comment]
Before.  We only announced HPE OneView 3.1 this last week at HPE Discover in Las Vegas.

**Comment by ChrisLynchHPE** [comment]
I just published an updated library, addressing this issue.  Please update to [Release 3.0.1358.2596 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1358.2596 ).

**Comment by ChrisLynchHPE** [comment]
Closing due to further inactivity.
