### ISSUE TITLE
Get-HPOVServer ignores the "-Label" parameter, returning all servers instead

### ISSUE THREAD

**Issue by ronanmcallister** [HewlettPackard/POSH-HPOneView#277]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior

When using Get-HPOVServer with the "-Label" parameter acting as a filter, the output should return only Server Hardware from Servers with matching Labels

### Actual Behavior

All Server Hardware in our OneView 3.0 are returned.

### Steps to reproduce

Notes:

- Both of these scenarios 1 and 2 below produce the same unexpected behaviour.

- To make things simple, my examples below are using only one unique Label associated with a single Server (DL380p Gen8) however in reality, we have added multiple Labels to some servers to help us track servers/issues.

**Scenario 1:** Using Get-HPOVServer -Label against Server HW already having Labels which were added through the OneView API in the past.

- For Server ILOXXXXXXXXXX, I have manually created a new (and the only) Label through the UI, naming it "5320400304".
    
- I've confirmed the Label I've added from the UI can be found using the APIs:
```

       Get-HPOVLabel -Name 5320400304
       
       Name      
       ----      
       5320400304

# Attempt to limit the Get-HPOVServer output to just the one Server Hardware with this label:

      Get-HPOVServer -Label 5320400304

```

Results: _All of the Server Hardware in OneView (419 DL* servers) are returned instead of ILOXXXXXXXXXX associated with 5320400304 Label alone._

**Scenario 2:** Create and associate a new Label with a different and single Server HW, and then attempt to limit Get-HPOVServer output to just that one Server, all through the POSH APIs:

```
      $Resources = Get-HPOVServer -Name ILOYYYYYYYYYY
      Add-HPOVResourceToLabel -Name APITEST -InputObject $Resources
```

The created label can be seen thereafter in the OneView UI associated with ILOYYYYYYYYYY
As well, the Label is returned with the Get-HPOVLabel cmdlet:

```
      Get-HPOVLabel -Name APITEST

		Name   
		----   
		APITEST

# Attempt to limit the Get-HPOVServer output to just the one Server Hardware with this label:

      Get-HPOVServer -Label "APITEST"

```
      
Results: _All of the Server Hardware in OneView (419 DL* servers) are returned instead of ILOYYYYYYYYYY alone._

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):

PowerShellLibraryVersion : 3.0.1293.3770

LibraryPath              : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300

HPE OneView Appliance Version:  3.00.05-0271823

Output from `$PSVersionTable` on your Windows Host:

Name						Value

PSVersion				        5.0.10586.117
PSCompatibleVersions		        {1.0, 2.0, 3.0, 4.0...}
BuildVersion				        10.0.10586.117
CLRVersion					4.0.30319.42000
WSManStackVersion			3.0
PSRemotingProtocolVersion	        2.3
SerializationVersion		                1.1.0.1

**Comment by ChrisLynchHPE** [comment]
Thanks Ronan.  This is a confirmed defect, which I will have fixed for the next update.

**Comment by ronanmcallister** [comment]
Thanks for your super-quick help!

R

**Comment by ChrisLynchHPE** [comment]
I just published an updated library, addressing this issue.  Please update to [Release 3.0.1358.2596 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1358.2596 ).

**Comment by ChrisLynchHPE** [comment]
Closing due to further inactivity.
