### ISSUE TITLE
 ConvertTo-HPOVServerProfileTemplate

### ISSUE THREAD

**Issue by Brandonk13** [HewlettPackard/POSH-HPOneView#279]
Please fill in as much information as possible to help resolve your issue.
Get-HPOVServerProfile -Name test | ConvertTo-HPOVServerProfileTemplate -Name testtemplate 

where 'test' is my server profile and I'm trying to convert it to 'testtemplate'
### Expected Behavior
testtemplate server profile template is created

### Actual Behavior
PS C:\WINDOWS\system32> Get-HPOVServerProfile -Name test | ConvertTo-HPOVServerProfileTemplate -Name testtemplate
ConvertTo-HPOVServerProfileTemplate : The field named initiatorName near line 1, column 740 is not a valid field in this JSON object. Check the valid fields for this JSON object and remove 
or correct the unrecognized field. 
At line:1 char:36
+ ... e -Name test | ConvertTo-HPOVServerProfileTemplate -Name testtemplate
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [ConvertTo-HPOVServerProfileTemplate], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,ConvertTo-HPOVServerProfileTemplate

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
PowerShellLibraryVersion : 3.0.1293.3770
LibraryPath              : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300
HPE OneView Appliance Version:  
Version 3.00.07-0288219
Date Mar 15, 2017
Output from `$PSVersionTable` on your Windows Host:
Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.15063.138                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.15063.138                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
Can you provide the JSON object of your server profile?

Get-HPOVServerProfile -Name Test | ConvertTo-Json -Depth 99 > ServerProfileObject.json

**Comment by Brandonk13** [comment]
[ServerProfileObject.zip](https://github.com/HewlettPackard/POSH-HPOneView/files/1089586/ServerProfileObject.zip)

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting this.  When we added iSCSI support in HPE OneView 3.00, I didn't take into account updating this Cmdlet to strip out unique server profile connection properties.  I have this fixed, and will be in the next update.

**Comment by ChrisLynchHPE** [comment]
I just published an updated library, addressing this issue.  Please update to [Release 3.0.1358.2596 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1358.2596 ).

**Comment by Brandonk13** [comment]
I found another bug with this cmdlet. Do you want to reopen this issue or should I open a new one?

**Comment by Brandonk13** [comment]
ConvertTo-HPOVServerProfileTemplate -InputObject $template -Name Test-Template1
ConvertTo-HPOVServerProfileTemplate : The field named sasLogicalJBODUri near line 1, column 1,012 is not a valid field in this JSON object. Check the valid fields for this JSON object and 
remove or correct the unrecognized field. 
At line:1 char:1
+ ConvertTo-HPOVServerProfileTemplate -InputObject $template -Name Test ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [ConvertTo-HPOVServerProfileTemplate], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,ConvertTo-HPOVServerProfileTemplate

**Comment by ChrisLynchHPE** [comment]
Looks like you are trying to clone a Server Profile from a Synergy Composer to a non-Synergy Composer appliance.  The property `sasLogicalJBODUri` is unique to a Synergy Server Profile.

**Comment by Brandonk13** [comment]
This is pulling a server profile from synergy to create a server profile template on the same synergy frame

**Comment by ChrisLynchHPE** [comment]
Ah, okay.  Well, I only tested and validated this on an OneView virtual machine appliance (aka non-Synergy environment).  I'll test this on a Synergy appliance.

**Comment by ChrisLynchHPE** [comment]
I have this fixed, and will be in the next update.

**Comment by ChrisLynchHPE** [comment]
This issue was fixed in the [Release 3.0.1358.2596](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1358.2596).  

With the 3.00 library is no longer a supported version, I am closing this issue.  If you have upgraded to a newer OneView and OneView PowerShell version and still experience this issue, please open a new issue.
