### ISSUE TITLE
Issue in reading data from Get-HPOVStoragePool

### ISSUE THREAD

**Issue by SahilMutha** [HewlettPackard/POSH-HPOneView#284]
Please fill in as much information as possible to help resolve your issue.

We are getting the output for this command (Get-HPOVStoragePool), but we could not read all the elements from the output such as RAID, Drive type. These values are present in output table but we are not able to read these values.

### Expected Behavior
```PowerShell
$a = Get-HPOVStoragePool

$a =
Name       Status Storage System Domain    Drive Type RAID  Total        Allocated Free        
----       ------ -------------- ------    ---------- ----  -----        --------- ----        
CPG_DATA01 OK     sstor01        NO DOMAIN FC         RAID5 10,917.00 GB 0.00 GB   10,917.00 GB
```
$a.RAID  -- This should return the RAID type that is coming in the output table (in this case 'RAID5')
$a.DriveType -- This should return the Drive type that is coming in the output table (in this case 'FC').

These values (RAID, Drive Type) should be exposed to read.

### Actual Behavior
``` powershell
$a = Get-HPOVStoragePool
$a.RAID  -- There is no value returned here despite of having RAID entry in table.
$a.DriveType -- There is no value returned here despite of having RAID entry in table.
```
### Steps to reproduce

1. Connect to OneView - Connect-HPOVmgmt
2. Run $a = Get-HPOVStoragePool
3. Run $a. RAID or $a.DriveType

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.10.1377.2109
HPE OneView Appliance Version:  3.10.04.0299553

Output from `$PSVersionTable` on your Windows Host: 

Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : BuildVersion
Value : 6.3.9600.17400

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

**Comment by ChrisLynchHPE** [comment]
The properties you are looking for changed in 3.10.  You need to be looking within a sub-attribute called `deviceSpecificAttributes`.  The values you are looking for are contained there.
