### ISSUE TITLE
Having an issue with New-HPOVLogicalInterconnectGroup -Name 'LIG-C' -Bays = @{ Frame1=@{Bay3 = 'SEVC40f8'; Bay6 ='SE20ILM'};  }

### ISSUE THREAD

**Issue by gavinp26** [HewlettPackard/POSH-HPOneView#285]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Create  LIG 

### Actual Behavior
Syntax error
```powershell
PS C:\Users\PGavin\Downloads\POSH-HPOneView-3.10\POSH-HPOneView-3.10\Samples> New-HPOVLogicalInterconnectGroup -Name 'LIG-C' $Bays = @{ Frame1 = @{Bay3 = 'SEVC40f8'; Bay6 = 'SE20ILM'}}
New-HPOVLogicalInterconnectGroup : A positional parameter cannot be found that accepts argument 'System.Collections.Hashtable'.
At line:1 char:1
+ New-HPOVLogicalInterconnectGroup -Name 'LIG-C' $Bays = @{ Frame1 = @{Bay3 = 'SEV ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-HPOVLogicalInterconnectGroup], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,New-HPOVLogicalInterconnectGroup
```

### Steps to reproduce
```powershell
New-HPOVLogicalInterconnectGroup -Name 'LIG-C' $Bays = @{ Frame1 = @{Bay3 = 'SEVC40f8'; Bay6 = 'SE20ILM'}}
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
owerShellLibraryVersion : 3.0.1358.2596
LibraryPath              : C:\Program Files\WindowsPowerShell\Modules\HPOneView.300
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
Your command is incorrect.  You are trying to set a variable to a value within the call to a Cmdlet.  Your call should be:

```PowerShell
$Bays = @{ Frame1 = @{Bay3 = 'SEVC40f8'; Bay6 = 'SE20ILM'}}
New-HPOVLogicalInterconnectGroup -Name 'LIG-C' -Bays $Bays
```

**Comment by gavinp26** [comment]
Tried this
$Bays = @{ Frame1 = @{Bay3 = 'SEVC40f8'; Bay6 = 'SEVC40f8'}}
New-HPOVLogicalInterconnectGroup -Name 'LIG-C' -Bays $Bays
got this
New-HPOVLogicalInterconnectGroup : The JSON sent in the request contained a unknown type where a different unknown type was required on line 1 near column 
2,345. Correct the content of the JSON and try the request again. 
At line:2 char:1
+ New-HPOVLogicalInterconnectGroup -Name 'LIG-C' -Bays $Bays
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [New-HPOVLogicalInterconnectGroup], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,New-HPOVLogicalInterconnectGroup

**Comment by ChrisLynchHPE** [comment]
Since you are trying to create a Synergy Logical Interconnect Group, you are missing a few parameters:
```PowerShell
$Bays = @{ Frame1 = @{Bay3 = 'SEVC40f8'; Bay6 = 'SEVC40f8'}}
New-HPOVLogicalInterconnectGroup -Name 'LIG-C' -Bays $Bays-FrameCount 1 -InterconnectBaySet 3 -FabricModuleType SEVC40F8
Appliance       Name   Owner         Created              Duration TaskState PercentComplete
---------       ----   -----         -------              -------- --------- ---------------
appliance.local Create Administrator 8/21/2017 2:49:48 PM 00:00:00 Completed 100

```

**Comment by gavinp26** [comment]
That worked thank you

**Comment by ChrisLynchHPE** [comment]
You're welcome.
