### ISSUE TITLE
can't remove server profiles using Remove-HPOVServerProfile

### ISSUE THREAD

**Issue by hitsujigithub** [HewlettPackard/POSH-HPOneView#286]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
The command below will remove the profile.
PS C:\Users\Administrator> Remove-HPOVServerProfile -ServerProfile "demo-bay03"

### Actual Behavior
I got error below.
The profile named "demo-bay03" exists.
Am I missing something?
PS C:\Users\Administrator> Remove-HPOVServerProfile -ServerProfile "demo-bay03"
Remove-HPOVServerProfile : A positional parameter cannot be found that accepts argument 'demo-bay03'.
At line:1 char:1
+ Remove-HPOVServerProfile -ServerProfile "demo-bay03"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-HPOVServerProfile], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Remove-HPOVServerProfile

### Steps to reproduce
After connecting to OneView using Connect-HPOVMgmt command,
PS C:\Users\Administrator> Remove-HPOVServerProfile -ServerProfile "demo-bay03"

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.10.1416.3042
HPE OneView Appliance Version: 3.10.04-0299553 (Synergy Composer)
Output from `$PSVersionTable` on your Windows Host: 
Name                           Value
----                           -----
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
Please provide the Server Profile object instead of using the name:

Get-HPOVServerProfile -Name demo-bay03 | Remove-HPOVServerProfile

Sent from my Windows 10 phone

**Comment by ChrisLynchHPE** [comment]
Closing, as resolved.
