### ISSUE TITLE
New-HPOVlicense does not handle comment lines within license file generated by HPE entitlement site.

### ISSUE THREAD

**Issue by sinelshchikov** [HewlettPackard/POSH-HPOneView#288]
Please fill in as much information as possible to help resolve your issue.

The FC licences do not install. They are working , because I can install them via GUI.
I will send you my FClicense1.txt file in private message .

### Expected Behavior

$license2 = 'Lic here'
New-HPOVlicense $license2
_I am not sure what is the proper output if the command works..._

### Actual Behavior

```
PS C:\Users\Administrator> $license2 = 'Lic here'
PS C:\Users\Administrator> New-HPOVlicense $license2

New-HPOVLicense : A positional parameter cannot be found that accepts argument 'Lic Here'.
At line:1 char:1
+ New-HPOVlicense $license2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-HPOVLicense], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,New-HPOVLicense

```
```
PS C:\Users\Administrator> GC "C:\classfiles\FClicense1.txt" | New-HPOVlicense

New-HPOVlicense : The "type" field content, "License", included in this request is invalid. Correct the content in the
'type' field of the JSON and try the request again.
At line:1 char:37
+ GC "C:\classfiles\FClicense1.txt" | New-HPOVlicense
+                                     ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (LicenseKey:String) [New-HPOVLicense], LicenseKeyException
    + FullyQualifiedErrorId : InvalidResult,New-HPOVLicense
```

```
PS C:\Users\Administrator> New-HPOVlicense -file "C:\classfiles\FClicense1.txt"

New-HPOVlicense : The "type" field content, "License", included in this request is invalid. Correct the content in the
'type' field of the JSON and try the request again.
At line:1 char:1
+ New-HPOVlicense -file "C:\classfiles\FClicense1.txt"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (LicenseKey:String) [New-HPOVLicense], LicenseKeyException
    + FullyQualifiedErrorId : InvalidResult,New-HPOVLicense

PS C:\Users\Administrator>
```

### Steps to reproduce

Please see "actual behavior"

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.10.1377.2109
HPE OneView Appliance Version:  DCS  3.10.05-0302465 
Output from `$PSVersionTable` on your Windows Host:
```PowerShell
Name                           Value
----                              -----
PSVersion                      4.0
WSManStackVersion     3.0
SerializationVersion       1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

**Comment by ChrisLynchHPE** [comment]
Two things:

1. Update your library.  The [current 3.10.1416.3042](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.10.1416.3042) release contains fixes to New-HPOVLicense.
2. The ultimate issue is with your license file, and not the Cmdlet.  Remove lines that are comments from your license file.

**Comment by ChrisLynchHPE** [comment]
I will add an enhancement to filter out lines of `[String]` starting with the `#` character, which will help with license files generated from our entitlement portal.

**Comment by ChrisLynchHPE** [comment]
This is now enhanced in [Release 3.10.1471.1581](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.10.1471.1581), which has also been published to the [PowerShellGallery](https://www.powershellgallery.com/packages/HPOneView.310).

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.
