### ISSUE TITLE
Command Connect-HPOVMgmt not recognized

### ISSUE THREAD

**Issue by jasonhuy** [HewlettPackard/POSH-HPOneView#291]
command not recognized
### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): HPOneView.310
HPE OneView Appliance Version:  3.10
Output from `$PSVersionTable` on your Windows Host: 
Import-Module : The specified module 'HPOneView.310' was not loaded because no
valid module file was found in any module directory.
At line:1 char:2
+ & <<<<  import-module HPOneView.310
    + CategoryInfo          : ResourceUnavailable: (HPOneView.310:String) [Imp
   ort-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Comm
   ands.ImportModuleCommand
PS C:\> Connect-HPOVMgmt
The term 'Connect-HPOVMgmt' is not recognized as the name of a cmdlet, function
, script file, or operable program. Check the spelling of the name, or if a pat
h was included, verify that the path is correct and try again.
At line:1 char:17
+ Connect-HPOVMgmt <<<<
    + CategoryInfo          : ObjectNotFound: (Connect-HPOVMgmt:String) [], Co
   mmandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\>

**Comment by ChrisLynchHPE** [comment]
How are you installing the library?  Did you use the Installer?  Did you install it from the PowerShellGallery?  You didn't include the output form `$PSVersionTable` on your PC.

**Comment by jasonhuy** [comment]
Hi Chris,

library 3.10 cannot work with Windows 7, but I tried with Windows 8 or Windows 10 then it worked

**Comment by ChrisLynchHPE** [comment]
Windows 7 is supported.  You need to make sure you have PowerShell 4 or 5 installed.  Can you provide the output of `$PSVersionTable` on your Windows 7 PC?

**Comment by ChrisLynchHPE** [comment]
Closing.  If there is still an issue, we can reopen this request or create a new on.
