### ISSUE TITLE
Get-HPOVStorageVolume not showing shared columes correctly

### ISSUE THREAD

**Issue by tknightblc** [HewlettPackard/POSH-HPOneView#292]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Get-HPOVStorageVolume shoudl return correct colume sharing (provate vs. shared)

See screen shot from OV GUI showing shared status

### Actual Behavior
My shared volumes are showing up as private
```PowerShell
PS C:\Users\tknight\Desktop\HPE OneView\HPE OV 3.1 DCS\PowerShell Scripts\Working Powershell Scripts for initial setup on pc> Get-HPOVStorageVolume

Name         Provisioning Provisioned Sharing Storage System Storage Pool Snapshot Pool Used By           
----         ------------ ----------- ------- -------------- ------------ ------------- -------           
Boot-BL660-1 Thin         10.00 GB    Private                FST_CPG2                   No server profiles
Boot-BL660-2 Thin         10.00 GB    Private                FST_CPG2                   No server profiles
VMFS-1       Thin         100.00 GB   Private                FST_CPG1                   No server profiles
VMFS-2       Thin         100.00 GB   Private                FST_CPG1                   No server profiles
```
### Steps to reproduce
```PowerShell
$sp = Get-HPOVStoragePool FST_CPG1
$sp
New-HPOVStorageVolume -Name TEST -Storagepool $sp -shared -ApplianceConnection $Connection1
Get-HPOVStorageVolume
```

output below
```PowerShell
PS C:\Users\tknight\Desktop\HPE OneView\HPE OV 3.1 DCS\PowerShell Scripts\Working Powershell Scripts for initial setup on pc> $sp = Get-HPOVStoragePool FST_CPG1
$sp
New-HPOVStorageVolume -Name TEST -Storagepool $sp -shared -ApplianceConnection $Connection1
Get-HPOVStorageVolume

Name     State   Status StorageSystem DriveType RAID  Total       Allocated Free     
----     -----   ------ ------------- --------- ----  -----       --------- ----     
FST_CPG1 Managed OK     ThreePAR-1    FC        RAID5 1,024.00 GB 0.00 GB   802.00 GB



Appliance      Name   Owner         Created              Duration TaskState PercentComplete
---------      ----   -----         -------              -------- --------- ---------------
192.168.56.150 Create Administrator 9/27/2017 8:44:45 AM 00:00:01 Completed 100            



Name         Provisioning Provisioned Sharing Storage System Storage Pool Snapshot Pool Used By           
----         ------------ ----------- ------- -------------- ------------ ------------- -------           
Boot-BL660-1 Thin         10.00 GB    Private                FST_CPG2                   No server profiles
Boot-BL660-2 Thin         10.00 GB    Private                FST_CPG2                   No server profiles
VMFS-1       Thin         100.00 GB   Private                FST_CPG1                   No server profiles
VMFS-2       Thin         100.00 GB   Private                FST_CPG1                   No server profiles
TEST         Thin         0.25 GB     Private                FST_CPG1                   No server profiles
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): HPOneView.Appliance.Version 3.10.1416.3042 C:\Program Files\WindowsPowerShell\Modules\HPOneView.310

HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:
ame                           Value                                                                                                                         
----                           -----                                                                                                                         
PSVersion                      5.1.15063.608                                                                                                                 
PSEdition                      Desktop                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                       
BuildVersion                   10.0.15063.608                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                               
WSManStackVersion              3.0                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                           
SerializationVersion           1.1.0.1    

[OV screen shot showing shared volume status.pdf](https://github.com/HewlettPackard/POSH-HPOneView/files/1341457/OV.screen.shot.showing.shared.volume.status.pdf)

**Comment by ChrisLynchHPE** [comment]
This is due to the Storage.formats.ps1xml file not being updated to display the newer objects properties.  I have this fixed in the next release I'm looking to publish today.

**Comment by tknightblc** [comment]
Thanks Chris

**Comment by ChrisLynchHPE** [comment]
This is now fixed in [Release 3.10.1471.1581](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.10.1471.1581), which has also been published to the [PowerShellGallery](https://www.powershellgallery.com/packages/HPOneView.310).

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.

**Comment by ehsanijavad** [comment]
Hi Chris
First of all, thank you for your support.
Please let me know how can I get the Used By?
I need it for change the name of Volume.

Thanks and Regards
Jawad

**Comment by ChrisLynchHPE** [comment]
The `UsedBy` is defined within the Format.psxml files shipped with the library.  It is an Index lookup of the parent to child relationship.  You can edit the name of a volume without needing to know what server profiles it is associated with.  The name of the resource has no applicability to the association.  Unless you wish to rename the volume to match that of the profile it is assigned to.  So, if you want to see what associated volumes are to a profile, you can do the following:

```powershell
# Get the volume you want to rename
$VolumeToRename = Get-OVStorageVolume -Name MyVolName

# Get the associated server profiles to the volume
$Uri = "/rest/index/associations?childUri=$($VolumeToRename.uri)&name=server_profiles_to_storage_volumes"
$AssociatedProfilesToVolume = (Send-OVRequest -Uri $Uri).members

if ($AssociatedProfilesToVolume) {

    $ServerProfiles = $AssociatedProfilesToVolume| ForEach { Send-OVRequest $_.parentUri }

}

# Display all of the server profile names
$ServerProfiles.name

# Perform your other operations here
```
