### ISSUE TITLE
New-Object : Cannot find an overload for "ContractAndWarrantyStatus" and the argument count: "25"

### ISSUE THREAD

**Issue by peterzhang718** [HewlettPackard/POSH-HPOneView#293]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Tried to get the server Remote Support Entitlement Status with:
 $a = Get-HPOVRemoteSupportEntitlementStatus -InputObject $_ ; $a.ObligationID}

### Actual Behavior
But got the following error message:
PS C:\Users\MyUserName> get-hpovserver  | % { $a = Get-HPOVRemoteSupportEntitlementStatus -InputObject $_ ; $a.ObligationID}
New-Object : Cannot find an overload for "ContractAndWarrantyStatus" and the argument count: "25".
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.310\HPOneView.310.psm1:16933 char:27
+ ... entStatus = New-Object HPOneView.RemoteSupport.ContractAndWarrantySta ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):310
HPE OneView Appliance Version:  310
Output from `$PSVersionTable` on your Windows Host:
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
Issue was local user PC, not library.  Closing.
