### ISSUE TITLE
Cannot get new SCMB Certificate - HPOV 3.10.07

### ISSUE THREAD

**Issue by Chris-L1** [HewlettPackard/POSH-HPOneView#294]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Should be able to run "Get-HPOVScmbCertificates" and have a new certificate generated.

### Actual Behavior
Run command and receive error "Get-HPOVScmbCertificates : The requested resource '/rest/certificates/client/rabbitmq/keypair/default' could not be found. Please supply a valid and unique common name and try again."

### Steps to reproduce
Run command from this instance of OneView 3.10.07 (have two other instances - no issues)

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):3.10.1416.3042
HPE OneView Appliance Version:  3.10.07
Output from `$PSVersionTable` on your Windows Host:

```PowerShell
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.18728
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

**Comment by Chris-L1** [comment]
I have three OV instances - this is the only one with the issue.  I first became aware when OV was filling Activity logs with "Client Certificate Generation" error (Issue       Error occurred while generating client certificate.Error occurred while creating Key pairs.     Resolution       Please retry the operation.)
All is identical on all three systems

**Comment by ChrisLynchHPE** [comment]
Can you by chance do the following for me:

```PowerShell
Get-HPOVCommandTrace -ScriptBlock { Get-HPOVScmbCertificate }
```

Attach the file created here.  You can look at the text file for any sensitive information.

**Comment by Chris-L1** [comment]
Good afternoon,

This failed to run – screen cap of error attached.

Thanks,

Chris Laskowski

Data Center Engineer II
State Employees’ Credit Union
(919) 839-7636 - Phone

chris.laskowski@ncsecu.org<mailto:chris.laskowski@ncsecu.org>

[cid:image001.gif@01CB6F7A.4D0F9070]

**Comment by ChrisLynchHPE** [comment]
Your attachment didn't come through.  You can't attach files when sending an email reply to a discussion.

Does the following call work?

```PowerShell
Send-HPOVRequest /rest/certificates/client/rabbitmq/keypair/rabbitmq_readonly
```

The SCMB key pair may have been created via a different process and changed the "default" name on your one appliance.

**Comment by Chris-L1** [comment]
Failed as well.  Below are the results of both of the scripts…

PS H:\> Get-HPOVCommandTrace -ScriptBlock { Get-HPOVScmbCertificate }
VERBOSE:
CONV0703v.ncsecu.local                            LibraryVersion                                    Path

----------------------                            --------------                                    ----

HPOneView.Appliance.Version                       3.10.1416.3042                                    C:\Program
Files\WindowsPowerShell\Modules\HPO...


VERBOSE: Executing:  Get-HPOVScmbCertificate  -verbose
Get-HPOVScmbCertificate : The term 'Get-HPOVScmbCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+  Get-HPOVScmbCertificate  -verbose
+  ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-HPOVScmbCertificate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

VERBOSE: --------------------------------------------------------------------------------

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        10/11/2017   3:12 PM       2894 1710111512_HPOV_transcript.log


PS H:\> Send-HPOVRequest /rest/certificates/client/rabbitmq/keypair/rabbitmq_readonly
Send-HPOVRequest : The requested resource '/rest/certificates/client/rabbitmq/keypair/rabbitmq_readonly' could not be found. Please supply a valid
and unique common name and try again.
At line:1 char:1
+ Send-HPOVRequest /rest/certificates/client/rabbitmq/keypair/rabbitmq_readonly
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (URI:String) [Send-HPOVRequest], ResourceNotFoundException
    + FullyQualifiedErrorId : ResourceNotFound,Send-HPOVRequest

PS H:\>

Chris Laskowski

Data Center Engineer II
State Employees’ Credit Union
(919) 839-7636 - Phone

chris.laskowski@ncsecu.org<mailto:chris.laskowski@ncsecu.org>

[cid:image001.gif@01CB6F7A.4D0F9070]

**Comment by Chris-L1** [comment]
Was able to run previous request - Cannot attach file - security on network prevents uploads.  Copied results below:

VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:
Key                                                                        Value

---                                                                        -----

uri                                                                        /rest/certificates/client/rabbitmq

method                                                                     POST

body                                                                       @{commonName=default; type=RabbitMqClientCertV2}

Hostname                                                                   <Appliance Name Edited>



VERBOSE: [WAIT-HPOVTASKCOMPLETE] Bound PS Parameters:
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Called from: Get-HPOVScmbCertificates
VERBOSE: [SEND-HPOVREQUEST] Process
VERBOSE: [SEND-HPOVREQUEST] Hostname value: <Appliance Name Edited>
VERBOSE: [SEND-HPOVREQUEST] Filtering for Connection Object via String: <Appliance Name Edited>
VERBOSE: [SEND-HPOVREQUEST] Processing '<Appliance Name Edited>' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/certificates/client/rabbitmq' to '<Appliance Name Edited>'
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for POST https://<Appliance Name Edited>/rest/certificates/client/rabbitmq
VERBOSE: [SEND-HPOVREQUEST] Body object found. Converting to JSON.
VERBOSE: [SEND-HPOVREQUEST] HTTP Method is POST. Removing 'ApplianceConnection' NoteProperty from object(s).
VERBOSE: InputObject is [PSCustomObject]. Copying...
VERBOSE: [SEND-HPOVREQUEST]  Request Body: {"commonName":"default","type":"RabbitMqClientCertV2"}
VERBOSE: [SEND-HPOVREQUEST] Request: POST https://<Appliance Name Edited>/rest/certificates/client/rabbitmq
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: User-Agent = HPEOneview_PowerShell/3.10
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: X-API-Version = 500
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 7: auth = [*****REDACTED******]
VERBOSE: [SEND-HPOVREQUEST] Request Header 8: Host = <Appliance Name Edited>
VERBOSE: [SEND-HPOVREQUEST] Response Status: 202 (Accepted)
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Content-Length = 0
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Date = Wed, 11 Oct 2017 20:09:58 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Location = /rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Server = Apache
VERBOSE: [SEND-HPOVREQUEST] FinalResponse:
VERBOSE: [SEND-HPOVREQUEST] Response:
VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] Async Task (HTTP 202) received
VERBOSE: [SEND-HPOVREQUEST] Async Task URI: /rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:
Key                                                                        Value

---                                                                        -----

uri                                                                        /rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C

method                                                                     GET

Hostname                                                                   <Appliance Name Edited>



VERBOSE: [SEND-HPOVREQUEST] Process
VERBOSE: [SEND-HPOVREQUEST] Hostname value: <Appliance Name Edited>
VERBOSE: [SEND-HPOVREQUEST] Filtering for Connection Object via String: <Appliance Name Edited>
VERBOSE: [SEND-HPOVREQUEST] Processing '<Appliance Name Edited>' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C' to '<Appliance Name Edited>'
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET
https://<Appliance Name Edited>/rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://<Appliance Name Edited>/rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: User-Agent = HPEOneview_PowerShell/3.10
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: X-API-Version = 500
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 7: auth = [*****REDACTED******]
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 (OK)
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Content-Language = en-us
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Pragma = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Content-Type = application/json;charset=UTF-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 6: Date = Wed, 11 Oct 2017 20:09:58 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 7: Expires = Thu, 01 Jan 1970 00:00:00 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 8: ETag = 0
VERBOSE: [SEND-HPOVREQUEST] Response Header 9: Server = Apache
VERBOSE: [SEND-HPOVREQUEST] FinalResponse:
{"type":"TaskResourceV2","associatedResource":{"resourceUri":null,"resourceCategory":"appliance","associationType":"MANAGED_BY","resourceName":null},
"stateReason":null,"hidden":false,"taskType":"User","data":null,"category":"tasks","percentComplete":0,"taskErrors":[],"parentTaskUri":null,"taskStat
e":"Running","associatedTaskUri":null,"completedSteps":0,"computedPercentComplete":0,"expectedDuration":0,"progressUpdates":[],"taskOutput":[],"taskS
tatus":null,"totalSteps":0,"userInitiated":false,"name":"Client Certificate
Generation.","owner":"hwsupport","eTag":"0","created":"2017-10-11T20:09:58.322Z","modified":"2017-10-11T20:09:58.322Z","uri":"/rest/tasks/FA5E7AEC-16
22-40EE-A02D-210160F3B77C"}
VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] Response object, no paging needed.
VERBOSE: [SEND-HPOVREQUEST] Cleaning up HttpWebRequest
VERBOSE: [SEND-HPOVREQUEST] Does nextPageUri member exist: False
VERBOSE: [SEND-HPOVREQUEST] Is nextPageUri Null or Empty: True
VERBOSE: [SEND-HPOVREQUEST] Stopping Do/Until loop because nextPageUri doesn't exist and have received all objects.
VERBOSE: [SEND-HPOVREQUEST] End
VERBOSE: [SEND-HPOVREQUEST] Adding 'HPOneView.Appliance.TaskResource' to PSObject TypeNames for task object
VERBOSE: [SEND-HPOVREQUEST] Response object, no paging needed.
VERBOSE: [SEND-HPOVREQUEST] Cleaning up HttpWebRequest
VERBOSE: [SEND-HPOVREQUEST] Does nextPageUri member exist: False
VERBOSE: [SEND-HPOVREQUEST] Is nextPageUri Null or Empty: True
VERBOSE: [SEND-HPOVREQUEST] Stopping Do/Until loop because nextPageUri doesn't exist and have received all objects.
VERBOSE: [SEND-HPOVREQUEST] End
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Task resource passed via pipeline input.
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Processing task resources.
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Task is System.Management.Automation.PSCustomObject. Task URI: /rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Processing taskcollection.
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Getting task object from API.
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:
Key                                                                        Value

---                                                                        -----

Hostname                                                                   <Appliance Name Edited>

uri                                                                        /rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C



VERBOSE: [SEND-HPOVREQUEST] Process
VERBOSE: [SEND-HPOVREQUEST] Hostname value: <Appliance Name Edited>
VERBOSE: [SEND-HPOVREQUEST] Filtering for Connection Object via String: <Appliance Name Edited>
VERBOSE: [SEND-HPOVREQUEST] Processing '<Appliance Name Edited>' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C' to '<Appliance Name Edited>'
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET
https://<Appliance Name Edited>/rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://<Appliance Name Edited>/rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: User-Agent = HPEOneview_PowerShell/3.10
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: X-API-Version = 500
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 7: auth = [*****REDACTED******]
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 (OK)
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Content-Language = en-us
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Pragma = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Content-Type = application/json;charset=UTF-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 6: Date = Wed, 11 Oct 2017 20:09:58 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 7: Expires = Thu, 01 Jan 1970 00:00:00 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 8: ETag = 0
VERBOSE: [SEND-HPOVREQUEST] Response Header 9: Server = Apache
VERBOSE: [SEND-HPOVREQUEST] FinalResponse:
{"type":"TaskResourceV2","associatedResource":{"resourceUri":null,"resourceCategory":"appliance","associationType":"MANAGED_BY","resourceName":null},
"stateReason":null,"hidden":false,"taskType":"User","data":null,"category":"tasks","percentComplete":0,"taskErrors":[],"parentTaskUri":null,"taskStat
e":"Running","associatedTaskUri":null,"completedSteps":0,"computedPercentComplete":0,"expectedDuration":0,"progressUpdates":[],"taskOutput":[],"taskS
tatus":null,"totalSteps":0,"userInitiated":false,"name":"Client Certificate
Generation.","owner":"hwsupport","eTag":"0","created":"2017-10-11T20:09:58.322Z","modified":"2017-10-11T20:09:58.322Z","uri":"/rest/tasks/FA5E7AEC-16
22-40EE-A02D-210160F3B77C"}
VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] Response object, no paging needed.
VERBOSE: [SEND-HPOVREQUEST] Cleaning up HttpWebRequest
VERBOSE: [SEND-HPOVREQUEST] Does nextPageUri member exist: False
VERBOSE: [SEND-HPOVREQUEST] Is nextPageUri Null or Empty: True
VERBOSE: [SEND-HPOVREQUEST] Stopping Do/Until loop because nextPageUri doesn't exist and have received all objects.
VERBOSE: [SEND-HPOVREQUEST] End
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Skipping Write-Progress display.
VERBOSE: [WAIT-HPOVTASKCOMPLETE] CMDLET Task Track ID: 1
Task Object Name: Client Certificate Generation.
Associated Resource Name:
Precent Complete: 0
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Processing taskcollection.
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Getting task object from API.
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:
Key                                                                        Value

---                                                                        -----

Hostname                                                                   <Appliance Name Edited>

uri                                                                        /rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C



VERBOSE: [SEND-HPOVREQUEST] Process
VERBOSE: [SEND-HPOVREQUEST] Hostname value: <Appliance Name Edited>
VERBOSE: [SEND-HPOVREQUEST] Filtering for Connection Object via String: <Appliance Name Edited>
VERBOSE: [SEND-HPOVREQUEST] Processing '<Appliance Name Edited>' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C' to '<Appliance Name Edited>'
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET
https://<Appliance Name Edited>/rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://<Appliance Name Edited>/rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: User-Agent = HPEOneview_PowerShell/3.10
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: X-API-Version = 500
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 7: auth = [*****REDACTED******]
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 (OK)
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Content-Language = en-us
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Pragma = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Content-Type = application/json;charset=UTF-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 6: Date = Wed, 11 Oct 2017 20:10:01 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 7: Expires = Thu, 01 Jan 1970 00:00:00 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 8: ETag = 2
VERBOSE: [SEND-HPOVREQUEST] Response Header 9: Server = Apache
VERBOSE: [SEND-HPOVREQUEST] FinalResponse:
{"type":"TaskResourceV2","associatedResource":{"resourceUri":null,"resourceCategory":"appliance","associationType":"MANAGED_BY","resourceName":null},
"stateReason":null,"hidden":false,"taskType":"User","data":null,"category":"tasks","percentComplete":100,"taskErrors":[{"errorSource":null,"nestedErr
ors":[],"details":"Error occurred while creating Key pairs.","recommendedActions":["Please retry the
operation."],"errorCode":null,"data":{},"message":"Error occurred while generating client
certificate."}],"parentTaskUri":null,"taskState":"Error","associatedTaskUri":null,"completedSteps":0,"computedPercentComplete":100,"expectedDuration"
:0,"progressUpdates":[],"taskOutput":[],"taskStatus":"Certificate Configuration Failed.","totalSteps":0,"userInitiated":false,"name":"Client
Certificate
Generation.","owner":"hwsupport","eTag":"2","created":"2017-10-11T20:09:58.322Z","modified":"2017-10-11T20:10:00.531Z","uri":"/rest/tasks/FA5E7AEC-16
22-40EE-A02D-210160F3B77C"}
VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] Response object, no paging needed.
VERBOSE: [SEND-HPOVREQUEST] Cleaning up HttpWebRequest
VERBOSE: [SEND-HPOVREQUEST] Does nextPageUri member exist: False
VERBOSE: [SEND-HPOVREQUEST] Is nextPageUri Null or Empty: True
VERBOSE: [SEND-HPOVREQUEST] Stopping Do/Until loop because nextPageUri doesn't exist and have received all objects.
VERBOSE: [SEND-HPOVREQUEST] End
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Task is finished, removing from collection.
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Task Collection size: 1
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Updated Task Collection size: 0
VERBOSE: [WAIT-HPOVTASKCOMPLETE] Client Certificate Generation. [<Appliance Name Edited>/rest/tasks/FA5E7AEC-1622-40EE-A02D-210160F3B77C] Task
finished.
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:
Key                                                                        Value

---                                                                        -----

uri                                                                        /rest/certificates/client/rabbitmq/keypair/default

Hostname                                                                   <Appliance Name Edited>



VERBOSE: [SEND-HPOVREQUEST] Process
VERBOSE: [SEND-HPOVREQUEST] Hostname value: <Appliance Name Edited>
VERBOSE: [SEND-HPOVREQUEST] Filtering for Connection Object via String: <Appliance Name Edited>
VERBOSE: [SEND-HPOVREQUEST] Processing '<Appliance Name Edited>' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/certificates/client/rabbitmq/keypair/default' to '<Appliance Name Edited>'
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET
https://<Appliance Name Edited>/rest/certificates/client/rabbitmq/keypair/default
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://<Appliance Name Edited>/rest/certificates/client/rabbitmq/keypair/default
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: User-Agent = HPEOneview_PowerShell/3.10
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: X-API-Version = 500
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 7: auth = [*****REDACTED******]
VERBOSE: [SEND-HPOVREQUEST] Net.WebException Error caught
VERBOSE: [SEND-HPOVREQUEST] The remote server returned an error: (404) Not Found.
VERBOSE: [SEND-HPOVREQUEST] Exception
VERBOSE: [SEND-HPOVREQUEST] Getting Error Response.
VERBOSE: [SEND-HPOVREQUEST] ERROR RESPONSE: {
    "details":  "",
    "errorSource":  null,
    "nestedErrors":  [

                     ],
    "recommendedActions":  [
                               "Please supply a valid and unique common name and try again."
                           ],
    "errorCode":  "RESOURCE_NOT_FOUND",
    "data":  {

             },
    "message":  "Certificate/Private key file is missing."
}
VERBOSE: [SEND-HPOVREQUEST] Response Status: HTTP 404 [Not Found]
VERBOSE: [SEND-HPOVREQUEST] Response Header: Transfer-Encoding =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Cache-Control =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Content-Type =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Date =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Server =
VERBOSE: [NEW-ERRORRECORD] Building ErrorRecord object
VERBOSE: [SEND-HPOVREQUEST] Cleaning up HttpWebRequest
Get-HPOVScmbCertificates : The requested resource '/rest/certificates/client/rabbitmq/keypair/default' could not be found. Please supply a valid and
unique common name and try again.
At line:1 char:2
+  Get-HPOVScmbCertificates  -verbose
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (URI:String) [Get-HPOVScmbCertificates], ResourceNotFoundException
    + FullyQualifiedErrorId : ResourceNotFound,Get-HPOVScmbCertificates

VERBOSE: --------------------------------------------------------------------------------

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        10/11/2017   4:10 PM      54376 1710111609_HPOV_transcript.log


PS H:\>

**Comment by ChrisLynchHPE** [comment]
Two things:

1. I don't see the complete output of the entire Cmdlet call from `Get-HPOVScmbCertificates`.
2. This looks like an appliance specific issue, and one that you should open a support case for.

**Comment by Chris-L1** [comment]
I will work on the output file and also open a support case.

Thanks for the assistance, it is greatly appreciated.

Chris Laskowski

Data Center Engineer II
State Employees’ Credit Union
(919) 839-7636 - Phone

chris.laskowski@ncsecu.org<mailto:chris.laskowski@ncsecu.org>

[cid:image001.gif@01CB6F7A.4D0F9070]

**Comment by ChrisLynchHPE** [comment]
Closing.  Please report back if we need to re-open this issue.
