### ISSUE TITLE
Server Firmware 

### ISSUE THREAD

**Issue by DAVIDMARTINEZROBLES** [HewlettPackard/POSH-HPOneView#304]
Hi.

Im not sure that it is a issue, it is possible that could be a improvement.

In the web browser we can obtain a Server firmware inventory (#/report/show/r/rest/reports/5), but in power shell the command Get-HPOVServer or Show-HPOVFirmwareReport is not the same info.

There are any option to obtain a similar info in posershell?

### Expected Behavior

Smart   Array P240nr Controller      Server Platform Services (SPS) Firmware      Smart Array P542D Controller      Redundant System ROM      Synergy 3820C 10/20Gb CNA      Synergy 3820C 10/20Gb CNA      iLO      HPE Smart Storage Battery 1 Firmware      HpSmartStorageDiskDrive (SAS)      HpSmartStorageDiskDrive (SAS)      System Programmable Logic Device      SAS Programmable Logic Device      Power Management Controller Firmware      Power Management Controller FW Bootloader      System ROM      Intelligent Platform Abstraction Data | Embedded RAID 1      System Board      Slot 1      System Board      Slot 2      Slot 3      System Board      Embedded      Bay 2      Bay 1      System Board      System Board      System Board      System Board      System Board      System Board | 6.06      3.1.3.21.4      6.06      I37 v2.52 (10/25/2017)      7.15.68      7.15.68      2.55 Aug 16 2017      2.1      HPD1      HPD1      Version 0x0F      Version 0x02      1.0.9      1.0      I37 v2.54 (12/07/2017)      22.72
-- | -- | --

### Steps to reproduce

```PowerShell
# 1. Capture verbose output using the Get-HPOVCommandTrace for HPOneView.310 or newer, or append the -Verbose switch to your Cmdlet call.
# 2. Put your code and/or captured output here.
# 3. Remove this comment block before submitting.
```

### Version Information

HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  

**HPOneView.Appliance.Version 3.10.1471.1581**

Output from `$PSVersionTable` on your Windows Host:
**Name                           Value**
**PSVersion                      5.0.10586.117**
**PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}**
**BuildVersion                   10.0.10586.117**
**CLRVersion                     4.0.30319.42000**
**WSManStackVersion              3.0**
**PSRemotingProtocolVersion      2.3**
**SerializationVersion           1.1.0.1**

```PowerShell
# Output from $PSVersionTable
```

**Comment by ChrisLynchHPE** [comment]
Yes, this is an enhancement request for a Cmdlet to support natively.  You can already accomplish this today as a workaround:

```PowerShell
Get-HPOVServer | % {

    (Send-HPOVRequest -Uri ($_.uri + "/firmware")).components | Format-Table componentName, componentKey, componentLocation, componentVersion

}
```

**Comment by DAVIDMARTINEZROBLES** [comment]
any option to show the rest info of the server?

Name | Server Name | Bay Number | Model | Processor Type | Memory (MB)

**Comment by jullienl** [comment]
What about this?

`
$servers = Get-HPOVserver

Foreach ($server in $servers) 

{

    Get-HPOVServer -Name $server.name | fl  name, serverName, model, processorType, memoryMb
    (Send-HPOVRequest -Uri ($server.uri + "/firmware")).components | Format-Table componentName, componentKey, componentLocation, componentVersion
                           

}`

**Comment by DAVIDMARTINEZROBLES** [comment]
Perfect.

Thanks

**Comment by ChrisLynchHPE** [comment]
The view @jullienl provided isn't a combined view.  The default output of Get-HPOVServer would supply you with what you need.  All of the properties are there.  We use Format Filtering to display the relevant information, but do not prohibit you from actually getting to it.
```PowerShell
# display the member properties and their values from a server hardware resource
Get-HPOVServer | Select -First 1 | Get-Member
```
As to the original request, I'm looking to refactor the `Show-HPOVFirmwareReport` Cmdlet.  Would it be helpful to continue to use that Cmdlet, or dedicate a new one to showing just the Server Hardware firmware in an object?

**Comment by DAVIDMARTINEZROBLES** [comment]
I think that it could be better two diferents Cmdlet, one of this to the Enclosure firmware and other to Server firmware

This is my preliminary version to extract the information that i need

$servers = Get-HPOVserver | Sort-Object locationuri, {[int]$_.position} 
$NewServer = " ################################ "
Foreach ($server in $servers)
{
echo $NewServer >> ficheros.txt
Get-HPOVServer -Name $server.name | Format-Table  position, name, mpModel, mpFirmwareVersion, model, serialNumber, processorType, memoryMb, romVersion, intelligentProvisioningVersion, state, powerState | Sort-Object -Property position | Out-File ficheros.txt -Append
(Send-HPOVRequest -Uri ($server.uri + "/firmware")).components | Format-Table componentName, componentLocation, componentVersion | Out-File ficheros.txt -Append
}

Thanks

**Comment by DAVIDMARTINEZROBLES** [comment]
Hi.

This is my version to extract the content of OneView

`
$fichero = "inventarioESTELABORATORIO.txt"
$SaltoDeLinea = "################################"
echo $SaltoDeLinea "RACK" $SaltoDeLinea >> $fichero
Get-HPOVRack | Get-HPOVRackMember | Sort-Object Ulocation >> $fichero
echo $SaltoDeLinea "ADDRESS POOL RANGE" $SaltoDeLinea >> $fichero
Get-HPOVAddressPoolRange >> $fichero
echo $SaltoDeLinea "ADDRESS POOL SUBNET" $SaltoDeLinea >> $fichero
Get-HPOVAddressPoolSubnet >> $fichero
echo $SaltoDeLinea "COMPOSER" $SaltoDeLinea >> $fichero
Get-HPOVComposerNode | ft Appliance, modelNumber, name, role, state, status, version, synchronizationPercentComplete >> $fichero
echo $SaltoDeLinea "IMAGE STREAMER" $SaltoDeLinea >> $fichero
Get-HPOVImageStreamerAppliance | ft oneViewIpv4Address, name, status, applianceserialnumber, imagestreamerversion, isactive, isprimary >> $fichero
echo $SaltoDeLinea "ENCLOSURE" $SaltoDeLinea >> $fichero
Get-HPOVEnclosure | Sort-Object -Property name >> $fichero
echo $SaltoDeLinea "SERVER RESUME" $SaltoDeLinea >> $fichero
Get-HPOVServer | Format-Table position, name, mpModel, mpFirmwareVersion, model, serialNumber, processorType, memoryMb, romVersion, intelligentProvisioningVersion, state, powerState | Sort-Object -Property locationUri, position >> $fichero
echo $SaltoDeLinea "DRIVE ENCLOSURE" $SaltoDeLinea >> $fichero
Get-HPOVDriveEnclosure | Format-Table name, bay, model, serialNumber, partNumber, productName, driveBayCount, firmwareVersion, ioAdapterCount, powerState | Sort-Object {[int]$_.bay}>> $fichero
echo $SaltoDeLinea "INTERCONNECT" $SaltoDeLinea >> $fichero
Get-HPOVinterconnect | Format-Table enclosureName, hostName,model, name, partNumber, serialNumber, interconnectIP, firmwareVersion, portCount, baseWWN | Sort-Object name >> $fichero

$Enclosures = Get-HPOVEnclosure | Sort-Object -Property name
Foreach ($Enclosure in $Enclosures)
{
echo $SaltoDeLinea "ENCLOSURE DETAIL" $Enclosure.name $SaltoDeLinea >> $fichero
echo $SaltoDeLinea "Interconnect" $Enclosure.serialNumber $SaltoDeLinea >> $fichero
  (Send-HPOVRequest -Uri ($Enclosure.uri)).interconnectBays | Format-Table bayNumber, interconnectModel, partNumber, serialNumber, ipv4Setting | Sort-Object -Property bayNumber >> $fichero
echo $SaltoDeLinea "Appliance Bays" $Enclosure.serialNumber $SaltoDeLinea >> $fichero
  (Send-HPOVRequest -Uri ($Enclosure.uri)).applianceBays | ft bayNumber, devicePresence, status, model, serialNumber, partNumber, poweredOn | Sort-Object -Property bayNumber >> $fichero
echo $SaltoDeLinea "Manager Bays" $Enclosure.serialNumber $SaltoDeLinea >> $fichero
  (Send-HPOVRequest -Uri ($Enclosure.uri)).managerBays | ft bayNumber, model, devicePresence, role, FwVersion, partNumber, sparePartNumber | Sort-Object -Property bayNumber >> $fichero
echo $SaltoDeLinea "PowerSupply" $Enclosure.serialNumber $SaltoDeLinea >> $fichero
  (Send-HPOVRequest -Uri ($Enclosure.uri)).powerSupplyBays | Format-Table | Sort-Object -Property bayNumber >> $fichero
echo $SaltoDeLinea "Fan" $Enclosure.serialNumber $SaltoDeLinea >> $fichero
  (Send-HPOVRequest -Uri ($Enclosure.uri)).fanBays | Format-Table bayNumber, devicePresence, fanBayType, model, serialNumber, partNumber, sparePartNumber | Sort-Object -Property bayNumber >> $fichero
}

$servers = Get-HPOVserver | Sort-Object locationuri, {[int]$_.position} 
Foreach ($server in $servers)
{
echo $SaltoDeLinea "SERVER DETAIL" $server.name $SaltoDeLinea >> $fichero
(Send-HPOVRequest -Uri ($server.uri)).portMap.deviceSlots | Format-Table >> $fichero
(Send-HPOVRequest -Uri ($server.uri)).portMap.deviceSlots.physicalPorts | Format-Table type, portNumber, physicalInterconnectPort, interconnectport, mac >> $fichero
(Send-HPOVRequest -Uri ($server.uri)).mpHostInfo.mpIpAddresses | Format-Table type, address >> $fichero
(Send-HPOVRequest -Uri ($server.uri + "/firmware")).components | Format-Table componentLocation, componentName, componentVersion | Sort-Object componentLocation, componentName | Out-File $fichero -Append
}
$DriveEnclosures = Get-HPOVDriveEnclosure | Sort-Object name, {[int]$_.bay} 
Foreach ($DriveEnclosure in $DriveEnclosures)
{
echo $SaltoDeLinea "DRIVE ENCLOSURE DETAIL" $DriveEnclosure.serialNumber $DriveEnclosure.name $SaltoDeLinea >> $fichero
 (Send-HPOVRequest -Uri ($DriveEnclosure.uri)).ioadapters | Format-Table model, partnumber, serialnumber, firmwareversion, portcount, redundantIoModule >> $fichero
 (Send-HPOVRequest -Uri ($DriveEnclosure.uri)).driveBays.drive | Format-Table name, serialNumber, model, deviceInterface, driveMedia, linkRateInGbs, drivePaths, firmwareVersion, status, temperature >> $fichero
}
`

**Comment by mi-hol** [comment]
@DAVIDMARTINEZROBLES when I try your code I get an error. Any hints?

 $servers = Get-HPOVserver | Sort-Object locationuri, {[int]$.position}
At line:1 char:60
+ ... servers = Get-HPOVserver | Sort-Object locationuri, {[int]$.position}
+                                                               ~~~~~~~~~~
Unexpected token '$.position' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by DAVIDMARTINEZROBLES** [comment]
When i write or edit the post, the correct form is

{[int]$_.position}

I don´t know whats happend.

Now its correct. I hope.

```PowerShell
write-host "-----------------------------"
write-host "INVENTARIO DE ENTORNO SYNERGY"
write-host "-----------------------------"
write-host 
write-host 
write-host Escribe el nombre deel fichero donde guardar todos los datos
$fichero = Read-Host -Prompt 'Fichero'
$SaltoDeLinea = "################################"
echo $SaltoDeLinea "RACK" $SaltoDeLinea >> $fichero
Get-HPOVRack | Get-HPOVRackMember | Sort-Object Ulocation >> $fichero
echo $SaltoDeLinea "ADDRESS POOL RANGE" $SaltoDeLinea >> $fichero
Get-HPOVAddressPoolRange >> $fichero
echo $SaltoDeLinea "ADDRESS POOL SUBNET" $SaltoDeLinea >> $fichero
Get-HPOVAddressPoolSubnet >> $fichero
echo $SaltoDeLinea "COMPOSER" $SaltoDeLinea >> $fichero
Get-HPOVComposerNode | ft Appliance, modelNumber, name, role, state, status, version, synchronizationPercentComplete >> $fichero
echo $SaltoDeLinea "IMAGE STREAMER" $SaltoDeLinea >> $fichero
Get-HPOVImageStreamerAppliance | ft oneViewIpv4Address, name, status, applianceserialnumber, imagestreamerversion, isactive, isprimary >> $fichero
echo $SaltoDeLinea "ENCLOSURE" $SaltoDeLinea >> $fichero
Get-HPOVEnclosure | Sort-Object -Property name >> $fichero
echo $SaltoDeLinea "SERVER RESUME" $SaltoDeLinea >> $fichero
Get-HPOVServer | Format-Table position, name, mpModel, mpFirmwareVersion, model, serialNumber, processorType, memoryMb, romVersion, intelligentProvisioningVersion, state, powerState | Sort-Object -Property locationUri, position >> $fichero
echo $SaltoDeLinea "DRIVE ENCLOSURE" $SaltoDeLinea >> $fichero
Get-HPOVDriveEnclosure | Format-Table name, bay, model, serialNumber, partNumber, productName, driveBayCount, firmwareVersion, ioAdapterCount, powerState | Sort-Object {[int]$_.bay}>> $fichero
echo $SaltoDeLinea "INTERCONNECT" $SaltoDeLinea >> $fichero
Get-HPOVinterconnect | Format-Table enclosureName, hostName,model, name, partNumber, serialNumber, interconnectIP, firmwareVersion, portCount, baseWWN | Sort-Object name >> $fichero

$Enclosures = Get-HPOVEnclosure | Sort-Object -Property name
Foreach ($Enclosure in $Enclosures)
{
echo $SaltoDeLinea "ENCLOSURE DETAIL" $Enclosure.name $SaltoDeLinea >> $fichero
echo $SaltoDeLinea "Interconnect" $Enclosure.serialNumber $SaltoDeLinea >> $fichero
  (Send-HPOVRequest -Uri ($Enclosure.uri)).interconnectBays | Format-Table bayNumber, interconnectModel, partNumber, serialNumber, ipv4Setting | Sort-Object -Property bayNumber >> $fichero
echo $SaltoDeLinea "Appliance Bays" $Enclosure.serialNumber $SaltoDeLinea >> $fichero
  (Send-HPOVRequest -Uri ($Enclosure.uri)).applianceBays | ft bayNumber, devicePresence, status, model, serialNumber, partNumber, poweredOn | Sort-Object -Property bayNumber >> $fichero
echo $SaltoDeLinea "Manager Bays" $Enclosure.serialNumber $SaltoDeLinea >> $fichero
  (Send-HPOVRequest -Uri ($Enclosure.uri)).managerBays | ft bayNumber, model, devicePresence, role, FwVersion, partNumber, sparePartNumber | Sort-Object -Property bayNumber >> $fichero
echo $SaltoDeLinea "PowerSupply" $Enclosure.serialNumber $SaltoDeLinea >> $fichero
  (Send-HPOVRequest -Uri ($Enclosure.uri)).powerSupplyBays | Format-Table | Sort-Object -Property bayNumber >> $fichero
echo $SaltoDeLinea "Fan" $Enclosure.serialNumber $SaltoDeLinea >> $fichero
  (Send-HPOVRequest -Uri ($Enclosure.uri)).fanBays | Format-Table bayNumber, devicePresence, fanBayType, model, serialNumber, partNumber, sparePartNumber | Sort-Object -Property bayNumber >> $fichero
}

$servers = Get-HPOVserver | Sort-Object locationuri, {[int]$_.position} 
Foreach ($server in $servers)
{
echo $SaltoDeLinea "SERVER DETAIL" $server.name $SaltoDeLinea >> $fichero
(Send-HPOVRequest -Uri ($server.uri)).portMap.deviceSlots | Format-Table >> $fichero
(Send-HPOVRequest -Uri ($server.uri)).portMap.deviceSlots.physicalPorts | Format-Table type, portNumber, physicalInterconnectPort, interconnectport, mac >> $fichero
(Send-HPOVRequest -Uri ($server.uri)).mpHostInfo.mpIpAddresses | Format-Table type, address >> $fichero
(Send-HPOVRequest -Uri ($server.uri + "/firmware")).components | Format-Table componentLocation, componentName, componentVersion | Sort-Object componentLocation, componentName | Out-File $fichero -Append
}
$DriveEnclosures = Get-HPOVDriveEnclosure | Sort-Object name, {[int]$_.bay} 
Foreach ($DriveEnclosure in $DriveEnclosures)
{
echo $SaltoDeLinea "DRIVE ENCLOSURE DETAIL" $DriveEnclosure.serialNumber $DriveEnclosure.name $SaltoDeLinea >> $fichero
 (Send-HPOVRequest -Uri ($DriveEnclosure.uri)).ioadapters | Format-Table model, partnumber, serialnumber, firmwareversion, portcount, redundantIoModule >> $fichero
 (Send-HPOVRequest -Uri ($DriveEnclosure.uri)).driveBays.drive | Format-Table name, serialNumber, model, deviceInterface, driveMedia, linkRateInGbs, drivePaths, firmwareVersion, status, temperature >> $fichero
}



echo $SaltoDeLinea $SaltoDeLinea >> $fichero
echo $SaltoDeLinea "PERFILES" $SaltoDeLinea >> $fichero
echo $SaltoDeLinea $SaltoDeLinea >> $fichero

echo $SaltoDeLinea "NETWORK" $SaltoDeLinea >> $fichero
Get-HPOVNetwork >> $fichero

echo $SaltoDeLinea "NETWORK SET" $SaltoDeLinea >> $fichero
Get-HPOVNetworkSet >> $fichero

echo $SaltoDeLinea "UPLINKS" $SaltoDeLinea >> $fichero
Get-HPOVUplinkSet

echo $SaltoDeLinea "PROFILE TEMPLATE" $SaltoDeLinea >> $fichero
Get-HPOVServerProfileTemplate >> $fichero

echo $SaltoDeLinea "PROFILES" $SaltoDeLinea >> $fichero
Get-HPOVServerProfile >> $fichero
```

Thanks

**Comment by ChrisLynchHPE** [comment]
I have added the functionality into the [Release 4.0.1612.2800](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v4.0.1612.2800) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.400/4.0.1612.2800).

**Comment by ChrisLynchHPE** [comment]
To keep track of the 3.10 Enhancement Request, I'm going to split this into two issues.  That way I can track this better.

**Comment by ChrisLynchHPE** [comment]
Closing this enhancement request due to no further input.  If there is an issue or needs to be addressed further, please open a new issue to investigate.
