### ISSUE TITLE
Need ability to Set labels using the AddServers_Monitored_Sample.ps1 script.

### ISSUE THREAD

**Issue by mlam32** [HewlettPackard/POSH-HPOneView#309]
I have looked at all HPOneView releases up to v4.0 but I only see a **Get-HPOVLabel**
Is there a way to **Set-HPOVLabel**? 

Ideally we'd add an additional column to the CSV used by **AddServers_Monitored_Sample.ps1** called Label so we can import those labels into OneView.
It would help us tremendously for automation and easy filtering purposes.

I was surprised to not find this feature :)

Please advise!

**Comment by ChrisLynchHPE** [comment]
There isn't a Set-HPOVLabel because you can't change the name of the Label.  You can add and then remove a label with a resource.  So, I would suggest you do the following:

```PowerShell
# Add to new or existing label
Get-HPOVServer -Name 'MyServer 1' -ErrorAction Stop | Add-HPOVResourceToLabel -Name MyNewLabel

# Remove resource from the prior label
Get-HPOVServer -Name 'MyServer 1' -ErrorAction Stop | Remove-HPOVResourceFromLabel -Name OriginalLabelName
```

**Comment by mlam32** [comment]
So the only way to add a label is if the entity already exists in OneView?

There's no way to append a label from a column on a csv file when this command runs?
Add-HPOVServer -hostname $_.hostname -username $_.account -password $_.password -Monitored -Async

Again, I'm trying to automate the importing of a few hundred systems into our OneView for monitoring and trying to also bulk set the label per item before importing.

**Comment by ChrisLynchHPE** [comment]
Labels are not your typical resource.  They are essentially used as Metadata, but are an Index resource.  So you don't really create one.  When you use the UI, you type in the value and press Enter, which then effectively creates the Label.  The `Add-HPOVResourceToLabel` Cmdlet does the very same thing.  Once the lable exists, you can't rename it, only adjust the association of a new or existing label to the resource.  That is why there is only `Get-HPOVLabel`, `Add-HPOVResourceToLabel` and `Remove-HPOVResourceFromLabel` Cmdlets.

If you want to filter and then delegate responsibility, then I would suggest you investigate upgrading your HPE OneView appliance to the 4.0 release and look at Scopes.  There is an option in the [Add-HPOVServer](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Add-HPOVServer) Cmdlet to add a resource to an existing Scope resource.  Then, there are similar Cmdlets to managing Scopes:

* [Get-HPOVScope](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Get-HPOVScope)
* [New-HPOVScope](https://github.com/HewlettPackard/POSH-HPOneView/wiki/New-HPOVScope)
* [Remove-HPOVScope](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Remove-HPOVScope)
* [Add-HPOVResourceToScope](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Add-HPOVResourceToScope)
* [Remove-HPOVResourceFromScope](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Remove-HPOVResourceFromScope)

**Comment by mlam32** [comment]
Thank you very much Chris for all the valuable info.
We will upgrade OneView to v4.0 and see what it provides for us.
Apparently the v4.0 release includes a Discovery option so we may opt to use that vs. custom scripting :)
