### ISSUE TITLE
Get-HPOVAddressPool / Get-HPOVAddressPoolRange

### ISSUE THREAD

**Issue by huberm001** [HewlettPackard/POSH-HPOneView#31]
Hi,

the help of the CMDLET Get-HPOVAddressPool describes that there is a parameter -range. Entering the command Get-HPOVAddressPool -range returns following message:

WARNING: The -Ranges swtich is being deprecated.  Please update your scripts to use the Get-HPOVAddressPoolRange CMDLET

But this CMDLET does not exist:
Get-HPOVAddressPoolRange : The term 'Get-HPOVAddressPoolRange' is not recognized as the name of a cmdlet, function, script file, or operable program.

BR,
Martin

**Comment by ChrisLynchHP** [comment]
Hmm...  It appears that the merge of a prior commit didn't include the CMDLET.  This will be fixed.

**Comment by ChrisLynchHP** [comment]
This is fixed in the [1.20.233 Release](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v1.20.233.0)
