### ISSUE TITLE
Issue Client Certificate already exists.

### ISSUE THREAD

**Issue by jeffus3** [HewlettPackard/POSH-HPOneView#315]
Issue Client Certificate already exists.
Cannot regenerate Client certificate as it already exists.
Resolution Delete existing Client certificate to regenerate new certificate

I am getting this error every minute or so.
HPE OneView 
Firmware 3.10.07-0310774 

### Steps to reproduce

```PowerShell
# 1. Capture verbose output using the Get-HPOVCommandTrace for HPOneView.310 or newer, or append the -Verbose switch to your Cmdlet call.
# 2. Put your code and/or captured output here.
# 3. Remove this comment block before submitting.
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  
Output from `$PSVersionTable` on your Windows Host:

```PowerShell
# Output from $PSVersionTable
```

**Comment by ChrisLynchHPE** [comment]
This is not an issue with the PowerShell library, but rather the appliance.  This isn't the right forum for appliance issues.  But this particular one is related to the State Change Message Bus.  You will need to use the `Remove-HPOVScmbCertificate` and then re-create it with `Get-HPOVScmbCertificate` Cmdlets.

**Comment by ChrisLynchHPE** [comment]
Closing due to any further activity.  If needed, we can reopen this issue.
