### ISSUE TITLE
Get-HPOVLicense - OneView Licenses

### ISSUE THREAD

**Issue by ritterjohannes** [HewlettPackard/POSH-HPOneView#317]
I have test the command "Get-HPOVLicense" and test the "Summary" and "Report" against our OneView appliance. We have the following gap. In the company have different peoples by order the OneView License activated and on Oneview appliance Portal activated. Is there a possibility to export extract the inserted, activated OneView Licenses? And how can i do this?

**Comment by ChrisLynchHPE** [comment]
All licenses installed on the appliance are "activated". Are you trying to identify what the customer purchased and have not yet activated? The appliance does not have that capability and you would need to reach out to either the HPE account team or our licensing team.

**Comment by ChrisLynchHPE** [comment]
Yes, you would use the -Export switch with contains the license keys added to the appliance.

**Comment by ritterjohannes** [comment]
I have tested the -Export Switch... but i get only a statistic view:
License Name          Available       Total     Associated Nodes
----------------         -----------      ------   ------------- --------
HPE OneView Advanced        0           16                               16

Device                    License Type               Applied Date
--------                   ---------------             ----------------
ILOBima-h01           Permanent

There ist no view / line with the License Keys like: 
9CLC D9MA H9P9 CHX3 V7B5 HWWB Y9JL KMPL.........

How can i get this keys?

**Comment by ritterjohannes** [comment]
Very good - this works fine! Thank you for your Support.

**Comment by jullienl** [comment]
Or you can directly get the license key information by using 
`$licensekey = (Get-HPOVLicense).key`

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.
