### ISSUE TITLE
Unable to add server hardware from comma separated list.

### ISSUE THREAD

**Issue by mlam32** [HewlettPackard/POSH-HPOneView#321]
We are using OneView v4.0

Whenever I try to bulk-add servers we are getting the following error:

Unable to perform a scan for new hardware.
Validation error during task creation. Text size is not in range

Resolution: Text value for a field should be less than or equal to maximum length.

No idea why this is happening but cannot import anything.

**Comment by ChrisLynchHPE** [comment]
Can you please provide the data that you cleared out when you opened this issue?  I need to know more about the call you are trying to make to the `Add-HPOVServer` Cmdlet.

**Comment by mlam32** [comment]
Sorry Chris,

We using the GUI after upgrading our appliance to v4.0
I understand if you cannot help with the GUI, but thought I would ask here anyway.

**Comment by mlam32** [comment]
Closing this issue.
Apparently when you are trying to add new hardware in OneView you must use the Add + button, not Add.
