### ISSUE TITLE
Server Firmware reporting support for 3.10

### ISSUE THREAD

**Issue by ChrisLynchHPE** [HewlettPackard/POSH-HPOneView#322]
Splitting from #304, to track for 3.10 enhancements.
---

Hi.

Im not sure that it is a issue, it is possible that could be a improvement.

In the web browser we can obtain a Server firmware inventory (#/report/show/r/rest/reports/5), but in power shell the command Get-HPOVServer or Show-HPOVFirmwareReport is not the same info.

There are any option to obtain a similar info in posershell?

### Expected Behavior

Smart   Array P240nr Controller      Server Platform Services (SPS) Firmware      Smart Array P542D Controller      Redundant System ROM      Synergy 3820C 10/20Gb CNA      Synergy 3820C 10/20Gb CNA      iLO      HPE Smart Storage Battery 1 Firmware      HpSmartStorageDiskDrive (SAS)      HpSmartStorageDiskDrive (SAS)      System Programmable Logic Device      SAS Programmable Logic Device      Power Management Controller Firmware      Power Management Controller FW Bootloader      System ROM      Intelligent Platform Abstraction Data | Embedded RAID 1      System Board      Slot 1      System Board      Slot 2      Slot 3      System Board      Embedded      Bay 2      Bay 1      System Board      System Board      System Board      System Board      System Board      System Board | 6.06      3.1.3.21.4      6.06      I37 v2.52 (10/25/2017)      7.15.68      7.15.68      2.55 Aug 16 2017      2.1      HPD1      HPD1      Version 0x0F      Version 0x02      1.0.9      1.0      I37 v2.54 (12/07/2017)      22.72
-- | -- | --

### Steps to reproduce

```PowerShell
# 1. Capture verbose output using the Get-HPOVCommandTrace for HPOneView.310 or newer, or append the -Verbose switch to your Cmdlet call.
# 2. Put your code and/or captured output here.
# 3. Remove this comment block before submitting.
```

### Version Information

HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  

**HPOneView.Appliance.Version 3.10.1471.1581**

Output from `$PSVersionTable` on your Windows Host:
**Name                           Value**
**PSVersion                      5.0.10586.117**
**PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}**
**BuildVersion                   10.0.10586.117**
**CLRVersion                     4.0.30319.42000**
**WSManStackVersion              3.0**
**PSRemotingProtocolVersion      2.3**
**SerializationVersion           1.1.0.1**

```PowerShell
# Output from $PSVersionTable
```

**Comment by mi-hol** [comment]
I'm actually looking for a slightly different expected behaviour than defined above.
My goal is to allow for exporting to excel a single row per component & firmware version in addition to server details. This is required to identify & plan patch activities for specific servers due to buggy firmware.

expected output:
```
serverName,romVersion,component.Name,component.FirmWareVersion
S1,P89 v2.42 (04/25/2017) ,HPE Smart Storage Battery 1 Firmware,1.1
S1,P89 v2.42 (04/25/2017) ,Intelligent Platform Abstraction Data,25.05
S1,P89 v2.42 (04/25/2017) ,Smart Array P440ar Controller,2.40
```
Any suggestion on how to create this?

**Comment by jullienl** [comment]
Have a look at a script created recently by DAVIDMARTINEZROBLES at 
https://github.com/HewlettPackard/POSH-HPOneView/issues/304

**Comment by mi-hol** [comment]
Thanks @jullienl , I've tried that but the referenced script didn't give a 'combined view' but instead 'several sections' in a txt file. Maybe I missed to find the right part in this long conversation?

**Comment by jullienl** [comment]
What about this?

```powershell


$servers = Get-HPOVServer 

echo "serverName;romVersion;component.Name;component.FirmWareVersion" >> Server_FW_Report.txt 


foreach ($server in $servers)

{

    $components = (Send-HPOVRequest -Uri ($server.uri + "/firmware")).components | % {$_.ComponentName}
    

    $name = (Get-HPOVServer -name $server.name ).name
    $romVersion = (Get-HPOVServer -name $server.name ).romVersion


    foreach ($component in $components)

    {

        $componentversion = (Send-HPOVRequest -Uri ($server.uri + "/firmware")).components | ? componentname -eq $component | select componentVersion | % {$_.componentVersion}
     
      "$name;$romVersion;$component;$componentversion" | Out-File Server_FW_Report.txt -Append

    }

}

import-csv Server_FW_Report.txt -delimiter ";" | export-csv Server_FW_Report.csv
remove-item Server_FW_Report.txt -Confirm:$false

**Comment by ChrisLynchHPE** [comment]
What I implemented in the 4.0 update is for the exact purpose @mi-hol is asking for.  The object returned can be exported to CSV using `Export-CSV`.

**Comment by DAVIDMARTINEZROBLES** [comment]
¿When you use the `Export-CSV`, you can use any filter to show only some properties?

```Powershell
Get-HPOVinterconnect | ConvertTo-Csv enclosureName, hostName,model, name, partNumber, serialNumber, interconnectIP, firmwareVersion, portCount, baseWWN | Sort-Object name 
```

**Comment by ChrisLynchHPE** [comment]
Yes, but your example is incorrect.  You should use the following:

```PowerShell
Get-HPOVinterconnect | Select-Object name, enclosureName, hostName,model, partNumber, serialNumber, interconnectIP, firmwareVersion, portCount, baseWWN | Export-Csv C:\temp\interconnects.csv -NoTypeInformation
```

**Comment by mi-hol** [comment]
@jullienl, thank you so much!
It's working exactly as required.

**Comment by mi-hol** [comment]
@ChrisLynchHPE could/should this be closed?

**Comment by ChrisLynchHPE** [comment]
Since we no longer support 3.10, yes, closing.
