### ISSUE TITLE
NEW-HPOVStorageVolume does not copy snapshot pool from the template

### ISSUE THREAD

**Issue by radekzima** [HewlettPackard/POSH-HPOneView#328]
Hi Chris, the New-HPOVStorageVolume cmdlet does not copy the snapshot storage pool defined in the template, R. 

![image](https://user-images.githubusercontent.com/37626769/37716101-f80a1e64-2d1d-11e8-85ea-69c8d1abcfb2.png)

**Comment by ChrisLynchHPE** [comment]
Please provide the following information about your system:

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  
Output from `$PSVersionTable` on your Windows Host:

```PowerShell
# Output from $PSVersionTable
```

**Comment by ChrisLynchHPE** [comment]
Closing due to older library installed.  If still an issue, we can re-open.
