### ISSUE TITLE
SIMtoOV.ps1

### ISSUE THREAD

**Issue by aradzys** [HewlettPackard/POSH-HPOneView#33]
Hi There,

great script for migration! :) At least for me it does not create log file and when script finishes it would be nice to get IP's or server names at this point:

Name            : Add
Owner           : Administrator
TaskState       : Error
PercentComplete : 100
ProgressUpdates : {}
TaskErrors      : {@{data=; errorCode=SERVER_ALREADY_MONITORED; recommendedActions=System.Object[]; errorSource=; nestedErrors=System.Object[]; details=Server {0} cannot be added as it is already being
                   monitored.; message=Server already monitored}}
Created         : 2015-08-07T10:39:07.930Z
Nodified        : 2015-08-07T10:39:07.998Z
ParentTaskUri   : 

from this info it is hard to say what server it is about. For example if error states that firmware is too old or you get connecion error.

Keep it up, nice work !!!

Regards,

Arturas

**Comment by ChrisLynchHP** [comment]
Thanks for the feedback. We added a new version to the release. Keep the feedback coming.

**Comment by aradzys** [comment]
Is there a new release or it will be there in future? Tried latest one from
your site and output still does not give IP or name

**Comment by ChrisLynchHP** [comment]
The update is posted already to the same Release Name.  The Server Name value is supposed to be in the error output, which is from the appliance.  You will need to capture the returned objects in a variable, and look at the taskErrors property (i.e. $resp[0].taskErrors).
