### ISSUE TITLE
New-HPOVLogicalInterconnectGroup in Powershell, need value for short code for "HP VC 16Gb 24-Port FC Module

### ISSUE THREAD

**Issue by waiyenwong** [HewlettPackard/POSH-HPOneView#330]
Hi, 

From this GitHub, following are the accepted values, but I need value(short code, for example : VCC24) for 'HP VC 16Gb 24-Port FC Module".  Where can I retrieve such information, appreciate any kind of help. 

Thank you.

-Bays <Hashtable>
HPE BladeSystem C7000 Support - A [System.Collections.Hashtable] object of each Interconnect Bay. Accepted values are:
* FlexFabric - HP VC FlexFabric 10Gb/24-Port Module
* Flex10     - HP VC Flex-10 Enet Module
* Flex1010D  - HP VC Flex-10/10D Module
* Flex2040f8 - HP VC FlexFabric-20/40 F8 Module
* VCFC20     - HP VC 8Gb 20-Port FC Module
* VCFC24     - HP VC 8Gb 24-Port FC Module
* FEX        - Cisco Fabric Extender for HP BladeSystem

**Comment by waiyenwong** [comment]
Found the solution, google the part number, add the following lines into the "HPOneView.310.psm1" file.

								"VC16GbFC24" 
								{

									#Get VC Flex-10/10D interconnect-type URI
									Write-Verbose "[$($MyInvocation.InvocationName.ToString().ToUpper())] Found VC 16Gb FC 24-port in bay $($_bay.name | out-string)"

									$_interconnectObject = Get-HPOVInterconnectType -partNumber "751465-B21" -Appliance $_appliance

								}

**Comment by ChrisLynchHPE** [comment]
This should not have been closed.  Looks like the module support wasn't added into the 3.10 library, let alone the 4.00 library.  I'll get this fixed.

**Comment by ChrisLynchHPE** [comment]
To follow the same format as the other Virtual Connect FC module names, the keyword will be `VCFC16`, not `VC16GbFC24`.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 4.00.1672.1789](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v4.0.1672.1789) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.400/4.00.1672.1789).

Please verify before this issue is closed.

**Comment by samwywong** [comment]
Hi Chris,

Thanks for the update....The command is working fine now.  Just one question, did you update the 'Help' as well? I'm not seeing the short code for "HP VC 16Gb 24-Port FC Module in the 'Help', did I missed anything?

<b>New-HPOVLogicalInterconnectGroup Help</b>
-Bays <Hashtable>
        HPE BladeSystem C7000 Support - A [System.Collections.Hashtable] object of each Interconnect Bay.  Accepted values are:
        
        	* FlexFabric - HP VC FlexFabric 10Gb/24-Port Module
        	* Flex10     - HP VC Flex-10 Enet Module
        	* Flex1010D  - HP VC Flex-10/10D Module
        	* Flex2040f8 - HP VC FlexFabric-20/40 F8 Module
        	* VCFC20     - HP VC 8Gb 20-Port FC Module
        	* VCFC24     - HP VC 8Gb 24-Port FC Module
        	* FEX        - Cisco Fabric Extender for HP BladeSystem
        		
        E.g. @{1 = "Flex10";2 = "Flex10";3 = "FlexFabric";4 = "Flexfabric";5 = "";6 = "";7 = "";8 = "";}

**Comment by ChrisLynchHPE** [comment]
Woops.  Thanks for catching that.  I'll publish an updated offline help release.  When published, you'll just need to do an `Update-Help` call to pick up the fix.

**Comment by ChrisLynchHPE** [comment]
@samwywong please update your offline help with the `Update-Help -Module HPOneView.400` command.  If you have already ran `Update-Help` within the last 24 hours, make sure to include the `-Force` parameter.

**Comment by samwywong** [comment]
@ChrisLynchHPE no luck on updating the Help file, here are the errors, any idea?

PS C:\WINDOWS\system32> update-help -Force -Module hponeview.400
update-help : Failed to update Help for the module(s) 'HPOneView.400' with UI culture(s) {en-US} : Unable to connect to Help content. The server on 
which Help content is stored might not be available. Verify that the server is available, or wait until the server is back online, and then try the 
command again.
At line:1 char:1
+ update-help -Force -Module hponeview.400
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToConnect,Microsoft.PowerShell.Commands.UpdateHelpCommand

**Comment by ChrisLynchHPE** [comment]
Do you have a Proxy server you need in order to access the Internet?  The URL is a public URL hosted on GitHub (specifically http://hewlettpackard.github.io/POSH-HPOneView/UpdateHelp, and the Help CAB file is https://hewlettpackard.github.io/POSH-HPOneView/UpdateHelp/HPOneView.400_9f892d35-7eda-4de9-aaab-172d6076b2e9_en-US_HelpContent.cab).

**Comment by ChrisLynchHPE** [comment]
Any further update on this?

**Comment by ChrisLynchHPE** [comment]
Closing issue due to no further input.
