### ISSUE TITLE
CompabilityCheckScript

### ISSUE THREAD

**Issue by jpaddock1** [HewlettPackard/POSH-HPOneView#332]
Is there any plan to have a compatibility check script as in VcToOneView script that can be run as standalone instance before migration occurs to OneView

**Comment by ChrisLynchHPE** [comment]
Do you have an HPE OneView appliance already running in your environment?  If so, the `Invoke-HPOVVcmMigration` has a `-Report` switch parameter that will generate the migration report only, which is the most accurate way to test pre-migration.

**Comment by ChrisLynchHPE** [comment]
Can you provide any further detail on this?

**Comment by jpaddock1** [comment]
Hi Chris,

 

Apologies, Yes, I got the results I needed from this command, thank you for the quick response

 

Regards;

 

Jeff

 

 

 

Jefferson Paddock
Cloud and Platform Services

T +44 5603032085
M +44 7790494188

DXC Technology
Bournemouth, UK

  _____  

EntServ UK Limited | Registered Office: EntServ UK Ltd, Royal Pavilion, Wellesley Road,Aldershot,Hampshire,

GU11 1PZ | Registered Number: 00053419 England | VAT number: GB 432 9959 15. EntServ UK Limited is authorised and regulated by the Financial Conduct Authority under registration number 687564.

 

This e-mail may contain confidential and/or legally privileged material for the sole use of the intended recipient. If you are not the intended recipient (or authorized to receive for the recipient) please contact the sender by reply e-mail and delete all copies of this message. If you are receiving this message internally within the DXC Technology group of companies, you should consider the contents “CONFIDENTIAL”.

  _____  



 <http://www.dxc.technology/> dxc.technology /  <https://twitter.com/dxctechnology> Twitter /  <https://www.facebook.com/DXCTechnology/> Facebook /  <https://www.linkedin.com/company/dxctechnology> LinkedIn
