### ISSUE TITLE
Get-HPOVRemoteSupportEntitlementStatus fails on G7

### ISSUE THREAD

**Issue by leearcher** [HewlettPackard/POSH-HPOneView#335]
When running get-hpovserver | Get-HPOVRemoteSupportEntitlementStatus the process looks to fail when it come across an unsupported server, like a G7.  I've had this working with OneView 3.1 but now I am running v4 it outputs:

```PowerShell
Get-HPOVRemoteSupportEntitlementStatus : null is not eligible for remote
support. The device must be eligible.
At line:1 char:18
+ get-hpovserver | Get-HPOVRemoteSupportEntitlementStatus
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Get
   -HPOVRemoteSupportEntitlementStatus], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Get-HPOVRemoteSupportEntitlemen
   tStatus
```

### Version Information
HPE OneView PowerShell Library Version 4.0.1672.1789
HPE OneView Appliance Version  4.00.07.02-0334467

PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.18728
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by leearcher** [comment]
Does anyone know if this is a bug or my usage?  It did work before I updated.

Thanks

**Comment by ChrisLynchHPE** [comment]
Remote Support is not supported with G6 and G7 servers.  It requires iLO4 at a minimum to enable.

**Comment by leearcher** [comment]
Hi Chris, I realise that but I'm sure the Get-HPOVRemoteSupportEntitlementStatus used to report Not Applicable for G7 servers and didn't just fail.  Has this command changed since v3.10?

Thanks

**Comment by ChrisLynchHPE** [comment]
No, and is likely the API generating the exception, in which Send-HPOVRequest (the core Cmdlet that interacts with the appliance API) is catching and in turn throwing the exception in your session.

**Comment by ChrisLynchHPE** [comment]
As I do not have a G7 server to test with, can you do the following and send me the output:

```PowerShell
$G7Server = Get-HPOVServer -Name 'Your G7 Server Name'
Get-HPOVCommandTrace -ScriptBlocak { Get-HPOVRemoteSupportEntitlementStatus -InputObject $G7Server }
```

**Comment by leearcher** [comment]
[1805101050_HPOV_transcript.log](https://github.com/HewlettPackard/POSH-HPOneView/files/1991162/1805101050_HPOV_transcript.log)

Hi, I've run the command and uploaded the results.

Thanks

**Comment by ChrisLynchHPE** [comment]
Thanks.  I see where the exception is being generated, and I'll add an enhancement to address this.  A non-terminating error will be generated, which would then allow you to use the `-ErrorAction` parameter and specify either `SilentlyContinue` or `Stop`.

**Comment by leearcher** [comment]
That would be great.

Thanks Chris.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 4.0.1821.1629](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v4.0.1821.1629) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.400/4.0.1821.1629).

Please verify before this issue is closed.

**Comment by leearcher** [comment]
Getting a different error now.  I've tried several erroraction options.

Get-HPOVRemoteSupportEntitlementStatus : The term
'HPOneView.Appliance.RemoteSupportResourceException' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:18
+ Get-HPOVServer | Get-HPOVRemoteSupportEntitlementStatus
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HPOneView.Appli...sourceExcepti
   on:String) [Get-HPOVRemoteSupportEntitlementStatus], CommandNotFoundExcept
  ion
    + FullyQualifiedErrorId : CommandNotFoundException,Get-HPOVRemoteSupportEn
   titlementStatus

**Comment by leearcher** [comment]
It was the latest 4.00 that was released a few days ago.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ChrisLynchHPE** [comment]
Hmm...  Did you update the library using the installer?  I have not been able to identify a potential issue with the installer where the library DLL is not updated correctly.  Can you please download the library off of PowerShell Gallery and try again?

**Comment by leearcher** [comment]
I’m getting exactly the same issue after getting it via the PS Galery.

Lee Archer

T: +44 (0) 113 397 4740
M: +44 (0) 7740 453 904 (6999)

**Comment by ChrisLynchHPE** [comment]
Are you trying to load two different OneView library versions within the same PowerShell console?  If so, please use separate consoles, as there would be a conflict with the `HPOneView` C# class that loads for each library.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.

**Comment by leearcher** [comment]
This is still an issue but I'll have to upgrade to 4.1 and see if the problem is still there.

**Comment by ChrisLynchHPE** [comment]
It still is.  I found another issue with both the 4.00 and 4.10 library when generating the error message to the caller the resource is unsupported with Remote Support.

I'm re-opening this issue.

**Comment by leearcher** [comment]
I've since updated my appliances to 4.10 and after installing the latest POSH version the commands run as expected.

Thanks for fixing it.
