### ISSUE TITLE
Cmdlet should not confirm operations by default

### ISSUE THREAD

**Issue by roberttco** [HewlettPackard/POSH-HPOneView#336]
Cmdlets that execute yet halt with a confirmation prompt should throw an exception unless they were told to explicitly prompt.  Case in point - Calling New-HPOVServerProfile against a server where there are errors in the IML log causes a prompt.  In the context where the cmdlet is executing with no user visible interface, the prompt causes the appearance that the cmdlet is hung or blocking for no apparent reason.

I propose that -Confirm:$true cause the prompt to be displayed, -Confirm:$false (the default) causes the cmdlet to throw and exception, and a -Force switch cause the Cmdlet to forcibly apply the change.

**Comment by ChrisLynchHPE** [comment]
The `-Confirm` switch cannot be implemented that way, and would go against all other Cmdlet implementations within the library that uses `SupportsShouldProcess`.  There are two realistic approaches that could be taken, one with additional logic needed in your script, or one that would change the behavior of `New-HPOVServerProfile` as it is today:

* Add logic to your script that gets the server, and then looks at the `state` attribute for anything other than `OK`.  If not `OK`, provide the `-Confirm:$false` for automation purposes IF you intent to deploy a server profile resource to a system that could be unhealthy.
* `New-HPOVServerProfile` is updated to look if `-Confirm:$false` is not supplied and yet the server is reported as "unhealthy", generate a terminating error as such.  Then allow the caller to supply the `-Confirm:$true` value to allow the profile to be assigned to a reported "unhealthy" server.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.
