### ISSUE TITLE
 Get-HPOVEnclosure -name 'Enclosure 1' | Show-HPOVFirmwareReport -Baseline $Baseline [3.10]

### ISSUE THREAD

**Issue by johdhpe** [HewlettPackard/POSH-HPOneView#342]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Firmware comparison between HPE Synergy installed firmware and uploaded HPE Synergy baseline. 

### Actual Behavior
The command is returning a result but it seems that the comparison is between the HPE Synergy installed firmware and a HPE C7000 baseline. I just removed the Appliance Connection and Name columns

PS C:\Users\admc05006as> Get-HPOVEnclosure -name 'M3P10-MID1' | Show-HPOVFirmwareReport -Baseline "Custom_Gen10Snap1FFSPP_B8 2017 10 24"
Device                   Component              Installed          Baseline                BaselinePolicy         Compliance

------                      ---------                   ---------                  --------           --------------         ----------
SY12000                 OA Bay 1 Active      2.01.01                    4.70               SPP 2017.10.24.03  Not Compliant
SY12000                 OA Bay 2 Standby   2.01.01                    4.70               SPP 2017.10.24.03  Not Compliant
SY 480 Gen9           ROM                       v2.52 (10.25.2017)                    SPP 2017.10.24.03      Not Compliant
SY 480 Gen9           ILO                           2.55                         2.55               SPP 2017.10.24.03 Compliant
SY 480 Gen9            Intelligent Pro...     Unknown                  N/A                N/A                       N/A
SY 480 Gen9            ROM                       v2.52 (10.25.2017)                    SPP 2017.10.24.03      Not Compliant
SY 480 Gen9            iLO                         2.55               2.55               SPP 2017.10.24.03             Compliant
SY 480 Gen9            Intelligent Pro...       Unknown                 N/A                N/A                       N/A
SY 480 Gen9            ROM                        v2.52 (10.25.2017)                    SPP 2017.10.24.03      Not Compliant
SY 480 Gen9             iLO                         2.55                           2.55               SPP 2017.10.24.03 Compliant
SY 480 Gen9              Intelligent Pro...     Unknown                  N/A                N/A                       N/A
SY 480 Gen9              ROM                      v2.52 (10.25.2017)                    SPP 2017.10.24.03       Not Compliant
SY 480 Gen9              iLO                        2.55                           2.55               SPP 2017.10.24.03 Compliant
SY 480 Gen9              Intelligent Pro...     Unknown                  N/A                N/A                       N/A
SY 480 Gen9              ROM                      v2.52 (10.25.2017)                    SPP 2017.10.24.03       Not Compliant
SY 480 Gen9               iLO                        2.55                           2.55               SPP 2017.10.24.03 Compliant
SY 480 Gen9               Intelligent Pro...     Unknown                  N/A                N/A                       N/A
SY 480 Gen9               ROM                      v2.52 (10.25.2017)                    SPP 2017.10.24.03       Not Compliant
SY 480 Gen9               iLO                         2.55                          2.55               SPP 2017.10.24.03 Compliant
SY 480 Gen9               Intelligent Pro...      Unknown                 N/A                N/A                       N/A
Synergy 12Gb SA...     Interconnect           1.2.4.0                      4.61               SPP 2017.10.24.03 Not Compliant
Virtual Connect...        Interconnect           1.1.1.1003                4.61               SPP 2017.10.24.03 Not Compliant
Virtual Connect...        Interconnect           1.1.1.1003                4.61               SPP 2017.10.24.03 Not Compliant
Synergy 12Gb SA...      Interconnect          1.2.4.0                      4.61               SPP 2017.10.24.03 Not Compliant
Synergy 20Gb In...       Interconnect          1.08                          4.61               SPP 2017.10.24.03 Not Compliant
Synergy 20Gb In...       Interconnect          1.08                          4.61               SPP 2017.10.24.03 Not Compliant

### Steps to reproduce
The same command gave the same results on the whole environment (16 frames)

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
3.10.1471.1581

HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`): 
3.10.1471.1581
 
Output from `$PSVersionTable` on your Windows Host:
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.18773
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by ChrisLynchHPE** [comment]
If you are still using the 3.10 library, can you please see if 
[Release https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.10.1808.1701](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/vhttps://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.10.1808.1701) fixes your issue?

**Comment by ChrisLynchHPE** [comment]
Further enhancements and fixes have been made in [Release 4.10.1954.1523](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v4.10.1954.1523) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.410/4.10.1954.1523).  The 3.10 library is no longer supported, and customers are encouraged to upgrade their appliance to either HPE OneView 4.00 or 4.10.

I'm closing this issue due to no further activity.  If you still have problems, please submit a new issue.
