### ISSUE TITLE
POSH login via AD Credentials

### ISSUE THREAD

**Issue by tlauder** [HewlettPackard/POSH-HPOneView#35]
Hello,

I'm trying to login to my HP OneView Appliance after setting up AD authentication and I'm unable to login using Local or AD credentials. I can login to the GUI via both AD and Local, just not using POSH. I've switched the default directories (Local and AD), but still no luck. I keep getting the following error:

Invalid username or password or directory.  Enter correct credentials and try again. To obtain a username or password,
contact your security administrator.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.120\HPOneView.120.psm1:2255 char:13

Thank you in advance.

- Todd Lauder

**Comment by ChrisLynchHP** [comment]
When you use ```Connect-HPOVMgmt```, you must provide the ```-AuthProvider``` parameter.  Here is an example:

```PowerShell
[PS] C:\> Connect-HPOVMgmt hpov.domain.local "ftoomey@domain.loca" hpinvent domain
```

**Comment by tlauder** [comment]
Awesome, thank you, Chris!
