### ISSUE TITLE
Confirmation Requirement of Add Enclosure

### ISSUE THREAD

**Issue by jpaddock1** [HewlettPackard/POSH-HPOneView#353]
Difference between GUI and PS for adding enclosures

Within the OneView GUI add enclosure , 3 options,

 Add enclosure for management
 Add enclosure for monitoring
 Add enclosure and migrate Virtual Connect domain

Within PS, only 2 options 
 Add enclosure for management
 Add enclosure for monitoring

Is the option to force confirmation within PS, the same as option 3 withing the GUI?

The script ran was as per example but did prompt for force before continuing 

Add-HPOVEnclosure -oa "192.168.1.1" -enclGroupName EG1 -user admin -pass hpinvent -license OneView

however, post migration although reported successful we found a profile was not retained and manual recovery of it required from VCShowall and 3Par reports taken prior to actual migration.

**Comment by ChrisLynchHPE** [comment]
Invoke-HPOVVcmMogration has been the Cmdlet to use.

**Comment by ChrisLynchHPE** [comment]
Closing to no further activity.
