### ISSUE TITLE
SUT Communication query 

### ISSUE THREAD

**Issue by jpaddock1** [HewlettPackard/POSH-HPOneView#354]
Possibly wrong place to mention this but as SUT interacts heavily with OneView

I have noticed that when deploying SUT for VMware deployment updates, in order to configure SUT command line to connect to the appliance , within the security session section "Require acknowledgement" must be unticked otherwise authentication fails, as far as i can see there is no option within SUT configuration to provide a -LoginAcknowledge type cmdlet to get around this. Any thoughts, as when either OneView or the hosting SUT server is rebooted, connectivity authentication is lost again and needs re-action.

**Comment by ChrisLynchHPE** [comment]
Closing.
