### ISSUE TITLE
4.00, 4.10 Sample AddServers_Monitored_Sample.ps1 v1.1 Suggestions and Questions on Async

### ISSUE THREAD

**Issue by ronanmcallister** [HewlettPackard/POSH-HPOneView#355]
===================

Please fill in as much information as possible to help resolve your issue.

Urgency: Low, information request, three items below related to Sample AddServers_Monitored_Sample.ps1 v1.1

### Expected Behavior

Looking for ideas on how I can monitor the state of Add-HPOVServer -Async tasks following the Sample AddServers_Monitored_Sample.ps1 other than my polling below.

It appears this Sample is v1.1 in both 4.00 and 4.10 so my comments/input applies to both.

I'm making only minor changes to the Sample script so I can understand/test Async tasks --though the Sample appears to needs minor changes to use Get-Credential over the deprecated and insecure -username, -password (hard coded in the input CSV) and to use modern PowerShell syntax.

I will eventually need to learn how I can subscribe to MSMQ/SCMB (or whatever messaging queue is appropriate) so I can understand and implement callbacks and avoid polling these Tasks for completion, as **polling for Async task completion IMHO defeats the purpose of Async tasks!**

1/ I am guessing the code block on line 103 should use $counter rather than $i in the Write-Progress expression for -PercentageComplete:

```powershell
Write-Progress -ID 1 -Activity ("Adding Servers to {0}" -f $ApplianceConnection.Name) -Status ("Processing {0}" -f $_.hostname) -PercentComplete ($i / $ServersList.Count * 100)
```
**Using $counter below appears to work better:**

```powershell
Write-Progress -ID 1 -Activity ("Adding Servers to {0}" -f $ApplianceConnection.Name) -Status ("Processing {0}" -f $_.hostname) -PercentComplete ($counter / $ServersList.Count * 100)
```
2/ Some additional Task completion checking could be added to the Default Sample below are two DL server HW being added with the Default code, the Task Objects report as  TaskState:Running and PercentComplete:0 when at the end of the script, the script block on line 117 runs:

```powershell
$AsyncTaskCollection | % { Send-HPOVRequest $_.uri } | Sort status -Descending | Format-Table
```
*Output from original Sample with two Server HW in my list:*

Appliance              Name Owner              Created      Duration TaskState PercentComplete
"---------              ---- -----              -------             -------- --------- ---------------"
oneview.local Add  administrator  8/8/2018 8:23:32 AM 00:00:05 Running   0              
oneview.local Add  administrator  8/8/2018 8:23:38 AM 00:00:03 Running   0 

*Output changing only $i to $counter in the current Sample:*

Appliance              Name Owner              Created             Duration TaskState PercentComplete
"---------              ---- -----              -------             -------- --------- ---------------"
oneview.local Add  administrator  8/8/2018 8:23:32 AM 00:00:05 Running   50           
oneview.local Add  administrator  8/8/2018 8:23:38 AM 00:00:03 Running   100 

*The Sample DOES correctly add all DL Server HW*, it is just that the Task(s) haven't all completed when the script block in line 117 subsequently executes unless you pause execution a minute or two before iterating over the Task statuses for completion.  *This got me to thinking about MSMQ/SCMB, callbacks, or perhaps better/different ways to do the same sans "polling"*,  so I can continue along with my logic and when all Task(s) are Completed 100%, do some final checking, create reports, and exit.

**I modified the script again to improve the task completion checking prior to exit:**
```powershell
#original Sample code line 117:
#
#$AsyncTaskCollection | % { Send-HPOVRequest $_.uri } | Sort status -Descending | Format-Table

# Mod to do polling instead for task completion (1s intervals):
#
foreach($task in $AsyncTaskCollection) { 

    $resp = Send-HPOVRequest $task.uri # ~38mS avg / request

    $pollsDone = 1

    do {
            $resp = Send-HPOVRequest $task.uri
            $pollsDone++
            Start-Sleep -Seconds 1 #delay a second to not hit the Appliance too hard

    } until ($resp.percentComplete -eq 100)

    Write-Host "URI:" $resp.uri " # of 1-sec pollsDone:" $pollsDone " taskState:" $resp.taskState " taskStatus:" $resp.taskStatus " percentComplete:" $resp.percentComplete
                          
}
```
**Output closer to what I need:**
...
...
We are all done.
2 async tasks were created.
Displaying final status of tasks.
URI: /rest/tasks/B3B89AD0-CBE2-445A-8DD8-D49409EA282B  # of 1-sec pollsDone: 28  taskState: Completed  taskStatus: Add server: ILO2M2427005B.  percentComplete: 100
URI: /rest/tasks/BCF39FC1-16BE-4131-A86A-4A4A48454BCD  # of 1-sec pollsDone: 6  taskState: Warning  taskStatus: Add server: ILO2M2427005D.  percentComplete: 100

3/ Is the limitation of 64 concurrent async tasks still in effect in 4.00 and 4.10 of the Appliance?  Comment on line 82:
```powershell
#Pauase the processing, as only 64 concurrent async tasks are supported by the appliance
```
### Actual Behavior

Please see above.

### Steps to reproduce

Please see above.

### Version Information

HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):

oneview.local              LibraryVersion Path                                                                  
----------------------              -------------- ----                                                                  
ApplianceVersion: 4.00.09.345092.00 4.0.1672.1789  C:\Program Files\WindowsPowerShell\Modules\HPOneView.400\4.0.1672.1789

HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  

msaoneview1.mgmt.local              LibraryVersion Path                                                                  
----------------------              -------------- ----                                                                  
ApplianceVersion: 4.00.09.345092.00 4.0.1672.1789  C:\Program Files\WindowsPowerShell\Modules\HPOneView.400\4.0.1672.1789

Output from `$PSVersionTable` on your Windows Host:

Name                           Value                                                                                                                    
----                           -----                                                                                                                    
PSVersion                      5.1.16299.492                                                                                                            
PSEdition                      Desktop                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                  
BuildVersion                   10.0.16299.492                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                          
WSManStackVersion              3.0                                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                                      
SerializationVersion           1.1.0.1 

=============================

**Comment by ChrisLynchHPE** [comment]
You only need to use the `Wait-HPOVTaskComplete` Cmdlet.  It handles multiple async task monitoring.  You simply supply a collection (`Array`, `ArrayList`, etc.) to the `-InputObject` Parameter or via pipeline.  The State Change Message Bus is not the right resource to monitor async task operations.  You would only want to attach to it in order to monitor for infrastructure state changes and take an appropriate path to perform some automated operation, or forward to another monitoring tool (like our [ServiceNow ] (https://github.com/HewlettPackard/servicenow-oneview) integration can open a service ticket and populate that information back to the activity that generated the alert.)

The version numbers within the samples do not correspond with the library release version. I update them when fixes or updates have been made so users can see they have been updated.

The appliance will regulate the flow of async tasks based on the operation being performed.  In other words, the number of concurrent async tasks is variable.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.

**Comment by ronanmcallister** [comment]
Thank you,
R
