### ISSUE TITLE
Get-HPOVProfileAssign is an alias to New-HPOVServerProfileAssign

### ISSUE THREAD

**Issue by armentpau** [HewlettPackard/POSH-HPOneView#358]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Get commands should never set data in PowerShell, this goes against the verb contract of Get.  As the alias of Get-HPOVProfileAssign is an alias of New-HPOVServerProfileAssign this could confuse someone and have unintended consequences.  If this was kept around to keep things consistent from an older version, then I understand it but wanted to bring it up.  In that case - then either this can be closed or on the next major version update can this be corrected as a breaking change?

### Actual Behavior
Get-HPOVProfileAssign invokes New-HPOVServerProfileAssign

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`): 4.0.1672.1789,4.10.1767.2250
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  4.00.07.334467.02
Output from `$PSVersionTable` on your Windows Host:

Name                           Value
----                           -----
PSVersion                      5.1.16299.551
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.551
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
Yes it is an Alias.  This was to address the very condition you stated, as the original Cmdlet Verb was `Get`.  And to support backwards compatibility, an Alias was added to not break existing Scripts.

**Comment by ChrisLynchHPE** [comment]
Closing this due to no further activity.
