### ISSUE TITLE
New-HPOVUplinkSet Error

### ISSUE THREAD

**Issue by tlauder** [HewlettPackard/POSH-HPOneView#36]
Hello,

When trying to script a new HPOVUPlinkSet with a forced fcuplinkspeed of anything other than "Auto" (2,4,8), I get the following error:

EX. New-HPOVUplinkSet -ligName "x86-LIG" -usName "SAN-B" -usNetworks "VSAN-B" -fcUplinkSpeed 8 -usType FibreChannel -usUplinkPorts "BAY2:X1","BAY2:X2"

Send-HPOVRequest : Invalid JSON data type. The JSON sent in the request contained a unknown type where a different
unknown type was required on line 1 near column 4,800.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.120\HPOneView.120.psm1:17307 char:17
+         $resp = Send-HPOVRequest $ligObject.uri PUT $ligObject

Maybe I am doing something wrong?

Thank you,
Todd Lauder

**Comment by ChrisLynchHP** [comment]
No, you aren't doing anything wrong.  The Enum hashtable that converts the speed value from the parameter had underscores in the API values.  This was an error in the library.  I've just tested a fix, and it resolves the issue.  I'm working on a few other updates, and should have a new release published tomorrow.

**Comment by tlauder** [comment]
Again, thank you!

**Comment by tlauder** [comment]
Hey Chris - Any ETA on the new release? Thank you!

**Comment by ChrisLynchHP** [comment]
I had other users report issues that I had to resolve.  I’m looking to push an update today.

**Comment by ChrisLynchHP** [comment]
This is now resolved in the [1.20.240.0 release](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v1.20.240.0).
