### ISSUE TITLE
Gen10 - New-HPOVServerProfileLogicalController "Mixed" Mode missing

### ISSUE THREAD

**Issue by MJaySama** [HewlettPackard/POSH-HPOneView#360]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
During server profile creation for Gen10 server the configured RAID should be imported or a new one should be created.

### Actual Behavior
LogicalDiskController / LogicalDisks could not be imported or created, because storage controller in Gen10 is in only in "mixed" mode and New-HPOVServerProfileLogicalDiskControlleronly supports following modes:
New-HPOVServerProfileLogicalDiskController

    -Mode [<String string>]
        The mode to configure the Smart Array Controller as.  Accepted values are:
        
        	* **HBA**
        	* **RAID**
        
        When specifying HBA, you cannot attach a RAID Logical Disk to this policy.
        
        Required?                    
        Position?                    named
        Default value                RAID
        Accept pipeline input?       false
        Accept wildcard characters?  false

If we take a look into the SHT you'll see the different controller modes:
(Get-HPOVServerHardwareType -Name "BL460c Gen10 1").storageCapabilities

raidLevels                 : {RAID0, RAID1, RAID1ADM, RAID10...}
driveTechnologies          : {SasHdd, SataHdd, SasSsd, SataSsd}
maximumDrives              : 256
controllerModes            : **{Mixed}**
nvmeBackplaneCapable       : False
standupControllerSupported : False
driveWriteCacheSupported   : True

On a Gen9 server (and below) everything works fine and RAID config could be imported or a new one created...

(Get-HPOVServerHardwareType -Name "BL460c Gen9 1").storageCapabilities

raidLevels                 : {RAID0, RAID1}
driveTechnologies          : {SasHdd, SataHdd, SasSsd, SataSsd}
maximumDrives              : 2
controllerModes            : **{RAID, HBA}**
nvmeBackplaneCapable       : False
standupControllerSupported : False
driveWriteCacheSupported   : False

### Steps to reproduce

```PowerShell
Script: 
$serverSN = "xyz"
$serverHW = Get-HPOVServer | ?{$_.serialNumber -eq $serverSN}
$vlanID = "1"
$PName = "New-Gen10"

$net1 = Get-HPOVNetwork -Name "$vlanID A *"
$con1 = New-HPOVServerProfileConnection -network $net1 -connectionType Ethernet -connectionID 1 -bootable -priority Primary
$conList = @($con1)
 
$Controller = New-HPOVServerProfileLogicalDiskController -ImportExistingConfiguration

$params = @{
name               = $PName;
#Affinity           = "Bay";
assignmentType     = "server";
server             = $serverHW.name;
manageboot         = $True;
connections        = $conList;
LocalStorage       = $True;
StorageController  = $Controller;
HideUnusedFlexnics = $True;
snAssignment       = "Physical"
}
New-HPOVServerProfile @params  | Wait-HPOVTaskComplete 

OUTPUT:
New-HPOVServerProfile : The specified controller mode RAID for Embedded SAS controller is not supported by this server hardware type.
At C:\Users\xyz\Profile1.ps1:27 char:1
+ New-HPOVServerProfile @params | Wait-HPOVTaskComplete
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (AsyncronousTask:String) [New-HPOVServerProfile], ServerProfileResourceException
    + FullyQualifiedErrorId : InvalidOperation,New-HPOVServerProfile



```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):

 LibraryVersion Path                                                    
-----------------------             -------------- ----                                                    
ApplianceVersion: 4.10.01.348545.00 4.10.1767.2250 C:\Program Files\WindowsPowerShell\Modules\HPOneView.410

Output from `$PSVersionTable` on your Windows Host:

```PowerShell
Name                           Value                                                                                                                                
----                           -----                                                                                                                                
PSVersion                      5.1.14409.1012                                                                                                                       
PSEdition                      Desktop                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                              
BuildVersion                   10.0.14409.1012                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                      
WSManStackVersion              3.0                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                  
SerializationVersion           1.1.0.1       
```

**Comment by ChrisLynchHPE** [comment]
You are using the `-ImportExistingConfiguation` parameter, which does not specify a Logical Disk configuration.  Can you do the following and provide the created log file:

```PowerShell
Get-HPOVCommandTrace -ScriptBlock { New-HPOVServerProfile @params }
```

BTW, in your parameter splat, you should be passing in the full server hardware object, not the name:

```PowerShell
$params = @{
   name               = $PName;
   #Affinity           = "Bay";
   assignmentType     = "server";
   server             = $serverHW;  # Supply the full server object here
   manageboot         = $True;
   connections        = $conList;
   LocalStorage       = $True;
   StorageController  = $Controller;
   HideUnusedFlexnics = $True;
   snAssignment       = "Physical"
}
```

**Comment by ChrisLynchHPE** [comment]
Can you please provide a status update on this?  Is your issue resolved?

**Comment by MJaySama** [comment]
Hi Chris, sorry for the delay. 
The issue still persists. Attached you'll find the log files. 

First log file: create server profile with RAID by using the "-ImportExistingConfiguation". Please note, our servers are preconfigured with RAID1 by factory, so the import should work.
[1808222107_HPOV_transcript_importdisk_issue.log](https://github.com/HewlettPackard/POSH-HPOneView/files/2396154/1808222107_HPOV_transcript_importdisk_issue.log)

Today I tried to create a server profile with following parameters:
[1809190937_HPOV_transcript_Create_RAID_ISSUE.log](https://github.com/HewlettPackard/POSH-HPOneView/files/2396155/1809190937_HPOV_transcript_Create_RAID_ISSUE.log)
$serverSN = "xyz blacked out xyz" 
$serverHW = Get-HPOVServer | ?{$_.serialNumber -eq $serverSN}
$vlanID = "xxxx"
$PName = "New-Gen10-1"

$net1 = Get-HPOVNetwork -Name "$vlanID A *"
$con1 = New-HPOVServerProfileConnection -network $net1 -connectionType Ethernet -connectionID 1 -bootable -priority Primary
$conList = @($con1)

$LogicalDisk = New-HPOVServerProfileLogicalDisk -Name "OS" -RAID RAID1 -NumberofDrives 2
$Controller = New-HPOVServerProfileLogicalDiskController -ControllerID 'Embedded' -Initialize -LogicalDisk $LogicalDisk

$params = @{
name               = $PName;
assignmentType     = "server";
server             = $serverHW;
connections        = $conList;
manageboot         = $True;
#bootMode           = "UEFI";
bootOrder          = "HardDisk";
HideUnusedFlexnics = $True;
LocalStorage       = $True;
#Initialize         = $True;
LogicalDisk        = $LogicalDisk;
snAssignment       = "Physical"
}

Get-HPOVCommandTrace -ScriptBlock {New-HPOVServerProfile @params}

(## -BootMode and -Initialize is not recognized as valid parameters for GEN10 server hardware. See attached screenshot. As workaround we set UEFI bootmode after profile creation with set-hpovresource command.. )
![grafik](https://user-images.githubusercontent.com/11180302/45741473-f108c480-bbf7-11e8-9595-8822fde36a46.png)

Thanks for your help

**Comment by ChrisLynchHPE** [comment]
The last reported condition is actually a duplicate of #334.  It will be fixed in both the 4.00 and 4.10 libraries.

**Comment by ChrisLynchHPE** [comment]
I posted an updated 4.10 library, as noted in the other issue,  [Release 4.10.1821.1567](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v4.10.1821.1567) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.410/4.10.1821.1567).

Please verify before this issue is closed.

**Comment by MJaySama** [comment]
Hi Chris, 
thanks for your help, really appreciate it :+1: 
Test with importing controller configuration and creating a new profile with local storage and controller was successful. :100:
