### ISSUE TITLE
Firmware Updates Question

### ISSUE THREAD

**Issue by jpaddock1** [HewlettPackard/POSH-HPOneView#368]
When looking at firmware for ILO, if logging directly in the prompt informs that the ILO is managed by OneView and local changes could affect the behaviour.

Is there a way that in the event say a critical update for ILO is needed, the ILO could be updated separately without the need to apply a complete SPP to the server 
ive not seen a method where individual items could be targeted for specific FW updates like the ILO from the OneView appliance

any pointers or references how to script multiple ILO FW updates from the appliance would be great. Thank you.

**Comment by ChrisLynchHPE** [comment]
You have a few options:

1. If a baseline was already applied by HPE OneView to a server, and all you needed to do was update the iLO firmware, you could create a new custom baseline on the appliance with the iLO component.  OneView could then deliver the update online (assuming HP Smart Update Tools, aka HPSUT, was available within the OS) or offline (requiring downtime).
1. Create a custom SPP using the [Custom SPP Portal](https://spp.hpe.com/custom), create a baseline that contains only firmware (Onboard Administrator, Virtual Connect, and iLO) for both RHEL7 and the supported OS if you intend to update online (which again requires HPSUT)

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
