### ISSUE TITLE
Error on Update-Module

### ISSUE THREAD

**Issue by VincentBerger** [HewlettPackard/POSH-HPOneView#369]
### Expected Behavior
Trying to update the 4.0 library from PSGallery with Update-Module

### Actual Behavior
It's complaining about a change in the Authenticode issuer between the source and target versions (see below for version numbers). Is this expected ?

### Steps to reproduce

```PowerShell
PS C:\Users\BergerV> update-module hponeview.400
PackageManagement\Install-Package : Authenticode issuer 'System.Object[]' of the new module 'HPOneView.400' with version '4.0.1821.1629' is not matching with the
authenticode issuer 'System.Object[]' of the previously-installed module 'HPOneView.400' with version '4.0.1672.1789'. If you still want to install or update, use
-SkipPublisherCheck parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2089 char:20
+ ...           $sid = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : AuthenticodeIssuerMismatch,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

**Comment by ChrisLynchHPE** [comment]
Did you modify any local permissions in `$env:ProgramFiles\WindowsPowerShell` directory?  I don't see how this is an issue with the library, as it is signed with HPE's software digital signature.

**Comment by VincentBerger** [comment]
Not knowingly, no. I did an Uninstall-Module, then Install-Module -NoClobber to work around the problem

**Comment by ChrisLynchHPE** [comment]
Not sure what happened there.  I have only seen that behavior with a bundled module, like Pester.  Not sure what to "fix" here.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.
