### ISSUE TITLE
Issue Importing Profiles

### ISSUE THREAD

**Issue by tlauder** [HewlettPackard/POSH-HPOneView#37]
Hello,

I'm trying to migrate profiles from one instance of HP OneView (1.20.05) to another instance of HP OneView (1.20.05) and I'm getting an error. I've exported the profiles using the following command:
Get-HPOVProfile -export -location D:\PowerShell\OneViewScripts\profiles
And it exported the profiles, and then I try to import the profiles with this command:
New-HPOVProfile -Import -file D:\PowerShell\OneViewScripts\profiles\servername.json | Wait-HPOVTaskComplete

I get the following error, no matter what server type I choose:
Name            : Create
Owner           : xxxxxxxxx
TaskState       : Error
PercentComplete : 100
ProgressUpdates : {}
TaskErrors      : {@{errorCode=UNKNOWN_SERVER_TYPE; data=; errorSource=; nestedErrors=System.Object[]; message=Unable to determine the server type /rest/server-hardware-types/E637BB79-2FE1-4E88-AEFE-7575623E6FCE for the server hardware.; details=; recommendedActions=System.Object[]}}
Created         : 2015-09-10T17:03:53.405Z
Nodified        : 2015-09-10T17:03:53.545Z
ParentTaskUri   :

Any help would be awesome.

Thanks,
Todd

**Comment by ChrisLynchHP** [comment]
You can't simply import the JSON file by itself.  You need to go through and modify URI's.  URI's are unique per OneView instance.  If you want to replicate objects, I would strongly suggest you look at the [Import-Export Sample Script] (https://github.com/HewlettPackard/POSH-HPOneView/wiki/Import-Export-OVResources) that is on the Wiki.
