### ISSUE TITLE
Error - Cannot edit or Delete the Group

### ISSUE THREAD

**Issue by jpaddock1** [HewlettPackard/POSH-HPOneView#370]
OneView Appliance  4.10.0-0348545

Settings:
Local login has been disabled to use AD authentication only.

Issue:
After defining Scopes, adding the AD group to "Users and Groups" and then setting the Role and Scope to the new AD Group, upon trying to edit the permissions, the following error is received:

- Cannot edit or delete the group
Enable local login or create another group with Infrastructure Administrator role before editing or deleting the group

This is seen for both amending current setting or trying to add new 

The account used to amend is member of the AD Admin group which has Infrastructure Admin role assigned to All resources.

**Comment by ChrisLynchHPE** [comment]
This currently is a restriction in that you cannot edit or modify the group your account maps to when authenticating from an external directory, unless you either:

1. Enable local users, which you stated is not desired.
1. Log in with a different user account that maps to a different security group that can edit Groups within OneView.

**Comment by jpaddock1** [comment]
I have tried using alternate account also. test account that is assigned to the test AD group and that group assigned Read-Only role. My account that is Infra Admin and assigned infra admin role only yet i cannot edit the Read-Only

**Comment by ChrisLynchHPE** [comment]
I had tested this on one of my 4.10 appliances, and had no issues.  Are you sure your LDAP/AD user account doesn't happen to map to the OneView group you are trying to edit?

Also, this isn't the right forum to discuss topics like this.  I would kindly suggest you start a thread at the [HPE OneView Communities](https://community.hpe.com/t5/HPE-OneView/bd-p/oneview
)

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
