### ISSUE TITLE
Cannot select Windows 2016 for HostOStype

### ISSUE THREAD

**Issue by davew1234** [HewlettPackard/POSH-HPOneView#372]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Cannot select Windows 2016 for HostOStype as Win2k16, only up to Win2K12 (CreateProfileTemplate and CreateProfile). However it can be selected within OneView.

### Version Information
PowerShell: 5.1.14409.1012
HPOneView.410: 4.10.1821.1567
OneView (Synergy): 4.10.03.364293.00

**Comment by ChrisLynchHPE** [comment]
Thanks for pointing this out.  For now, you should be able to specify Win2K12 as the OS type.  This will be updated in the next 4.10 library update.
