### ISSUE TITLE
In Get-HPOVTask missing "Pending" in State filter options

### ISSUE THREAD

**Issue by dunsdon** [HewlettPackard/POSH-HPOneView#378]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
```powershell
 Get-HPOVTask -State Pending

Get-HPOVTask  | where {$_.taskstate -eq "Pending"}
```

### Actual Behavior
```powershell
 Get-HPOVTask -State Pending
-------
Get-HPOVTask : Cannot validate argument on parameter 'State'. The argument "Pending" does not belong to the set
"Unknown,New,Running,SuspEnded,Terminated,Killed,Completed,Error,Warning" specified by the ValidateSet attribute. Supply an argument that is in the set and
then try the command again.
At line:1 char:55
+ Get-HPOVTask  -State Pending
+                                                       ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-HPOVTask], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-HPOVTask
-----
```
### Steps to reproduce
 Get-HPOVTask -State Pending

### Version Information

 ApplianceVersion: 4.10.03.364293.00
 4.10.1821.1567
 C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\4.10.1821.1567

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
Even though I had just added the labels above, looking at the current 4.10 library release, I added that to the ParemterSet ValidationSet attribute.  Please update to the current 4.10 library release.

**Comment by dunsdon** [comment]
Simple test of running the commandlet works.  (currently don't have an easy way to generate pending tasks)
