### ISSUE TITLE
Not able to connect to HP OneView appliance 1.10.09 using Release 1.20.240

### ISSUE THREAD

**Issue by baddridevi0116** [HewlettPackard/POSH-HPOneView#38]
Hi,

When i try to make a connection, i get the below exception:
Connect-HPOVMgmt : [Send-HPOVRequest]: The specified API version is not valid. Check the value of the X-API-Version
header, then resend the request.
At line:1 char:1
+ Connect-HPOVMgmt -appliance applicancename -authProvider "Active  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Connect-HPOVMgmt:String) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-HPOVMgmt

Next i tried using Release Release 1.10.1506. Now i get the below exception 

Connect-HPOVMgmt : Cannot create object of type "HPOneView.PKI.SslCertificate". The Response property was not found
for the HPOneView.PKI.SslCertificate object. The available property is: [OriginalURI <System.Uri>] , [ReturnedURi
<System.Uri>] , [Certificate <System.Security.Cryptography.X509Certificates.X509Certificate2>] , [Issuer
<System.String>] , [Subject <System.String>] , [SubjectAlternativeNames <System.String>] , [CertificateIsValid
<System.Boolean>] , [ErrorInformation <System.String>]
At line:1 char:1

Based on one of your threads, i found that the SSL certificate issue has been fixed in version 1.2. 

Any help greatly appreciated.

Thanks
Best Regards,
Baddri

**Comment by ChrisLynchHP** [comment]
You cannot use a 1.20 library with an older appliance version. The library versions are locked to specific API versions that match the appliance major and minor release.  Are you sure you are using the correct library version

**Comment by baddridevi0116** [comment]
Hi Chris,

Thanks a lot for your response.

As recommended by you, I used the correct version and I was able to
connect. But can you let me know what should be the syntax to connect to HP
OV using cmdlet Connect-HPOVMgmt using a domain user. I was able to connect
using a local user but domain user is failing. I used the below given syntax

Connect-HPOVMgmt -appliance <app string> -authstring <Active Directory>
-user domain\userid -password password

Thanks a lot

Best Regards,
Baddri

**Comment by ChrisLynchHP** [comment]
The correct syntax would be the following:

``powershell
Connect-HPOVMgmt -appliance $ApplianceName -Username user@addomain.com -Password "MyP@ssw0rd" -AuthProvider "DirectoryName"
```

DirectoryName will be the display name you configured on the Appliance when adding an Authentication Directory.  The Directory Name does not need to match the AD Domain Name in any way.

**Comment by ChrisLynchHP** [comment]
Closing this issue.  If you feel it is still an open problem, please reply.
