### ISSUE TITLE
Support request for Mac (powershell )

### ISSUE THREAD

**Issue by ajayvaaka** [HewlettPackard/POSH-HPOneView#381]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior

Import module have to happen without issues. i already had this module in my repository
* Import-Module HPOneView.410 

needs to request for composer information
* Connect-HPOVMgmt   

### Actual Behavior
```powershell
Import-Module HPOneView.410
Import-Module : Could not load type 'Microsoft.PowerShell.Commands.OutPrinterCommand' from assembly 'Microsoft.PowerShell.Commands.Utility, Version=6.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
At line:1 char:1
+ Import-Module HPOneView.410
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
+ FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
PS /Users/xxxxxxx> Connect-HPOVMgmt           
Connect-HPOVMgmt : The 'Connect-HPOVMgmt' command was found in the module 'HPOneView.410', but the module could not be loaded. For more information, run 'Import-Module HPOneView.410'.
At line:1 char:1
+ Connect-HPOVMgmt
+ ~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Connect-HPOVMgmt:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
```

### Steps to reproduce

```PowerShell
# 1. Capture verbose output using the Get-HPOVCommandTrace for HPOneView.310 or newer, or append the -Verbose switch to your Cmdlet call.
# 2. Put your code and/or captured output here.
# 3. Remove this comment block before submitting.
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  
Output from `$PSVersionTable` on your Windows Host:

```PowerShell
# Output from $PSVersionTable
```

**Comment by ChrisLynchHPE** [comment]
Unfortunately, PowerShell Core (aka PowerShell 6) is not supported at this time.  It is on our backlog, and will require a substantial amount of re-work.

**Comment by ChrisLynchHPE** [comment]
I am revisiting this topic. I have performed some research on transitioning to .Net Standard 2.0 to support PowerShell 5.1, 6.x and PowerShellCore 6.x. I will be uploading a new test branch of the 4.20 library that can be used to test with. However, I will not be looking to release the newer PowerShell library and associated class library until HPE OneView 5.0 is released (which we announced back at HPE Discover Las Vegas 2019).

I'll follow up on #406 when the test branch has been added.

**Comment by ChrisLynchHPE** [comment]
Can you also provide the output from `$PSversiontable` on your Mac?

**Comment by VincentBerger** [comment]
Here is mine:
```
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ajayvaaka** [comment]
@VincentBerger , thanks for sharing . @ChrisLynchHPE  above version works for me too. power-shell above 6.x version

**Comment by ChrisLynchHPE** [comment]
I committed the [dev branch](https://github.com/HewlettPackard/POSH-HPOneView/tree/4.20-DotNetStandard-Dev) in the other thread I referenced above, #406.  Please feel free to download and use it in non-production environment.  Do know that it is not signed with HPE's digital signing certificate.

**Comment by ajayvaaka** [comment]
@ChrisLynchHPE  thanks for help . Works for me too

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting.  Do know that the 4.20 dev branch will not be supported and will be deleted soon.  I am publishing the 5.00 library either later today or over the weekend, as all unit tests have passed.  No, the 5.00 library is not backwards compatible with older OneView versions.

The main reason why I am not changing the 4.20 release to supporting PowerShell 6 or Core is that it would mean removing PowerShell 4.0 support from the library.  That is happening with the OneView 5.00 PowerShell library release anyhow, but I can't make that drastic of a change with a released version.

**Comment by ChrisLynchHPE** [comment]
@ajayvaaka can you tell me if you ran into any initial issues using the library on your Mac?  Did you need to use the `$IgnoreCertErrors = $True` statement before using the library?  Can you tell me what version of DotNetCore is installed on your system?

To get the DotNet runtime information, execute:

``` bash
dotnet --info
```
