### ISSUE TITLE
Security Questions

### ISSUE THREAD

**Issue by jpaddock1** [HewlettPackard/POSH-HPOneView#384]
As part of pen testing the following came back, is it possible to address these?

Username Enumeration - it was found to respond differently to existing and non-existing users which made it possible to enumerate legitimate users

Security Response Headers - the host did utilise common security headers as those recommended by OWASP secure headers project

**Comment by ChrisLynchHPE** [comment]
This is the wrong forum or place to inquire about HPE OneView security assessment questions.  Please feel free to ask this question on the [HPE OneView Communities forum](https://community.hpe.com/t5/HPE-OneView/bd-p/oneview).
