### ISSUE TITLE
Update-HPOVServerHardwareLicenseIntent example have 4 errors

### ISSUE THREAD

**Issue by uzimmermann42** [HewlettPackard/POSH-HPOneView#386]
Version HPOV 4.10

Example for Update-HPOVServerHardwareLicenseIntent has 4 errors in it:

Current example: $Servers = Get-HPOVServer | ? licenseIntent -ew "OneViewNoIlo" $Tasks = $Servers | Update-HPOVServerHardwareLicenseIntent -async

1.) The property member is called "licensingIntent" and not "licenseIntent"
2.) It should be "-eq" and not "-ew"
3.) It should be "OneViewNoiLO" and not "OneViewNoIlo"
4.) There should be a line/command break before $Tasks

**Comment by ChrisLynchHPE** [comment]
Thanks for pointing out a few errors.  Do know that PowerShell is not case sensitive, so `#3 above is not an error in the documentation.  `#4 is a formatting issue I'll have to look at in the HTML code generated from the library MAML help.

**Comment by ChrisLynchHPE** [comment]
Docs have been updated.  Please either update your library as a new one was just published today, or use `Update-Help -Module HPOneView.410`.
