### ISSUE TITLE
Add Server with scope parameter

### ISSUE THREAD

**Issue by Schwitzd** [HewlettPackard/POSH-HPOneView#387]
### Expected Behavior
Add a server in a specific scope with the command:
`Add-HPOVServer Srv01 -ApplianceConnection $session -Username Administrator -Password xxx -Scope Scope1 -monitored`

### Actual Behavior

```
> Add-HPOVServer : Cannot process argument transformation on parameter 'Scope'. Cannot convert the "Scope1" value of type "System.String" to type
> "HPOneView.Appliance.ScopeCollection".
> At line:1 char:108
> + ... ession -Username Administrator -Password xxx -Scope Scope1 -monito ...
> +                                                              ~~~~
>     + CategoryInfo          : InvalidData: (:) [Add-HPOVServer], ParameterBindingArgumentTransformationException
>     + FullyQualifiedErrorId : ParameterArgumentTransformationError,Add-HPOVServer
```

### Steps to reproduce
`Add-HPOVServer Srv01 -ApplianceConnection $session -Username Administrator -Password xxx -Scope Scope1 -monitored`

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`): 4.10.1889.2173
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  4.10.01.348545.00
Output from `$PSVersionTable` on your Windows Host: PS 5.1

**Comment by ChrisLynchHPE** [comment]
This isn't the proper use.  You need to get the Scope resource object, and pass that into the `-Scope` Cmdlet parameter.

```powershell
$MyScope = Get-HPOVScope -Name MyScope
Add-HPOVServer -Hostname Srv01 -Username Administrator -Password xxx -Scope Scope1 -monitored
```

The `-ApplianceConnection` parameter is not required unless you have multiple appliance connections, and need to target a specific appliance for the operation.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish to continue discussing, feel free to re-open the issue.
