### ISSUE TITLE
New-HPOVUplinkSet Error

### ISSUE THREAD

**Issue by tlauder** [HewlettPackard/POSH-HPOneView#39]
Hi,

I am seeing a new error when trying to created a new Uplink set.

Example Command:
New-HPOVUplinkSet -ligName "x86-LIG" -usName "ETH-A" -usNetworks "800,801,803" -usType "Ethernet" -usUplinkPorts "BAY1:X3","BAY1:X4","BAY1:X5","BAY1:X6" -usEthMode "Auto"

Error:
[Send-HPOVRequest]: An internal error occurred while attempting the operation. If the error persists, contact your authorized support representative and provide them with a support dump.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.120\HPOneView.120.psm1:1934 char:29
+                             Throw $errorRecord
+                             ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [], InvalidOperationException
    + FullyQualifiedErrorId : CRM_DEFAULT_INTERNAL_SERVER_EXCEPTION

Any help would be appreciated.

Thanks!
Todd

**Comment by ChrisLynchHP** [comment]
Can you create an Uplink Set in the UI?  I would also need to see the output from -verbose when you attempt to create this Uplink Set.

**Comment by tlauder** [comment]
Hi Chris - Yes I can create an Uplink Set in the UI. Please see output from -verbose:

New-HPOVUplinkSet -ligName "x86-LIG" -usName "ETH-A" -usNetworks "800,801" -usType "Ethernet" -usUplinkPorts "BAY1:X3","BAY1:X4","BAY1:X5","BAY1:X6" -usEthMode "Auto" -Verbose
VERBOSE: [NEW-HPOVUPLINKSET] LIG Resource Name provided: x86-LIG
VERBOSE: [GET-HPOVLOGICALINTERCONNECTGROUP] Bound PS Parameters:

Key   : name
Value : x86-LIG



VERBOSE: [GET-HPOVLOGICALINTERCONNECTGROUP] Logical Interconnect Group name provided: 'x86-LIG'
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:

Key   : uri
Value : /rest/logical-interconnect-groups?filter=name='x86-LIG'



VERBOSE: [SEND-HPOVREQUEST] SSLCheckFlag: True
VERBOSE: [SEND-HPOVREQUEST] Requested URI: /rest/logical-interconnect-groups?filter=name='x86-LIG'
VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [RESTCLIENT] Bound PS Parameters:
Key    Value
---    -----
method GET
uri    /rest/logical-interconnect-groups?filter=name='x86-LIG'


VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET
https://xxx.xxx.xxx.xxx/rest/logical-interconnect-groups?filter=name='x86-LIG'
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://xxx.xxx.xxx.xxx/rest/logical-interconnect-groups?filter=name='x86-LIG'
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 120
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = iSkg5tNgl1lCK5s0nqWKZQi-IGEJB4ai
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 OK
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Vary = Accept-Encoding
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Content-Encoding =
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Content-Type = application/json;charset=UTF-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 6: Date = Thu, 17 Sep 2015 18:51:47 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 7: Via = 1.1 server.domain.com
VERBOSE: [SEND-HPOVREQUEST] Response:

type        : LogicalInterconnectGroupCollectionV2
members     : {@{type=logical-interconnect-groupV2; snmpConfiguration=; telemetryConfiguration=;
              uplinkSets=System.Object[]; interconnectMapTemplate=; ethernetSettings=; stackingHealth=;
              stackingMode=Enclosure; description=; status=; name=x86-LIG; state=Active;
              eTag=821cfd43-f655-4dc4-9f6d-60ddf8bc480a; created=2015-09-17T18:51:27.267Z;
              modified=2015-09-17T18:51:27.700Z; category=logical-interconnect-groups;
              uri=/rest/logical-interconnect-groups/7079695f-a0d9-4dae-b8ea-0aef2704165b}}
start       : 0
nextPageUri :
prevPageUri :
count       : 1
total       : 1
eTag        :
created     :
modified    :
category    : logical-interconnect-groups
uri         : /rest/logical-interconnect-groups?start=0&count=1&filter="name='x86-LIG'"



VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] END
VERBOSE: [GET-HPOVLOGICALINTERCONNECTGROUP] Found 1 Logical Interconnect Group resource(s).
VERBOSE: Done. 1 logical interconnect group(s) found.
VERBOSE: [NEW-HPOVUPLINKSET] Getting supported Interconnect Types from appliance.
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:

Key   : uri
Value : /rest/interconnect-types



VERBOSE: [SEND-HPOVREQUEST] SSLCheckFlag: True
VERBOSE: [SEND-HPOVREQUEST] Requested URI: /rest/interconnect-types
VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [RESTCLIENT] Bound PS Parameters:
Key    Value
---    -----
method GET
uri    /rest/interconnect-types


VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET
https://xxx.xxx.xxx.xxx/rest/interconnect-types
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://xxx.xxx.xxx.xxx/rest/interconnect-types
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 120
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = iSkg5tNgl1lCK5s0nqWKZQi-IGEJB4ai
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 OK
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Vary = Accept-Encoding
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Content-Encoding =
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Content-Type = application/json;charset=UTF-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 6: Date = Thu, 17 Sep 2015 18:51:48 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 7: Via = 1.1 server.domain.com
VERBOSE: [SEND-HPOVREQUEST] Response:

type        : InterconnectTypeCollectionV2
members     : {@{type=interconnect; downlinkCount=16; downlinkCapabilities=System.Object[]; portInfos=System.Object[];

              partNumber=638526-B21; unsupportedCapabilities=System.Object[]; minimumFirmwareVersion=4.10;
              maximumFirmwareVersion=4.99; description=; status=OK; name=HP VC Flex-10/10D Module; state=Active;
              eTag=1700e98a-7f64-4434-920e-42a0c1dda898; created=2015-09-17T18:37:46.741Z;
              modified=2015-09-17T18:37:46.753Z; category=interconnect;
              uri=/rest/interconnect-types/1f615da1-51e8-4f2c-a084-f06ec3246a67}, @{type=interconnect;
              downlinkCount=16; downlinkCapabilities=System.Object[]; portInfos=System.Object[];
              partNumber=571956-B21; unsupportedCapabilities=System.Object[]; minimumFirmwareVersion=4.10;
              maximumFirmwareVersion=4.99; description=; status=OK; name=HP VC FlexFabric 10Gb/24-Port Module;
              state=Active; eTag=3523887d-4021-48eb-baea-7ea1b3671487; created=2015-09-17T18:37:46.395Z;
              modified=2015-09-17T18:37:46.422Z; category=interconnect;
              uri=/rest/interconnect-types/49a47466-9159-4b3d-af8f-3c8f035e4691}, @{type=interconnect;
              downlinkCount=16; downlinkCapabilities=System.Object[]; portInfos=System.Object[];
              partNumber=641146-B21; unsupportedCapabilities=System.Object[]; minimumFirmwareVersion=9.00;
              maximumFirmwareVersion=9.99; description=; status=OK; name=Cisco Fabric Extender for HP BladeSystem;
              state=Active; eTag=05ddf1ac-c8cd-4704-9e8c-40bafeaae778; created=2015-09-17T18:37:47.493Z;
              modified=2015-09-17T18:37:47.501Z; category=interconnect;
              uri=/rest/interconnect-types/8ca8bb80-1cfc-4560-aac9-ea52c2bff37a}, @{type=interconnect;
              downlinkCount=16; downlinkCapabilities=System.Object[]; portInfos=System.Object[];
              partNumber=691367-B21; unsupportedCapabilities=System.Object[]; minimumFirmwareVersion=4.20;
              maximumFirmwareVersion=4.99; description=; status=OK; name=HP VC FlexFabric-20/40 F8 Module;
              state=Active; eTag=af2dd08d-317c-4903-9b7b-5afa0886695c; created=2015-09-17T18:37:46.991Z;
              modified=2015-09-17T18:37:47.000Z; category=interconnect;
              uri=/rest/interconnect-types/8e089cf6-5525-4489-aa2f-554f83734682}...}
start       : 0
nextPageUri :
prevPageUri :
count       : 7
total       : 7
eTag        :
created     :
modified    :
category    : interconnect-types
uri         : /rest/interconnect-types?start=0&count=7



VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] END
VERBOSE: [NEW-HPOVUPLINKSET] Uplink Ports: BAY1:X3
BAY1:X4
BAY1:X5
BAY1:X6
VERBOSE: [NEW-HPOVUPLINKSET]] Processing Port Bay1:X3
VERBOSE: [NEW-HPOVUPLINKSET]] Looking for Interconnect URI for Bay 1
VERBOSE: [NEW-HPOVUPLINKSET]] Found permitted Interconnect Type URI
/rest/interconnect-types/49a47466-9159-4b3d-af8f-3c8f035e4691 for Bay 1
VERBOSE: [NEW-HPOVUPLINKSET] Adding Uplink Set to LIG:
logicalLocation                                             desiredSpeed

---------------                                             ------------

{locationEntries}                                           Auto



VERBOSE: [NEW-HPOVUPLINKSET]] Processing Port Bay1:X4
VERBOSE: [NEW-HPOVUPLINKSET]] Looking for Interconnect URI for Bay 1
VERBOSE: [NEW-HPOVUPLINKSET]] Found permitted Interconnect Type URI
/rest/interconnect-types/49a47466-9159-4b3d-af8f-3c8f035e4691 for Bay 1
VERBOSE: [NEW-HPOVUPLINKSET] Adding Uplink Set to LIG:
logicalLocation                                             desiredSpeed

---------------                                             ------------

{locationEntries}                                           Auto



VERBOSE: [NEW-HPOVUPLINKSET]] Processing Port Bay1:X5
VERBOSE: [NEW-HPOVUPLINKSET]] Looking for Interconnect URI for Bay 1
VERBOSE: [NEW-HPOVUPLINKSET]] Found permitted Interconnect Type URI
/rest/interconnect-types/49a47466-9159-4b3d-af8f-3c8f035e4691 for Bay 1
VERBOSE: [NEW-HPOVUPLINKSET] Adding Uplink Set to LIG:
logicalLocation                                             desiredSpeed

---------------                                             ------------

{locationEntries}                                           Auto



VERBOSE: [NEW-HPOVUPLINKSET]] Processing Port Bay1:X6
VERBOSE: [NEW-HPOVUPLINKSET]] Looking for Interconnect URI for Bay 1
VERBOSE: [NEW-HPOVUPLINKSET]] Found permitted Interconnect Type URI
/rest/interconnect-types/49a47466-9159-4b3d-af8f-3c8f035e4691 for Bay 1
VERBOSE: [NEW-HPOVUPLINKSET] Adding Uplink Set to LIG:
logicalLocation                                             desiredSpeed

---------------                                             ------------

{locationEntries}                                           Auto



VERBOSE: [NEW-HPOVUPLINKSET] Getting "800,801" URI
VERBOSE: [GET-HPOVNETWORK] Bound PS Parameters:

Key   : type
Value : Ethernet

Key   : name
Value : 800,801



VERBOSE: [GET-HPOVNETWORK] Verify auth
VERBOSE: [GET-HPOVNETWORK] Looking for Ethernet networks...
VERBOSE: [GET-HPOVNETWORK] Looking for '800,801' Ethernet Network network.
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:

Key   : uri
Value : /rest/ethernet-networks?filter="name matches '800,801'"



VERBOSE: [SEND-HPOVREQUEST] SSLCheckFlag: True
VERBOSE: [SEND-HPOVREQUEST] Requested URI: /rest/ethernet-networks?filter="name matches '800,801'"
VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [RESTCLIENT] Bound PS Parameters:
Key    Value
---    -----
method GET
uri    /rest/ethernet-networks?filter="name matches '800,801'"


VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET
https://xxx.xxx.xxx.xxx/rest/ethernet-networks?filter="name matches '800,801'"
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://xxx.xxx.xxx.xxx/rest/ethernet-networks?filter="name matches '800,801'"
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 120
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = iSkg5tNgl1lCK5s0nqWKZQi-IGEJB4ai
VERBOSE: [SEND-HPOVREQUEST] Net.WebException Error caught
VERBOSE: [SEND-HPOVREQUEST] ERROR RESPONSE:

details            : An internal error occurred while attempting the operation
nestedErrors       : {}
errorSource        :
recommendedActions : {If the error persists, contact your authorized support representative and provide them with a
                     support dump.}
data               :
errorCode          : CRM_DEFAULT_INTERNAL_SERVER_EXCEPTION
message            : Internal error



VERBOSE: [SEND-HPOVREQUEST] Response Status: HTTP 500 [Server Error]
VERBOSE: [SEND-HPOVREQUEST] Response Header: Vary = Thu, 17 Sep 2015 18:51:48 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header: Content-Encoding = 1.1 server.domain.com
VERBOSE: [SEND-HPOVREQUEST] Response Header: Connection =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Transfer-Encoding =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Cache-Control =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Content-Type =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Date =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Via =
VERBOSE: [NEW-ERRORRECORD] Building ErrorRecord object
[Send-HPOVRequest]: An internal error occurred while attempting the operation. If the error persists, contact your
authorized support representative and provide them with a support dump.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.120\HPOneView.120.psm1:1934 char:29
+                             Throw $errorRecord
+                             ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [], InvalidOperationException
    + FullyQualifiedErrorId : CRM_DEFAULT_INTERNAL_SERVER_EXCEPTION

**Comment by ChrisLynchHP** [comment]
You have your call wrong.  The Networks parameter value needs to be an Array.  Your command should be:

``` PowerShell
New-HPOVUplinkSet -ligName "x86-LIG" -usName "ETH-A" -usNetworks "800”,”801" -usType "Ethernet" -usUplinkPorts "BAY1:X3","BAY1:X4","BAY1:X5","BAY1:X6" -usEthMode "Auto" –
```

**Comment by tlauder** [comment]
Hi Chris,

This is the code that used to work:

$ANets = Get-HPOVNetwork | where { $_.Name -like "VLAN*-A"}
$AVLANs = $ANets.Name -join ","
New-HPOVUplinkSet -ligName "x86-LIG" -usName "ETH-A" -usNetworks "$AVLANs" -usType "Ethernet" -usUplinkPorts "BAY1:X3","BAY1:X4","BAY1:X5","BAY1:X6" -usEthMode "Auto"

But no longer does.... Any thoughts?

Thanks,
Todd

**Comment by ChrisLynchHP** [comment]
What you have should never have worked.  The -Networks parameter only accepts an Array of Strings, Array of Objects, a String (Network URI or Name) or PSCustomObject (Network Object).  The second command you have in your script takes the names of networks found and joins their string value into a long string value, with commas, which is wrong.  I had updated documentation to reflect this as the documentation was wrong quite a while ago.

You do not need to use PowerShell filtering to look for a Network Name.  Your script should be:

``` PowerShell
$ANets = Get-HPOVNetwork “VLAN*-A"
New-HPOVUplinkSet -ligName "x86-LIG" -usName "ETH-A" -usNetworks $ANets -usType "Ethernet" -usUplinkPorts "BAY1:X3","BAY1:X4","BAY1:X5","BAY1:X6" -usEthMode "Auto"
```

**Comment by tlauder** [comment]
That's pretty crazy... It's working now!

Thank you!
