### ISSUE TITLE
Need to script connection to 'smart card-only' enabled appliance

### ISSUE THREAD

**Issue by BarryGS** [HewlettPackard/POSH-HPOneView#392]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Need a non-interactively connect to an appliance with 'smart-card only' enabled in order to update internally-signed CRLs.

### Actual Behavior
Script halts on Connect-HPOVMgmt, prompting for a PIN.

### Steps to reproduce
1. Enable smart card-only authentication.
2. Run powershell script invoking Connect-HPOVMgmt with '-certificate' option.

### Version Information
Synergy appliance firmware is  4.10.03-0364293.
PowerShell Library is 4.10.

**Comment by ChrisLynchHPE** [comment]
If your certificate requires a PIN to unlock, I do not know how to support that automatically.  From some research, this isn't possible due to security risk exposure.

**Comment by BarryGS** [comment]
Thanks Chris.

Suspected as much, I believe our choices are: 
1. Craft a certificate that doesn't require a PIN or;
2. Disable the 'smart card only' feature on the appliances.

Shall pass on to our security/architecture team.

**Comment by ChrisLynchHPE** [comment]
You are unfortunately correct.  SmartCard with PIN support isn't possible unless you can cache the PIN in some fashion.  Or, you use PIN-less SmartCard for authentication.

**Comment by BarryGS** [comment]
Yep, an architecture/security decision above my pay grade :)
 

**Comment by ChrisLynchHPE** [comment]
Closing.  If needed, this issue can be re-opened to discuss further if new data points are discovered.
