### ISSUE TITLE
New-HPOVServerProfile -ServerProfileTemplate

### ISSUE THREAD

**Issue by i1Smirnov** [HewlettPackard/POSH-HPOneView#393]
### Expected Behavior
Create new server profile from server profile template.

### Actual Behavior

```powershell
New-HPOVServerProfile : Cannot determine the scope for a created resource. The user session is authorized to create the resource in multiple scopes. Retry the operation, specifying the desired resource sc
ope. 
At line:1 char:1
+ New-HPOVServerProfile -Name $ovSPName -ServerProfileTemplate $ovSPT - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [New-HPOVServerProfile], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,New-HPOVServerProfile
```

### Steps to reproduce
```powershell
$ovSPName = 'sp001'
$ovServer = Get-HPOVServer -Name 's001'
$ovSPT = Get-HPOVServerProfileTemplate -Name 'spt01'

New-HPOVServerProfile -Name $ovSPName -ServerProfileTemplate $ovSPT
```
### Version Information
LibraryVersion 4.10.1889.2173

ApplianceVersion 4.10.04.370820.00
                                                                                                                                                                  
PSVersion                            5.1.14393.1613                                                                                                                                                               
PSEdition                             Desktop                                                                                                                                                                      
PSCompatibleVersions        {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                         10.0.14393.1613                                                                                                                                                              
CLRVersion                           4.0.30319.42000                                                                                                                                                              
WSManStackVersion             3.0                                                                                                                                                                          
PSRemotingProtocolVersion 2.3                                                                                                                                                                          
SerializationVersion               1.1.0.1

**Comment by ChrisLynchHPE** [comment]
The error is stating that you need to supply a Scope to assign the resource to, as you have multiple scopes for your user account.  You need to provide the `-Scope` parameter, and a scope resource value from `Get-HPOVScope`, so that the profile can be assigned to a specific scope.

**Comment by i1Smirnov** [comment]
If I do same (same account, same server profile template, same server hardware type... all same) procedure from the appliance web-gui,  i have not this error.

**Comment by ChrisLynchHPE** [comment]
OneView is stating that your user account is a member of multiple scopes.  The UI defaults to placing the resource into all scopes you have Write access into.  You need to specify one of those scopes as a destination using the `-Scopes` parameter I specified above.

**Comment by i1Smirnov** [comment]
Chris, thank You for answer.
Cmdlet "New-HPOVServerProfile" nas no parameter "-Scopes" - 
New-HPOVServerProfile -Name <String> [-ServerProfileTemplate <Object>] -AssignmentType <String> [-Enclosure <Object>] [-EnclosureBay <Int32>] [-Server <Object>] [-Description <String>] [-Connections <Array>] [-Firmware <SwitchParameter>] [-Baseline <Object>] [-FirmwareInstallMode <String>] [-FirmwareActivationMode <String>] [-FirmwareActivateDateTime <DateTime>] [-ForceInstallFirmware <SwitchParameter SwitchParameter>] [-ManageBoot <SwitchParameter>] [-LocalStorage <SwitchParameter>] [-StorageController <Object>] -IscsiIPv4Address <Array> -ISCSIInitatorName <String> -ChapSecret <SecureString> -MutualChapSecret <SecureString> [-OSDeploymentPlan <Object>] [-OSDeploymentAttributes <Array>] [-Async <SwitchParameter>] [-ApplianceConnection <Object>] -Passthru <SwitchParameter> [-WhatIf <>] [-Confirm <>] [<CommonParameters>]

Cmdlet "New-HPOVServerProfileTemplate " also nas no parameter "-Scopes" -
    New-HPOVServerProfileTemplate -Name <String> -ServerHardwareType <Object> [-Description <String>] [-ServerProfileDescription <String>] [-ManageConnections <Boolean>] [-Connections <Array>] [-EnclosureGroup <Object>] [-Firmware <SwitchParameter>] [-FirmwareInstallMode <String>] [-FirmwareActivationMode <String>] [-Baseline <Object>] [-ForceInstallFirmware <SwitchParameter>] [-OSDeploymentPlan <Object>] [-OSDeploymentPlanAttributes <Array>] [-Bios <SwitchParameter>] [-BiosSettings <Array>] [-BootMode <String>] [-PxeBootPolicy <String>] [-ManageBoot <SwitchParameter>] [-BootOrder <Array>] [-SecureBoot <String>] [-LocalStorage <SwitchParameter>] [-StorageController <Object>] [-Affinity <String>] [-MacAssignment <String>] [-WwnAssignment <String>] [-SnAssignment <String>] [-HideUnusedFlexNics <Boolean>] [-Async <SwitchParameter>] -PassThru <SwitchParameter> [-ApplianceConnection <Object>] [<CommonParameters>]

    New-HPOVServerProfileTemplate -Name <String> -ServerHardwareType <Object> [-SANStorage <SwitchParameter>] [-HostOStype <String>] [-StorageVolume <Object>] [-Description <String>] [-ServerProfileDescription <String>] [-ManageConnections <Boolean>] [-Connections <Array>] [-EnclosureGroup <Object>] [-Firmware <SwitchParameter>] [-FirmwareInstallMode <String>] [-FirmwareActivationMode <String>] [-Baseline <Object>] [-ForceInstallFirmware <SwitchParameter>] [-OSDeploymentPlan <Object>] [-OSDeploymentPlanAttributes <Array>] [-Bios <SwitchParameter>] [-BiosSettings <Array>] [-BootMode <String>] [-PxeBootPolicy <String>] [-ManageBoot <SwitchParameter>] [-BootOrder <Array>] [-SecureBoot <String>] [-LocalStorage <SwitchParameter>] [-StorageController <Object>] [-EvenPathDisabled <SwitchParameter>] [-OddPathDisabled <SwitchParameter>] [-Affinity <String>] [-MacAssignment <String>] [-WwnAssignment <String>] [-SnAssignment <String>] [-HideUnusedFlexNics <Boolean>] [-Async <SwitchParameter>] -PassThru <SwitchParameter> [-ApplianceConnection <Object>] [<CommonParameters>]

I added my server profile template in scope. However, creating server profile is failed. 

$ovEnclosureGroupName  = 'egPROD'
$ovScopeName = 'OS ESXi'
$ovServerName = 'SDC01-AEE-BS-01, bay 1'
$ovServerProfileTemplateName = 'PROD_BL460cGen8-1_SPP8.1'
$ovServerHardwareTypeName = 'BL460c Gen8 1'
$ovServerProfileName = 'test_profile'
$testOvServerProfileTemplateName = 'test_spt'

$ovScope  = Get-HPOVScope -Name $ovScopeName
$ovServer = Get-HPOVServer -Name $ovServerName
$ovServerProfileTemplate = Get-HPOVServerProfileTemplate -Name $ovServerProfileTemplateName
$ovServerHardwareType = Get-HPOVServerHardwareType -Name $ovServerHardwareTypeName
$ovEnclosureGroup = Get-HPOVEnclosureGroup -Name $ovEnclosureGroupName

New-HPOVServerProfileTemplate -Name $testOvServerProfileTemplateName -ServerHardwareType $ovServerHardwareType -EnclosureGroup $ovEnclosureGroup | Wait-HPOVTaskComplete

$testOvServerProfileTemplate = Get-HPOVServerProfileTemplate -Name $testOvServerProfileTemplateName

Add-HPOVResourceToScope -Scope $ovScope -InputObject $testOvServerProfileTemplate | Wait-HPOVTaskComplete

$ovServer | New-HPOVServerProfile -Name $ovServerProfileName -ServerProfileTemplate $testOvServerProfileTemplate
New-HPOVServerProfile : Cannot determine the scope for a created resource. The user session is authorized to create the resource in multiple scopes. Retry the operation, specifying the desired reso
urce scope. 
At line:1 char:13
+ $ovServer | New-HPOVServerProfile -Name $ovServerProfileName -ServerP ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [New-HPOVServerProfile], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,New-HPOVServerProfile

And the same result for command without assign the server - 
New-HPOVServerProfile -Name $ovServerProfileName -ServerProfileTemplate $testOvServerProfileTemplate -AssignmentType Unassigned
New-HPOVServerProfile : Cannot determine the scope for a created resource. The user session is authorized to create the resource in multiple scopes. Retry the operation, specifying the desired reso
urce scope. 
At line:1 char:1
+ New-HPOVServerProfile -Name $ovServerProfileName -ServerProfileTempla ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [New-HPOVServerProfile], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,New-HPOVServerProfile

My user account has "infrastructure administrator" role. 

Also, if I create server profile without server profile template, the procedure complete succesfull.

**Comment by ChrisLynchHPE** [comment]
Hmmm... Can you provide the output from:

```PowerShell
$ConnectedSessions[0].ActivePermissions
```

After you have connected to an appliance?

**Comment by i1Smirnov** [comment]
```
RoleName                     ScopeName        Active
--------                     ---------        ------
Server administrator         OS ESXi          True  
Server profile administrator OS XEN           True  
Server administrator         project BE       True  
Server administrator         project KASPP    True  
Server administrator         project PZUD     True  
Server administrator         OS XEN           True  
Server administrator         project GLONASS  True  
Server profile administrator OS ESXi          True  
Server administrator         project UD       True  
Server administrator         project SDOP     True  
Server administrator         project SAP HANA True  
Infrastructure administrator AllResources     True 
```

**Comment by ChrisLynchHPE** [comment]
Thanks.  You do realize that Infrastructure Administrator takes precedence over the other roles, right?  I will look at enhancing both `New-HPOVServerProfileTemplate` and `New-HPOVServerProfile` Cmdlets to add a `-Scope` parameter, and support Scope permissions that have multiple scopes.

For your case, can you provide a screenshot of the `Scope` field in the UI when you attempt to create either a Server Profile or Server Profile Template?

**Comment by i1Smirnov** [comment]
Good day, Chris! Thank You! That's right. Temporary, my AD account is a member of two security groups. In one group I have 'Infrastructure administrator' role, in the second - 'Server administrator' for some scopes. 
I created a new OneView local account with 'Infrastructure administrator' privileges. I succesfully created new server profile from server profile template with the new OV account.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
