### ISSUE TITLE
New Change NetOp Password for 4.20 and VC Interconnects

### ISSUE THREAD

**Issue by JaragonCR** [HewlettPackard/POSH-HPOneView#395]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior

OV 4.20 adds a feature to be able to change the NetOP password. Can this be exposed through this tool?
### Actual Behavior
Currently not supported on the tool.

### Steps to reproduce
PATCH/rest/interconnects/{id}

Set the password for the netop user in the interconnect. Note: netop user is only                               supported for Virtual Connect SE 40Gb F8 Modules and Virtual Connect SE 100Gb F32                               Modules for Synergy. | replace | /netOpPasswd | Password
-- | -- | -- | --

**Comment by ChrisLynchHPE** [comment]
I have added this to the 4.20 library backlog and will address it in a future update.

**Comment by ChrisLynchHPE** [comment]
This enhancement was delivered in [Release 4.20.2133.3186](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v4.20.2133.3186) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.420/4.20.2133.3186).
