### ISSUE TITLE
Importing an enclosure

### ISSUE THREAD

**Issue by Anbeek** [HewlettPackard/POSH-HPOneView#40]
Hi Chris,

I have the following issue:

First I add a new enclosure group:
[HPONEVIEW]: administrator@131.224.76.100 PS C:\Users\a-anbeekc> New-HPOVEnclosureGroup -name "SSCC_KNMI" -logicalInterConnectGroup "SSCC_KNMI_SH"
Done. 1 logical interconnect group(s) found.

type                        : EnclosureGroupV2
uri                         : /rest/enclosure-groups/04d28506-beff-4e87-8ebe-094d94531f98
category                    : enclosure-groups
name                        : SSCC_KNMI
created                     :
modified                    :
eTag                        :
status                      : OK
state                       : Normal
stackingMode                : Enclosure
portMappingCount            : 8
portMappings                : {@{midplanePort=1; interconnectBay=1}, @{midplanePort=2; interconnectBay=2}, @{midplanePort=3; interconnectBay=3}, @{midplanePort=4; interconnectBay=4}...}
interconnectBayMappingCount : 8
interconnectBayMappings     : {@{interconnectBay=1; logicalInterconnectGroupUri=/rest/logical-interconnect-groups/9c3d8bc1-e245-4614-b2a1-19263c438b08}, @{interconnectBay=2; logicalInterconnectGroupUri=/re
                              icalInterconnectGroupUri=/rest/logical-interconnect-groups/9c3d8bc1-e245-4614-b2a1-19263c438b08}, @{interconnectBay=4; logicalInterconnectGroupUri=/rest/logical-interconnect-g
description                 :

Then I import an enclosure:

[HPONEVIEW]: administrator@131.224.76.100 PS C:\Users\a-anbeekc>  Add-HPOVEnclosure -oa "145.23.160.30" -enclGroupName SSCC_KNMI -user IloAdmin -pass Password -license OneViewNoIlo
Done. 1 enclosure group(s) found.
caught System.InvalidOperationException exception
Add-HPOVEnclosure : Enclosure group 'SSCC_KNMI' not found!  Please check the Enclosure Group Name and try again.
At line:1 char:2
+  Add-HPOVEnclosure -oa "145.23.160.30" -enclGroupName SSCC_KNMI -user IloAdmin - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-HPOVEnclosure:String) [Add-HPOVEnclosure], InvalidOperationException
    + FullyQualifiedErrorId : EnclosureGroupResourceNotFound,Add-HPOVEnclosure

But when I look for the enclosure group, it exists:

[HPONEVIEW]: administrator@131.224.76.100 PS C:\Users\a-anbeekc> Get-HPOVEnclosureGroup -name SSCC_KNMI

type                        : EnclosureGroupV2
uri                         : /rest/enclosure-groups/04d28506-beff-4e87-8ebe-094d94531f98
category                    : enclosure-groups
name                        : SSCC_KNMI
created                     : 2015-09-17T11:32:21.087Z
modified                    : 2015-09-17T11:32:21.091Z
eTag                        : 2015-09-17T11:32:21.091Z
status                      : OK
state                       : Normal
stackingMode                : Enclosure
portMappingCount            : 8
portMappings                : {@{midplanePort=1; interconnectBay=1}, @{midplanePort=2; interconnectBay=2}, @{midplanePort=3; interconnectBay=3}, @{midplanePort=4; interconnectBay=4}...}

Do you have a clue?

best regards,

Cees Anbeek
RIVM
Netherlands

**Comment by ChrisLynchHP** [comment]
What version of the library are you using?

**Comment by Anbeek** [comment]
[HPONEVIEW]: administrator@131.224.76.100 PS C:\Users\a-anbeekc> hpovversion

Name                           Value
----                           -----
libraryLoadedPath              C:\Users\a-anbeekc\Documents\WindowsPowerShell\Modules\HPOneView.120
OneViewPowerShellLibrary       1.20.0112.0

**Comment by ChrisLynchHP** [comment]
Please update your library to the [current](https://github.com/HewlettPackard/POSH-HPOneView/releases/latest) 1.20 version

**Comment by Anbeek** [comment]
Hi Chris,

I have updated the library to version 240, but that didn't solve the issue. See the log below:

PS C:\Users\a-anbeekc> Get-HPOVLogicalInterconnectGroup

Name                 Enclosure Groups
----                 ----------------
KNMI
SSCC_VDI_RIVM_legacy SSCC_VDI
SSCC                 SSCC_SH
SSCC 20GB            SSCC_SH_20GB


PS C:\Users\a-anbeekc> New-HPOVEnclosureGroup -name "KNMI_SH" -logicalInterConnectGroup "KNMI"


type                        : EnclosureGroupV2
uri                         : /rest/enclosure-groups/2116447e-9864-4111-b1df-560c5da3d27e
category                    : enclosure-groups
name                        : KNMI_SH
created                     :
modified                    :
eTag                        :
status                      : OK
state                       : Normal
stackingMode                : Enclosure
portMappingCount            : 8
portMappings                : {@{midplanePort=1; interconnectBay=1}, @{midplanePort=2; interconnectBay=2}, @{midplanePort=3; interc
                              onnectBay=3}, @{midplanePort=4; interconnectBay=4}...}
interconnectBayMappingCount : 8
interconnectBayMappings     : {@{interconnectBay=1; logicalInterconnectGroupUri=/rest/logical-interconnect-groups/04d9478f-4eb9-438
                              a-9734-b6aca50666b1}, @{interconnectBay=2; logicalInterconnectGroupUri=/rest/logical-interconnect-gro
                              ups/04d9478f-4eb9-438a-9734-b6aca50666b1}, @{interconnectBay=3; logicalInterconnectGroupUri=/rest/log
                              ical-interconnect-groups/04d9478f-4eb9-438a-9734-b6aca50666b1}, @{interconnectBay=4; logicalInterconn
                              ectGroupUri=/rest/logical-interconnect-groups/04d9478f-4eb9-438a-9734-b6aca50666b1}...}
description                 :



PS C:\Users\a-anbeekc> Add-HPOVEnclosure -oa "145.23.160.30" -enclGroupName "KNMI_SH" -user IloAdmin -pass Puppet0n1$ -license OneVi
ewNoIlo -verbose
VERBOSE: [ADD-HPOVENCLOSURE] Bound PS Parameters:

Key   : hostname
Value : 145.23.160.30

Key   : enclGroupName
Value : KNMI_SH

Key   : username
Value : IloAdmin

Key   : password
Value : Puppet0n1$

Key   : licensingIntent
Value : OneViewNoIlo

Key   : Verbose
Value : True



VERBOSE: [ADD-HPOVENCLOSURE] Bound PS Parameters:

Key   : hostname
Value : 145.23.160.30

Key   : enclGroupName
Value : KNMI_SH

Key   : username
Value : IloAdmin

Key   : password
Value : Puppet0n1$

Key   : licensingIntent
Value : OneViewNoIlo

Key   : Verbose
Value : True



VERBOSE: [ADD-HPOVENCLOSURE] - Starting
VERBOSE: [GET-HPOVENCLOSUREGROUP] Bound PS Parameters:

Key   : name
Value : KNMI_SH



VERBOSE: [GET-HPOVENCLOSUREGROUP] Enclosure Group name provided: 'KNMI_SH'
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:

Key   : uri
Value : /rest/enclosure-groups?filter=name='KNMI_SH'



VERBOSE: [SEND-HPOVREQUEST] SSLCheckFlag: True
VERBOSE: [SEND-HPOVREQUEST] Requested URI: /rest/enclosure-groups?filter=name='KNMI_SH'
VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [RESTCLIENT] Bound PS Parameters:
Key    Value
---    -----
method GET
uri    /rest/enclosure-groups?filter=name='KNMI_SH'


VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET
https://131.224.76.100/rest/enclosure-groups?filter=name='KNMI_SH'
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://131.224.76.100/rest/enclosure-groups?filter=name='KNMI_SH'
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 120
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = 39OweLbxBoRip7bvWvwr5afl78JkPoUx
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 OK
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Vary = Accept-Encoding
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Content-Encoding =
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Content-Type = application/json;charset=UTF-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 6: Date = Fri, 18 Sep 2015 08:05:54 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 7: Via = 1.1 sscc-oneview-a01p.int.ssc-campus.nl
VERBOSE: [SEND-HPOVREQUEST] Response:

type        : EnclosureGroupListV2
members     : {@{type=EnclosureGroupV2; uri=/rest/enclosure-groups/2116447e-9864-4111-b1df-560c5da3d27e;
category=enclosure-groups;
               name=KNMI_SH; created=2015-09-18T08:05:08.919Z; modified=2015-09-18T08:05:08.922Z; eTag=2015-09-18T08:05:08.922Z;
st
              atus=OK; state=Normal; stackingMode=Enclosure; portMappingCount=8; portMappings=System.Object[];
interconnectBayMappi
              ngCount=8; interconnectBayMappings=System.Object[]; description=}}
nextPageUri :
start       : 0
prevPageUri :
count       : 1
total       : 1
created     : 2015-09-18T08:05:54.631Z
eTag        : 2015-09-18T08:05:54.631Z
modified    : 2015-09-18T08:05:54.631Z
category    : enclosure-groups
uri         : /rest/enclosure-groups?filter=name='KNMI_SH'&start=0&count=100



VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] END
VERBOSE: [GET-HPOVENCLOSUREGROUP] Found 1 Enclosure Group resources.
VERBOSE: Done. 1 enclosure group(s) found.
VERBOSE: [ADD-HPOVENCLOSURE] - Found Enclosure Group KNMI_SH
VERBOSE: [ADD-HPOVENCLOSURE] - Sending request to import managed enclosure
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:

Key   : uri
Value : /rest/enclosures

Key   : method
Value : POST

Key   : body
Value : @{hostname=145.23.160.30; username=IloAdmin; password=Puppet0n1$; licensingIntent=OneViewNoIlo;
enclosureGroupUri=/rest/enc
        losure-groups/2116447e-9864-4111-b1df-560c5da3d27e; firmwareBaselineUri=; forceInstallFirmware=False;
updateFirmwareOn=Encl
        osureOnly}



VERBOSE: [SEND-HPOVREQUEST] SSLCheckFlag: True
VERBOSE: [SEND-HPOVREQUEST] Requested URI: /rest/enclosures
VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [RESTCLIENT] Bound PS Parameters:
Key    Value
---    -----
method POST
uri    /rest/enclosures


VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for POST https://131.224.76.100/rest/enclosures
VERBOSE: [SEND-HPOVREQUEST] Body object found. Converting to JSON.
VERBOSE: [SEND-HPOVREQUEST] Request Body:
{"hostname":"145.23.160.30","username":"IloAdmin","password":"Password$","licensingIntent":"OneViewNoIlo","enclosureGroupUri":"/re
st/enclosure-groups/2116447e-9864-4111-b1df-560c5da3d27e","firmwareBaselineUri":null,"forceInstallFirmware":false,"updateFirmwareOn
":"EnclosureOnly"}
VERBOSE: [SEND-HPOVREQUEST] Request: POST https://131.224.76.100/rest/enclosures
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 120
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = 39OweLbxBoRip7bvWvwr5afl78JkPoUx
VERBOSE: [SEND-HPOVREQUEST] Request Header 7: Host = 131.224.76.100
VERBOSE: [SEND-HPOVREQUEST] Net.WebException Error caught
VERBOSE: [SEND-HPOVREQUEST] ERROR RESPONSE:

errorSource        :
nestedErrors       : {}
recommendedActions : {Correct the content of the JSON and try the request again.}
details            : The JSON sent in the request contained a unknown type where a different unknown type was required on line 1
ne
                     ar column 73.
errorCode          : INVALID_JSON_DATA_TYPE
data               :
message            : Invalid JSON data type.



VERBOSE: [SEND-HPOVREQUEST] Response Status: HTTP 400 [Bad Request]
VERBOSE: [SEND-HPOVREQUEST] Response Header: Vary = 1.1 sscc-oneview-a01p.int.ssc-campus.nl
VERBOSE: [SEND-HPOVREQUEST] Response Header: Content-Encoding =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Connection =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Content-Length =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Cache-Control =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Content-Type =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Date =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Via =
VERBOSE: [SEND-HPOVREQUEST] HTTP 400 error caught.
VERBOSE: [NEW-ERRORRECORD] Building ErrorRecord object
VERBOSE: [NEW-ERRORRECORD] Building ErrorRecord object
Add-HPOVEnclosure : Enclosure group 'KNMI_SH' not found!  Please check the Enclosure Group Name and try again.
At line:1 char:1
+ Add-HPOVEnclosure -oa "145.23.160.30" -enclGroupName "KNMI_SH" -user IloAdmin -p ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-HPOVEnclosure:String) [Add-HPOVEnclosure], InvalidOperationException
    + FullyQualifiedErrorId : EnclosureGroupResourceNotFound,Add-HPOVEnclosure

PS C:\Users\a-anbeekc> Get-HPOVEnclosureGroup

Name         Logical Interconnect Group Used By
----         -------------------------- -------
KNMI_SH      KNMI                       sscc-be-am3-05,sscc-be-am3-02,sscc-be-am3-04,sscc-be-am3-03,sscc-be-am3-01,sscc-be-ams3-...
SSCC_SH_20GB SSCC 20GB                  sscc-be-am3-05,sscc-be-am3-02,sscc-be-am3-04,sscc-be-am3-03,sscc-be-am3-01,sscc-be-ams3-...
SSCC_VDI     SSCC_VDI_RIVM_legacy       sscc-be-am3-05,sscc-be-am3-02,sscc-be-am3-04,sscc-be-am3-03,sscc-be-am3-01,sscc-be-ams3-...
SSCC_SH      SSCC                       sscc-be-am3-05,sscc-be-am3-02,sscc-be-am3-04,sscc-be-am3-03,sscc-be-am3-01,sscc-be-ams3-...


PS C:\Users\a-anbeekc> 


There is another strange thing, because the new enclosure group KNMI_SH and the logical Interconnect isn't used by anything, but the output stated different.
I hav some more problems with importing an enclosure through the GUI and therefore I have now a level 2 case with HP.

best regards and hope that you can help.

Cees Anbeek

**Comment by ejschulte** [comment]
It appears that the appliance does not approve of the json body specifically the licensingIntent parameter.  Try altering your value to OneViewNoiLO.

**Comment by ChrisLynchHP** [comment]
The error response you see is reporting incorrectly.  As Eric stated, the issue is with the License Intent value.  Some of the property values are camel case strict, and there should have been a flag in our library that checks for the camel case value for the licenseintent parameter.

**Comment by ChrisLynchHP** [comment]
I added a Camel Case enforcement to the `-LicensingIntent` parameter to `Add-HPOVEnclosure`. Please download the current 1.20 library under the Releases section.
