### ISSUE TITLE
API Question - Relating IPs to Composers

### ISSUE THREAD

**Issue by milesoursler** [HewlettPackard/POSH-HPOneView#401]
Hi,

I'm trying to script inventorying of some of the stuff in OneView and I need to relate the IP info to the specific appliance.

Get-HPOVApplianceNetworkConfig gets me the information for app1Ipv4Addr and app2Ipv4Addr but neither Get-HPOVComposerNode or Get-HPOVEnclosure seem to get me the ability to determine which one is actually using which IP.

Any help is greatly appreciated.

M

**Comment by ChrisLynchHPE** [comment]
Is this question for HPE Synergy?  If so, `Get-HPOVEnclosure` will not contain any additional information with IP address assingement, unless you are then asking about iLO or fabric module IP addresses.

**Comment by milesoursler** [comment]
Yes, HPE Synergy. How do I determine which appliance is using which maintenance IP? 

Miles

-----Original Message-----

**Comment by ChrisLynchHPE** [comment]
What you are looking for are the `app1Ipv4Addr ` and `app2Ipv4Addr ` properties.  They would be the composer maintenance IP addesses assigned to the composers.  The `virtIpv4Addr` property is the cluster VIP you connect with to access the OneView UI/REST API.

```PowerShell
[PS] C:\Users\clynch> (Get-HPOVApplianceNetworkConfig).appliancenetworks | fl *


interfaceName              : Appliance
device                     : eth0
macAddress                 : 00:15:5d:5f:c0:32
ipv4Type                   : STATIC
ipv6Type                   : UNCONFIGURE
overrideIpv4DhcpDnsServers : False
overrideIpv6DhcpDnsServers : False
confOneNode                : True
activeNode                 : 1
hostname                   : hpov7.lab.local
app1Ipv4Addr               : 192.168.19.37
app2Ipv4Addr               : 192.168.19.38
virtIpv4Addr               : 192.168.19.33
ipv4Subnet                 : 255.255.255.0
ipv4Gateway                : 192.168.19.1
app1Ipv6Addr               :
app2Ipv6Addr               :
virtIpv6Addr               :
ipv6Subnet                 :
ipv6Gateway                :
app1Ipv4Alias              :
app2Ipv4Alias              :
app1Ipv6Alias              :
app2Ipv6Alias              :
domainName                 :
searchDomains              : {lab.local}
ipv4NameServers            : {192.168.19.11, 192.168.19.12}
ipv6NameServers            : {}
bondedTo                   :
unconfigure                : False
aliasDisabled              : False
```

**Comment by milesoursler** [comment]
Yes, I have that but I need to know which IP (not VIP) is being used by which specific appliance.

Sent from MailDroid

-----Original Message-----

**Comment by ChrisLynchHPE** [comment]
The `Get-HPOVComposerNode` will tell you which appliance is active.  The IP Addresses are assigned based on which composer powered on first and became Active.  I would have to check if it is possible to get any further information from there.  What are you trying to solve?

**Comment by milesoursler** [comment]
For compliance reasons I need to associate each IP with a specific serial number. I need to know which composer is using which IP. 

Thanks,

Miles

-----Original Message-----

**Comment by ChrisLynchHPE** [comment]
The Maintenance IP is only needed for out of band things like access the nodes SSH service console.  You can view which node is active with the `Get-HPOVComposerNode` Cmdlet, by looking at the `role` and `location` properties:

```PowerShell
PS C:\Users\Administrator> Get-HPOVComposerNode | fl *


type                           : HANode
uri                            : /rest/appliance/ha-nodes/CN7516021F
category                       : ha-nodes
eTag                           : "889265239"
created                        : 2019-03-01T06:09:58.737Z
modified                       : 2019-03-01T08:05:42.300Z
role                           : Active
version                        : 4.20.01-0380241
location                       : @{bay=2; description=Rack1-Mid-CN751500Z9, appliance bay 2; enclosure=}
synchronizationPercentComplete : 100
synchronizationSecondsLeft     : 0
incompatibilityError           :
weakETag                       : W/"204798696"
state                          : OK
name                           : Rack1-Mid-CN751500Z9, appliance bay 2
description                    :
status                         : OK
modelNumber                    : Synergy Composer
extAttributes                  :
applianceId                    : 86475fb7-3a70-4e87-b1cc-b149a50f9d25
oldUri                         : /rest/appliance/ha-nodes/CN7516021F
ApplianceConnection            : Appliance1

type                           : HANode
uri                            : /rest/appliance/ha-nodes/CN75150116
category                       : ha-nodes
eTag                           : "65874327"
created                        : 2019-03-01T07:36:17.463Z
modified                       : 2019-03-01T08:05:20.166Z
role                           : Standby
version                        : 4.20.01-0380241
location                       : @{bay=1; description=Rack1-Bot-CN75150107, appliance bay 1; enclosure=}
synchronizationPercentComplete : 100
synchronizationSecondsLeft     : 0
incompatibilityError           :
weakETag                       : W/"1854239901"
state                          : OK
name                           : Rack1-Bot-CN75150107, appliance bay 1
description                    :
status                         : OK
modelNumber                    : Synergy Composer
extAttributes                  :
applianceId                    : 86475fb7-3a70-4e87-b1cc-b149a50f9d25
oldUri                         : /rest/appliance/ha-nodes/CN75150116
ApplianceConnection            : Appliance1
```

But the `Active` Composer Node is determined only by which one first powers on and presents the First Time Setup.  The IP Addresses do not change if they change their role.

**Comment by milesoursler** [comment]
Yes, I know that. I still need to know which specific device is using which IP. 

Miles

-----Original Message-----

**Comment by ChrisLynchHPE** [comment]
I just checked the API, and there is no current way to report which node is assigned to which maintenance IP address.  This is currently a gap within the OneView REST API that I cannot code around.  I have brought this to our dev teams attention and we will look at enhancing the experience in the future.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
