### ISSUE TITLE
Module Layout

### ISSUE THREAD

**Issue by FriedrichWeinmann** [HewlettPackard/POSH-HPOneView#402]
Maintaining all functions in a single PSM1 file comes with significant disadvantages:

 - Scares off contributors
 - Harder to debug
 - Not compatible with all editors
 - Hard to automate against
 - Easy to miss bugs

Instead, having one file per function and compiling them as part of the build step would help with all of that, without giving up the fast import time from having a single file.

Fortunately, doing this transformation need not be as prohibitively labor intensive as you would expect. Using the `PSModuleDevelopment` module, creating a new module layout, splitting out the function and setting up the build logic is fairly simple:

Creating a new module project:
```powershell
Invoke-PSMDTemplate PSFProject
```

Separating out functions:
```powershell
Split-PSMDScriptFile -File '.\HPOneView.420.psm1' -Path .
```

If there is an interest in going that way, I'll be happy to offer detailed guidance through the setup.

**Comment by ChrisLynchHPE** [comment]
I have contemplated spitting up the PSM1 module into different, small modules.  But I didn't because VSCode didn't track very well of functions/methods/contents across multiple source files within the editor or workspace, since that is my may dev IDE.

I'll check out your suggestion to see how that works, but I won't be able to do that for a while, since I have a lot of other customer features to add to my library.

**Comment by FriedrichWeinmann** [comment]
Heya Chris,

if it's ok with you, I'll create a sample PR. I will not spend too much time cleaning things up and I don't have any way to test actual functionality, but it would give you a good idea of what the end result would look like.
Not sure about VSCode (I loathe the tool), PowerShell Studio has been good to me when it comes to projects however. Easily maintains all references across the entire project and refactoring stuff updates all references as well (e.g. when renaming parameters)

**Comment by ChrisLynchHPE** [comment]
Sure, you can submit a PR.  I have AppVeyor test gates that would need to be run.  But I'm not looking to massively change the structure of the module today.  If you want to fork the project, and specifically the 4.20 branch, go a head and make your changes.  You can then send me a pointer to that forked repo so I can look at it.

To each their own with IDE's, as I am not a fan of PowerShell Studio.  I too didn't like VSCode in the early days, but it has since vastly improved.  I don't strictly code or develop in PowerShell, so I need the flexibility of a cross development IDE.

**Comment by FriedrichWeinmann** [comment]
Oh absolutely, PSS is only really useful in PS-centric coding.
Mind you, for that I have found it beyond compare (though some tweaking to its settings really help in that regard. Like clean up its UI as the bare minimum ...), but then again … PS (and C# in Visual Studio) is pretty much all I do ^^

**Comment by FriedrichWeinmann** [comment]
Alright, got my comparison design up and spinning:
https://github.com/FriedrichWeinmann/POSH-HPOneView

**Comment by FriedrichWeinmann** [comment]
Additionally, you are currently exporting the following functions that no longer exist:
```
Set-HPOVAlertAssignToUser
Set-HPOVLdapGroup
Import-HPOVCluster
Remove-HPOVCluster
Update-HPOVCluster
Get-HPOVAvailableServerConnections
```
End this command is exported twice:
```
Get-HPOVPowerPotentialDeviceConnection
```

**Comment by ChrisLynchHPE** [comment]
That's because those have yet to be implemented. I use external Cmdlet help because the builtin advanced function help system is broken and will not work for my needs.

I'll take a look at your forked example over the weekend.

**Comment by FriedrichWeinmann** [comment]
Hm, looks like this is a dead issue.
I'll leave my fork up but am closing the issue to declutter your issue view (and my own list of active issues to track). If you later get around to taking a look after all, feel free to either reach out directly or reopen the issue and post again (mail notifications should get me back into the discussion)

**Comment by ChrisLynchHPE** [comment]
Sorry, I did take a look at what you had done, and I just lost track of replying.  The amount of work needed to then change my testing and build workflows was too large, and I didn't like each Cmdlet as its own script file.  It broke Intellisense.  Prior to you opening a discussion here, I had been looking at breaking the module apart, into different "sections" based in our product category types.  The main reason I haven't is the lose of Intellisense across modules and script files, unless you have a script or module imported into your PowerShell console/session or within the module or script file directly.

I'll continue to look at this, and will eventually have to break it apart.

**Comment by FriedrichWeinmann** [comment]
Hm, with the VSCode limitation ... have you considered updating your profile to import the psm1 file straight from your local clone? With the template I posted you can definitely load it straight from the repo and would probably be the best compromise where splitting things up neatly and intellisense are concerned, given your choice of editor.
Regarding the testing and build workflow:
How are you currently performing those? Don't think I've seen anything in the repo.
As for my solution, it's basically a 20 minutes setup when done in Azure DevOps as automation engine (though the test&build scripts can be run on any platform, including locally). Without a comparison to how you currently do that I can't really join _that_ conversation though ^^
