### ISSUE TITLE
Use of Global Variables

### ISSUE THREAD

**Issue by FriedrichWeinmann** [HewlettPackard/POSH-HPOneView#403]
The module declares several global variables during import.
E.g.:

```powershell
$Global:CallStack
${Global:ConnectedSessions}
${Global:ResponseErrorObject}
```

and uses other variables such as: `$Global:IgnoreCertPolicy`

I have several concerns with this decision:

- Users may accidentally overwrite them
- Users can discover what should be internal runtime variables (Not too likely, but possible via tab completion)
- May conflict with other modules, since very generically named

In case of the last example, `$Global:IgnoreCertPolicy`, which appears to be an import preference:
While users _can_ discover it, it is unlikely to happen. Basically, users would have to read the docs to figure out it exists and what it is good for.
For configuration settings, employing a configuration module - such as `Configuration` or the configuration component of `PSFramework` - would make it a lot more manageable.

As for the runtime variables:
I can only guess _why_ you picked them (Too much code and not enough time).
The most common scenario I have seen that in, is if you have code that needs to access it but is not executed from within the module scope, and thus would not have access to module scope variables.

You can execute code from within the module scope while outside it:

```powershell
$module = Get-Module 'HPOneView.420'
& $module { $script:FSOpenMode }
```

So if it's for this reason, please use this trick or a scope-neutral access method to avoid the risks and inconvenience.

**Comment by ChrisLynchHPE** [comment]
Thanks for your feedback here.  There are a number of reasons for using these scope definitions.  Some of them (mostly those with the `$Script` scope) are being removed from that scope, so they are implicitly within the script execution scope when the module is imported.  That is taking time as to not break internal code.

There really is only the 1 `$Global` variable, and that recently moved into the Class library to control its real state.  The global scope variable is mainly there for backwards compatibility reasons.

**Comment by FriedrichWeinmann** [comment]
Ah, alright.
My general observation has been that you are really tying yourself down with all those module scope variables and costing yourself flexibility. A lot of those definitions could easily have been enumerations instead (e.g. the mapping hashtables - multiple labels with the same numeric value on an enumeration would have done the same, without causing headaches with scopes). Others configurations or stored/defined in C# / class library.
As it is, changing any variables in any function is an incredible danger of breaking something.

As for explicit versus implicit module scope: I significantly prefer being explicit about it, both when defining _and_ consuming them, as that makes it a lot easier to see where the information comes from. However changing every definition at the module root from explicit to implicit is totally safe, unless you accidentally rename it as well.
Depending on your priorities probably a low prio item, I'd recommend not adding any more module scope variables though, as you are seriously adding technical debt to your module.

**Comment by ChrisLynchHPE** [comment]
This module isn't overtly complex.  The reason for explicit `$Script:` scope was at one point PowerShell wasn't behaving correctly, and the thought was the variable wasn't being properly scoped during import of the module.  So, all of the variables were scoped to `$Script:`, except for rare ocassions where `$Global:` was needed.  Most of the `$Global:` variables have moved to either `New-Variable -Option Constent` or simply a variable that points to a C# static property.

**Comment by FriedrichWeinmann** [comment]
Please, if you can don't reference by variable at all. Makes it really confusing within functions where some information came from. Accessing via .NET classes or using a helper class helps prevent a lot of confusion:
```powershell
Get-Constant -Name foo
```

**Comment by ChrisLynchHPE** [comment]
I don't understand.  We are talking about Variables.  99% of the variables with the `$Script:` scope are internal to the module, not exported to the PowerShell session, and have zero involvement from the script caller.  Developer, I get.  However, that is no different than using `string const` variables or class properties.  So I don't understand what you are trying to suggest here.

Also, looking at other projects, like Pester, the use of `$Script:` is used throughout their module.  So again, I don't understand why we are discussing this.

**Comment by FriedrichWeinmann** [comment]
Well …
for one thing, please don't use pester as a reference. It is a special case amongst special cases in the way it has to handle scopes. (Mind you, it's a brilliant module)
And I'm only looking at internal usage here.
I do PowerShell pretty much 100% of my at-customer time (and lot in my free time, as it is my main hobby). Most of the customer tasks involve fixing code, refactoring code or extending code. That is: I need to work with code others built.
Scope boundary violations are my greatest pain*: It makes it hard to track code logic, it makes it easy to break things, it costs a lot of extra time. Seeding a module with dozens of module scope variables makes it a lot harder for outsiders to come in and help.
As the dev who's dealt with it for years, you may not mind, if you can remember them.
But a new team member? May not have as much fun.
And public contributors will have a harder time (and may give up without bothering to help what they meant to help with after all).

*Scope Boundary Violation: Using a variable from an outside scope without passing it into a command as a parameter / argument.

**Comment by FriedrichWeinmann** [comment]
(Granted, given my constant exposure to that pain, I may have a few more emotions involved in it than may be warranted)

**Comment by ChrisLynchHPE** [comment]
> Scope Boundary Violation: Using a variable from an outside scope without passing it into a command as a parameter / argument.

I disagree here.  Almost all of the scoped variables we are talking about here are for URI purposes, or similar in nature to how Pester wrote their `Safe-Callers` hashtable code.  They will not be defined within a Cmdlet because they need to be __shared across__ Cmdlets.  So, no, this would not be a violation of scope boundary.  

Now, if you have a scoped variable (e.g. `$Scope:MyVar1`), and then within a Function/Cmdlet define another scoped variable (e.g. `$MyScope:MyVar`), that would be horrible design.  However, that is not the case within my module.  I mentioned above why `$Script:` scope was used, and I'm going through my module removing that scope reference as to avoid that style of confusion.  However, this discussion to me is almost no different than "spaces" or "tabs" topic.

**Comment by FriedrichWeinmann** [comment]
We'll have to agree to disagree on that aspect then :)
(Which is not an inherently bad thing)

**Comment by ChrisLynchHPE** [comment]
> As it is, changing any variables in any function is an incredible danger of breaking something.

And implementing a hashtable or enum lookup would be no different.  You change the dict or key name, you break other code.  So, not sure how that really saves or helps the code design.

Please do not get me wrong.  I do appreciate the dialog and someone else bringing experiences to the table.

**Comment by FriedrichWeinmann** [comment]
Example time:
Let's say there is a module variable called `$ResourceUrl` (A constant value the user should never directly interact with and should not change)
Functions `Get-Something`, `Set-Something`, `New-Something` and `Remove-Something` all use it directly.
The commands call each other (mostly `Get-` being called by the other commands).

Now, at a later time, Timmy, the new dev joins the team and adds a completely now command `Invoke-Mayhem` which has a _parameter_ called `$ResourceUrl` (he didn't notice the one in the module scope).
`Invoke-Mayhem` calls `Get-Something`, now he's puzzling why it's behaving a bit odd …

After figuring it out the issue, now he decides to rename the module variable to something less likely to overlap: `$HPE_ImageResourceUrl`, but misses how it is used in `Set-Something` but doesn't test it, since it is not part of his workflow.

Figuring out those interelations will always mean extra work.
If instead all commands had used `Get-Constant -Name ResourceUrl`, Timmy would never have encountered the issue. When inspecting `Get-Something` he could have followed the definition of `Get-Constant` to see where it got its information from. A helpful comment in `Get-Constant` would then have told him which script file(s) during import adds those to a static hashtable in your library or a single module scope variable.

Being explicit about being module scope using `$script:` would have also avoided the problem and probably been faster for Timmy to track as well.

I've been Timmy for years now.

**Comment by ChrisLynchHPE** [comment]
I get your point.  My point still stands.  The variables I use are Inter-Cmdlet, and none of the Cmdlet parameters overlap with variables set.  I have enforced that for the very reason you have articulated in your example.  Parameters need to be either very specific or generic enough to avoid variable overlap.

Also, `$Script:` and omitting that within either a PS1 or PSM1 is still scoped to `Script` implicitly.  The variables used in my module are set for the very reasons I have already explained above.

**Comment by FriedrichWeinmann** [comment]
I never argued against it currently working. I'm assuming it does.
But my point also stands: Anybody trying to change things will need to spend extra care and caution (and thus time) as they perform changes.
This increases cost (little for your own work, since you are very experienced with your layout, a lot more when somebody tries to touch it that is not) and reduces the likelihood of outside contribution.
Which is why I consider it technical debt (It is not something that currently breaks anything, but adds costs in the long term).

**Comment by FriedrichWeinmann** [comment]
Closing issue. It's been discussed and will likely not be done. Either way no point keeping it in plain view as an active 'issue' when there is no active discussion.
