### ISSUE TITLE
Get-HPOVBaseline fails with valid SPP version name

### ISSUE THREAD

**Issue by roberttco** [HewlettPackard/POSH-HPOneView#408]
After upload a baseline with the name MAS-SPP-GEN10-2019.06.20.D1.iso successfully, OneView 4.20 was queried.  The name includes a valid version per the SUM custom baseline instructions (https://support.hpe.com/hpsc/doc/public/display?docId=a00026608en_us
) utilizing a date plus a 2 character identifier.

### Expected Behavior
Get-HPOVBaseline returns the appropriate baseline information

### Actual Behavior
Get-HPOVBaseline  fails with an error

```powershell
ERROR: Cannot convert argument "3", with value: "2019.06.20.D1", for "Baseline" to type "System.Version": "Cannot convert value "2019.06.20.D1" to type "System.Version". Error: "Input string was not in a correct format.""
At: C:\Program Files\WindowsPowerShell\Modules\HPOneView.420\HPOneView.420.psm1, line 27031, char 7
```
### Steps to reproduce

1. Successfully upload a baseline with the name MAS-SPP-GEN10-2019.06.20.D1.iso (using the actual file name MAS-SPP-GEN10-2019_06_20_D1.iso and Add-HPOVBaseline)
2. Invoke Get-HPOVBaseline

### Version Information
Library version: 4.20.2068.2204
OV version: 4.20.01.01

The error seems to be fairly straightforward; the version format as described by the SUM instructions is not compatible with the version object since the last value has a non-numeric value.  This is a regression from the 4.00 library's behavior (version 1820.2663) where we did not have any issues and no code changes have been made - just a change to the 4.20 library against a 4.20 OV appliance.  A related close issue (https://github.com/HewlettPackard/POSH-HPOneView/issues/371) does not apply here because we are using a valid version string per the SUM instructions and a version scheme we have used for many releases.

The OV support dump is available however I don't think that is necessary for this issue.

**Comment by ChrisLynchHPE** [comment]
The library currently employs [Semantic Versioning practices](https://semver.org/), which HPSUM violates.  The `D` in the version string is the violation.  This is to conform to the Microsoft provided [`System.Version`](https://docs.microsoft.com/en-us/dotnet/api/system.version?view=netframework-4.6) class, which is based on Semantic version values.

This change was introduced in the 4.10 library.

**Comment by jullienl** [comment]
FYI, the same issue also affects `add-HPOVBaseline`

**Comment by ChrisLynchHPE** [comment]
The Baseline needs to be in a Semantic Version, and one that conforms to the `System.Version` class.  That means, no string characters in the value.  

However, @jullienl the Add-HPOVBaseline is a Cmdlet that returns an Async task.  It does not return the uploaded SPP or hotfix object.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
