### ISSUE TITLE
Regression in Get-HPOVStoragePool

### ISSUE THREAD

**Issue by emcmillan** [HewlettPackard/POSH-HPOneView#41]
The documentation states that "Get-HPOVStoragePool" with no parameters should return all the storage pools in the appliance, and this worked fine in 1.20.0112.  However, in 1.20.240 it fails:

[HPONEVIEW] Get-HPOVStoragePool
The variable cannot be validated because the value  is not a valid value for the poolName variable.
At C:\users\mcmillan\documents\2xc-automation\ci\common\HPOneView.120\HPOneView.120.psm1:9873 char:3
+         $poolName = $poolName -replace ("[*]","%25") -replace ("[&]","%26")
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure

**Comment by ChrisLynchHP** [comment]
This is a parameter value enumeration issue.  This will be fixed in an update being published today.

**Comment by ChrisLynchHP** [comment]
This issue was fixed in 45d55246b6ae5609e0baae4e2f4c786fcd295387 (Release 1.20.255.0. Closing.
