### ISSUE TITLE
Remove-HPOVBaseline Fails when using a string input

### ISSUE THREAD

**Issue by BrandonBlankHPE** [HewlettPackard/POSH-HPOneView#410]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Remove-HPOVBaseline should take a string value for -InputObject which is the string name of the baseline ISO file name. Once provided, Remove-HPOVBaseline should prompt for confirmation to remove the expected baseline.

### Actual Behavior
Remove-HPOVBaseline fails when calling Get-HPOVBaseline with the following error;

Remove-HPOVBaseline : Cannot validate argument on parameter 'File'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:1 char:1

### Steps to reproduce

```PowerShell
# 1. Call Remove-HPOVBaseline using an existing ISO file name string which is already loaded in OneView as the value for -InputObject
```

### Version Information
HPOneView.400, OV 4.00.11.360315.00

**Extra note**
This was found in the Azure Stack team while updating our SPP version strings to conform to the next expected versioning.
It seems that the issue is with the following line in Remove-HPOVBaseline:
$InputObject = Get-HPOVBaseline  -File $_HotFix -ApplianceConnection $_appliance -ErrorAction SilentlyContinue

In this case, $_HotFix does not exist. It seems this line and the lines following it are copy/paste from New-HPOVCustomBaseline and weren't updated for Remove-HPOVBaseline to correct $_HotFix not existing.

**Comment by ChrisLynchHPE** [comment]
Please use the following as the supported method of removing baselines:

`Get-HPOVBaseline -Name BaselineName | Remove-HPOVBaseline`

I will update the user docs to reflect the correct usage.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
