### ISSUE TITLE
Support Question

### ISSUE THREAD

**Issue by albvar** [HewlettPackard/POSH-HPOneView#412]
Server Profiles > <myserver> > Bios Settings I can view Inconsistent configurations.
Is there an Inconsistent flag and or a way to retrieve what is inconsistent via the POSH commands?
Thanks in advance.

![image](https://user-images.githubusercontent.com/10334630/63473945-49b69200-c445-11e9-9f8b-cc51e2d0744b.png)

**Comment by ChrisLynchHPE** [comment]
You can use the [`Update-HPOVServerProfile -WhatIf`](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Update-HPOVServerProfile) Cmdlet call.  It will return an object with the diff of the profile to associated profile template.

**Comment by albvar** [comment]
Thanks for the quick reply. It seems like this only works if the profiles are tied to a base template which doesn't appear to be my case.
![image](https://user-images.githubusercontent.com/10334630/63520614-ff73f600-c4c2-11e9-9d3e-e3e53ec75bd8.png)

**Comment by ChrisLynchHPE** [comment]
Ah, I misunderstood your question.  If you wanted to compare the server hardware actual versus what is within the server profile, you can use this script code:

```PowerShell
#  Get the server profile in question
$ServerProfile = Get-HPOVServerProfile -Name MyProfile

# Get the associated server resource
$Server = Get-HPOVServer -InputObject $ServerProfile

# Get the BIOS settings of the server in question
$CurrentBiosSettings = Send-HPOVRequest -Uri ($Server.uri + '/bios')

# Now, compare the settings
$BiosSettingsDiffCol = [System.Collections.ArrayList]::new()

ForEach ($setting in $ServerProfile.bios.OverriddenSettings)
{

    # Setting is different
    if (($CurrentBiosSettings.currentSettings | ? id -eq $setting.id).value -ne $setting.value)
    {

        $diff = [PSCustomObject]@{
            serverProfileName   = $ServerProfile.name;
            serverHardwareName  = $Server.name;
            id                  = $setting.id;
            serverProfileValue  = $setting.value;
            serverHardwareValue = ($CurrentBiosSettings.currentSettings | ? id -eq $setting.id).value
        }

        [void]$BiosSettingsDiffCol.Add($diff)

    }

}

# Show the results
$BiosSettingsDiffCol | Format-Table
```

Here is an example of the output:
``` powershell


serverProfileName serverHardwareName id                      serverProfileValue serverHardwareValue
----------------- ------------------ --                      ------------------ -------------------
MyProfile         172.18.6.29        PowerProfile            MaxPerf            BalancedPowerPerf
MyProfile         172.18.6.29        PowerRegulator          StaticHighPerf     DynamicPowerSavings
MyProfile         172.18.6.29        MinProcIdlePower        NoCStates          C6
MyProfile         172.18.6.29        MinProcIdlePkgState     NoState            C6Retention
MyProfile         172.18.6.29        IntelQpiPowerManagement Disabled           Enabled
MyProfile         172.18.6.29        EnergyPerfBias          MaxPerf            BalancedPerf

```

**Comment by albvar** [comment]
Thank you for helping me out, this gives me what I needed. 
Thanks for the work you do in this space, HP is lucky to have you.
I had to change one thing (could be that I am using HPOOneView.300)

``
$Server = Get-HPOVserver -Name (Send-HPOVRequest $ServerProfile.serverHardwareUri).Name

$ServerProfile.GetType() was returning a PSCustomObject and -InputObject was expecting a different type.

**Comment by ChrisLynchHPE** [comment]
Please look to upgrade your PowerShell library and OneView instance ASAP.  3.00 has not been supported in a few years.

But glad you have a solution.
