### ISSUE TITLE
New-HPOVUplinkSet (ver 5.00) creates Ethernet uplinks with different “LACP load balancing” values

### ISSUE THREAD

**Issue by nightzone** [HewlettPackard/POSH-HPOneView#417]
### Expected Behavior

Add option to New-HPOVUplinkSet  cmdlet to configure “LACP load balancing”   

### Actual Behavior

New-HPOVUplinkSet     creates Ethernet uplinks with “LACP load balancing” equal to “None”.
To be more precise, my script creates 3 uplinks (two FCoE and one Eth). 
One uplink (first FCoE) created with “LACP load balancing” = “Source & Destination MAC Address”
And two uplinks (FCoE and Eth) created with “LACP load balancing” = “None”
I use same commands, at least for FCoE (why “LACP load balancing” values different I don’t know)

### Steps to reproduce
DCS 5.00

New-HPOVUplinkSet     creates Ethernet uplinks with “LACP load balancing” equal to “None”.
To be more precise, my script creates 3 uplinks (two FCoE and one Eth). 
One uplink (first FCoE) created with “LACP load balancing” = “Source & Destination MAC Address”
And two uplinks (FCoE and Eth) created with “LACP load balancing” = “None”
I use same commands, at least for FCoE (why “LACP load balancing” values different I don’t know)

If I create it manually from GUI – there are no “None” option and by default “Source & Destination MAC Address” selected.
I didn’t find option to set “LACP load balancing” using New-HPOVUplinkSet   commandlet

Because of this issue ( or not ), my Eth and FCoE uplinks created with “None” didn’t link up and I have to recreate it.
After that my LI was inconsistent  with LIG because of “LACP load balancing” setting (have to change this setting in LIG).
Additionally my LE was inconsistent with EG (just cleared this alert, because it not shows any difference).

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  

10.72.14.13                         LibraryVersion Path                                                                  
-----------                         -------------- ----                                                                  
ApplianceVersion: 5.00.00.400525.00 5.0.2152.1665  C:\Program Files\WindowsPowerShell\Modules\HPOneView.500\5.0.2152.1665
```PowerShell
# Output from $PSVersionTable

Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.17763.592                                                                                                                             
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.17763.592                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1       
````

**Comment by ChrisLynchHPE** [comment]
This is enhanced in the [Release 5.0.2226.2609](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.0.2226.2609) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2226.2609).

Please verify before this issue is closed.

**Comment by nightzone** [comment]
Just tested it. 
All networks created as expected and environment green.
Issue fixed.
