### ISSUE TITLE
When I try get-hpovserverprofiletemplate no getting Ilo setting info

### ISSUE THREAD

**Issue by ajayvaaka** [HewlettPackard/POSH-HPOneView#418]
# get-hpovserverprofiletemplate to pull ilo setting details oneview 4.20 & 5.00

## Expected Behavior
get-hposerverprofiletemplate should pull ilo setting info

## Actual Behavior
get-hposerverprofiletemplate is not pulling ilo setting info 

## Request
can you guide me how to retrieve ilo setting info on server profile template?

**Comment by DungKHoang** [comment]
If you are talking about the iLO settings in server profile/template, they are located under
the managementProcessor attribute of the profile/template object
Dung

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you feel this is in error, please feel free to re-open this issue.
