### ISSUE TITLE
New-HPOVServerProfile integrated SAS controller

### ISSUE THREAD

**Issue by LeonKNL** [HewlettPackard/POSH-HPOneView#419]
Hello when i run : 

```PowerShell
New-HPOVServerProfile -Name $name -Description $description -AssignmentType Server -Server $server -ServerProfileTemplate $spt
```
I get the following error:

```PowerShell
New-HPOVServerProfile : The selected server hardware does not appear to have an integrated SAS controller.
At line:15 char:1
+ New-HPOVServerProfile -Name $name -Description $description -Assignme ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (AsyncronousTask:String) [New-HPOVServerProfile], ServerProfileResourceException
    + FullyQualifiedErrorId : InvalidOperation,New-HPOVServerProfile
```

If i create a profile (from template) and i apply it to server hardware, the ui gives a warning and i am able to continue.

Is there a way to let powershell continue and ignore this error?

**Comment by ChrisLynchHPE** [comment]
The error you are getting is returned from the API, which is rejecting the request to create a server profile for that server resource.  Are you sure you are trying to use the same server resource via PowerShell as you are with the UI?  Can you provide the generated log file from using the following:

```PowerShell
Get-HPOVCommandTrace -ScriptBlock { New-HPOVServerProfile -Name $name -Description $description -AssignmentType Server -Server $server -ServerProfileTemplate $spt }
```

**Comment by LeonKNL** [comment]
I used the same template as in the UI. As i did not had time on my side, i decided to use the ui instead of powershell. So issue can be closed, if i even run into this problem again, i'll let you know.

**Comment by ChrisLynchHPE** [comment]
The issue isn't with the Server Profile Template, but the server hardware resource you are trying to create a profile for.  As I stated, the error you are getting is from the API, which is stating the server hardware resource does not contain a controller.  And you are saying that you were able to create the server profile for the specific server you attempted via the Cmdlet?  I would not expect that behavior, as the UI is an API client just like the PowerShell library is.

**Comment by SecondView** [comment]
I ran into the same issue, executing the following PS commandlets:
>> Get-HPOVServer -Name "ilo-DL380Gen10OV" | New-HPOVServerProfile -name "ESXi for Automation" -ServerProfileTemplate "Hypervisor“

Executing the above syntax to a blade server works, with a DL380Gen10 I get the following error on command line:
New-HPOVServerProfile : The selected server hardware does not appear to have an integrated SAS controller.

To work around the issue I used the PS commandlet "New-HPOVServerProfileAssign" to assign/unassign an existing profile to the DL server:
Get-HPOVServerProfile -name "ESXi for automated Rollout" | New-HPOVServerProfileAssign -Server "ilo-DL380Gen10OV"

**Comment by ajayvaaka** [comment]
**********************
Windows PowerShell transcript start
Start time: 20200727195412
Username: xxxxx
RunAs User: xxxxx
Machine: xxxxxx (Microsoft Windows NT 6.3.9600.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\avaaka\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\xxx\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Normal' -LogPath 'c:\Users\xxxx\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1595875748-eebbcefb-057f-4284-9ce5-c1b2e97e5fa11595862439541\EditorServices.log' -SessionDetailsPath 'c:\Users\avaaka\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-4928-243120' -FeatureFlags @() 
Process ID: 5204
PSVersion: 5.1.14409.1012
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14409.1012
BuildVersion: 10.0.14409.1012
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
PS>TerminatingError(New-HPOVServerProfile): "The selected server hardware does not appear to have an integrated SAS controller."
New-HPOVServerProfile : The selected server hardware does not appear to have an integrated SAS controller.
At C:\ESXAutoloader\ESXAutoloader\Functions\Private\All-Purpose\New-OVServerProfile.ps1:78 char:88
+ ... rhardware | New-HPOVServerProfile -name $serverprofile -ServerProfile ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (AsyncronousTask:String) [New-HPOVServerProfile], 
ServerProfileResourceException
    + FullyQualifiedErrorId : InvalidOperation,New-HPOVServerProfile
**********************
Windows PowerShell transcript end
End time: 20200727195417
**********************

**Comment by ajayvaaka** [comment]
@ChrisLynchHPE ,

I faced the same issue today on OV5.20 environment (5.20.2422.3962 :HPOneView.520 module) .

Thanks
Ajay Vaaka

**Comment by ChrisLynchHPE** [comment]
This is not related to the library. Please do an EFuse to the server, power it on and let it POST successfully once. Then try again.

**Comment by spatel0816** [comment]
I am getting this issue on DLs, how do we resolve it?

New-HPOVServerProfile : The selected server hardware does not appear to have an integrated SAS controller.

**Comment by ChrisLynchHPE** [comment]
This is caused by the SA controller not registering with the iLO correctly.  You need to do one of the following:

1. Reboot the iLO
2. Look for update SA controller firmware
3. Physically reseat the controller
