### ISSUE TITLE
POSH 2.0?

### ISSUE THREAD

**Issue by tlauder** [HewlettPackard/POSH-HPOneView#42]
Hi Team,

I was just wondering about the ETA for POSH 2.0, since OneView 2.0 is now out and it seems the 1.20 libraries like to throw errors all over the place :)

Thanks!
Todd

**Comment by ChrisLynchHP** [comment]
We are still working on the 2.0 library.  I don't have an ETA at this point.  We have performed regression testing of the 1.20 library with a 2.0 appliance, and there is still one outstanding issue with Wait-HPOVTaskStart and Wait-HPOVTaskComplete.  What issues are you running into?

**Comment by tlauder** [comment]
Hi Chris,

I have a setup-oneview script that errored all over the place. Here is one snipet:

PowerCLI D:\PowerShell\OneViewScripts> New-HPOVNetwork -type Ethernet -Name "TUNNEL-A" -vlanid 0 -VLANType Tunnel -purpose General
Creating Ethernet Network TUNNEL-A
[Send-HPOVRequest]: Authorization error: User not authorized for this operation..  Request was 'POST' at '/rest/ethernet-networks'.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.120\HPOneView.120.psm1:1879 char:33
+                                 Throw $errorRecord
+                                 ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (Send-HPOVRequest:String) [], AuthPrivilegeException
    + FullyQualifiedErrorId : InsufficientPrivilege

And I'm logged in with Administrator which is an Infrastructure administrators.

Thanks,
Todd

**Comment by ChrisLynchHP** [comment]
We certainly have not experienced or seen that, as internal testers use the 1.20 library to setup and configure an appliance.  Can you do your call again, but include –verbose and provide the output?

**Comment by tlauder** [comment]
see below:

VERBOSE: [NEW-HPOVLDAPGROUP] Processing Server administrator
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:

Key   : uri
Value : /rest/logindomains/grouptorolemapping

Key   : method
Value : POST

Key   : body
Value : {credentials, group2rolesPerGroup, type}



VERBOSE: [SEND-HPOVREQUEST] SSLCheckFlag: True
VERBOSE: [SEND-HPOVREQUEST] Requested URI: /rest/logindomains/grouptorolemapping
VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [RESTCLIENT] Bound PS Parameters:
Key    Value
---    -----
method POST
uri    /rest/logindomains/grouptorolemapping


VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for POST https://gissappovw01/rest/logindomains/grouptorolemapping
VERBOSE: [SEND-HPOVREQUEST] Body object found. Converting to JSON.
VERBOSE: [SEND-HPOVREQUEST] Request Body: {"credentials":{"password":"passwordhere","userName":"usernamehere"},"group2rolesPerGroup":{"egroup":"OperGroup","loginDomain":"domain.com","type":"Group2RolesMappingPerGroupDto","roles":["Server
administrator"]},"type":"Group2RolesMappingPerGroupValidationDto"}
VERBOSE: [SEND-HPOVREQUEST] Request: POST https://gissappovw01/rest/logindomains/grouptorolemapping
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 120
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = 5BjyR4TgWbsqMPC4l0khwhG0nQkM1BdD
VERBOSE: [SEND-HPOVREQUEST] Request Header 7: Host = gissappovw01
VERBOSE: [SEND-HPOVREQUEST] Net.WebException Error caught
VERBOSE: [SEND-HPOVREQUEST] ERROR RESPONSE:

data               :
errorCode          : AUTHORIZATION
details            : User not authorized for this operation.
errorSource        :
nestedErrors       : {}
recommendedActions : {Please verify your credentials and re-authenticate before attempting the operation again.}
message            : Authorization error: User not authorized for this operation.



VERBOSE: [SEND-HPOVREQUEST] Response Status: HTTP 401 [Unauthorized]
VERBOSE: [SEND-HPOVREQUEST] Response Header: Vary = Wed, 28 Oct 2015 16:55:43 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header: Content-Encoding = 1.1 gissappovw01.pharma.aventis.com
VERBOSE: [SEND-HPOVREQUEST] Response Header: Keep-Alive =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Connection =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Transfer-Encoding =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Cache-Control =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Content-Type =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Date =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Via =
VERBOSE: [SEND-HPOVREQUEST] HTTP 401 error caught.
VERBOSE: [SEND-HPOVREQUEST] Authorization error: User not authorized for this operation. Request was 'POST' at
'/rest/logindomains/grouptorolemapping'.
VERBOSE: [NEW-ERRORRECORD] Building ErrorRecord object
[Send-HPOVRequest]: Authorization error: User not authorized for this operation..  Request was 'POST' at '/rest/logindomains/grouptorolemapping'.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.120\HPOneView.120.psm1:1879 char:33
+                                 Throw $errorRecord
+                                 ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (Send-HPOVRequest:String) [], AuthPrivilegeException
    + FullyQualifiedErrorId : InsufficientPrivilege

**Comment by ChrisLynchHP** [comment]
Can you provide your config sample script?  Did you accept the EULA first prior to performing any other operations?  If you did not, then 401 is the correct error response, as the EULA needs to be accepted first prior to any other operations against a brand new appliance.

**Comment by tlauder** [comment]
Hi Chris,

How can I send it privately? Rather not post it for anyone to view (corp stuff in it).

Thanks,
Todd

**Comment by ChrisLynchHP** [comment]
You can send it to me directly to chris dot lynch (at) hpe dot com.

**Comment by ChrisLynchHP** [comment]
I have posted the 2.00 PowerShell library update.  It is not 100% parity with the 1.20 library, and I will track the progress in an issue I will open.
