### ISSUE TITLE
New-HPOVRestore only uploads a backup to synergy oneview.

### ISSUE THREAD

**Issue by sinelshchikov** [HewlettPackard/POSH-HPOneView#421]
New-HPOVRestore does not initiate restore of an appliance  and only uploads a backup to oneview.

### Expected Behavior
PS C:\scripts> New-HPOVRestore -ApplianceConnection $Connection1 -FileName $Backup -Confirm:$false -ErrorAction Stop

Output: "Appliance restore in progress.  All users are now logged off."

### Actual Behavior

PS C:\scripts> New-HPOVRestore -ApplianceConnection $Connection1 -FileName $Backup -Confirm:$false -ErrorAction Stop
PS C:\scripts>

### Steps to reproduce

```PowerShell
Import-Module HPOneView.500

$Connection1 = Connect-HPOVMgmt -appliance 10.1.0.101 -user Administrator -password password
$Backup = "C:\scripts\backup01.bkp"

New-HPOVRestore -ApplianceConnection $Connection1 -FileName $Backup -Confirm:$false -ErrorAction Stop 

```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):

5.0.2152.1665  

HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  

5.00.00.400525.00

Output from `$PSVersionTable` on your Windows Host:

```PowerShell
# Output from $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by ChrisLynchHPE** [comment]
The API changed in 5.00 and broke the Cmdlet.  I have a fix for this issue, and will be in the next update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release ##](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.0.2226.2609) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2226.2609).

Please verify before this issue is closed.

**Comment by sinelshchikov** [comment]
Verified, please close.
