### ISSUE TITLE
New-HPOVSnmpTrapDestination does not have ApplianceConnection attribute

### ISSUE THREAD

**Issue by olant** [HewlettPackard/POSH-HPOneView#424]
Unlike other POSH CMdlets I cannot pass an ApplianceConnection attribute to New-HPOVSnmpTrapDestination

**Comment by ChrisLynchHPE** [comment]
That Cmdlet is a helper Cmdlet to create an SNMP trap destination for Logical Interconnect Groups, Logical Interconnect resources only.  If you are trying to configure an appliance SNMP trap destination, then you need to use [New-HPOVApplianceTrapDestination](https://github.com/HewlettPackard/POSH-HPOneView/wiki/New-HPOVApplianceTrapDestination)

**Comment by olant** [comment]
Thanks Chris!
