### ISSUE TITLE
Get Running and Pending Jobs list

### ISSUE THREAD

**Issue by guidojones** [HewlettPackard/POSH-HPOneView#426]
IT appears that Get-HPOVAlert doesn't work with AlertState of Running or Pending.
How can I get a list of Running and Pending jobs

**Comment by ChrisLynchHPE** [comment]
HPE OneView "jobs" are not alerts, they are tasks.  [Get-HPOVTask](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Get-HPOVAlert) is the Cmdlet you want to use.

Sample code:

```PowerShell
# Get pending tasks
Get-HPOVTask -State Pending

# Get running tasks
Get-HPOVTask -State Running
```

**Comment by guidojones** [comment]
Ok,

The numbers don't line up with what I see in in activity (GUI). I see a lot of jobs Name: Manage utilization owned by System from OneView, but these don't show up in the GUI.

What I'm looking to do is we've had issues where jobs get "stuck" and are either in the running or pending state for days. At that point we need to restart the appliance to clear things up. I want to know this proactivly, not when other user jobs are hung waiting.

**Comment by ChrisLynchHPE** [comment]
That's because the UI hides certain tasks.  If you have tasks that are in a pending or running state for days, please open a support case to examine why that is happening.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.
