### ISSUE TITLE
Edit Logical Interconnect uplink networks

### ISSUE THREAD

**Issue by neocox** [HewlettPackard/POSH-HPOneView#430]
In the GUI interface I can edit a logical interconnect and add a network to a Uplink. How can I do this with the module? 

It is true that I could update the Logical Interconnect from the Logical Interconnect Group, but I would like to be able to edit the Logical Interconnect uplink networks with the module as I can with the GUI.

Thank you!

**Comment by ChrisLynchHPE** [comment]
Set-HPOVUplinkSet is the Cmdlet you want to use.  However, it appears that it is not an exported function in either the 4.20 or 5.00 libraries.  That will need to be fixed.

**Comment by neocox** [comment]
Is it already solved in the 4.20 branch? Thank you.

**Comment by ChrisLynchHPE** [comment]
Not yet.  I just published an updated 5.00 library that adds the Cmdlet.  I'll need to backport it to the 4.20 library.  And it isn't an easy copy and paste backport.  I had to do some re-work to reduce duplicated code between a number of other Cmdlets.

**Comment by Sergong** [comment]
Hi, I have the Set-HPOVUplinkSet commandlet available in version 5.0.2368.2592 of the 500 module. However I can't find any documentation on how to use it.
When I try something like:
Set-HPOVUplinkSet -UplinkSetName "MyUplink' -AddNetwork $Networks 

It says it needs an InputObject? When I pass it the same $Networks array of networks I want to add, it says [string] is an unsupported data type. Only [system.string] or [PSCustomObject] Network Set resources are allowed.

So documentation or any help on how to use this commandlet would be helpful.

-Edit
Sorry I didn't realise the Help files hadn't downloaded yet. I managed to make it work with the provided examples in the PowerShell help files for the module.
I did notice this commandlet is not documented on the GitHub site for the module though.

Thanks!

**Comment by ChrisLynchHPE** [comment]
The `-InputObject` parameter is either a Logical Interconnect Group (where the `-UplinkSetName` is required) or an Uplink Set that is provisioned to a Logical Interconnect (using the `Get-HPOVUplinkSet` Cmdlet.)

The Cmdlet is documented within the offline help.

**Comment by neocox** [comment]
> Not yet. I just published an updated 5.00 library that adds the Cmdlet. I'll need to backport it to the 4.20 library. And it isn't an easy copy and paste backport. I had to do some re-work to reduce duplicated code between a number of other Cmdlets.

OK thanks Chris. Do you have an estimation of when this functionality will be available in 4.20?  We have OneView 5.x on roadmap but it will not launch until after the summer.

**Comment by ChrisLynchHPE** [comment]
Unfortunately, there will be no planned updates to the 4.20 library at this time.  Please update to a 5.x release in order to utilize the newer Cmdlets.  Will you be able to update to the 5.x release anytime soon?  If not, then I could look at backporting the Cmdlet in best effort.

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

Closing.
