### ISSUE TITLE
Get-HPOVServerProfile / Convertto-HPOVPowershellscript / Option for MAC/WWN

### ISSUE THREAD

**Issue by Georgimi** [HewlettPackard/POSH-HPOneView#432]
We had two customers trying to copy their environement to a second datacenter. They want it to be identical. Including MAC and WWNs. The second datacenter is pure standby.

They used the import/export scripts until they got obsolete and were looking into the converttopowershellscript cmdlet. This is a great option to get all those information. 

But we are lacking an option to get our own MACs and WWNs in there.

**Comment by ChrisLynchHPE** [comment]
The ConvertTo-HPOVPowerShellScript does not "backup" the assigned MAC or WWN values within the Profile.  It is to re-create the profile using the appropriate Cmdlet calls based on the parsed object.

The Import-Export scripts are not obsolete, and were moved to [here](https://github.com/DungKHoang/Import-Export-OneView-Resources).

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
