### ISSUE TITLE
Where do I find the MAC and WWN's 

### ISSUE THREAD

**Issue by guidojones** [HewlettPackard/POSH-HPOneView#433]
I started with the sample script "Get-BladeSystemInventory.ps1". It runs without error, but output file "Connections" is blank.

Is there documentation somewhere I can get that will point me in the correct direction ?

- Thanks

**Comment by matthewjones2381** [comment]
Hey,

Not sure what's in your script there.... but I use the command "Get-HPOVServerProfileConnectionList" gives you a list of all profiles and associated WWPN's and MAC addresses.

Hope this helps.
M

**Comment by guidojones** [comment]
Thanks,
Unfortunately I need to get the WWN's from the hardware, not the profile. In our environment we are not using Virtual Connect. We are using Brocade FC switches. As such the WWN's are not in the profile.

**Comment by DungKHoang** [comment]
Try Get-HPOVServer  as follow:
$s = Get-HPOVServer -name 'Frame1, Bay 1'   # as an example
foreach ($port in $s.portMap.deviceSlots)
{
     foreach ($pp in $port.PhysicalPorts)
     {
      $MAC = $pp.mac
      $WWNN  = $pp.wwn
      "MAC is --> $MAC, WWNN is --->$WWNN"
      }
}

**Comment by guidojones** [comment]
Thanks. That's exactly the information I was looking for.
Works great !
