### ISSUE TITLE
Cancel Firmware Update

### ISSUE THREAD

**Issue by matthewjones2381** [HewlettPackard/POSH-HPOneView#436]
Hello,

I have a stuck firmware update on a Synergy frame (specifically the vSAN module) and I was wondering if there was a way to terminate the update via the HP POSH from the back end. I've had a dig and I can't see anything obvious.

Appreciate any help offered. Thanks!

**Comment by ChrisLynchHPE** [comment]
You should be able to use the following:

```powershell
# Get the currently running task
$task = Get-HPOVServerProfile -Name "My VSAN Node 1" | Get-HPOVTask -State Running

# Check if the task can be cancelled
if ($task.IsCancellable) {

    # Now request to cancel it
    Send-HPOVRequest -Uri $task.uri -Method PATCH
    
}

else {

   # Task cannot be cancelled. Maybe have other logic to do something else here.

}
```

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
