### ISSUE TITLE
New-HPOVServerProfile of BL460 G7 not possible - UnsupportedBootMode

### ISSUE THREAD

**Issue by andrevdn** [HewlettPackard/POSH-HPOneView#437]
Function fails with errorCode=UnsupportedBootMode when creating a new profile for a BL460 G7 
Message=The specification of the boot mode for this server hardware type is not supported.

**Conform Oneview documentation:**
Boot mode settings to be configured on the server.
For Gen 7 and Gen 8 servers these values should not be specified

The BootMode is not null in the final HPOV Request. There is no option / specific function parameter to prevent BootMode from being set.

This function doesn't fail with HPOV 4.20.

**Comment by ChrisLynchHPE** [comment]
Can you please provide the output from `$PSLibraryVersion` and `$PSVersionTable`?

**Comment by andrevdn** [comment]
`PS M:\> $psversiontable

Name                           Value                                                                                                                                                     
PSVersion                      5.1.17763.771                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                   
BuildVersion                   10.0.17763.771                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                                   

PS M:\> $PSLibraryVersion

hpov-cp99.wurnet.nl                 LibraryVersion Path                                           
ApplianceVersion: 5.00.01.410269.00 5.0.2226.2609  D:\Powershell\Bindings\GitModules\HPOneview.500
`

**Comment by ChrisLynchHPE** [comment]
Is this still an issue?  As I don't have Gen7 servers to test with, it is difficult to identify this issue.  If you do, please use the Get-HPOVCommandTrace or Get-OVCommandTrace to capture the output from the New-HPOVServerProfile or New-OVServerProfile Cmdlet.  As an example:

```powershell
# Cmdlet Noun changed in the 5.30 library releases
Get-OVCommandTrace -ScriptBlock { New-OVServerProfile @ParameterHash }
```

**Comment by andrevdn** [comment]
Hi
It's not an issue for us. The last 2 Gen7's will be gone within a month.
Regards,
André

**Comment by ChrisLynchHPE** [comment]
Thanks.  Closing.
