### ISSUE TITLE
Unable to specify multiple scopes when using Add-HPOVServer

### ISSUE THREAD

**Issue by ghost** [HewlettPackard/POSH-HPOneView#438]
### Expected Behavior
Get-Help Add-HPOVServer shows this for the -Scope parameter:

-Scope `[<Array>`]
        Provide an array of <HPOneView.Appliance.ScopeResource> Scope resource(s) to initially add.

Required? false
Position? named
Default value
Accept pipeline input? false
Accept wildcard characters? false

To me, this suggests I can specify multiple scopes when adding a server.  Hopefully, this is just a blunder on my part not fully understanding how to specify the array (see below).

### Actual Behavior
When I try to add specify multiple scopes I get an error:

Add-HPOVServer : Cannot process argument transformation on parameter 'Scope'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type "HPOneView.Appliance.ScopeCollection".
At line:1 char:97

### Steps to reproduce
Add-HPOVServer -ApplianceConnection $Conn -Hostname "SERVERILO" -Credential $ILOCred -Scope $Scope1, $Scope2 -Monitored:$true

Maybe this is just my misunderstanding of how to specify multiple objects to the parameter.  I also tried specifying an actual array of scopes, but I get the same error.

($Scopes is array of scope object that I obtained using the Get-HPOVScope cmdlet with a where-object to filter the results.)

Add-HPOVServer -ApplianceConnection $Conn -Hostname "SERVERILO" -Credential $ILOCred -Scope $Scopes -Monitored:$true

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`): 5.0.2226.2609
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  5.00.00.400525.00
Output from `$PSVersionTable` on your Windows Host: 5.1.14409.1018

**Comment by ghost** [comment]
Not sure what is going on, but I updated my original post to show this:
-Scope [<Array>]
        Provide an array of <HPOneView.Appliance.ScopeResource> Scope resource(s) to initially add.

But, it still shows my old version...

**Comment by ghost** [comment]
LOL - it keeps removing "Array" from inside the [] in my post.

**Comment by ghost** [comment]
Apologies, I guess I need to freshen up on my Markdown...need to escape out the brackets.

**Comment by ChrisLynchHPE** [comment]
Yes, this is a bug.  The parameter type is missing the `[]` so the parameter type needs to be `HPOneView.Appliance.ScopeResource[]`.  Alternatively, you can add the server to one scope duruing the Add call, then use [Add-HPOVResourceToScope](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Add-HPOVResourceToScope) Cmdlet to add the server to other scopes.

**Comment by ghost** [comment]
Thanks!
NK

**Comment by ChrisLynchHPE** [comment]
This was already addressed in an updated 5.00 library update.

Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
