### ISSUE TITLE
HPOneView.500 complains about too old .net even though the latest is installed

### ISSUE THREAD

**Issue by mstreibe** [HewlettPackard/POSH-HPOneView#440]
On a system with multiple .net versions, one being older than 4.7.2, but the other being the latest 4.8, HPOneView.500 does not load and complains it is missing the required .NetFramework 4.7.2 client.

I checked the code in HPOneView.500.psm1, and it seems it is expecting only one value being returned from this command in line 33:

Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\' |  Get-ItemPropertyValue -Name Release

However, the system where it is throwing the error, returns two values:

461308 (older version)
528049 (4.8)

According to the MS documentation, Get-ChildItem will display subkeys from the specified registry key, not the key itself, see

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_registry_provider?view=powershell-6

"Each registry key can also have subkeys. When you use Get-Item on a registry key, the subkeys are not displayed. The Get-ChildItem cmdlet will show you children items of the "Spooler" key, including each subkey's properties. The parent keys properties are not shown when using Get-ChildItem."

So I think the script should be using Get-Item instead of Get-ChildItem, or continue to use Get-ChildItem but then it should be able to handle multiple numbers.

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting this.  You are correct in that Get-ChildItem was recursively getting properties when multiple .NetFramework Client languages were installed.  This will be fixed in the next library update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 5.0.2295.3359](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.0.2295.3359) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2295.3359).

Please verify before this issue is closed.

**Comment by mstreibe** [comment]
I can't test it right now because I have no access to a system with multiple .net versions, however I can't find any change in the respective code. It is still using Get-ChildItem and is still handling only one number. Please check.

**Comment by ChrisLynchHPE** [comment]
Hmmm...  I made that change, and for some reason it was lost.  As I do not have any systems to test with, it was missed.  I will release a new version with this corrected.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release5.00.2341.1920](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.00.2341.1920) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2341.1920).

Please verify before this issue is closed.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
