### ISSUE TITLE
New-HPOVStorageVolumeTemplate

### ISSUE THREAD

**Issue by mleach8948** [HewlettPackard/POSH-HPOneView#441]
### Expected Behavior
Correctly build a StorageVolumeTemplate.

When running:  New-HPOVStorageVolumeTemplate -Capacity 100 -Name SVT-3PAR-Shared-1 -ProvisionType Thin -StoragePool CPG-SSD -Shared -SnapshotStoragePool CPG-SSD -StorageSystem ThreePAR-1

### Actual Behavior

We are getting an exception:
New-HPOVStorageVolumeTemplate : Cannot process argument transformation on parameter 'StoragePool'. Cannot convert the "CPG-SSD" value of type "System.String" to type "HPOneView.Storage.StoragePool".

### Steps to reproduce
Run command above when a 3PAR is correctly attached (in this case I was using a DCS).

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):

gold-1.demo.local                   LibraryVersion Path                                                                  
-----------------                   -------------- ----                                                                  
ApplianceVersion: 5.00.00.400525.00 5.0.2152.1665  C:\Program Files\WindowsPowerShell\Modules\HPOneView.500\5.0.2152.1665

HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  
Output from `$PSVersionTable` on your Windows Host:

### Output from $PSVersionTable
Name                           Value                                                                      
----                           -----                                                                      
PSVersion                      5.1.14393.3383                                                             
PSEdition                      Desktop                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                    
BuildVersion                   10.0.14393.3383                                                            
CLRVersion                     4.0.30319.42000                                                            
WSManStackVersion              3.0                                                                        
PSRemotingProtocolVersion      2.3                                                                        
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
You need to specify the pool object, not the name.  This is documented as such.

```powershell
$StorageSystem = Get-HPOVStorageSystem -Name ThreePAR-1
$StoragePool = Get-HPOVStoragePool -Name CPG-SSD -StorageSystem $StorageSystem
New-HPOVStorageVolumeTemplate -Capacity 100 -Name SVT-3PAR-Shared-1 -ProvisionType Thin -StoragePool $StoragePool -Shared -SnapshotStoragePool $StoragePool
```

**Comment by mleach8948** [comment]
Thanks Chris.  The documentation does reference that, but at the same time it implied it can be used directly:

[cid:image001.png@01D5C552.08611D30]

I appreciate the clarification.

**Comment by ChrisLynchHPE** [comment]
No problem.  The user docs are going through a major re-write, and just haven't gotten to the New-HPOV verb Cmdlets yet.
