### ISSUE TITLE
New-HPOVLogicalInterconnectGroup has no StormControl settings

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#444]
Using the GUI , when creating LIG, one can enable StormControl in the Interconnect Settings but the cmdlet New-HPOVLogicalInterconnectGroup has no parameter for setting Storm Control
Check with OneView 5.00

**Comment by ChrisLynchHPE** [comment]
This will added in the next 5.00 library update.

**Comment by DungKHoang** [comment]
Thanks!

**Comment by ChrisLynchHPE** [comment]
This issue will be closed when the release has been published.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 5.00.2341.1920](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.00.2341.1920) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2341.1920).

Closing.
