### ISSUE TITLE
iLO settings not present when creating server profile/template 

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#445]
# Summary of the new feature/enhancement

The Get-HPOVserverProfile/Template cmdlets expose the configuration for iLO settings ( accounts/ admin password...)
However, the new-HPOVServerprofile/template cdmlets do not have parameter to set iLO settings

POSH library v5.0

**Comment by ChrisLynchHPE** [comment]
Yes, this has been on my backlog to address.  Not there yet.

**Comment by j-crawford17** [comment]
I'd like to +1 this enhancement. Would it be possible to bump up this enhancement to add/remove/modify ilo settings with get/new-serverprofile/template?

**Comment by DungKHoang** [comment]
While waiting for the HPOV library to be updated for iLO settings set in SPT/SP, you can use this example to configure iLO attributes for SPT with HPOV PowerShell
https://github.com/HewlettPackard/oneview-powershell-samples/blob/master/Server%20Profiles/Update-ProfileTemplateiLOAccounts.ps1

**Comment by j-crawford17** [comment]
Thanks, I'll give it a shot!

**Comment by ChrisLynchHPE** [comment]
I have been working on a massive documentation update that has taken me away from any major library enhancements.  I will be working on iLO settings in a library update here soon.  I have one update that will be published in the next few days, but it is big fixes, not major enhancements.

**Comment by ChrisLynchHPE** [comment]
iLO settings were added a number of releases ago.  I just forgot to tag those releases.  It is supported in 5.00 and newer libraries.  Closing.
