### ISSUE TITLE
New-HPOVLogicalInterconnectGroup and snmp configuration

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#446]
### Expected Behavior
Using the GUI, you can configure snmp for a given LIG as follow:
--- SNMPv3 Enabled
--- SNMPv1 Disabled
--- System Contact ---> Some name
--- ReadCommunity string --> some value

The corresponding  Powershell code for snmp configuration for a LIG generates error

### Actual Behavior
The Powershell script generates an error
taskStatus              : SNMPv3 traps can not be disabled for SNMP configuration.
taskState               : Error

### Steps to reproduce

```PowerShell
$name                       = "LIG1"
$frameCount                 = 1
$bayConfig                  = @{
	Frame1 = @{
		Bay3 = 'SEVC40f8';
		Bay6 = 'SEVC40f8'
	}
}
$redundancyType             = "Redundant"
$fabricModuleType           = "SEVC40f8"
$InterconnectBaySet         = 3
$networkLoopProtection      = $True
$InterconnectConsistency    = "Exact"
#-- Generating snmp object for LIG
$snmpConsistencyChecking    = "Exact"
$readCommunity              = "comunity"
$contact                    = "dung@abc.com"
$snmpConfig                 = New-HPOVSnmpConfiguration -ReadCommunity $readCommunity -Contact $contact
New-HPOVLogicalInterconnectGroup -Name $name -Bays $bayConfig -FabricModuleType $fabricModuleType -fabricredundancy $redundancyType -FrameCount $frameCount -InterConnectBaySet $InterconnectBaySet -enablenetworkLoopProtection:$networkLoopProtection -InterconnectConsistencyChecking $InterconnectConsistency -snmpConsistencyChecking $snmpConsistencyChecking -SnmpV1 $False -SnmpV3 $True  -SNMP $snmpConfig 
```
[2001270722_HPOV_transcript.log](https://github.com/HewlettPackard/POSH-HPOneView/files/4117834/2001270722_HPOV_transcript.log)

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  
Output from `$PSVersionTable` on your Windows Host:

```PowerShell
# Output from $PSVersionTable
```

**Comment by ChrisLynchHPE** [comment]
This is happening because the code to generate the SnmpConfiguration object is incorrect.  Setting SNMP to enabled or disabled must be within the `New-HPOVSnmpConfiguration` call.  So the code within `ConvertTo-HPOVPowerShellScript` needs to be fixed.

**Comment by DungKHoang** [comment]
Thanks!
Will take a look at the code for this snmpConfiguration
