### ISSUE TITLE
Configuring desiredSpeed for uplinkPorts in Uplinkset

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#448]
Using the GUI, when configuring UplinkPorts in Uplinkset ( Ethernet/FC), administrator can set the desired speed to specific values ("Auto'or 40Gb....)
However, this parameter  is only available for FC uplinkset and not Ethernet uplinkset in the cmdlet new-HPOVUplinkSet :   -fcUplinkSpeed
Suggest to have this parameter also available for Ethernet uplinkset

**Comment by geraldine-kuo** [comment]
We also would like to be able to set the parameter for Ethernet uplinkset

**Comment by ChrisLynchHPE** [comment]
Apologies for the very late reply here.  It got lost in my list of items to follow up on.

Unless there is a 1Gb port, why is it necessary to specify the uplink port speed when auto negotiation works just fine?  There is no duplex speed, so forcing a port to a specific speed isn't needed anymore.  Is it?

**Comment by geraldine-kuo** [comment]
When testing HPE VC SE 100Gb F32 Interconnect Module with Composable Fabric switches, we have to set the desired speed to be 100Gb/s for Composable Fabric switches to work properly. When testing with HPE 5945 switches, setting speed to Auto will work.

**Comment by ChrisLynchHPE** [comment]
Uplink port speed can be set where supported in `New-OVUplinkSet` using the `-PortSpeed` parameter.  This feature was added in the 5.x library versions.

Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
