### ISSUE TITLE
How to update Network Set with new network?

### ISSUE THREAD

**Issue by ChrisLynchHPE** [HewlettPackard/POSH-HPOneView#45]
I'm creating this Issue for you @ljohnston11.

Chris, is there good method to add a network to a network set? and not clear out the existing networks in the network set? Or a way to read existing networks in the set to then compile a file list of networks to include in the network set? and same for uplinks, interconnects and interconnect groups.
 I'm still on HPOV 1.2 release.
 Thanks, Lee

**Comment by ChrisLynchHP** [comment]
There are a few different way to add Networks to an existing Network Set.

1. You can Get the Network Set with `$MyNetworkSet = Get-HPOVNetworkSet 'MyNetSet Name'`. There is a property called `networkUris`. This is where Network Resource Object URI's are stored.  You can then get an additional network to add, say `$MyNet200 = Get-HPOVNetwork 'MyNet200'`, and then add it to the `networkUris` by using `$MyNetworkSet.networkUris += $MyNet200.uri`.  Then use the `Set-HPOVResource $MyNetworkSet` CMDLET to commit the resource update on your appliance.
2. There is a `Set-HPOVNetworkSet` CMDLET.  To use it, you'll need to provide an Array collection of the Networks you want as a member of the Network Set.

**Comment by 5truja** [comment]
Hi Chris,
I am not using Networkset but i did you New-HPOVUplinkSet to create new uplinkset adding networks at the same time. My question to you is how to add new networks later (by scripting) to an existing UplinkSet since I see New-HPOVUplinkSet and Get-HPOVUplinkset but not Update-HPOVUplinkset (or something like that). Sorry if I missed something but at present I do not see any way to update it if new networks need to be added later.
Anyway I still do not see pros and cons regarding (HPOV-Uplinkset vs Networkset). Still in VCEM thoughts having only SUS and Tunnel in my mind (and imported them too and SUS appears as UpplinkSet in this case).

**Comment by ChrisLynchHPE** [comment]
`Network Sets` are not an alternative to `Uplink Sets`.  They serve different purposes.  `Uplink Sets` are similar to the `Shared Uplink Set` concept you are used to with VCM.  `Network Sets` replaces the `Multiple Network` option at the Server Profile Connection in VCM.

Updating `Uplink Sets` is very similar to the process found above.  Instead of using the `Get-HPOVNetworkSet` CMDLET, use the `Get-HPOVUplinkSet`, if you want to modify a Logical Interconnect.  There is an `uplinkSets` property you will perform the same operation above.  If you need to modify a Logical Interconnect Group, then you would use the `Get-HPOVLogicalInterconnectGroup` Cmdlet, as the Uplink Set(s) are associated at that object level.

**Comment by 5truja** [comment]
Hi Chris, 
Thanks again for a quick reply. I am reading your lines and at the same time reading the document "Introduction of HP Oneview concepts for HP virtual connect customers". Still a bit confused. Sorry.
Today I am running not only VCM but also VCEM which means I am able to distribute configuration to multiple enclosures by changing (first by checkling-out) only one enclosure. I suppose that this equals to LogicalInterconnect group (anyway enclosure groups are still confusing me there). 
This is my perception (and I apologize if I am not quite clear here).
I created uplinkset having multiple VLANs and I am still able to distibute changes to multiple logicalinterconnects (or enclosures) and even modify (by adding new). Still need syntax to see an example when adding additional but I will try that tomorrow (CET is my timezone).
Best practice according to me:
Use Uplinkset (just as in previous scenario with VCM or VCEM) to configure and distribute active-active uplinks (_A and _B VLANs, I have it now and I had it before), When adding addtional networks use Get-HPOVLogicalInterconnectGroup to add new VLANs and to distribute config to multiple VLANs (syntax?).
Or use Get-HPOVUplinkSet to add aditional VLANs (but it applied only to that particular LogicalInterconnect (syntax?)
When dealing when serverprofiles and at the same time using multiple VLANs (on a Single NIC or ethernet connection) use Network Sets (?). 
VCM or VCEM had a mechanism to "inherit" VLANs from SUS and I am wondering if I have that option.
Basically I will have the following in my ESXi profile (vc-eth)
Uplink set 1 -A (ESXiA, VMotion-A, FT-A, MGMT1-A,MGMT2-B,MGMT3-A)
Uplink set 1 -B (ESXiB, VMotion-B, FT-B, MGMT1-B,MGMT2-B,MGMT3-B)
Upplink set 2-A Tunnel-A
Upplink set 2-B Tunnel-B
and of course FC (A and B vc-fc module)
Server profile would have:
NIC1 (only ESXi-A)
NIC2 (only ESXi-B)
NIC3 (the rest of A-VLANs excl. Tunnel)
NIC4 (the rest of B-VLANs excl. Tunnel)
NIC5 (Tunnel-A)
NIC6 (Tunne-B)
So basically I will make a template but is it possible to update all at one place (regardless if is via LogicalInterconnect group, via Uplink set or some master server profile template AND get all of serverprofiles updated with new VLANs (hot-add as I could in VCEM)?
Please ignore my question I you find it cumbersome. In that case I just need to test but inheritance or simple configuration distribution (when performing a change-read adding new VLANs) is the word that I am looking for :-)
Kind regards

**Comment by ChrisLynchHPE** [comment]
> Today I am running not only VCM but also VCEM which means I am able to distribute configuration to multiple enclosures by changing (first by checkling-out) only one enclosure. I suppose that this equals to LogicalInterconnect group (anyway enclosure groups are still confusing me there). 

Not quite.  a `VCEM Domain Group` does not equal a `Logical Interconnect`.  a `VCEM Domain Group` is actually split into a number of different HPE OneView resources: `Enclosure Group`, `Logical Interconnect Group`, and to a certain extent a `Logical Interconnect`.

An `Enclosure Group` is the resource bound to a particular Enclosure that defines how it will be managed, and has association to 1 or more `Logical Interconnect Groups` (or `LIG`).  A `LIG` defines the Interconnect and Fabric connectivity for a collection of `Enclosures`.  The `LIG` is the policy you maintain.  (Think of the `LIG` as a `Server Profile` of sorts.)  You can sort of relate this back to a `VCEM Domain Group`, but not really.  You would need to put a `VCM Domain` into Maintenance Mode, log into VCM, make your allowed changes (you can't change everything), take the VC Domain out of Maintenance Mode, and then VCEM could replicate settings.  

HPE OneView replaces those steps and consolidates them into a single interface.  Remember, HPE OneView is THE manager. VCM is turned off and inaccessible.

A `Logical Interconnect` is the 'running configuration' if you will.  It represents the deployed configuration to the interconnects present within an Enclosure.  Yes, you can manage the Logical Interconnect directly, but that isn't the intended operation, and you lose a lot of simplified management if you do.

Why?  HPE OneView employs an `Expected and Compliance` model.  Meaning, when you configure or manage resources, you expect them to be configured/deployed in a certain manner.  And the way to provide the Expected part of the model is to provide Compliance with parent level objects.  That would be the `LIG` and the `Enclosure Group`.  If their child objects are no longer `compliant` or `not consistent with group`, HPE OneView will flag those resources to get the Administrators attention.

VCM and VCEM never had this concept, and is unique to HPE OneView.

> I created uplinkset having multiple VLANs and I am still able to distibute changes to multiple logicalinterconnects (or enclosures) and even modify (by adding new). Still need syntax to see an example when adding additional but I will try that tomorrow (CET is my timezone).

No.  An Uplink Set is an actual object inside of HPE OneView.  It can only be associated with a single Logical Interconnect.  If you need to add a VLAN so multiple Logical Interconnects pick up that new configuration, you update the `LIG` resource.  Here is an example:

``` PowerShell
#Get the LIG Resource
$Lig = Get-HPOVLogicalInterconnectGroup 'My LIG Policy' -ApplianceConnection $ApplianceConnection

#Display the 'Prod Uplink Set 1_A' Uplink Set resource
$Lig.uplinkSets | ? name -eq 'Prod Uplink Set 1_A'

#Get MyNewVLAN_A network resource
$NewNetwork = Get-HPOVNetwork 'MyNewVLAN_A' -ApplianceConnection $ApplianceConnection

#Add it to the 'Prod Uplink Set 1_A'
($Lig.uplinkSets | ? name -eq 'Prod Uplink Set 1_A').networkUris.Add($NewNetwork.uri)

#Save the object
$resp = Send-HPOVRequest $lig.uri PUT $lig -Hostname $ApplianceConnection
```

> VCM or VCEM had a mechanism to "inherit" VLANs from SUS and I am wondering if I have that option.

Yes, VCM and VCEM have that option.  It was added because neither had or have a concept like `Network Sets`.  A `Network Set` is a collection of Ethernet Networks that is then assigned to a `Server Profile Connection`.  One of the unique capabilities a `Network Set` has over the VCM/VCEM option you are using (besides the Inhert option being inflexible) is that if I modify the `Network Set`, that change is replicated to all associated `Server Profile Connections`.  It makes Server-side network management MUCH easier, even if you were using the Inhert feature found in VCM/VCEM.

>So basically I will make a template but is it possible to update all at one place (regardless if is via LogicalInterconnect group, via Uplink set or some master server profile template AND get all of serverprofiles updated with new VLANs (hot-add as I could in VCEM)?

Yes, it's all available via the single interface that is HPE OneView.  Here are the high-level steps one would perform to add a new Ethernet Network:


1. Create new Ethernet Network.
 * Repeat if creating an A/A network configuration.
2. Add the new Ethernet Network to an Uplink Set within a Logical Interconnect Group.
 * Repeat if creating an A/A network configuration.
3. Add the new Ethernet Network to a Network Set.
 * Repeat if creating an A/A network configuration.
4. Perform the `Update from group` Action at each Logical Interconnect (or use the `Update-HPOVLogicalInterconnect` Cmdlet).
5. $$$ (aka profit)

Ok, so I made up '5' above.  But hopefully that helps.

**Comment by 5truja** [comment]
Hi Chris,

Thank you a lot for taking your time to explain this. 5 steps explanation helps a great deal.
According to that I need to maintain both uplinksets and Network Sets.
Since Network Set override (read update) the existing configuration all way down (and I suppose it’s non-interruptable process) I find it to be attractive and efficient way to handle both LIGs and Serverprofiles.

Enclosure group is still tricky part since you say that it is the resource bound to a particular Enclosure or Enclosures
I need probably to try with multiple enclosures in order to be able to see which configuration is applied (inherited first from the group): EG? or LIG and what parameters are included in each and who is overriding who.
I should be nice to have some kind of matrix for this. There is only table in concept document for VCM or VCEM admins.

I will go ahead and try ;-)

Kind regards

**Comment by ChrisLynchHPE** [comment]
> Thank you a lot for taking your time to explain this. 5 steps explanation helps a great deal.
According to that I need to maintain both uplinksets and Network Sets.
**Since Network Set override (read update) the existing configuration all way down **(and I suppose it’s non-interruptable process) I find it to be attractive and efficient way to handle both LIGs and Serverprofiles.

No, that is not correct.  `Network Sets` and `Uplink Sets` are completely different resources, and one does not manage the other.  `Network Sets` are server-side managed resources, while `Uplink Sets` are bound to uplink ports.

> Enclosure group is still tricky part since you say that it is the resource bound to a particular Enclosure or Enclosures

`Enclosure Groups` simply define the associated `Logical Interconnect Group` mapping per potential `Interconnect Bay`.  That defines the Expected configuration of 1 or more Enclosures.  Contrast this with you needing to do the following steps without HPE OneView:

1. Log into the OA and configure SNMP, SSO, HPSIM monitoring, and other OA-related settings.
2. Log into VCM to create a Virtual Connect Domain. (this step could be bypassed if adding the enclosure to an existing VCEM Domain Group).
3. Log into VCEM to discover the newly configured enclosure.
4. Access VCEM management console to then add to a new (or existing) VCEM Domain Group.

With the `Enclosure Group` and `Logical Interconnect Group` resources, I simplify those steps above, to just needing an IP Address on the OA, a valid Administrator account for the OA, and EBIPA setup for the iLO's and Interconnects.  The Enclosure Config script can take care of other OA configurations (supported or allowed OA CLI commands, which are documented in the HPE OneView User Guide).

This conversation has taken a tangent to the original posted question. If you'd wish to continue discussing this further, please reach out to me directly at chris ((dot)) lynch [a t ] hpe ({dot)} com.

**Comment by ChrisLynchHPE** [comment]
Closing.

**Comment by NJBean** [comment]
Can this be updated with the set-hpovnetworkset commandlet? When I try to use this new command it doesn’t update, it replaces the set networks.

**Comment by ChrisLynchHPE** [comment]
It could.  Please open a new issue for that request.
