### ISSUE TITLE
Issue with PowerShell conversion script with OS Deployment configuration

### ISSUE THREAD

**Issue by xusarmy** [HewlettPackard/POSH-HPOneView#450]
### Expected Behavior
When you look at the output of the Powershell script it does not do any translation/cleanup between the original ESXi Mgmt Network URI/ESXi Vmotion Network URI to the new environment

### Actual Behavior
This is one of 4 lines in the PS output in the Attributes of the OS Deployment settings:
($planAttribs | Where-Object name -eq "ManagementNIC.networkuri").value = "/rest/ethernet-networks/**369e25f0-60a3-4b3f-8456-9e0fbe9a8ce4**"
$CustomAttribs     += $planAttribs | Where-Object name -eq "ManagementNIC.networkuri"

The error message when trying to import it into new environment is the following:
New-HPOVServerProfileTemplate : One or more networks in the network set {"name":"Prod_ESX", "uri":"/rest/network-sets/2820ef68-488e-4434-bb55-ebd82e32b212"} on physical port 
Mezzanine (Mezz) 3:2 are not available on logical interconnect group {"name":"PROD_B_LIG", "uri":"/rest/logical-interconnect-groups/86681cef-0aa4-4598-bac7-df783318cfaf"}.
At C:\Users\xusar\todd1.ps1:198 char:1
+ New-HPOVServerProfileTemplate -Name $name -ServerHardwareType $sht -E ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (AsyncronousTask:String) [New-HPOVServerProfileTemplate], ServerProfileTemplateResourceException
    + FullyQualifiedErrorId : InvalidOperation,New-HPOVServerProfileTemplate

This led me to look at the original URI for the Networks in my Network Set and I confirmed they were the same.  I had to find out what the new URI was and edit the script and all was  good.

### Steps to reproduce

```PowerShell
1.  Create a Profile Template with an OS Deployment.
2.  Convert the Profile Template to Powershell
3.  Validate the Network URI's are in the converted PS output
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):  ApplianceVersion: 5.00.00.404934.02 ApplianceVersion: 5.00.00.404934.02 5.0.2319.1872  C:\Program Files\WindowsPowerShell\Modules\HPOneView.500\5.0.2295.3359
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  ApplianceVersion: 5.00.00.404934.02 ApplianceVersion: 5.00.00.404934.02 5.0.2319.1872  C:\Program Files\WindowsPowerShell\Modules\HPOneView.500\5.0.2295.3359
Output from `$PSVersionTable` on your Windows Host:

Name                           Value                                                                                                                                           
----                           -----                                                                                                                                           
PSVersion                      5.1.17763.771                                                                                                                                   
PSEdition                      Desktop                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                         
BuildVersion                   10.0.17763.771                                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                             
SerializationVersion           1.1.0.1  

```PowerShell
# Output from $PSVersionTable
```

**Comment by ChrisLynchHPE** [comment]
I've added additional logic to handle this scenario.  In the future, the Cmdlet will generate helper code that will get the resource, instead of just blanketly assigning a URI that might not be valid for another appliance.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
