### ISSUE TITLE
Add-HPOVRacktoDataCenter error

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#455]
The cmdlet generates an error when executing the folllowing code

### Steps to reproduce

```PowerShell
$dc                                 = Get-HPOVDataCenter | where name -match "DemarkDC" 
$rack                               = Get-HPOVRack | where serialNumber -match "2AB100LMNB" 
Add-HPOVRackToDataCenter  -InputObject $rack  -DataCenter $dc  -X 600 -Y 600 -Millimeters:$True
```
[2003011651_HPOV_transcript.log](https://github.com/HewlettPackard/POSH-HPOneView/files/4272880/2003011651_HPOV_transcript.log)

**Comment by ChrisLynchHPE** [comment]
This was fixed in newer HPE OneView 5.20 library update.

Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
