### ISSUE TITLE
Documentation on Set-HPOVApplianceDateTime for parameter -NTPServers

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#457]
PowerShell version 5.0.2341.1920
Help documentation of the cmdlet Set-HPOVApplianceDateTime for parameter -NTPServers is confusing:
-----
-NTPServers <Array>
    Parameter is deprecated.  Please use the Set-HPOVApplianceDateTime Cmdlet.
-----

**Comment by ChrisLynchHPE** [comment]
This obviously is an error in the documentation.  `-NTPServers` is an array of 1 or more IPv4 Addresses or FQDN's.

**Comment by ChrisLynchHPE** [comment]
This was fixed in user documentation.  
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
