### ISSUE TITLE
Backup fails with New-HPOVBackup on HPOneview 2.0

### ISSUE THREAD

**Issue by SorenTKristensen** [HewlettPackard/POSH-HPOneView#46]
I've been using a simple backup script to backup our Oneview 1.20 appliances. Basically the script just connects to the Oneview server, runs New-HPOVBackup and then disconnects.

When I use the same simple script on our Oneview 2.0 appliances, and using the new Oneview.200 Library script fails.

First problem I encountered was that the script wasn't able to connect to the oneview appliance when using a local user account that only had backup rights on the Oneview appliance.
The Connect-HPOVMgmt commandlet throws an 'user not authorized' error.

If I then give the backup user full permission on the Oneview appliance, the script is able to connect to the appliance, and the backup is created, but then fails to download the backup file. 
The New-HPOVBackup commandlet throws the following error:

Send-HPOVRequest : No appliance Hostname parameter provided and no valid appliance session(s) found.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:11183 char:23
+             $_backupFileUri = (Send-HPOVRequest $_backupUri -Hostname $_Connection.Applia ...
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Hostname:String) [Send-HPOVRequest], AuthSessionException
    + FullyQualifiedErrorId : NoAuthSession,Send-HPOVRequest

New-HPOVBackup : Cannot validate argument on parameter 'uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:1 char:1
+ New-HPOVBackup -Location C:\HPOVBackup
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-HPOVBackup], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-HPOVBackup 

The script is running from a Windows Server 2012 R2 server, using the 2.0.40.0 version of the Oneview.200 library.

Any help is appreciated.

Regards,
Søren Kristensen

**Comment by ChrisLynchHP** [comment]
Thank you for reporting this.  I found this late last night, and is a regression bug.  I have it fixed in a newer  version I will be posting at the end of this week.  In the mean time, can you use the 1.20 library?

**Comment by ChrisLynchHP** [comment]
This will be fixed in the upcoming 2.0.67.0 release.  Closing issue.
