### ISSUE TITLE
New-HPOVsnmpV3user with security level = AuthOnly - cryptic error message

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#460]
Cryptic error message when creating a snmpV3User with securityLevel=AuthOnly

### Steps to reproduce
$authParaphrase                 = "P@ssword1" | ConvertTo-SecureString -AsPlainText -Force
new-HPOVSnmpV3User -ApplianceSnmpUser -UserName "sDung3"  -SecurityLevel "AuthOnly" -AuthProtocol "SHA1" -AuthPassword $authParaphrase

[2003071657_HPOV_transcript.log](https://github.com/HewlettPackard/POSH-HPOneView/files/4302688/2003071657_HPOV_transcript.log)

**Comment by ChrisLynchHPE** [comment]
This is an internal error where the creation of the error message object isn't correct.  This will be fixed in the next library update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 5.00.2368.2592 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.00.2368.2592) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.500/5.00.2368.2592).

Please verify before this issue is closed.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
