### ISSUE TITLE
Documentation of New-HPOVLogicalJBOD with DriveType parameter

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#462]
In New-HPOVLogicalJBOD help, there is mention about 2 parameters: -DriveSelectionBy and -AvailableDriveType under -DriveType help as follow:
DriveType <string>
        When attempting to create a logical JBOD, specify the interface type for drives that will be used to build the
        logical drive. Supported values depend on the local storage capabilities of the selected server hardware type.
         Allowed value:

                * SAS
                *SATA
                *SASSSD
                *SATASSD
                *Auto
        NOTE: Auto is not supported when attempting to create an HPE Synergy D3940 Logical or JBOD disk.  You must specify a disk technology type unless **-DriveSelectionBy** is changed to DriveType and **-AvailableDriveType** is used.  Allowed values are:....
However, the cmdlet does not support those 2 parameters

**Comment by ChrisLynchHPE** [comment]
Actually, only the `-DriveSelectionBy` parameter doesn't exist on this Cmdlet.  I'll get that fixed in my docs update.

**Comment by ChrisLynchHPE** [comment]
Documentation has been updated, both online and offline.  To update docs, use `Update-Help -Module HPOneView.500`, or download the current release of the library.
