### ISSUE TITLE
Parameter 'BootOrderConsistency'  not defined in new-HPOVserverprofileTemplate 

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#468]
# Set BootOrderConsistency when creating spt

HPOV library version: 5.0.2341.1920

**Comment by ChrisLynchHPE** [comment]
This support was added in [Release 5.0.2368.2592](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.0.2368.2592) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2368.2592).

Please verify before this issue is closed.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
