### ISSUE TITLE
New-HPOVLogicalInterconnectGroup with -FabricModuleType parameter

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#469]
When creating logicalInterconnectGroup one should be able to provide addtional types for Fabric Module especially:
SEVC100F32, SEVC16FC, SEVC32FC
As of today ( HPOV 5.x),only supports : SEVC40F8 and SEVCFC

**Comment by ChrisLynchHPE** [comment]
The library already supports the 100Gb and 16Gb FC modules.  What is missing is the SEVC32FC module type.

**Comment by ChrisLynchHPE** [comment]
This support was added in [Release 5.0.2368.2592](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.0.2368.2592) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2368.2592).

Please verify before this issue is closed.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
