### ISSUE TITLE
Support Question - Updating Remote Support Contact on an interconnect level

### ISSUE THREAD

**Issue by j-crawford17** [HewlettPackard/POSH-HPOneView#471]
I was wondering if there's a way to update the remote support contact per interconnect. I know I can get and change the information on a per server and enclosure level, but not seeing anything for interconnect remote support contacts with:

$Interconnect= Get-HPOVInterconnect
$InterconnectSupport = $Interconnect | Get-HPOVRemoteSupportSetting

Is Get-HPOVRemoteSupportSetting not able to be passed thru with Get-HPOVInterconnect? 

As for Get-HPOVInterconnect, I do see a ${var}.remotesupport, but nothing about contacts.

**Comment by ChrisLynchHPE** [comment]
I will have to look into this.  As it stands only Enclosures and Servers can be updated via the Cmdlets.

**Comment by ChrisLynchHPE** [comment]
I will have this feature in the next library update.  I'm working on addressing a PowerShell 7/Core issue with file downloads and uploads not transferring fast enough, or working at all (on non-Windows systems).

**Comment by j-crawford17** [comment]
Sounds good, appreciate the support. Any timeframe on when the next update will be?

**Comment by ChrisLynchHPE** [comment]
Later today.

**Comment by ChrisLynchHPE** [comment]
This is addressed in [Release 5.0.2400.1845](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.0.2400.1845) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2400.1845).

Please verify before this issue is closed.

**Comment by j-crawford17** [comment]
Thanks! Verified I can pull the remote support contacts on interconnects now. Appreciate the quick turnaround

**Comment by ChrisLynchHPE** [comment]
Excellent.  Thanks for reporting.
