### ISSUE TITLE
Typo InsightOnline

### ISSUE THREAD

**Issue by andrewhpe** [HewlettPackard/POSH-HPOneView#476]
if ($PSCmdlet.ParameterSetName -eq 'InsightOnline')
            {

                $_PortalRegsitrationObject = NewObject -InsightOnlineRegistration
                $_PortalRegsitrationObject.userName = $InsightOnlineUsername
                $_PortalRegsitrationObject.password = [Runtime.InteropServices.Marshal]::PtrToStringBSTR([Runtime.InteropServices.Marshal]::SecureStringToBSTR($InsightOnlinePassword))

                Try
                {

                    $_InsightOnlineConfig = Send-HPOVRequest -uri $InsightOnlinePortalRegistraionUri -Method POST -Body $_PortalRestrationObject -Hostname $_appliance.Name

                }

--------------------------------------------
Should be
------------------------------------------------
            if ($PSCmdlet.ParameterSetName -eq 'InsightOnline')
            {

                $_PortalRegistrationObject = NewObject -InsightOnlineRegistration
                $_PortalRegistrationObject.userName = $InsightOnlineUsername
                $_PortalRegistrationObject.password = [Runtime.InteropServices.Marshal]::PtrToStringBSTR([Runtime.InteropServices.Marshal]::SecureStringToBSTR($InsightOnlinePassword))

                Try
                {

                    $_InsightOnlineConfig = Send-HPOVRequest -uri $InsightOnlinePortalRegistraionUri -Method POST -Body $_PortalRegistrationObject -Hostname $_appliance.Name

                }

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting this.  It will be fixed in an upcoming 5.00 and 5.20 library update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 5.20.2470.2147](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.20.2470.2147) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2470.2147).

Please verify before this issue is closed.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
