### ISSUE TITLE
ConvertTo-HPOVPowerShellScript generates unknown parameters with new-hpovserverprofile

### ISSUE THREAD

**Issue by jullienl** [HewlettPackard/POSH-HPOneView#480]
It seems that the code generated has changed from the 5.00 library.

I am just using `ConvertTo-HPOVPowerShellScript `against a `get-hpovserverprofile` and now the code generates some parameters that are not even available in `new-hpovserverprofile` like `BootModeConsistencyChecking `and `ManageConnections`

`get-hpovserverprofile -name <profilename> | ConvertTo-HPOVPowerShellScript`

Generates the following:

`New-HPOVServerProfile -Name $name -Description $description -AssignmentType Server -Server $server -Affinity $affinity -ManageConnections $False -Connections $connections -LocalStorage  -StorageController $controllers -ManageBoot:$manageboot -BootMode $biosBootMode -BootModeConsistencyChecking $bmConsistency -BootOrder $bootOrder -HideUnusedFlexNics $true`

### Version Information
HPE OneView PowerShell Library Version : 5.20.2443.1695
HPE OneView Appliance Version: 5.20  
$PSversiontable:
- PSVersion                      5.1.18362.145
- PSEdition                      Desktop
- PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
- BuildVersion                   10.0.18362.145
- CLRVersion                     4.0.30319.42000
- WSManStackVersion              3.0
- PSRemotingProtocolVersion      2.3
- SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
This was fixed in the recent 5.20 library update.  Please update from the PowerShell Gallery and verify the issue has been resolved for you.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
