### ISSUE TITLE
not able to install hponeview

### ISSUE THREAD

**Issue by santhoshpcv** [HewlettPackard/POSH-HPOneView#488]
Where is the msi or exe file to install the hp one view module.Install-module doesnot work as I dont have internet access.please help me.

**Comment by ChrisLynchHPE** [comment]
There is no EXE or MSI of the module.  If your PC does not have Internet access, please use the `[Save-Module](https://docs.microsoft.com/en-us/powershell/module/powershellget/save-module?view=powershell-7)` PowerShell Cmdlet from a system that does have Internet access.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
