### ISSUE TITLE
Remove-hpovenclosure in not working ,version 4.20

### ISSUE THREAD

**Issue by santhoshpcv** [HewlettPackard/POSH-HPOneView#489]
Remove-hpovenclosure in not working ,version 4.20

![oneviewissue](https://user-images.githubusercontent.com/66933280/87502759-15ad1680-c680-11ea-84f6-84413e0e6851.PNG)

We are doing decommission of the enclosures.post deleting the server profile and i am trying to delete enclosure.I am following the steps from "get-help ".still not working.please help this is majot roadblock now.ERROR is attached

**Comment by VincentBerger** [comment]
The error means you need to specify the parameter name for $enclosure, i.e. write
`Remove-HPOVEnclosure -InputObject $enclosure -confirm:$true` 
or
`Get-HPOVEnclosure -Name "$decoenclosure" | Remove-HPOVEnclosure -confirm:$true`
Yes, the example in the help is wrong...

**Comment by ChrisLynchHPE** [comment]
Thanks for letting me know the docs are wrong.  I have updated the online help for `Remove-HPOVEnclosure`.

**Comment by ChrisLynchHPE** [comment]
Docs have been updated.  Closing.
