### ISSUE TITLE
Make Wait-HPOVTaskComplete progress display optional

### ISSUE THREAD

**Issue by VincentBerger** [HewlettPackard/POSH-HPOneView#492]
The new output of Wait-HPOVTaskComplete with progress bars on subtasks is nice when running interactively, but no so much when running in a script and capturing the output. It looks ugly when I use it in Jupyter for example.
It would be nice to have a -NoProgress switch or something like that to skip the progress display.

**Comment by ChrisLynchHPE** [comment]
That is what the `-Async` parameter is for in the other Cmdlets.  Displaying output is by design.
