### ISSUE TITLE
Add-HPOVServer

### ISSUE THREAD

**Issue by RSHollaway** [HewlettPackard/POSH-HPOneView#493]
We have a group and scope defined in OneView with Role Permissions set to Scope Operator and Server Administrator. Any member of this group through the UI can add DL380s to OneView as Managed, can set Scopes, and create the Server Profile.

When they try from PowerShell using the Add-HPOServer cmdlet, we are getting the following message: "Resource creation in the specified scope is not authorized. The scope does not match the user session permissions or does not exist. Retry the operation, specifying a resource scope that is allowed by the user session."

`$AddResults = Add-HPOVServer -Hostname $iLOIPAddress -Credential $iLOCreds -LicensingIntent OneView -ErrorAction Stop | Wait-HPOVTaskComplete`

Are Roles/Permissions different from the UI versus PowerShell?

**Comment by ChrisLynchHPE** [comment]
No.  Scopes are supposed to be the same.  What could be happening is that the API might be requiring a Scope to be set during the call to `Add-HPOVServer` Cmdlet.  With the scoped user, please examine `$ConnectedSessions.ActivePermissions`.  More details about Active Permissions and Scope usage is documented [here](https://hpe-docs.gitbook.io/posh-hpeoneview/about/about_appliance_connection_permissions). 

When you look at the scoped user accounts `ActivePermissions`, are they a member of a singular or multiple scopes?  You could in turn do this:

```powershell
# Get the Server administrator scope of the user account. This may return multiple values if connected to more than 1 appliance, and/or if there are multiple scopes assigned to the Server administrator role
$ServerAdministratorScope = $ConnectedSessions | Where-Object { $_.ActivePermissions.RoleName -contains "Server administrator" }

# Add the server resource with the provided scope, if the variable contains a single active permissions for Server administrator role
$AddResults = Add-HPOVServer -Hostname $iLOIPAddress -Credential $iLOCreds -LicensingIntent OneView -Scope (Get-HPOVScope -Name $ServerAdministratorScope.ScopeName -ErrorAction Stop) -ErrorAction Stop | Wait-HPOVTaskComplete
```

**Comment by RSHollaway** [comment]
Thanks Chris.

I'm going to try to scope it during the add as you have recommended. I made the code change, and tested with a local account. I'm just waiting for my guys to test it on their end to confirm.

**Comment by ChrisLynchHPE** [comment]
Closing this due to no further activity.  If you feel this is in error, please feel free to re-open this issue.
