### ISSUE TITLE
Update-Help not working with OneView modules

### ISSUE THREAD

**Issue by VincentBerger** [HewlettPackard/POSH-HPOneView#494]
I'm not quite sure what is going on here:
```
PS /Users/vincent> update-help -UICulture en-US
Update-Help: Failed to update Help for the module(s) 'HPEOneView.530, HPOneView.500, HPOneView.520' with UI culture(s) {en-US} : A Help URI cannot contain more than 10 redirections. Specify a valid Help URI..
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

```PowerShell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ChrisLynchHPE** [comment]
This is likely due to the renaming of the project from HPOneView to HPEOneView and the redirects GitHub employs.  The update CAB is hosted on gh-pages.  This should have been fixed in the 5.30 and 5.20 updates I published already.  I'll need to look into that some more.

**Comment by ChrisLynchHPE** [comment]
I had updated the module help info XML manifest files.  This should be working.  Can you please validate?  You may need to update the library to a current release:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
