### ISSUE TITLE
networks question

### ISSUE THREAD

**Issue by frankzo** [HewlettPackard/POSH-HPOneView#5]
I'm using oneview 1.20 with 4 bladesystems c7000 with gen 9 bl 460 systems.  

When a server profile is created the network is in a VLAN where we use pxe boot voor installation of the OS. After the installation I would like to change the network to a different 'network (vlan)' whilst maintaining the network adapter and thus the mac adres. 
I can do this by hand easily. But for provisioning I would like to do this using powershell. Is this possible?

**Comment by ejschulte** [comment]
With the current set of cmdlets in the 1.20 POSH library, you would accomplish it with the following flow...

1.  Get the network resource that you want to assign to the connection after installation.
2.  Get the server profile resource that you want to update.
3.  Update the networkUri property on the connection of the server profile
4.  Use Send-HPOVRequest with a PUT and include the updated server profile resource as the BODY and the server profile uri as the URI parameter.

$newNet = Get-HPOVNetwork -name "newNetwork" -type Ethernet
$updateProfile = Get-HPOVServerProfile -name "MyServerProfile"
$updateProfile.connections | ? {$_.networkUri -match $newNet.uri} | ForEach-Object {$_.networkUri = $newNet.uri}
Send-HPOVRequest -method PUT -body $updateProfile -uri $updateProfile.uri

**Comment by ejschulte** [comment]
Sorry... I left out a step.  You'll need to get the uri of the existing PXE network as well, and then search the connections with that uri

$pxeNet = Get-HPOVNetwork -name "pxeNetwork" -type Ethernet
$updateProfile.connections | ? {$_.networkUri -match $pxeNet.uri} | ForEach-Object {$_.networkUri = $newNet.uri)
