### ISSUE TITLE
5.30 - Get-OVDatacenter error

### ISSUE THREAD

**Issue by huberm1** [HewlettPackard/POSH-HPOneView#500]
the cmdlet returns an error:

```powershell
At C:\Program Files\WindowsPowerShell\Modules\hpeoneview.530\5.30.2472.1534\HPEOneView.530.psm1:38651 char:25
+ ...             $member | Add-Member -NotePropertyName RemoteSupportLocat ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastConstructorException
```
can't post captured output here as it will include the remote-support contact informations

### Version Information
5.30.2472.1534

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting this.  It will be fixed in the update I'm in the process of publishing now.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 5.30.2515.1313](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.30.2515.1313) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.530/5.30.2515.1313).

Please verify before this issue is closed.

**Comment by huberm1** [comment]
Thanks Chris!

I have verified it and everything is fine.

BR,
Martin

**Comment by ChrisLynchHPE** [comment]
Thanks.  Closing.
