### ISSUE TITLE
Latest 5.20 update breaks New-HPOVLogicalEnclosure

### ISSUE THREAD

**Issue by VincentBerger** [HewlettPackard/POSH-HPOneView#501]
It looks like the latest 5.20 update 5.20.2506.1628 introduces a breaking change for New-HPOVLogicalEnclosure.
### Expected Behavior
This code used to work:
```PowerShell
New-HPOVLogicalEnclosure -EnclosureGroup $EG -Name LE-Synergy-Local -Enclosure $Encl
```
### Actual Behavior
Now it results in 
```
New-HPOVLogicalEnclosure: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued can
not be used together or an insufficient number of parameters were provided.
```
I presume this is related to all the parameters you've added for EBIPA but I shouldn't have to use EBIPA, should I ?

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`): 5.20.2506.1628

**Comment by ChrisLynchHPE** [comment]
No, this should not have been a breaking change.  This is caused by the lack of a DefaultParameterSetName attribute that should have been set within the Cmdlet.  I'll push out a quick update to fix this.

**Comment by VincentBerger** [comment]
Updated to 5.20.2506.1630, it's  better but not quite there yet... now we get past the parameter validation but there's a problem in the request body. Error message is:
```
New-HPOVLogicalEnclosure: The field named enclosures near line 1, column 132 is not a valid field in this JSON object. Check the v
alid fields for this JSON object and remove or correct the unrecognized field.
```
-Verbose output showing the body with the extra field:
<pre>
VERBOSE: [SEND-HPOVREQUEST] Request Body: {"name":"LE-Synergy-Local","enclosureUris":["/rest/enclosures/0000000000A66101","/rest/e
nclosures/0000000000A66102"],<b>"enclosures"</b>:{"/rest/enclosures/0000000000A66101":{"enclosureUri":"/rest/enclosures/0000000000A66101"
,"interconnectBays":[{"bayNumber":1,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":2,"manualAddress
es":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":3,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}}
,{"bayNumber":4,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":5,"manualAddresses":[],"licenseInten
ts":{"FCUpgrade":"Automatic"}},{"bayNumber":6,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":7,"man
ualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":8,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Au
tomatic"}}],"deviceBays":[{"bayNumber":1,"manualAddresses":[]},{"bayNumber":2,"manualAddresses":[]},{"bayNumber":3,"manualAddresse
s":[]},{"bayNumber":4,"manualAddresses":[]},{"bayNumber":5,"manualAddresses":[]},{"bayNumber":6,"manualAddresses":[]},{"bayNumber"
:7,"manualAddresses":[]},{"bayNumber":8,"manualAddresses":[]},{"bayNumber":9,"manualAddresses":[]},{"bayNumber":10,"manualAddresse
s":[]},{"bayNumber":11,"manualAddresses":[]},{"bayNumber":12,"manualAddresses":[]}]},"/rest/enclosures/0000000000A66102":{"enclosu
reUri":"/rest/enclosures/0000000000A66102","interconnectBays":[{"bayNumber":1,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"
Automatic"}},{"bayNumber":2,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":3,"manualAddresses":[],"
licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":4,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNu
mber":5,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":6,"manualAddresses":[],"licenseIntents":{"FC
Upgrade":"Automatic"}},{"bayNumber":7,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":8,"manualAddre
sses":[],"licenseIntents":{"FCUpgrade":"Automatic"}}],"deviceBays":[{"bayNumber":1,"manualAddresses":[]},{"bayNumber":2,"manualAdd
resses":[]},{"bayNumber":3,"manualAddresses":[]},{"bayNumber":4,"manualAddresses":[]},{"bayNumber":5,"manualAddresses":[]},{"bayNu
mber":6,"manualAddresses":[]},{"bayNumber":7,"manualAddresses":[]},{"bayNumber":8,"manualAddresses":[]},{"bayNumber":9,"manualAddr
esses":[]},{"bayNumber":10,"manualAddresses":[]},{"bayNumber":11,"manualAddresses":[]},{"bayNumber":12,"manualAddresses":[]}]}},"e
nclosureGroupUri":"/rest/enclosure-groups/3720405e-7069-443b-a989-9876ad4262ed","firmwareBaselineUri":null,"forceInstallFirmware":
false,"initialScopeUris":[]}
VERBOSE: [SEND-HPOVREQUEST] Request: POST https://192.168.1.170/rest/logical-enclosures
</pre>

**Comment by ChrisLynchHPE** [comment]
Ah, I see what is happening.  There is a property name that is used to configure Synergy EBIPA (`enclosureBaySettings`) and it is a different name after the LE is created (`enclosures`).  It isn't documented in the API docs, so I'll need to file a defect on that.  I'll get another quick fix out today.

**Comment by VincentBerger** [comment]
Still not quite there... Using 5.20.2506.1632, error now is
```
New-HPOVLogicalEnclosure: The field named unknown near line 1, column 2,566 is not a valid field in this JSON object. Check the va
lid fields for this JSON object and remove or correct the unrecognized field.
```
This is the body being sent:
```
VERBOSE: [SEND-HPOVREQUEST] Request Body: {"name":"LE-Synergy-Local","enclosureUris":["/rest/enclosures/0000000000A66101","/rest/e
nclosures/0000000000A66102"],"enclosureBaySettings":{"/rest/enclosures/0000000000A66101":{"enclosureUri":"/rest/enclosures/0000000
000A66101","interconnectBays":[{"bayNumber":1,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":2,"man
ualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":3,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Au
tomatic"}},{"bayNumber":4,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":5,"manualAddresses":[],"li
censeIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":6,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumb
er":7,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":8,"manualAddresses":[],"licenseIntents":{"FCUp
grade":"Automatic"}}],"deviceBays":[{"bayNumber":1,"manualAddresses":[]},{"bayNumber":2,"manualAddresses":[]},{"bayNumber":3,"manu
alAddresses":[]},{"bayNumber":4,"manualAddresses":[]},{"bayNumber":5,"manualAddresses":[]},{"bayNumber":6,"manualAddresses":[]},{"
bayNumber":7,"manualAddresses":[]},{"bayNumber":8,"manualAddresses":[]},{"bayNumber":9,"manualAddresses":[]},{"bayNumber":10,"manu
alAddresses":[]},{"bayNumber":11,"manualAddresses":[]},{"bayNumber":12,"manualAddresses":[]}]},"/rest/enclosures/0000000000A66102"
:{"enclosureUri":"/rest/enclosures/0000000000A66102","interconnectBays":[{"bayNumber":1,"manualAddresses":[],"licenseIntents":{"FC
Upgrade":"Automatic"}},{"bayNumber":2,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":3,"manualAddre
sses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":4,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"
}},{"bayNumber":5,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":6,"manualAddresses":[],"licenseInt
ents":{"FCUpgrade":"Automatic"}},{"bayNumber":7,"manualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}},{"bayNumber":8,"m
anualAddresses":[],"licenseIntents":{"FCUpgrade":"Automatic"}}],"deviceBays":[{"bayNumber":1,"manualAddresses":[]},{"bayNumber":2,
"manualAddresses":[]},{"bayNumber":3,"manualAddresses":[]},{"bayNumber":4,"manualAddresses":[]},{"bayNumber":5,"manualAddresses":[
]},{"bayNumber":6,"manualAddresses":[]},{"bayNumber":7,"manualAddresses":[]},{"bayNumber":8,"manualAddresses":[]},{"bayNumber":9,"
manualAddresses":[]},{"bayNumber":10,"manualAddresses":[]},{"bayNumber":11,"manualAddresses":[]},{"bayNumber":12,"manualAddresses"
:[]}]}},"enclosureGroupUri":"/rest/enclosure-groups/5110abae-950e-4d19-ab85-a53f0099a512","firmwareBaselineUri":null,"forceInstall
Firmware":false,"initialScopeUris":[]}
VERBOSE: [SEND-HPOVREQUEST] Request: POST https://192.168.1.173/rest/logical-enclosures
```
In the doc I can see, enclosureBaySettings does not contain enclosure URIs, it only contains a deviceBays and interconnectBays array, and each array member contains a enclosureNumber property that refers to the position of the enclosure in the enclosureUris list outside of enclosureBaySettings. Yes, quite different from the enclosures property in the PUT call...

**Comment by ChrisLynchHPE** [comment]
This is finally fixed  in [Release 5.20.2515.1660](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.20.2515.1660) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2515.1660).

The 5.30 library is being published now.  So within the next few hours (barring anything further from failing in the lab), I'll post a reply with the link to the 5.30 update.

**Comment by ChrisLynchHPE** [comment]
The 5.30 version, [Release 5.30.2515.1313](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v5.30.2515.1313) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.530/5.30.2515.1313), is now published.

Please verify before this issue is closed.

**Comment by VincentBerger** [comment]
Fix verified, closing
