### ISSUE TITLE
__HPOneViewAdmin Account

### ISSUE THREAD

**Issue by tlauder** [HewlettPackard/POSH-HPOneView#502]
For the _HPOneViewAdmin accounts created on iLO during the initial setup of a new server in HPE OneView. Is the password the same for all servers you add to OneView, or is it different for each server? If it is different, is there a cmdlet to change the password per server (security reasons)?

**Comment by ChrisLynchHPE** [comment]
The account password is randomly generated for every single iLO, to the maximum allowed length by the ilo, including alpha and non-alpha numeric characters.  The only commonality is the account name.  There is no ability to change this value.  With the password being unique, what is the reason the password must be changed?  If the password happens to be compromised, it is only that 1 iLO.  Removing and re-adding it to the appliance would reset the password.  But I certainly would not expect a customer to do this to a production running server that is managed by OneView.

**Comment by tlauder** [comment]
Hi Chris,

As a security precaution, we rotate our iLO passwords monthly. Having the ability to rotate the OneViewAdmin account password is the only reason we are not able to implement OneView on our most secure servers. We have requested a feature enhancement since version 3.0 asking for HPE to change the OneViewAdmin account on a regular basis, but it has not gained traction.

Thanks,
Todd

**Comment by ChrisLynchHPE** [comment]
Unfortunately, this is not the right forum to inquire about product enhancements.  Feel free to contact me via email chris.lynch@hpe.com if you wish to discuss this further.
