### ISSUE TITLE
Get-OVAddressPool and Get-OVAddressPoolRange do not support IPv6

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#506]
### Expected Behavior
When executing Get-OVAddressPool, all pools including IPv6 pools should be returned.
When executing Get-OVAddressPool -Type IPv6, only IPv6 pools should be returned.
When executing Get-OVAddressPoolRange , all pool ranges including IPv6 pools should be returned.
When executing Get-OVAddressPoolRange -Type IPv6, only IPv6 pool ranges should be returned.

### Actual Behavior
When executing Get-OVAddressPool, all pools EXCEPT IPv6 are returned.
When executing Get-OVAddressPool -Type IPv6, only **IPv4** pools are returned.
When executing Get-OVAddressPoolRange , all pool ranges EXCEPT IPv6 are returned.
When executing Get-OVAddressPoolRange -Type IPv6, only **IPv4** pool ranges are returned.

### Steps to reproduce
Get-OVAddressPool
Get-OVAddressPool -Type IPv6
Get-OVAddressPoolRange 
Get-OVAddressPoolRange -Type IPv6

### Version Information
HPE OneView PowerShell Library Version 5.30.2541.2687
HPE OneView Appliance Version 5.30.00.421400.00
Output from `$PSVersionTable` on your Windows Host: 5.1.17763.1007

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting this.  As I am in the middle of getting an update released, this fix will be in the next library update.

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

Please verify prior to closing this issue.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
