### ISSUE TITLE
Add-OVServer -- ValidationError - Unable to determine...

### ISSUE THREAD

**Issue by docbios** [HewlettPackard/POSH-HPOneView#508]
Hi Support Team,

Since we switched our OV landscape to v5.40 we are facing node discovery issues with PS 

**The error message we getting back locks like that:**
_ValidationError - Unable to determine the hardware configuration for 'OV FQDN'
(PARSE_ERROR) at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception) at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )_

**used PS Library**
_PS C:\Users\> get-ovversion
[PLEASE READ] Due to Hewlett-Packard Enterprise and HP Inc. spinout legal
reasons, .....
LibraryVersion Path
5.40.2534.2926 C:\Program Files\*\HPEOneView.540\5.40.2534.2926_

**A discovery via -verbose option**

VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/version
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [[HPEOneView.PKI.SslValidator]::CertificateValidationCallBack()] Starting callback verification.
VERBOSE: [[HPEOneView.PKI.SslValidator]::CertificateValidationCallBack()] Certificate:  [Subject]
  CN=<appliance>, O=Hewlett Packard Enterprise, L=Palo Alto, S=California, C=US
[Issuer]
  CN=<appliance>, O=Hewlett Packard Enterprise, L=Palo Alto, S=California, C=US
[Serial Number]

[Not Before]
  7/18/2018 9:07:46 AM
[Not After]
  7/18/2028 9:07:46 AM
[Thumbprint]
  7D7ECD762738DDE7D323F32BE99ACBA1744DAD93
VERBOSE: [[HPEOneView.PKI.SslValidator]::CertificateValidationCallBack()] Host: '<appliance>'
VERBOSE: [[HPEOneView.PKI.SslValidator]::IsTrustedHost()] Looking for '<appliance>' within TrustedHosts dictionary.
VERBOSE: [[HPEOneView.PKI.SslValidator]::IsTrustedHost()] In TrustedHosts dictionary: 'False'
VERBOSE: [[HPEOneView.PKI.SslValidator]::CertificateValidationCallBack()] Cert has chain errors.
VERBOSE: [[HPEOneView.PKI.SslValidator]::CertificateValidationCallBack()] Processing 'UntrustedRoot' chain status.
DEBUG: [[HPEOneView.PKI.SslValidator]::ParseSubjectAlternativeName()] Init parse SAN from certificate.
DEBUG: [[HPEOneView.PKI.SslValidator]::ParseSubjectAlternativeName()] Certificate contains Subject Alternative Names. Parsing.
DEBUG: [[HPEOneView.PKI.SslValidator]::ParseSubjectAlternativeName()] Adding '<appliance>' to collection.
VERBOSE: [[HPEOneView.PKI.SslValidator]::CertificateValidationCallBack()] SAN contains host: True
VERBOSE: [[HPEOneView.PKI.SslValidator]::CertificateValidationCallBack()] Cert is self-signed, and untrusted.
VERBOSE: [[HPEOneView.PKI.SslValidator]::CertificateValidationCallBack()] Trusting Cert with no further chain errors.
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/logindetails
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/login-sessions
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: POST
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/roles
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/appliance/nodeinfo/version
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/version
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/sessions
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [[HPEOneView.PKI.SslValidator]::AddTrustedHost()] Adding host <appliance> to TrustedHosts collection.
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/index/resources?category=server-hardware&sort=name:asc&query=
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/server-hardware/30333436-3638-5A43-4A33-333330393458
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/server-hardware/30333436-3638-5A43-4A34-303930355146
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/server-hardware/30333436-3638-5A43-4A34-303930355135
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/server-hardware/33344D41-4137-4247-3830-30354A453636
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/server-hardware/39333835-3431-5A43-3330-343534303846
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/server-hardware/39333835-3431-4247-3830-333836423932
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/server-hardware
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: POST
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b?view=tree
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/tasks/55d7b17d-7cae-4e63-bc88-396b848dd38b
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [HPEOneView.Utilities.Net.RestClient] URI: https://<appliance>/rest/login-sessions
VERBOSE: [HPEOneView.Utilities.Net.RestClient] Method: DELETE
VERBOSE: [HPEOneView.Utilities.Net.RestClient] XApiVersion: 2000
VERBOSE: [[HPEOneView.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [[HPEOneView.Library.ConnectedSessionsList]::RemoveConnection()] Removing host <appliance> from collection.
VERBOSE: [[HPEOneView.Library.ConnectedSessionsList]::RemoveConnection()] Calling to remove host <appliance> from TrustedHost collection.
VERBOSE: [[HPEOneView.PKI.SslValidator]::RemoveTrustedHost()] Removing host <appliance> to TrustedHosts collection

**Comment by ChrisLynchHPE** [comment]
I'm sorry, but there is nothing here to help me understand what the problem is.  Can you please provide the code you are trying to use, what is happening, and what the expectations are of executing the code?

**Comment by NotTheEvilOne** [comment]
Hi Chris,

Maybe I can help here.

### Expected Behavior

HP servers added to an OV instance.

### Actual Behavior

Error result:
stateReason `ValidationError` - errorCode `PARSE_ERROR` - Message `Unable to determine the hardware configuration for 'OV FQDN'`

### Steps to reproduce

PS: `Add-OVServer -Hostname iloFQDN -Credential $Credential -monitored -Confirm:$false`

OV FQDN is an HPE OneView VM 5.40.00-0423953.

**Comment by ChrisLynchHPE** [comment]
This is a validation error.  Nothing changed with the Add-OVServer Cmdlet in any of the recent updates.  So either you have attempted to add an unsupported server, or there is an issue with OneView trying to parse the inventory of the iLO.   Are you able to add this server to your appliance via the UI?  If not, then please open a support case with the HPE Support Center, or through your HPE ASM.

**Comment by docbios** [comment]
We verified the setting and checked if we are able to add the servers via UI -> it is working.
The server type we are trying to add are Gen8 to Gen10
Also there are no changes within the executing of the commands in the script from our end.
Only change we made in the past upgrading from PS 5.20 to 5.40
We verified also for the supported .NET Framework and so on, since we are looking somehow in the fog -> nothing changed the behavior to a positive result.
May ask for a remote session with all involved persons in charge to analyze this strange behavior?

**Comment by ChrisLynchHPE** [comment]
The exception message provided in this thread is a message from the appliance.  The Cmdlet does nothing to perform the discovery of a server, unless the initial validation of the submitted task fails as the server is already claimed, to then allow the caller to override and force claim the server resource.

Are you using IP Address or FQDN/hostname when attempting to add your servers?  Have you validated that there are no DNS lookup issues if you are indeed using FQDN/hostname?  That can certainly explain why there would be inconsistent discovery.

Otherwise, please use the [Get-HPOVCommandTrace](https://hpe-docs.gitbook.io/posh-hpeoneview/cmdlets/v5.20/library/get-hpovcommandtrace) or [Get-OVCommandTrace](https://hpe-docs.gitbook.io/posh-hpeoneview/cmdlets/v5.40/library/get-ovcommandtrace) Cmdlet to generate an API trace of the issue and supply it here.

**Comment by docbios** [comment]
Hi Chris,
after some additional days of investigation and checking we could identify the issue causing that strange behavior.
We can confirm it was not related to any HPE related software release.
Therefore we can close this request and sorry for any inconvenience this request caused.

**Comment by ChrisLynchHPE** [comment]
Can you provide any input to what the cause was?  It would certainly help the community if anyone else experienced this issue in the future.
