### ISSUE TITLE
Feature Request: REAL SSO for AD-Users

### ISSUE THREAD

**Issue by CermakPOI** [HewlettPackard/POSH-HPOneView#51]
Hi,
It would be good if the Windows (Active Directory) credentials could be used directly from the logged o User. Without entering AuthLoginDomain+Username+Password
Would be helpful for automated Scripts like Backup.

__suggested new parameter:__
```powershell
Connect-HPOVMgmt -ConnectWithCurrentUser
```

**Comment by ChrisLynchHP** [comment]
We would love to support this feature, but we can't.  `System.Security.Principal.WindowsIdentity` can get us the current user, but does not expose or provide a method to decrypt the users password into plaintext.  HPE OneView does not support Kerberos ticketing.
