### ISSUE TITLE
Get-HPOVBaseline cannot handle multiple Baselines with the same name

### ISSUE THREAD

**Issue by MoritzMuellerHPE** [HewlettPackard/POSH-HPOneView#510]
### Expected Behavior
List of all Baselines.

### Actual Behavior
```
Exception calling ".ctor" with "4" argument(s): "The value  is not a semantic version format.
Parameter name: version"
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.520\HPOneView.520.psm1:29931 char:21
+ ...             $_FwComponentsList.Add(([HPOneView.Appliance.Baseline+FwC ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
 
Cannot convert argument "releaseDate", with value: "", for ".ctor" to type "System.DateTime": "Cannot convert null to type "System.DateTime"."
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.520\HPOneView.520.psm1:30070 char:25
+ ...             [HPOneView.Appliance.BaselineHotfix]::new($_baseline.name ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument
```
This issue occurs for those Baselines with the same name (different versions). The same issue happens when trying to add a Baseline to New-HPOVServerProfileTemplate. 

### Code
```
Connect-HPOVMgmt -Hostname -UserName -AuthLoginDomain -Password 
Get-HPOVBaseline
Disconnect-HPOVMgmt 
```

### Version Information

```
# Output from $PSVersionTable
Name                           Value                                                                                                                                                        
----                           -----                                                                                                                                                        
PSVersion                      5.1.17763.1007                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                      
BuildVersion                   10.0.17763.1007                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                          
SerializationVersion           1.1.0.1 

# CMDlet Version
HPOneView.520
5.20.2561.3357
```

**Comment by ChrisLynchHPE** [comment]
Your assessment isn't correct.  The name of the resource has nothing to do with the issue.  I'll need to you provide the output from `Get-HPOVCommandTrace -ScriptBlock { Get-HPOVBasline }` and attach the generated file.

**Comment by MoritzMuellerHPE** [comment]
[Get-HPOVBaseline.log](https://github.com/HewlettPackard/POSH-HPEOneView/files/5406798/Get-HPOVBaseline.log)

Here is the logfile generated by Get-HPOVCommandTrace

**Comment by ChrisLynchHPE** [comment]
The issue stems from the "Yeah custom ISO" present on the appliance.  Where did you get this from?  Is this a baseline you intend to use?  It looks like an incomplete baseline, as the firmware component catalog is missing quite a few important properties.  I have never seen a baseline defined like this before, so trying to figure out how to support it.

**Comment by MoritzMuellerHPE** [comment]
"Yeah custom ISO" isn't the Baseline I intend to use. 
The Baseline I want to use is "Service Pack for ProLiant". When specifying this in the Server Profile Template, the same issue arose. Since there are two Baselines with the name "Service Pack for ProLiant", I thought it may be an issue with that. Because when issuing following command `Get-HPOVBaseline -Name Service Pack for ProLiant`, same issue. But when specifying the Version `Get-HPOVBaseline -Name Service Pack for ProLiant -Version 2020.03.0`, no problem. So how do the Commandlets know which Baseline to gather when specifying only the name? But I will check on that "Yeah Custom ISO"

**Comment by ChrisLynchHPE** [comment]
The `-Name` parameter is a way to filter the results from the appliance REST API.  It isn't that the Cmdlet doesn't support handling baselines with the same name. The API allows the resources to be named the same, but the difference is the version, and subsequently the ISO file name to ensure it is unique.

But in this case, it appears the issue you are facing is with the "Yeah custom ISO" baseline.  Remove it from the appliance and use the Cmdlets again, and you should have results returned without exception.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you feel this is in error, please feel free to re-open this issue.
