### ISSUE TITLE
Unable to create Permanent Logical JBOD on on D3940 using New-OVServerProfileLogicalDisk

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#511]
### Expected Behavior

The New-OVServerProfileLogicalDisk cmdlet should let you check the "Permanent" checkbox for Logical JBODs. P.t. it seems only Erase On Delete is implemented.

### Actual Behavior

The New-OVServerProfileLogicalDisk cmdlet has no Permanent parameter for Logical JBODs

### Steps to reproduce

Correct Get-OVServerProfileTemplate set-up manually does not yield a Permanent parameter when you pipe it to ConvertTo-OVPowerShellScript

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`): 5.40.2559.2085
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  5.40.00.423953.00
Output from `$PSVersionTable` on your Windows Host:

```PowerShell
# PSVersion: 5.1
```

**Comment by ChrisLynchHPE** [comment]
This will be enhanced in the 5.20 and newer libraries.

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

Please verify prior to closing this issue.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
