### ISSUE TITLE
OV PS 5.20 - New-HPOVServerProfile failing w/ Physical WWNs

### ISSUE THREAD

**Issue by ericholton** [HewlettPackard/POSH-HPOneView#513]
# Expected Behavior
Attached script should create a server profile with existing managed volumes and physical WWNs

### Actual Behavior
The error seems to indicate that there is a mismatch between the global setting for physical vs virtual WWNs but I believe the settings match. Even so, shouldn't it be possible to create a server profile using physical WWNs even if Virtual WWNs are enabled globally. I did try enabling Virtual WWNs and it didn't help.

### Steps to reproduce
Run the attached script. Unfortunately, it does require a number of preconfigured networks and volumes.

```PowerShell
# 1. Capture verbose output using the Get-HPOVCommandTrace for HPOneView.310 or newer, or append the -Verbose switch to your Cmdlet call.
The script and output are attached to this.
# 2. Put your code and/or captured output here.
This is the non-verbose output.
PS C:\Users\Administrator\Desktop> .\HA-DRS-Cluster-Node3.ps1
New-HPOVServerProfile : When the WWPN type is not user-defined, the WWPN type must be the same as the global wwpnType
assignment (Physical).
At C:\Users\Administrator\Desktop\HA-DRS-Cluster-Node3.ps1:120 char:1
+ New-HPOVServerProfile -Name $name -Server $server -ServerHardwareType ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (AsyncronousTask:String) [New-HPOVServerProfile], ServerProfileResourc
   eException
    + FullyQualifiedErrorId : InvalidOperation,New-HPOVServerProfile
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  
Output from `$PSVersionTable` on your Windows Host:

```powershell
PS C:\Users\Administrator\Desktop> Get-HPOVVersion

synergy.hpe.local                   LibraryVersion Path
-----------------                   -------------- ----
ApplianceVersion: 5.20.01.420365.00 5.20.2561.3357 C:\Program Files\WindowsPowerShell\Modules\HPOneView.520\5.20.256...


PS C:\Users\Administrator\Desktop> Get-HPOVVersion -ApplianceVer

synergy.hpe.local                   LibraryVersion Path
-----------------                   -------------- ----
ApplianceVersion: 5.20.01.420365.00 5.20.2561.3357 C:\Program Files\WindowsPowerShell\Modules\HPOneView.520\5.20.256...

PS C:\Users\Administrator\Desktop> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

[HA-DRS-Cluster-Node3.txt](https://github.com/HewlettPackard/POSH-HPEOneView/files/5448176/HA-DRS-Cluster-Node3.txt)
[output.txt](https://github.com/HewlettPackard/POSH-HPEOneView/files/5448177/output.txt)

**Comment by ChrisLynchHPE** [comment]
Did someone disable WWN address pools on the appliance?  It appears that you are trying to create another server profile template resource from one appliance to another.  Do I have that assumption right?  If so, this isn't a bug with the Cmdlet, rather the appliance needs to be examined why WWN's are disabled, which likely there isn't an available pool to assign from.  The profile that you are trying to create uses virtual address assignment, so address pools must be defined and have available capacity.

**Comment by ericholton** [comment]
Hi Chris, yes, the virtual WWNs are disabled because zoning isn't integrated into Synergy. The profile I am trying to create is set to use Physical WWNs. That said, I did try enabling the Virtual WWN pool but still got the same error.

I believe the command is correct. The last line in the HA-DRS-Cluster-Node3.txt file, the powershell script file, set the WwnAssignement to "Physical".

Thanks,
Eric

**Comment by ChrisLynchHPE** [comment]
Can you supply the JSON of the source server profile so I can examine it?  You can do that with this command:

```powershell
Get-HPOVServerProfile -Name "Profile Name" | ConvertTo-Json -Depth 99 | Out-File $env:Temp\server-profile.json
```

Then attach that created file here.

**Comment by ericholton** [comment]
Here is that output file renamed to .txt so that it can be uploaded. Thanks!

[server-profile.txt](https://github.com/HewlettPackard/POSH-HPEOneView/files/5466544/server-profile.txt)

**Comment by ChrisLynchHPE** [comment]
Well, it appears New-HPOVServerProfile isn't handling this type of profile correctly.  Meaning, if connections are supposed to use physical addresses, then they are not being set to the right assignment type.  The same exists for New-HPOVServerProfileTemplate.  I have this identified and a fix in place.

In the meantime, you can do the following:

```powershell
# Replace the last line of the generated PowerShell code from ConvertTo-HPOVPowerShellScript to the following
$prf = New-HPOVServerProfile -Name $name -Server $server -ServerHardwareType $sht -EnclosureGroup $eg -Affinity $affinity -Connections $connections -LocalStorage  -StorageController $controllers -SanStorage -HostOsType $osType  -StorageVolume $volumeAttachments -ManageBoot:$manageboot -BootMode $biosBootMode -BootOrder $bootOrder -HideUnusedFlexNics $true -WwnAssignment $wwnType -Passthru

# Update the connections with the 'Physical' property value
$prf.connectionSettings.connections | ForEach {
    $_.macType = 'Physical'
    $_.wwnType = 'Physical'
}

Send-HPOVRequest -Uri "/rest/server-profiles' -Method POST -Body $prf | Wait-HPOVTaskComplete
```

**Comment by ericholton** [comment]
I will test no later than Monday. The servers are in use today. Thank you!

**Comment by ericholton** [comment]
I have been testing for several hours and can't make it work. First, the 'Passthru' fails because it isn't Virtual, Physical, or Userdefined. So I tried Virtual and UserDefined but the library expects a single quote at the beginning of the name: 'UserDefined, but then that fails. 

When I set it to Virtual, also enabled a virtual pool, the profile was created but the adapters couldn't be changed to 'physical'. When I create the profile manually, once the profile is created, the wwnType cannot be changed.

Any other thoughts or suggestions?

**Comment by ChrisLynchHPE** [comment]
What I am suggesting is that you use the code that was generated, but append `-Passthru` as noted in the sample to `New-HPOVServerProfile` Cmdlet call.  Then, in the variable, change the `wwpnType` and `macType` properties from Virtual to Physical.  I tested this code in my lab prior to providing you with a viable workaround until a 5.20 library is published with this addressed.

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

Closing.
