### ISSUE TITLE
Set-OVApplianceCurrentSecurityMode does not return HPEOneView.Appliance.SecurityMode after (successful) reboot

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#517]
### Expected Behavior

Get-OVApplianceAvailableSecurityMode -ModeName CNSA | Set-OVApplianceCurrentSecurityMode -Confirm:$false

should return a HPEOneView.Appliance.SecurityMode object post-reboot

### Actual Behavior

Get-OVApplianceAvailableSecurityMode -ModeName CNSA | Set-OVApplianceCurrentSecurityMode -Confirm:$false

The cmdlet returns blank (Wiki says it should return an HPEOneView.Appliance.SecurityMode object) and will prompt "Appliance rebooting" 10 minutes after a successful reboot.

Is it possible to have it write "Appliance rebooting" less often?

![image](https://user-images.githubusercontent.com/20067955/98705759-568f1080-237e-11eb-95da-5c69065e4b21.png)

### Steps to reproduce

See above.

### Version Information
HPE OneView PowerShell Library Version (Get-HPOVVersion or $PSLibraryVersion): 5.50.2591.2980
HPE OneView Appliance Version (Get-HPOVVersion -ApplianceVer): 5.50.00.426657.00
Output from $PSVersionTable on your Windows Host: 5.1.17763.1432

```PowerShell
# Output from $PSVersionTable
```

**Comment by ChrisLynchHPE** [comment]
The `WARNING: Appliance is rebooting` message is only supposed to be displayed once.

As for the returned object, yes it will be returned after the appliance has rebooted.  There is no guaranteed way to return that object before the appliance reboots.

**Comment by erikgraa** [comment]
Seems to write the warning every 30 seconds in the `Wait-OVTaskComplete` function.

No object was returned when I tried earlier today with either CNSA or FIPS, but the prompt was released after 10 minutes or so after the UI had become usable post-reboot. I surmise it does something until then.

Is it the Send-OVRequest that should have returned the object?

**Comment by ChrisLynchHPE** [comment]
> Seems to write the warning every 30 seconds in the Wait-OVTaskComplete function.

Correct.  That will be shown only 1 time now with the change I have made.

> No object was returned when I tried earlier today with either CNSA or FIPS,

Please provide the library version you are using using `$PSLibraryVersion`.  Without that (and that was required data when you created this issue), I have to dig through a number of released libraries to see where this could be getting hung up at.

**Comment by erikgraa** [comment]
> > No object was returned when I tried earlier today with either CNSA or FIPS,
> 
> Please provide the library version you are using using `$PSLibraryVersion`. Without that (and that was required data when you created this issue), I have to dig through a number of released libraries to see where this could be getting hung up at.

5.50.2591.2980 as stated above (HPEOneView.550)

**Comment by ChrisLynchHPE** [comment]
The doc return object is incorrectly documented.  It is supposed to be the async task that was created.  I'll have to look into that further, as something may have changed with the API behavior in OneView 5.50.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
