### ISSUE TITLE
Feature parity between HPE OneView 5.50 automatic retrieval of Host SSH Key and Set-OVAutomaticBackupConfig which requires the HostSSHKey parameter

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#519]
# Summary of the new feature/enhancement

Set-OVAutomaticBackupConfig requires that the Host SSH Key is input whereas the HPE OneView 5.50.00 UI will retrieve it for you automatically

Feature parity would be nice in such a way that the parameter is recommended, but optional

**Comment by ChrisLynchHPE** [comment]
I'm about to publish an update to the 5.50 library.  The other versions will follow later this week.

**Comment by erikgraa** [comment]
I tried the enhanced Cmdlet today unsuccessfully, but haven't been able to troubleshoot yet. Will let you know in a bit.

The error was:

![image](https://user-images.githubusercontent.com/20067955/99706340-34db0b00-2a9b-11eb-9214-b5e5e5ba9e66.png)

**Comment by erikgraa** [comment]
The above error was related to a firewall opening. I can confirm the enhanced functionality works as intended!

**Comment by erikgraa** [comment]
Addendum: Are you in touch with the people in HPE working on Global Dashboard? It would be nice if automatic SSH key retrieval were possible in the UI. The Automatic Backup Configuration UI in Global Dashboard also forces you to input a backup directory (i.e. backing up to the designated root folder for a user isn't possible as it is in OneView)

Is an official HPE OneView Global Dashboard PowerShell Library in the works by the way?

**Comment by ChrisLynchHPE** [comment]
I will let the OVGD PM know about the request to pull SSH/SFTP public keys like OV does.

As for an OVGD PowerShell library, unfortunately, we don't have one today.

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)

Closing.
