### ISSUE TITLE
New-HPOVBackup Result handling

### ISSUE THREAD

**Issue by CermakPOI** [HewlettPackard/POSH-HPOneView#52]
Hi,
Would it be possible to return an Result for the function New-HPOVBackup ?
Now it returns ... nothing. So i don't know if the backup was sucessfull, 
```powershell
PS Z:\10_Powershell> $r= New-HPOVBackup -Location d:\HPOV
PS Z:\10_Powershell> $r
PS Z:\10_Powershell>
```
I would prefer if it returned an Result Object containing the State and the path of the new Backup File:
Usually i use an simple Object like this in all my functions :
```powershell
$objResult = "" | Select-Object OK,Num,Txt,Obj
$obj?Result.ok  = $false | $True
$obj?Result.Num = Number, see down
$obj?Result.Txt = "Backup created successfully in Path '...'" or "Backup failed, Reason: ..."
$obj?Result.obj = this is optional, but i like to put objects here, like a filesystem-item object form get-item or get-childitem
```
__Numbers__ from Standard Windows Error Codes:
0 The operation completed successfully.
1 Incorrect function.
2 The system cannot find the file specified.
3 The system cannot find the path specified.
4 The system cannot open the file.
5 Access is denied.
6 The handle is invalid.
...
I'm sure you understand how i mean it.

btw if i don't assign the result to a variable, i get the backup path displayed - why?
```powershell
PS Z:\10_Powershell> New-HPOVBackup -Location d:\HPOV


    Directory: D:\


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        22.12.2015     07:46            HPOV
```

**Comment by ChrisLynchHP** [comment]
We try to follow the API's return logic, so not to confuse custom versus actual behaviors.  I have added this request to our backlog and will return an object with the following properties:

``` PowerShell
[PSCustomObject]@{
   status = 'Completed';
   file = 'C:\Path\to\file.ext';
   ApplianceConnection = [HPOneView.Appliance.Connection].Name
}
```

As for the path output being captured, if the ```-location``` parameter doesn't exist, it is created for the caller.

**Comment by ChrisLynchHP** [comment]
[Release 2.0.111.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.111.0) has this enhancement.
