### ISSUE TITLE
Feature Request: Get-HPOVServer -Name option

### ISSUE THREAD

**Issue by xusarmy** [HewlettPackard/POSH-HPOneView#523]
I've modified this script to first run Import-csv a CSV file that has a Server profile name, MGMT NIC, vMotion NIC and the Serial Number.  I so wish that Get-HPOVServer could accept the serial number with the -Name option, but what I have had to do is do it this way:

$Server = Get-HPOVServer | Where-Object serialnumber -eq $object.ServerSN

I also used the convert to powershell script of a server profile template so I have all the options that are required by the OSdeployment piece, and I dont have to include the password, since it was captured in the original template.

**Comment by ChrisLynchHPE** [comment]
This will be added to the next round of library updates after the US holiday break:

![Screenshot 2020-11-19 094544](https://user-images.githubusercontent.com/6956305/99703490-03871e80-2a4c-11eb-85d3-6f73f7c40a04.png)

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

**Comment by ChrisLynchHPE** [comment]
Closing.
