### ISSUE TITLE
Cmdlet(s) for Emergency Local Login

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#525]
I have been unable to find the cmdlet(s) for disabling and enabling Emergency Local Login. Can you advise me on the correct procedure?

**Comment by ChrisLynchHPE** [comment]
It appears to be within the Cmdlet to set two factor authentication, which is not right.  This really needs to be within the Set-OVLdapDefaultDirectory Cmdlet.  I'll work to enhance and fix this.

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

The [Set-OVLdapDefaultDirectory](https://hpe-docs.gitbook.io/posh-hpeoneview/cmdlets/v5.50/security/set-ovldapdefaultdirectory) Cmdlet has been updated to properly set the default authentication directory, and to configure local logins, emergency logins, and what emergency login type allowed.

Please verify prior to closing this issue.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
