### ISSUE TITLE
Cmdlet for starting the second Composer Node in a Synergy prior to enabling HA

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#528]
Is there a Cmdlet for starting the second Composer Node in a HPE Synergy after you have e.g. done a Factory Reset?

The Cmdlet ```Enable-OVComposerHANode``` exists but requires that the second Composer Node is already started.

**Comment by ChrisLynchHPE** [comment]
It looks like the Cmdlet that I wrote wasn't exported, and isn't available to use.  In the meantime, you can use the following to perform that operation:

```powershell
$BayID = 1
$Enclosure = Get-OVEnclosure -Name EnclosureName

$_request = @{

    op    = 'replace';
    path  = ('/applianceBays/{0}/power' -f $BayID);
    value = 'on'

}

Send-OVRequest -Uri $Enclosure.uri -Method PATCH -Body $_PatchRequest -AddHeader @{'If-Match' = $Enclosure.eTag} | Wait-OVTaskComplete
```

**Comment by erikgraa** [comment]
Thank you @ChrisLynchHPE

**Comment by ChrisLynchHPE** [comment]
You're welcome.  Do know that you can only power on a device, which will be provided by `Start-OVEnclosureAppliance`.  You stop or power off a Composer or VM using [Stop-OVAppliance](https://hpe-docs.gitbook.io/posh-hpeoneview/cmdlets/v5.50/appliance/stop-ovappliance).

**Comment by ChrisLynchHPE** [comment]
I added this Cmdlet to the [Release 5.50.2607.2724](https://github.com/HewlettPackard/POSH-HPEOneView/releases/tag/v5.50.2607.2724) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2607.2724).

**Comment by ChrisLynchHPE** [comment]
This issue will be addressed in other library versions after the US holiday break, in early Dec.

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the following releases:

* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
