### ISSUE TITLE
Are Server Profile Templates supported on POSH 2.0

### ISSUE THREAD

**Issue by tknightblc** [HewlettPackard/POSH-HPOneView#53]
Not seeing any way to create OV 2.0 Server profile templates or create a new profile from a OV 2.00 server profile template. I can do it the 1.20 way of not assigning a server profile to a bay, but want to use true templates. 

Am I missing something or is this not yet supported?

**Comment by ChrisLynchHP** [comment]
Yes, we have 3 CMDLETs:

* New-HPOVServerProfileTemplate 
* Get-HPOVServerProfileTemplate
* Join-HPOVServerProfileToTemplate

However, looking at the mainly module, none are exported.  So they exist, just an external caller cannot access them.  That is an omission on our part.  That will be fixed on the next release.

**Comment by ChrisLynchHP** [comment]
[Release 2.0.111.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.111.0) adds these CMDLETs and New-HPOVServerProfile was extended to support provisioning Server Profiles from a Server Profile Template.
