### ISSUE TITLE
Registry Error with Version  5.40.2551.2353

### ISSUE THREAD

**Issue by MarcelDuke** [HewlettPackard/POSH-HPOneView#530]
Hi, by switching from POSH-HPEOneView 4 to Version: 5.40.2551.2353, we've tracked an Issue with the Module.
With Importing the Module, it tries to put an entry in the Registry with:

`New-Item "HKCU:\Software\Hewlett-Packard\HPOneView" -force | Out-Null`

When we try to import the Module in a Script with, i.e. a Service User, that is not a Local Admin, we get an Error and the Module can't be loaded.

**Comment by ChrisLynchHPE** [comment]
This shouldn't happen as the location is HKEY_CURRENT_USER, to which the user should have the necessary permissions to create, update, read and delete anything within that section of the registry hive.  Are you sure this isn't a local permissions issue with the account you are using?

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you feel this is in error, please feel free to re-open this issue.
