### ISSUE TITLE
New-OVSNMPTrapDestination with SNMPv3 Enabled produces incorrect JSON values

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#539]
### Expected Behavior
When creating a snmpTrap with SNMPV3, the JSON structure should:
a) have username specified
b) Not have communityString configured to Public

### Actual Behavior
Username is empty
CommunityString = Public

### Steps to reproduce

```PowerShell
$user = New-OVSnmpV3User -username 'snmpv3user' -SecurityLevel None 
$trap   = New-OVSnmpTrapDestination   -Destination "10.10.10.10"  -Port 162   -NotificationType "Inform"  -SnmpFormat SNMPv3  -SnmpV3user $user
$trap | fl *
trapDestination    : 10.10.10.10
communityString    : public
trapFormat         : SNMPv3
trapSeverities     : {}
vcmTrapCategories  : {}
enetTrapCategories : {}
fcTrapCategories   : {}
userName           :
inform             : True
engineId           :
port               : 162
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):  5.20.2597.1857
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  ApplianceVersion: 5.40.00.424900.00
Output from `$PSVersionTable` on your Windows Host: 5.1.14409.1018

```PowerShell
# Output from $PSVersionTable
```

**Comment by DungKHoang** [comment]
Fixed in 5.50

**Comment by ChrisLynchHPE** [comment]
A 5.50 library that fixes this issue has not been released yet.

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)
