### ISSUE TITLE
Invalid HelpInfoURI in module manifest

### ISSUE THREAD

**Issue by bradyevans** [HewlettPackard/POSH-HPOneView#54]
Unable to update help because of invalid URI..

**Comment by ChrisLynchHP** [comment]
Thank you for reporting this.  This has been a known issue internally, just not added to the Issue Tracker.  We have been working to get this resolved.  In the meantime, please use the -Online switch with your Get-Help call to read the most current documentation until we can resolve this.

**Comment by ChrisLynchHP** [comment]
[Release 2.0.111.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.111.0) has the correct HelpInfoUri and the offline help system files have been staged correctly.
