### ISSUE TITLE
SNMPConfiguration for LIG : error with EngineID in SNMPv3 User

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#540]
### Expected Behavior
Create a LIG with snmp configuration

### Actual Behavior
When creating a snmptrap destination for a LIG, the help file states that there is NO need to specify EngineID for SNMPv3 user.
However, when we create a LIG with snmpConfiguration, it states that engineID is required

### Steps to reproduce

```PowerShell
# -------------- Attributes for LIG "LIG-Ethernet"
$name                                  = "LIG-Ethernet"
$frameCount                            = 3
$interconnectBaySet                    = 3
$fabricModuleType                      = 'SEVC40f8'
$redundancyType                        = "HighlyAvailable"
$bayConfig                             = @{Frame1=@{Bay3='SEVC40f8';Bay6='SE20ILM'};Frame2=@{Bay3='SE20ILM';Bay6='SEVC40f8'};Frame3=@{Bay3='SE20ILM';Bay6='SE20ILM'}}
$enableNetworkLoopProtection           = $True
$enableRichTLV                         = $False
$enableTaggedLldp                      = $False
$lldpIpAddressMode                     = 'IPV4'
$interconnectConsistency               = 'Exact'


$communityString                       = 'ligRead'
$contact                               = 'dung@hpe.com'


$snmpv3Users                           = [System.Collections.ArrayList]::new()



write-host -foreground CYAN "----- Creating snmpV3 user lig-snmpUser " 
$securepass                             = 'password' | ConvertTo-SecureString -AsPlainText -Force  
$snmpv3User1                           = new-OVSnmpV3User  -UserName "lig-snmpUser" -AuthProtocol SHA -AuthPassword $securepass -privProtocol des56 -privPassword $securepass -securityLevel AuthandPriv


$snmpv3Users                           = @($snmpv3User1)

write-host -foreground CYAN "----- Creating snmp trap $trap1 " 


$trap1                                 = New-OVSnmpTrapDestination   -Destination "10.10.10.10"  -Port 162   -NotificationType "Inform"  -SnmpFormat SNMPv3  -SnmpV3user $snmpV3user1 

"temporary fix for trap"
$trap1.PSObject.Properties.Remove('communityString')
$trap1.username                         = 'lig-snmpUser'

$snmpTraps                             = @($trap1)
$snmpConfiguration                     = New-OVSnmpConfiguration  -snmpV1 $True -ReadCommunity $communityString  -Contact $contact  -snmpV3 $True   -TrapDestination $snmpTraps   -snmpV3Users $snmpv3Users 


$snmpConfiguration


 New-OVLogicalInterconnectGroup -Name $name  -fabricModuleType $fabricModuleType -frameCount $frameCount -interConnectBaySet $interConnectBaySet  `
             -Bays $bayConfig -FabricRedundancy $redundancyType `
             -snmp $SnmpConfiguration
```

### Version Information
HPE OneView PowerShell Library Version (Get-HPOVVersion or $PSLibraryVersion): 5.20.2597.1857
HPE OneView Appliance Version (Get-HPOVVersion -ApplianceVer): ApplianceVersion: 5.40.00.424900.00
Output from $PSVersionTable on your Windows Host: 5.1.14409.1018

```PowerShell
# Output from $PSVersionTable
```
[2012300036_needEngineID_transcript.log](https://github.com/HewlettPackard/POSH-HPEOneView/files/5752564/2012300036_needEngineID_transcript.log)

**Comment by ChrisLynchHPE** [comment]
The documentation is correct. What isn't is the fact that if you don't provide a value for the SNMPv3 engine ID, an API caller shouldn't be attempting to pass the engine ID property, as it cannot be null.  So, this is a bug, but not with the documentation.

**Comment by DungKHoang** [comment]
Fixed in 5.50 library

**Comment by ChrisLynchHPE** [comment]
A 5.50 library that fixes this issue has not been released yet.

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)
