### ISSUE TITLE
OV POSH: 5.40: New-OVNetworkSet fails to create network set with untagged network

### ISSUE THREAD

**Issue by ramakrishnan20** [HewlettPackard/POSH-HPOneView#541]
While creating a network set along with untagged network OV POSH API New-OVNetworkSet fails to create. Same thing is possible via GUI.

We have networks vMotion and FT already created in OV., When we create a network set grouping them by adding vMotion as untagged and FT as tagged the creation fails.

It throws the following error.
New-OVNetworkSet : The native network URI: /rest/ethernet-networks/641598b5-ca1f-47ad-b478-c430257d5add is not a member of the network(s) in the vMotion_FT_Set network set.

Following is the code snippet:

![image](https://user-images.githubusercontent.com/62111482/103999767-531fd600-51c3-11eb-9d77-4f66b3b4e4d2.png)

I have attached the output of the command trace.
[2101080321_HPEOV_transcript.log](https://github.com/HewlettPackard/POSH-HPEOneView/files/5786406/2101080321_HPEOV_transcript.log)

OV POSH version: 5.40
OV Appliance version: 5.50
Windows powershell: 5.1

**Comment by ChrisLynchHPE** [comment]
When setting trying to set the untagged  network, it must also be within the array of networks provided in the `-Networks` parameter.  If it isn't, then an error is generated.  Ensure you are providing the right untagged network.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity. If you believe this is in error, please feel free to re-open.
