### ISSUE TITLE
New-OVIloDirectoryGroup requires GroupSID while the GUI does not

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#543]
### Expected Behavior

When creating iLO directory Group with the GUI, GroupSid can be blank.
When using the cmdlet new-ovIloDirectoryGroup, the parameter -GroupSiD is mandatory
### Actual Behavior
GroupSiD is mandatory in new-OVIloDirectoryGroup

### Version Information
HPE OneView PowerShell Library Version (Get-HPOVVersion or $PSLibraryVersion): 5.40.2605.2185
HPE OneView Appliance Version (Get-HPOVVersion -ApplianceVer): ApplianceVersion: 5.40.00.424900.00
Output from $PSVersionTable on your Windows Host: 5.1.14409.1018

```PowerShell
# Output from $PSVersionTable
```

**Comment by DungKHoang** [comment]
Fixed in 5.50

**Comment by ChrisLynchHPE** [comment]
A 5.50 library that fixes this issue has not been released yet.  Re-opening.

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) release.  Please confirm before closing this issue.

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)
