### ISSUE TITLE
SAT toolkit 2.5 not able to connect to Synergy oneview , but from PowerShell it works fine. Tried disabling/enabling proxy still have the same issue.

### ISSUE THREAD

**Issue by ChrisLynchHPE** [HewlettPackard/POSH-HPOneView#544]
SAT toolkit 2.5 not able to connect to Synergy oneview , but from PowerShell it works fine. Tried disabling/enabling proxy still have the same issue.

FYI.. FQDN is updated in the host's file on the window machine and DNS lookup work fine.

Output from sat tool  --> **connection fails on browser**
==============

VERBOSE: [HPOneView.Utilities.Net.RestClient] URI: https://x.x.x.x/rest/version
VERBOSE: [HPOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPOneView.Utilities.Net.RestClient] XApiVersion: 1200
VERBOSE: [[HPOneVIew.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for [System.Net.ServicePointManager.SecurityProtocol].
VERBOSE: [[HPOneView.Library.ConnectedSessionsList]::RemoveConnection()] Removing host x.x.x.x from collection.
VERBOSE: [[HPOneView.Library.ConnectedSessionsList]::RemoveConnection()] Calling to remove host x.x.x.x from TrustedHost collection.
VERBOSE: [[HPOneView.PKI.SslValidator]::RemoveTrustedHost()] Host x.x.x.x does not exist in TrustedHosts collection.
**The operation has timed out
No valid devices to run this validation.
Failed to connect to OneView.**

Output from power shell ---> **Connection successful** 
================

VERBOSE: [[HPOneView.PKI.SslValidator]::CertificateValidationCallBack()] Host: 'x.x.x.x '
VERBOSE: [[HPOneView.PKI.SslValidator]::IsTrustedHost()] Looking for 'x.x.x.x ' within TrustedHosts dictionary.
VERBOSE: [[HPOneView.PKI.SslValidator]::IsTrustedHost()] In TrustedHosts dictionary: 'False'
VERBOSE: [[HPOneView.PKI.SslValidator]::CertificateValidationCallBack()] Cert has chain errors.
VERBOSE: [[HPOneView.PKI.SslValidator]::CertificateValidationCallBack()] Processing 'UntrustedRoot' chain status.
DEBUG: [[HPOneView.PKI.SslValidator]::ParseSubjectAlternativeName()] Init parse SAN from certificate.
DEBUG: [[HPOneView.PKI.SslValidator]::ParseSubjectAlternativeName()] Certificate contains Subject Alternative Names. Parsing.
DEBUG: [[HPOneView.PKI.SslValidator]::ParseSubjectAlternativeName()] Adding 'xyz.glhc-hpe.local' to collection.
DEBUG: [[HPOneView.PKI.SslValidator]::ParseSubjectAlternativeName()] Adding 'xxy' to collection.
DEBUG: [[HPOneView.PKI.SslValidator]::ParseSubjectAlternativeName()] Adding 'x.x.x.x ' to collection.
DEBUG: [[HPOneView.PKI.SslValidator]::ParseSubjectAlternativeName()] Adding 'fe80:0000:0000:0000:aae1:c6b0:ac2e:ed15' to collection.
VERBOSE: [[HPOneView.PKI.SslValidator]::CertificateValidationCallBack()] SAN contains host: True
VERBOSE: [[HPOneView.PKI.SslValidator]::CertificateValidationCallBack()] Cert is self-signed, and untrusted.  Host matches 1 or more Subject Alertnative Name extension values.
VERBOSE: [[HPOneView.PKI.SslValidator]::CertificateValidationCallBack()] Trusting Cert with no further chain errors.
VERBOSE: [HPOneView.Utilities.Net.RestClient] URI: https://x.x.x.x/rest/logindetails
VERBOSE: [HPOneView.Utilities.Net.RestClient] Method: GET
VERBOSE: [HPOneView.Utilities.Net.RestClient] XApiVersion: 1200
VERBOSE: [[HPOneVIew.PKI.SslValidator]::SslValidation()] Enforcing TLS1, TLS1.1 and TLS1.2 only for **[System.Net.ServicePointManager.SecurityProtocol].
This management appliance is a company owned asset and provided for the exclusive use of authorized personnel. Unauthorized use or abuse of this system may lead to corrective action including termination, civil and/
or criminal penalties.**

_Originally posted by @prabhum456 in https://github.com/HewlettPackard/POSH-HPEOneView/discussions/542_

**Comment by ChrisLynchHPE** [comment]
Please specify what the version of the library is.  Ensure that you have an empty PowerShell profile for testing to rule out any custom profile settings  (see more at [about_Profiles](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.1))

**Comment by prabhum456** [comment]
Thanks, @ChrisLynchHPE . 
It was a profile issue, the interesting part was an issue was seen on 4.8 .net but not on the 4.7.2 .net.
with the error message below from the library, I installed new windows with 4.7.2 and it worked.

![image](https://user-images.githubusercontent.com/55988297/104678612-d2f0f780-5711-11eb-90b3-97393ad29cd0.png)

**Comment by prabhum456** [comment]
I did not create any profile as part of the deployment guide, Just want to understand when does this profile gets created or modified.

**Comment by ChrisLynchHPE** [comment]
For PowerShell 5 and older, I think a blank one is created, for the console and ISE. PowerShell 7 you have to create it. And there is no ISE for PowerShell 7.

**Comment by ChrisLynchHPE** [comment]
If this is solved, then I am closing this.

**Comment by ChrisLynchHPE** [comment]
As for the .NetFramework, make sure you are installing the correct language pack as well.  If you don't, it won't increment the CLR version that the module checks for.
