### ISSUE TITLE
Feature Request   New-OVUplinkSet  to set  port speed and FEC mode for Ethernet uplinks of VC SE 100Gb F32 LIG/LI

### ISSUE THREAD

**Issue by nightzone** [HewlettPackard/POSH-HPOneView#555]
# Summary of the new feature/enhancement

New-OVUplinkSet     should be able to set port speed and FEC mode for Ethernet uplinks of VC SE 100Gb F32 LIG/LI

# Proposed technical implementation details (optional)

Currently not possible set port speed and FEC mode for Ethernet uplink ports of VC SE 100Gb F32. 
It would be good to have such option.

**Comment by ChrisLynchHPE** [comment]
What is "FEC mode"?  As for uplink port speed, auto negotiation is more than fine here.  There is no need to enforce it, as there is no Duplex negotiation in 10Gb and faster specs. Plus, it would make the `-UplinkPorts` object complex to define.

**Comment by nightzone** [comment]
@ChrisLynchHPE   
FEC is Forward Error Correction, can be configured for 25/100 Gb Ethernet uplink ports.

The need for and use of FEC increases as the signaling speed increases. However, certain switches do not enable or disable the FEC mode automatically based on the auto-negotiated transmission speed. This FEC mode must be set manually with the speed while editing the uplink sets.

From json file perspective this values are returned with Get-OVLogicalInterconnectGroup
- desiredSpeed
- desiredFecMode

                    "logicalPortConfigInfos": [
                        {
                            "logicalLocation": {
                                "locationEntries": [
                                    {
                                        "type": "Enclosure",
                                        "relativeValue": 1
                                    },
                                    {
                                        "type": "Port",
                                        "relativeValue": 70
                                    },
                                    {
                                        "type": "Bay",
                                        "relativeValue": 3
                                    }
                                ]
                            },
                            "desiredSpeed":  "Speed100G",
                            "desiredFecMode": "Cl74"
                        },

**Comment by ChrisLynchHPE** [comment]
Thanks.  I was looking at the UI to know where this feature was.

So, I'll add two new parameters then:

* `-PortSpeed`
* `-FecMode`

Which will be for all specified ports provided in the `-UplinkPorts` hashtable.

**Comment by ChrisLynchHPE** [comment]
This feature was added to the 6.x releases of the library.

Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
