### ISSUE TITLE
Missing use case in the Cmdlet New-OVLdapGroup

### ISSUE THREAD

**Issue by phsimons** [HewlettPackard/POSH-HPOneView#557]
# Summary of the new feature/enhancement

I am using an appliance that is connected to AD with a service account.
I want to use New-OVLdapGroup to select a group in AD and assign it some roles/permissions.
But the command requiers authentication (mandatory) (I am already connected to the appliance with Connect-OVMgmt)

In the GUI/Web interface I don't need to provide credential to perform this operation.

# Proposed technical implementation details (optional)

I would expect the New-OVLdapGroup to reply on the -ApplianceConnection

**Comment by ChrisLynchHPE** [comment]
After looking at this when you first reported it on the HPE OneView Communities forum, the Cmdlet does support this, just not relaxing the credential requirement.  So, if you provide the `-Credential` parameter with a dummy value, like:

```powershell
New-OVLdapGroup -Credential (Get-Credential -Username dummy)
```

It should work.  I will be looking to address this in both `New-OVLdapGroup` and `Set-OVLdapGroup`.

**Comment by ChrisLynchHPE** [comment]
The `-Credential` parameter was relaxed and no longer required by the 6.00 library release.

Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
