### ISSUE TITLE
Get-OVEnclosureGroup  | ConvertTo-OVPowerShellScript   generates wrong $ligX and $LigMapping variables.

### ISSUE THREAD

**Issue by nightzone** [HewlettPackard/POSH-HPOneView#558]
### Expected Behavior
Have to generate working script that will create enclosure groups

### Actual Behavior
Generate script where $ligX variable list is incomplete and $LigMapping hash table wrong.

### Steps to reproduce
Get-OVEnclosureGroup  | ConvertTo-OVPowerShellScript > c:\temp\ov-script.ps1
and run script after that with changed EG name.

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting this.  It looks like the logic to build the calls to the various get logical interconnect group resources is flawed.  I'll work on fixing it.

**Comment by ChrisLynchHPE** [comment]
This was addressed in the impacted libraries, and by the 6.00 library release.

Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
