### ISSUE TITLE
New-HPOVUser issue?

### ISSUE THREAD

**Issue by tknightblc** [HewlettPackard/POSH-HPOneView#56]
Trying to do a simple add user and getting an index error with latest POSH 2.xx library:

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $ConnectedSessions

ConnectionID Name                          UserName      AuthLoginDomain
------------ ----                          --------      ---------------
1            tk1-ov200-dcsdemo.advizex.net Administrator LOCAL          

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> New-HPOVUser Nat   -fullName "Nat Network Admin"  -password hpinvent -roles "Network administrator"
New-HPOVUser : Index operation failed; the array index evaluated to null.
At line:1 char:1
+ New-HPOVUser Nat   -fullName "Nat Network Admin"  -password hpinvent -roles "Net ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-HPOVUser], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex,New-HPOVUser
 

PS

I did with and without -ApplianceConnection. Same script worked with 1.20

**Comment by ChrisLynchHP** [comment]
I will look into this.

Do know that -ApplianceConnection is new in the 2.00 library, which the same scripts you had working with the 1.20 library may not work in 2.00.  It was an unavoidable change.

**Comment by tknightblc** [comment]
Yes, I have been adding –ApplianceConenction to all and tried with this commandlet as well, same error

**Comment by ChrisLynchHP** [comment]
Somehow a flag variable was deleted in the (when we validate authentication), causing this issue.  The CMDLET works as expected if not for that strange omission.  Will be fixed in the upcoming update.

**Comment by ChrisLynchHP** [comment]
This issue is fixed, and will be in the 2.0.139.0 release.
