### ISSUE TITLE
Unable to add Network connection while creating server profile

### ISSUE THREAD

**Issue by bksaroja** [HewlettPackard/POSH-HPOneView#565]
Hi Team,

We are using POSH-HPEOneView v5.5.  We get the below error, when we try to add connections to server profile:

**Cannot validate argument on parameter 'RequestedBW'. The " [String]$_ -eq
'Auto'
-or ([Int]$_ -le 20000 -and [Int]$_ -ge 0) " validation script for the argument with value
"25000" did not return a result of True. Determine why the validation script failed, and then try
the command again**

From the error message, it looks like we cannot add a connection whose bandwidth is higher than 20GBps.
Please find the details:
cmdlet used : $Network_connection_attach = New-OVServerProfileConnection @params

@params = @{
		name             = value;
		ConnectionID     = value;
		ConnectionType   = value;
		PortId           = value;
		RequestedBW      = value; # the value is 25000
		Network          = value;
		Bootable         = value;
		priority         = value;
		LagName          =  value;
		Virtualfunctions =  value;
	}
Powershell library version : 5.5
Powershell version: 5.1

Incase I change the value of RequestBw to Auto I get the below error:
Add-Connection : Cannot convert value "Auto" to type "System.Int32". Error: "Input string was
not
in a correct format."

**Comment by ChrisLynchHPE** [comment]
It looks like you removed the bug report text needed to document the issue.  Please provide the following:

* What Cmdlet are you using?
* What is the syntax you are using?
* What version of the PowerShell library are you using?
* What version of PowerShell environment are you using?

**Comment by ChrisLynchHPE** [comment]
If this issue is related to `New-OVServerProfileConnection`, that is a helper Cmdlet that creates an object to be used by `New-OVServerProfileTemplate` and `New-OVServerProfile` Cmdlets.  To workaround this, just use `-RequestedBW Auto`, then edit the object after it is returned and set the `requestedMbps` property to the value you wish and is supported.

For example:

```powershell
$connection1 = New-OVServerProfileConnection -Network $Network

# Adjust the requested bandwidth to a higher value than the Cmdlet currently supports. In this case, 
# set it to 25Gb, expressed in Mbps
$connection1.requestedMbps = 25000
```

**Comment by bksaroja** [comment]
Incase I change the value of RequestBw to Auto I get the below error:
Add-Connection : Cannot convert value "Auto" to type "System.Int32". Error: "Input string was
not
in a correct format."

**Comment by ChrisLynchHPE** [comment]
Set `-RequestedBW` it to an integer

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
