### ISSUE TITLE
Cannot add Drive Enclosures to scope

### ISSUE THREAD

**Issue by odesaphy** [HewlettPackard/POSH-HPOneView#566]
### Expected Behavior
Drive enclosure is added to the scope.

### Actual Behavior
Drive enclosure is not added to the scope.

### Steps to reproduce
```PowerShell
$de = Get-OVDriveEnclosure -Name "Frame02, bay 7"
Get-OVScope -Name ScopeName | add-OVResourcetoScope  -InputObject $de
```

in the Verbose output : 
VERBOSE: [SEND-OVREQUEST] Request Body: [{"op":"add","path":"/addedResourceUris","value":[]}]

The value list in the request body is empty.

drive-enclosures is not in the $ScopeCategoryEnum HashTable

sas-interconnects, sas-logical-interconnect-groups, sas-logical-interconnects, sas-logical-jbods cannot be added or removed to a scope using Add-OVResourcetoScope or Remove-OVResourcefromScope

### Version Information
```PowerShell
ApplianceVersion: 5.40.00.424900.00
LibraryVersion     : 5.40.2725.2163
```

**Comment by ChrisLynchHPE** [comment]
Support for adding Synergy D3940 drive enclosures to scopes was added in the 5.40.2929.2263 release.

Closing due to no further activity.  This issue can always be re-opened if needed.
