### ISSUE TITLE
module HPEOneView.610 & 600 convert to script & export error

### ISSUE THREAD

**Issue by AtomP4FX** [HewlettPackard/POSH-HPOneView#572]
**Expected Behavior**

running of cmdlets
`Get-OVServerProfileTemplate | ConvertTo-OVPowerShellScript -Export c:\temp\spt.csv`

will result in a file with 
`$ThisNetwork                        = Get-OVNetwork -Type Ethernet -Name $netName`
string among connection variables.

**Actual Behavior**

```
Get-OVServerProfileTemplate | ConvertTo-OVPowerShellScript -Export c:\temp\spt.csv
Index operation failed; the array index evaluated to null.
At C:\Program Files\WindowsPowerShell\Modules\hpeoneview.610\6.10.2778.2020\HPEOneView.610.psm1:15502 char:17
+ ...             [void]$ScriptConnection.Add((Generate-CustomVarCode -Pref ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex
 
Index operation failed; the array index evaluated to null.
At C:\Program Files\WindowsPowerShell\Modules\hpeoneview.610\6.10.2778.2020\HPEOneView.610.psm1:15502 char:17
+ ...             [void]$ScriptConnection.Add((Generate-CustomVarCode -Pref ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex

```

File is created but there is no string
`$ThisNetwork                        = Get-OVNetwork -Type Ethernet -Name $netName`

**Steps to reproduce**

Run 
`Get-OVServerProfileTemplate | ConvertTo-OVPowerShellScript -Export "path"`

checked with 6.00 and 6.10 modules at 6.10 Appliance.

After above string was added manually, New-OVServerProfileTemplate executed successfully.

Running just
`Get-OVServerProfileTemplate | ConvertTo-OVPowerShellScript `
shows the correct output with` $ThisNetwork` variable.

**Version Information**

HPE OneView PowerShell Library Version (Get-OVVersion or $PSLibraryVersion):  6.10.2778.2020
HPE OneView Appliance Version (Get-OVVersion -ApplianceVer): 6.10.00.436703.00
Output from $PSVersionTable on your Windows Host:

Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      5.1.18362.1474                                                                                                    
PSEdition                      Desktop                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
BuildVersion                   10.0.18362.1474                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                   
WSManStackVersion              3.0                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1

**Comment by ChrisLynchHPE** [comment]
Any chance you can provide the profile template in JSON format in order to investigate further?

```powershell
Get-OVServerProfileTemplate | ConvertTo-Json -depth 99 | Out-File C:\profile_templates.json
```

**Comment by ChrisLynchHPE** [comment]
Fix commits were made to address this.  Closing due to no further activity.
