### ISSUE TITLE
Show-OVUtilization "was not recognized as a valid DateTime"

### ISSUE THREAD

**Issue by apapiro** [HewlettPackard/POSH-HPOneView#573]
When I use the showutilization parameter I get this error:

Get-OVServer -Name "ILOCZ3402XW33" | Show-OVUtilization
MethodInvocationException: C:\Users\ANPAPI1\Documents\PowerShell\Modules\HPEOneView.550\5.50.2794.1655\HPEOneView.550.psm1:60394
 Line |
60394 |  …                  [HPEOneView.ServerUtilization]::new($_resource.name,
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Exception calling ".ctor" with "13" argument(s): "String '06/23/2021 02:20:00' was not recognized as a valid DateTime."

**Comment by ChrisLynchHPE** [comment]
Can you please provide more detail on your environment?  Please provide the captured output from:

```powershell
$PSVersionTable | CLIP
```

**Comment by ChrisLynchHPE** [comment]
Closing do to no further activity.  This issue can always be re-opened if needed.
