### ISSUE TITLE
 New-HPOVRestore Failing on POSH 2.00.67

### ISSUE THREAD

**Issue by abaert3** [HewlettPackard/POSH-HPOneView#58]
Hi,

Today I made a full script for backup and restore using the POSH library , but when I tried to do the restore it gave me this result : 

New-HPOVRestore : A parameter cannot be found that matches parameter name 'Hostname'.
At line:1 char:1
+ New-HPOVRestore "C:\File\Path....
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-HPOVRestore], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-HPOVRestore

So I tried to use the command itself , and it gave the same result.

What this parameter issue is ? is there any known bug on this ?

**Comment by ChrisLynchHP** [comment]
No, this is not a known issue.  However, it appears that an internal helper cmdlet is missing a parameter alias that maps Hostname to a required parameter.  I'm attaching an unreleased and unsigned PSM1 file.  Can you help validate this fixes the issue you are reporting?

[HPOneView.200.psm1.zip](https://github.com/HewlettPackard/POSH-HPOneView/files/101179/HPOneView.200.psm1.zip)

**Comment by abaert3** [comment]
Thank you for this , unfortunately I will be able to test this on Monday Morning 09:00 am CET .
Will keep you informed !

**Comment by ChrisLynchHP** [comment]
I will be publishing an update today, which will include this as a potential fix.  If it is still broken (which I do not believe it will be), I can publish another update next week.

**Comment by abaert3** [comment]
Hi,

I made the test and now upload of the file works , but when launching the restore part it fails with :
New-HPOVrestore : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware)
in its value. Please correct the value and try again.
At D:\BLADE\HP\oneview\bin\oneview-backup.ps1:62 char:3
+   New-HPOVrestore "$bkploc/$file_rest"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-HPOVRestore], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-HPOVRestore
is it something on my script ?  This is the line which sends the Restore :
New-HPOVrestore "$bkploc/$file_rest"

let me know if there is anything with that

**Comment by ChrisLynchHP** [comment]
It’s not your script.  I found and fixed the issue.

**Comment by abaert3** [comment]
Thank you ! Let me know when this is available :)

**Comment by ChrisLynchHP** [comment]
NP.  I’m working on some final updates to the sample scripts, and working on updating the HP Code Signing cert we use.  Once those two are done (which I hope is today or tomorrow), I will post the update.

**Comment by abaert3** [comment]
OK , will check Github tomorrow then :)

**Comment by abaert3** [comment]
Hello , any news from this new release ? I'm testing the library for using it in prod , and currently backup/restore is a show stopper ... Let me know when you will release the new code :) thx

**Comment by ChrisLynchHP** [comment]
Sorry for the delay.  I am posting the update now as I type this.  Look for 2.0.139.0 as the release.

**Comment by abaert3** [comment]
Thank you for this release , I'm currently testing it , will keep you posted ASAP.

**Comment by abaert3** [comment]
Hi,

Restore is starting and looks to be working , at least the progress bar displays on the Web GUI , but on the POSH console , we have a strange behaviour , where an exception keeps displaying each time the screen is updated I think :

Index operation failed; the array index evaluated to null.
At C:\Users\XXXXXX\Documents\WindowsPowerShell\Modules\HPOneView.200\HPOneView.200.psm1:11748 char:28
+                         $_statusMessage = "$($script:progressStepEnum[$restoreStatus.progressStep] ...
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex

Currently it's not blocking , only giving a strange display :)

**Comment by abaert3** [comment]
Any news from this last issue

**Comment by ChrisLynchHP** [comment]
Hmm... I have sent 2 emails to this discussion and none of them have been added.  The [2.0.175.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.175.0) release contains the fix for this issue.

**Comment by abaert3** [comment]
Thank you
