### ISSUE TITLE
Problem with get-HPOVStoragePool

### ISSUE THREAD

**Issue by reinhardn** [HewlettPackard/POSH-HPOneView#59]
Hi. 
When I run the command I get a following message. At the moment I am not sure if the problem is with OneView configuration or with HP POSH. 
Maybe someone here has seen this before.
Thanks!
Errromessage:
PS C:\Users\Administrator> Get-HPOVStoragePool
Collection was modified; enumeration operation may not execute.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.2
00.psm1:20060 char:12
+         ForEach ($_Connection in $ApplianceConnection)
+                  ~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidOperationExcept
   ion
    + FullyQualifiedErrorId : System.InvalidOperationException

**Comment by DungKHoang** [comment]
Hi
What is stored in $ApplianceConnection?
Also I notice that the 'strange' syntax here; $_Connection
Should it be $_.Connection or $Connection?

DKHoang

**Comment by ChrisLynchHP** [comment]
There is a commented out variable that is used when we enumerate the `-ApplianceConnection` parameter to order to validate authentication.  I'm going to be releasing a small update with some additional fixes (no new features) later today.  This will be fixed in that release.

**Comment by reinhardn** [comment]
Thanx, Chris.

**Comment by ChrisLynchHP** [comment]
This is fixed in the [2.0.175.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.175.0) release.
