### ISSUE TITLE
how to replicate settings from 1 OV to many OV instances

### ISSUE THREAD

**Issue by zeshan1977** [HewlettPackard/POSH-HPOneView#590]
I have say 10 OV Instances in production.
I configure the settings for notifcations per se in 1 OV or the network settings.

 How cn I replicate this throughtout my 9 OV instances?

a)s there a file with ALL OneView Attribs and there values, that I can get perhap iva REST API?

Question above spans DL and Synergy

**Comment by aricbernard** [comment]
Evaluate: https://github.com/DungKHoang/Import-Export-OneView-Resources

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
