### ISSUE TITLE
Add-OVServer: missing force option

### ISSUE THREAD

**Issue by woertz** [HewlettPackard/POSH-HPOneView#593]
```
PS C:\> Add-OVServer -Hostname server.name.com -Monitored -Username administrator -Password "passwd"
WARNUNG: The -Username and -Password parameters are being deprecated.  Please transition your scripts to using the -Credential parameter.
Add-OVServer : "The server hardware has already been added as "". Release the server from its current manager and try again, or retry the request using force option.  If the server is orphaned, use Remove-OVServer -Force Cmdlet, and then try your add again.
In Zeile:1 Zeichen:1
+ Add-OVServer -Hostname server.name.com -Monito ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (Hostname:String) [Add-OVServer], ServerHardwareResourceException
    + FullyQualifiedErrorId : ServerResourceExists,Add-OVServer
```
I am getting this error please help.
I am using hponeview.630 module version.

**Comment by jullienl** [comment]
Have you tried to use the `confirm` parameter? According to the help, this parameter can be used when the server is claimed by another appliance to bypass the confirmation prompt, and force add the server resource.

**Comment by woertz** [comment]
Adding "-Confirm:$false" throws the same error.
What is a bit strange is the error message: The server hardware has already been added as ""
It should be: "The server hardware has already been added as "server.name.com"

**Comment by jullienl** [comment]
Yes, it is strange. Maybe the initial add was not successful. You need to solve this problem first. Try refreshing this resource and once it has finished successfully, try your `remove-ovserver` command again.

**Comment by woertz** [comment]
An initial add via OneView GUI is successful. Then a
```
Get-OVServer -Name server.name.com | Remove-OVServer -Force
```
works fine. But add via Powershell does not work.

**Comment by ChrisLynchHPE** [comment]
Add-OVServer will attempt to add the specified server resource.  A task is part of that attempt.  If the server was claimed by another appliance, then it will generate a confirmation message asking if you wish to force claim the server.  That is what `-Confirm:$false` will override.

If the server is added already to the same appliance, it will terminate stating the server is already present and also mention that if the server is orphaned to force remove it then add back again.  Which is what you are getting.  You need to first force remove the server using `Get-OVServer -Name server.name.com | Remove-OVServer -Force | Wait-OVTaskComplete -OutVar ForceRemoveTask`.  Then, look at the `$ForceRemoveTask` object for the `taskState`.  If it is `Error` or `Failed`, then you need to examine the `taskErrors` property for why it failed.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
