### ISSUE TITLE
Connect-OVMgmt  causes script to exit if already connected

### ISSUE THREAD

**Issue by cmbaker82** [HewlettPackard/POSH-HPOneView#594]
The problem described here: https://github.com/HewlettPackard/POSH-HPEOneView/issues/175
Is still active in 630

`Connect-OVMgmt -UserName Administrator -Password <password> -Hostname <host>`
works as expected if you are not connected; however if you are already connected it returns the following warning
`WARNING: You are already connected to <hostname>`
But the script does not continue to execute.  You can reproduce this by executing the following script twice in the same session
`Connect-OVMgmt -UserName Administrator -Password <password> -Hostname <host>`
`write-host "got here" `
On first execution you will get the message "got here" but on second you will not

**Comment by jullienl** [comment]
To workaround this, you can use `if (! $ConnectedSessions) { connect-OVMgmt...}` so that if you are already connected, the script will continue to execute.

**Comment by ChrisLynchHPE** [comment]
@jullienl offers a good workaround.  However, the Cmdlet does need to be fixed.  It currently uses `Continue` after displaying the `Write-Verbose` message.  This should not have been used:

> When continue is used outside of a construct that directly supports it (loops, switch, trap), PowerShell looks up the call stack for an enclosing construct. If it can't find an enclosing construct, the current runspace is quietly terminated.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 6.30.3188.1900](https://github.com/HewlettPackard/POSH-HPEOneView/releases/tag/v6.30.3188.1900) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPEOneView.630/6.30.3188.1900).

Please verify before this issue is closed.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
