### ISSUE TITLE
Get-OVServerProfile -Name XXXXX -Detailed gives Firmware Baseline as none

### ISSUE THREAD

**Issue by KranthiKG** [HewlettPackard/POSH-HPOneView#599]
The output of below cmdlet provides with lot of information but the Firmware Baseline is none. even though we have firmware baseline set in the profile. 

Get-OVServerProfile -Name XXXXX -Detailed 

Firmware Baseline
-----------------
none

PS C:\Windows\system32> Get-OVVersion

My Appliance                       LibraryVersion Path
-------------                       -------------- ----
ApplianceVersion: 6.50.00.452161.00 6.30.2928.3678 C:\Program Files\WindowsPowerShell\Modules\HPEOneView.630\6.30.29...

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 6.30.3188.1900](https://github.com/HewlettPackard/POSH-HPEOneView/releases/tag/v6.30.3188.1900) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPEOneView.630/6.30.3188.1900).

Please verify before this issue is closed.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
