### ISSUE TITLE
Set Profile to unassigned

### ISSUE THREAD

**Issue by jeffreyeobrien** [HewlettPackard/POSH-HPOneView#6]
I'm trying to script a way to unassign a profile from a server.  I do not want to delete the profile.  Reviewing the command I don't see an option in Remove-HPOVProfile to set the server hardware to unassigned.  Nor do I see any other commandlet that I would use to accomplish this task.  I found a work around but unsure if this is the only way to do so or even recommended.

I've used the following method:
$pro1 = Get-HPOVProfile "name_of_profile"
$pro1.serverHardwareUri = ""
$pro1.enclosureUri = ""
$pro1.enclosureBay = ""
Set-HPOVResource $pro1

This will unassign the profile from the hardware.  The Set-HPOVResource can then be used to assign the profile back to the server.  If I try to assign the profile to the server from the GUI after removing it from the powershell method above, it hangs at Verifying Parameters on the Edit Profile screen.

Not sure if this is the route I should be using, but I don't see any other way to do so at the moment.  Any thoughts?

Thanks!

**Comment by ChrisLynchHP** [comment]
I am unable to replicate this issue.  What you are doing is correct.  Can you tell me what version of the PowerShell library you are using?  Also, what browser were you using to edit the Server Profile to assign to an empty bay?

**Comment by jeffreyeobrien** [comment]
Using the latest PowerShell library Release 1.20.0007 running on Windows Server 2012 r2.  Browser being used was Firefox 34.0.5 (x86) on a Windows Server 2008 R2 host that I normally use for OneView administration.  I have not tried other browsers, that is something I could try from a different host.

I appreciate the response and that this is the correct method to accomplish the task.  I will try to do a few more tests with different browsers.

**Comment by ChrisLynchHP** [comment]
There have been some bugs in the past that were browser specific.  I use IE11 (Server 2012 R2 or Windows 8.1), and just now tried with FF 32.0.1, with no issue.

**Comment by ChrisLynchHP** [comment]
Are you closing this because you found the problem?

Sent from my Windows Phone
________________________________

**Comment by jeffreyeobrien** [comment]
I didn't want to keep this open.  I believe it was a browser issue if this
was tested by you, I haven't update they browser on that host in a while.
I will run my workflow at the end of the week when I clean up the lab this
was provisioning.
