### ISSUE TITLE
problem with 2.0 add-hpovserver

### ISSUE THREAD

**Issue by jonathan7777** [HewlettPackard/POSH-HPOneView#60]
Hi, i have the following problem with oneview 2.0 cmdlet "add-hpovserver":

VERBOSE: [ADD-HPOVSERVER] Bound PS Parameters:

Key   : Hostname
Value : "hostname"

Key   : Username
Value : Administrator

Key   : Password
Value : "password"

Key   : LicensingIntent
Value : OneViewNoiLO

Key   : ApplianceConnection
Value : "oneviewconnection"

Key   : Verbose
Value : True

VERBOSE: [ADD-HPOVSERVER] Called from: <ScriptBlock>
VERBOSE: [ADD-HPOVSERVER] Verify auth
VERBOSE: [TEST-HPOVAUTH] Caller: Add-HPOVServer
VERBOSE: [TEST-HPOVAUTH] Verify Auth for rdoneview
VERBOSE: [NEWOBJECT] Bound PS Parameters:

Key   : ServerImport
Value : True

VERBOSE: [NEWOBJECT] Called from: Add-HPOVServer
The property 'configurationState' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\hponeview.200\HPOneView.200.psm1:13348 char:4
+             $server.configurationState = "Managed"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

VERBOSE: [ADD-HPOVSERVER] Sending request to add server resource ("hostname")
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:

Key   : Hostname
Value : "oneview"

Key   : uri
Value : /rest/server-hardware

Key   : method
Value : POST

Key   : body
Value :

VERBOSE: [SEND-HPOVREQUEST] PROCESS
VERBOSE: [SEND-HPOVREQUEST] Processing '"oneviewconnection"' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/server-hardware' to '"oneviewconnetion"'
VERBOSE: [RESTCLIENT] Bound PS Parameters:

Key   : method
Value : POST

Key   : uri
Value : /rest/server-hardware

Key   : Appliance
Value : rdoneview

VERBOSE: [RESTCLIENT] Called from: Send-HPOVRequest
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for POST https://"oneview"/rest/server-hardware
VERBOSE: [SEND-HPOVREQUEST] Request: POST https://"oneview"/rest/server-hardware
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: X-API-Version = 200
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: auth = ""
VERBOSE: [SEND-HPOVREQUEST] Net.WebException Error caught
VERBOSE: [SEND-HPOVREQUEST] ERROR RESPONSE:

details            :
nestedErrors       : {}
errorSource        :
recommendedActions : {}
errorCode          : REQUEST_DATA_READ_ERROR
data               :
message            : Could not read JSON: No content to map to Object due to end of input; nested exception is java.io.EOFException: No content to
                     map to Object due to end of input

VERBOSE: [SEND-HPOVREQUEST] Response Status: HTTP 400 [Bad Request]
VERBOSE: [SEND-HPOVREQUEST] Response Header: Connection = 1.1 "oneviewconnection"
VERBOSE: [SEND-HPOVREQUEST] Response Header: Transfer-Encoding =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Cache-Control =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Content-Type =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Date =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Server =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Via =
VERBOSE: [SEND-HPOVREQUEST] HTTP 400 error caught.
VERBOSE: [NEW-ERRORRECORD] Building ErrorRecord object
Add-HPOVServer : Could not read JSON: No content to map to Object due to end of input; nested exception is java.io.EOFException: No content to map
to Object due to end of input
At line:1 char:1
+ Add-HPOVServer -Hostname "hostname" -Username Administrator -Password "password"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Add-HPOVServer], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Add-HPOVServer

**Comment by ChrisLynchHP** [comment]
Please upgrade to the [2.0.175.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/latest) version, which was one of the issues fixed.  To check for newer versions, you can use the `Get-HPOVVersion -CheckOnline` CMDLET and parameter.

**Comment by jonathan7777** [comment]
Thank you very much !!
