### ISSUE TITLE
Enable-OVComposerIlo not working as expected

### ISSUE THREAD

**Issue by mlengnin** [HewlettPackard/POSH-HPOneView#609]
Two issues found with Enable-OVComposerIlo (line # mentioned are based on Ver. 6.30.2928.3678)

### First issue: Model Type is incorrectly validated (line 55469)

# Validate Composer type is Composer2
        if ($InputObject.model -ne "Synergy Composer2")

# Modelstring of Composer 2 has no blank, so this should be like this:
        if ($InputObject.model -ne "SynergyComposer2")

### Second issue: $_Uri is incorrectly build (line 55612)

        $_Uri = $InputObject.Uri + "/iloConfig"
        $resp = Send-OVRequest -Uri $_Uri -Method PUT -Body $_NewComposerConfig -Hostname $ApplianceConnection

# $InputObject.Uri needs to be more specific: $InputObject.Uri.OriginalString

        $_Uri = $InputObject.Uri.OriginalString + "/iloConfig"
        $resp = Send-OVRequest -Uri $_Uri -Method PUT -Body $_NewComposerConfig -Hostname $ApplianceConnection

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 6.30.3188.1900](https://github.com/HewlettPackard/POSH-HPEOneView/releases/tag/v6.30.3188.1900) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPEOneView.630/6.30.3188.1900).

Please verify before this issue is closed.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
