### ISSUE TITLE
Problem with "ResourceNotFound"

### ISSUE THREAD

**Issue by reinhardn** [HewlettPackard/POSH-HPOneView#61]
Hi! This might be a problme with sample script "Get-BladeSystemInventory.ps1" I am using but maybe someone has a hint. If I am at the wrong place to raise this issue, please let me know.

The connection part of the script runs fine but it seems it cannot find the REST URI when it tries to pull the first detail information. Now I need to figure out if this is a problem an the OneView managment server (question already sent) or with the OneView module.
If you have a hint, let me know. If it is not seen anywhere else then I keep checking on the managment server. 

Error after successful connection:
The request resource
'/rest/drive-enclosures/f07586c6-43a8-4de6-b454-1b94280a2d5a' could not be
found. Check the request URI, then resend the request.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.2
00.psm1:5266 char:33
+                                 Throw $errorRecord
+                                 ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (URI:String) [], ResourceNotFoun
   dException
    + FullyQualifiedErrorId : ResourceNotFound

**Comment by ChrisLynchHP** [comment]
Please provide more details about your environment.  What version of the PowerShell library are you using?  What version of HPE OneView are you using?

**Comment by reinhardn** [comment]
Thanks for looking into this.
PowerShell Library Version : 2.0.175.0
Library Path               : C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200

OneView: Need to ask. I think it is 2.0 but I will get back with more details.

Cheers
Reinhard

**Comment by reinhardn** [comment]
One more info: System has Synergy composer blade and Synergy drive enclosure.

**Comment by ChrisLynchHP** [comment]
Please email me directly at chris (dot) lynch [2] hpe (dot) com.
