### ISSUE TITLE
Get-OVserver | Get-OVRemoteSupportSetting command errors with Add-Member : cannot add member, see attached output

### ISSUE THREAD

**Issue by MSHAFFER64** [HewlettPackard/POSH-HPOneView#611]
[Get-OVserver_Get-OVRemoteSupportSetting_Error.txt](https://github.com/HewlettPackard/POSH-HPEOneView/files/8774742/Get-OVserver_Get-OVRemoteSupportSetting_Error.txt)

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 6.30.3188.1900](https://github.com/HewlettPackard/POSH-HPEOneView/releases/tag/v6.30.3188.1900) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPEOneView.630/6.30.3188.1900).

Please verify before this issue is closed.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
