### ISSUE TITLE
Problems with loading hponeview.300

### ISSUE THREAD

**Issue by seamusobr1** [HewlettPackard/POSH-HPOneView#613]
I am having issues loading hponeview.300 and get the error below. I need this version as the 310 version will not connect correctly and I get api errors. I can import the 310 version successfully just wondering if you know of any way I can load the 300 version

Many Thanks

mport-module : Could not load file or assembly
'file:///C:\Users\a1207393\Documents\WindowsPowerShell\Modules\HPOneView.300\lib\HPOneView_Classes.dll' or one of its
dependencies. The system cannot find the file specified.
At line:1 char:1
+ import-module -Name HPOneView.300
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by ChrisLynchHPE** [comment]
How did you obtain the library?  Can you verify that the DLL is in the directory?  Also, did you try to unblock the file using `Unblock-File C:\Users\a1207393\Documents\WindowsPowerShell\Modules\HPOneView.300\lib\HPOneView_Classes.dll`?

Please know that any of the libraries older than 6.00 are no longer supported and no further updates will be provided.  If you also have an HPE OneView 3.x appliance, please update it to the current releases, as we have not and will not provide fixes or patches for those releases.

**Comment by ChrisLynchHPE** [comment]
If you just did a git pull from the 3.00 branch, that isn't how you install the library.  Please download the EXE installer [here](https://github.com/HewlettPackard/POSH-HPEOneView/releases/download/v3.0.1358.2596/HPE.OneView.3.00.PowerShell.Library.exe).  That is the final release of the 3.00 library and is provided as-is.

**Comment by seamusobr1** [comment]
That is fantastic worked as you said managed to get the ome appliance up to 7.1
Thanks for your help

**Comment by ChrisLynchHPE** [comment]
Glad you are set.  Closing.
