### ISSUE TITLE
Feature Request: Add HealthCategory Security to valid Category to Get-OVAlert Cmdlet

### ISSUE THREAD

**Issue by stephan-koch** [HewlettPackard/POSH-HPOneView#615]
# Summary of the new feature/enhancement

Get-OVAlert does not allow to filter on HealthCategory Security.
Please add it.

 Get-OVAlert -AlertState Active -HealthCategory Security

# Proposed technical implementation details (optional)

**Comment by ChrisLynchHPE** [comment]
This was added to the library starting with the 7.10 library release.  I will be adding this back to the 6.60 and 7.00 libraries soon.

**Comment by ChrisLynchHPE** [comment]
I just pushed out updated 6.60 and 7.00 libraries that contain this enhancement.  Both are available on PowerShell Gallery.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
