### ISSUE TITLE
Invalid task object provided: Set-HPOVServerPower | Wait-HPOVTaskComplete

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#63]
Get-HPOVServer -Name "se01, bay 1" | Set-HPOVServerPower -powerState "Off" -powerControl "PressAndHold" | Wait-HPOVTaskComplete

Wait-HPOVTaskComplete : Invalid task object provided.  Please verify the task object you are passing and try again.
At line:1 char:107
+ ... ressAndHold" | Wait-HPOVTaskComplete
+                    ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (-1:String) [Wait-HPOVTaskComplete], InvalidOperationException
    + FullyQualifiedErrorId : InvalidArgumentValue,Wait-HPOVTaskComplete

PSMessageDetails      :
Exception             : System.InvalidOperationException: Invalid task object provided.  Please verify the task object
                        you are passing and try again.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord
                        errorRecord)
TargetObject          : -1
CategoryInfo          : InvalidArgument: (-1:String) [Wait-HPOVTaskComplete], InvalidOperationException
FullyQualifiedErrorId : InvalidArgumentValue,Wait-HPOVTaskComplete
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Wait-HPOVTaskComplete<Process>,
                        C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 42140
                        at Set-HPOVServerPower<Begin>,
                        C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 14091
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by ChrisLynchHP** [comment]
This will be fixed in the upcoming 2.0.202.0 release.

**Comment by ChrisLynchHP** [comment]
Fixed in [Release 2.0.202.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.202.0)
