### ISSUE TITLE
Invalid task object provided: Remove-HPOVEnclosureGroup | Wait-HPOVTaskComplete 

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#64]
Get-HPOVEnclosureGroup | Remove-HPOVEnclosureGroup -Confirm:$false | Wait-HPOVTaskComplete 

PSMessageDetails      :
Exception             : System.InvalidOperationException: Invalid task object provided.  Please verify the task object
                        you are passing and try again.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord
                        errorRecord)
TargetObject          : @{StatusCode=204; Message=Resource deleted successfully.; ApplianceConnection=}
CategoryInfo          : InvalidArgument: (@{StatusCode=20...nceConnection=}:String) [Wait-HPOVTaskComplete],
                        InvalidOperationException
FullyQualifiedErrorId : InvalidArgumentValue,Wait-HPOVTaskComplete
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Wait-HPOVTaskComplete<Process>,
                        C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 42200
                        at Remove-HPOVEnclosureGroup<End>,
                        C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 15278
                        at <ScriptBlock>, C:\HPCS\OneView\Configure-OneView.2.0.ps1: line 122
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by aricbernard** [comment]
PSMessageDetails      :
Exception             : System.InvalidOperationException: Invalid task object provided.  Please verify the task object
                        you are passing and try again.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord
                        errorRecord)
TargetObject          : @{StatusCode=204; Message=Resource deleted successfully.; ApplianceConnection=}
CategoryInfo          : InvalidArgument: (@{StatusCode=20...nceConnection=}:String) [Wait-HPOVTaskComplete],
                        InvalidOperationException
FullyQualifiedErrorId : InvalidArgumentValue,Wait-HPOVTaskComplete
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Wait-HPOVTaskComplete<Process>,
                        C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 42200
                        at Remove-HPOVEnclosureGroup<End>,
                        C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 15278
                        at <ScriptBlock>, C:\HPCS\OneView\Configure-OneView.2.0.ps1: line 122
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by ChrisLynchHP** [comment]
This is not an Async task operation. You dont pass the result to Wait-HPOVTaskComplete.
