### ISSUE TITLE
Invalid task object provided: Remove-HPOVUnmanagedDevice | Wait-HPOVTaskComplete

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#65]
Get-HPOVUnmanagedDevice | Remove-HPOVUnmanagedDevice -Confirm:$false | Wait-HPOVTaskComplete

PSMessageDetails      :
Exception             : System.InvalidOperationException: Invalid task object provided.  Please verify the task object
                        you are passing and try again.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord
                        errorRecord)
TargetObject          : @{StatusCode=204; Message=Resource deleted successfully.; ApplianceConnection=; Name=snet01}
CategoryInfo          : InvalidArgument: (@{StatusCode=20...=; Name=snet01}:String) [Wait-HPOVTaskComplete],
                        InvalidOperationException
FullyQualifiedErrorId : InvalidArgumentValue,Wait-HPOVTaskComplete
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Wait-HPOVTaskComplete<Process>,
                        C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 42200
                        at Remove-HPOVUnmanagedDevice<End>,
                        C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 25306
                        at <ScriptBlock>, C:\HPCS\OneView\Configure-OneView.2.0.ps1: line 134
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by ChrisLynchHP** [comment]
This is not an Async task operation. You dont pass the result to Wait-HPOVTaskComplete.
