### ISSUE TITLE
Invalid task object provided: Remove-HPOVSanManager | Wait-HPOVTaskComplete 

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#66]
Get-HPOVSanManager | Remove-HPOVSanManager -Confirm:$false | Wait-HPOVTaskComplete 

PSMessageDetails      :
Exception             : System.InvalidOperationException: Invalid task object provided.  Please verify the task object
                        you are passing and try again.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord
                        errorRecord)
TargetObject          : @{StatusCode=200; Message=Resource deleted successfully.; ApplianceConnection=}
CategoryInfo          : InvalidArgument: (@{StatusCode=20...nceConnection=}:String) [Wait-HPOVTaskComplete],
                        InvalidOperationException
FullyQualifiedErrorId : InvalidArgumentValue,Wait-HPOVTaskComplete
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Wait-HPOVTaskComplete<Process>,
                        C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 42200
                        at Remove-HPOVSanManager<End>,
                        C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 24502
                        at <ScriptBlock>, C:\HPCS\OneView\Configure-OneView.2.0.ps1: line 136
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by ChrisLynchHP** [comment]
I don't think this is an Async task operation. I'll look into it.

**Comment by ChrisLynchHP** [comment]
This operation does not generate an async task.
