### ISSUE TITLE
Feature Request: Restart-OVServer "ResetType": "AuxCycle"

### ISSUE THREAD

**Issue by davidvf** [HewlettPackard/POSH-HPOneView#663]
# Summary of the new feature/enhancement

I would like to have an extra option for the already existing `Restart-OVServer`.
Looking for `"ResetType": "AuxCycle"`

# Proposed technical implementation details (optional)
Restart-OVServer
    [-Server] <Object>
    [-AuxCycle]

**Comment by ChrisLynchHPE** [comment]
Not sure what you are asking for.  There are two reset options:

* ColdRest
* Reset

ColdReset is a hard reset taking power away and presenting it back.  Reset is a warm reboot of the server without removing power.  There are no other server reset options available.

**Comment by davidvf** [comment]
Hello @ChrisLynchHPE , is ColdReset in this case the same as AuxCycle, I don't think so, because those are 2 seperate options  as `ResetType`.
https://servermanagementportal.ext.hpe.com/docs/concepts/performing_actions/#auxiliary-power-cycle-hpe-specific-action
Looks like this with REST:

iLO 4:
```
curl -k -H "Content-Type: application/json" -X POST --data '{"ResetType": "AuxCycle"}' https://$ilo/redfish/v1/Systems/1/Actions/Oem/Hp/ComputerSystemExt.SystemReset/ -u iLOuser:iLOpass

```
ILO 5:
```
curl -k -H "Content-Type: application/json" -X POST --data '{"ResetType": "AuxCycle"}' https://$ilo/redfish/v1/Systems/1/Actions/Oem/Hpe/HpeComputerSystemExt.SystemReset/ -u iLOuser:iLOpass
```

In powershell:
```
$AuxPowerCycleURI = "$uri/Systems/1/Actions/Oem/Hpe/HpeComputerSystemExt.SystemReset/"
		$AuxPowerCylceBody = @{ 
			Action = 'SystemReset' 
			ResetType = 'AuxCycle'
		} | convertto-json
```


From the ilo rest api docs, there seems to be a difference, i think you've implemented `ResetType: ColdBoot`
https://servermanagementportal.ext.hpe.com/docs/redfishservices/ilos/ilo6/ilo6_153/ilo6_computersystem_resourcedefns153/#actions
```
ResetType (string)

ResetType identifies the type of Action to be performed.

Value
ColdBoot	
AuxCycle
```

**Comment by ChrisLynchHPE** [comment]
ColdBoot is the only option from the OneView REST API and core product that provides what you are looking for.  Are you trying to do this for Synergy Compute Node?  If you are, the only supported eFuse methods is from the Synergy Composer Maintenance CLI.  eFuse isn't a common operation we want customers to use, unless for last-case-resort purposes.  While eFuse is available via the Maintenance Console, it can put a Compute Node into a worse state.

**Comment by davidvf** [comment]
Hi Chris, no we are looking for this "feature" for DL servers.

We are working to fix the following advisory:
https://support.hpe.com/hpesc/public/docDisplay?docId=a00060003en_us

But some servers are in remote locations where we cannot pull the plug. Therefore an `AuxCycle Reset` would be beneficial.

**Comment by ChrisLynchHPE** [comment]
Closing this issue, as the only option available is ColdBoot.  This is a limitation to OneView that does not support `AuxCycle Reset`.
