### ISSUE TITLE
New-HPOVNetwork creating network but throwing error

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#68]
New-HPOVNetwork -Name $($Enet.Name) -type $($Enet.Type) -vlanId $($ThisVLANID) -purpose $($Enet.Purpose) -typicalBandwidth $MinSpeed -maximumBandwidth $MaxSpeed -privateNetwork $Private -smartLink $SmartLink

New-HPOVNetwork : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware)
in its value. Please correct the value and try again.
At C:\HPCS\OneView\Configure-OneView.2.0.ps1:192 char:17
+         $Task = New-HPOVNetwork -Name $($Enet.Name) -type $($Enet.Type) -vlanId  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-HPOVNetwork], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-HPOVNetwork

**Comment by ChrisLynchHPE** [comment]
Thanks.  This is a regression issue from the 2.0.233.0 release.  I found and fixed the issue.  An update will be posted later tonight.

**Comment by ChrisLynchHPE** [comment]
Fixed in [Release 2.0.243.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.243.0)
