### ISSUE TITLE
New-HPOVStorageVolume cannot consume Get-HPOVStoragePool object

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#69]
$StoragePool = Get-HPOVStoragePool -poolName $ProfileTemplateBFSVolumeCPGName
if($StoragePool)
{
$TempVolume = New-HPOVStorageVolume -ApplianceConnection $OVConnection -volumeName "TemporaryVolume" -description "Temporary Volume used during profile creation process" -StoragePool $StoragePool -capacity "1" | Wait-HPOVTaskComplete
}

PSMessageDetails      :
Exception             : System.InvalidOperationException: Invalid value for parameter storagePoolURI in
                        provisioningParameters provided for creating volume resource. Invalid value for parameter
                        storagePoolURI in provisioningParameters provided for creating volume resource. Ensure there
                        are no null values in input.
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord
                        errorRecord)
TargetObject          : Send-HPOVRequest
CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationException
FullyQualifiedErrorId : InvalidAuthOperation,Send-HPOVRequest
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>,
                        C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5248
                        at New-HPOVStorageVolume<Process>,
                        C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 22714
                        at <ScriptBlock>, C:\HPCS\OneView\Configure-OneView.2.0.ps1: line 685
                        at <ScriptBlock>, C:\HPCS\OneView\Configure-OneView.2.0.ps1: line 548
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by ChrisLynchHPE** [comment]
Fixed in [Release 2.0.243.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.243.0).
