### ISSUE TITLE
Copy-HPOVProfile not working

### ISSUE THREAD

**Issue by SSvilen** [HewlettPackard/POSH-HPOneView#7]
Hello,

We have the same issue before with version 1.06 of the Powershell library. Now we have appliance 1.20 with 1.20 version of the library, but the issue is still here. Please contact me at sultanov_at_hp.com so I can provide you with detailed verbose output.

Best Regards,
Svilen Sultanov

**Comment by ChrisLynchHP** [comment]
Was fixed in the Release 1.20.0050 update.
