### ISSUE TITLE
Add-HPOVStorageSystem errors with POSH 2.x

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#70]
Using the latest version of OneView Library 2.0.xxx
When using the cmdlet Add-HPOVStorageSystem , I get lots of error, although the storage is added to the appliance

--------------------------------------

PS C:\> Connect-HPOVMgmt -Hostname 10.254.13.39 -UserName Administrator -password P@ssword1

ConnectionID Name         UserName      AuthLoginDomain
------------ ----         --------      ---------------
1            10.254.13.39 Administrator LOCAL

PS C:\> write-host -ForegroundColor Cyan "SAN Manager is already added"
SAN Manager is already added
PS C:\> Add-HPOVStorageSystem -hostname 172.18.11.12 -username dcs -password dcs -Domain ScaleTestingDomain

Name              State     Status  Serial Number Model        WWN                     Firmware
----              -----     ------  ------------- -----        ---                     --------
ThreePAR7200-4555 Connected Unknown TXQ1010307    HP_3PAR 7200 20:00:00:02:AC:00:08:F6 3.2.1.292

Name                      Status Storage System Domain             Drive Type RAID  Total       Allocated Free
----                      ------ -------------- ------             ---------- ----  -----       --------- ----
ScaleTestingDomain_CPG_32                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_40                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_38                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_23                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_21                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_17                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_8                        ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_11                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_39                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_4                        ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_2                        ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_20                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_16                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_9                        ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_36                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_14                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_37                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_18                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_3                        ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_31                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_7                        ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_28                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_19                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
cpg_growth-warning-100GiB                       TestDomain         FC         RAID5 1,024.00 GB 0.00 GB   1,024.00 GB
ScaleTestingDomain_CPG_1                        ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_15                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
cpg-growth-limit-1TiB                           TestDomain         FC         RAID5 1,024.00 GB 222.00 GB 802.00 GB
ScaleTestingDomain_CPG_33                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_22                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_30                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
CPG_FC-AO                                       TestDomain         FC         RAID5 1,024.00 GB 0.00 GB   1,024.00 GB
ScaleTestingDomain_CPG_34                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
CPG-SSD                                         TestDomain         SSD        RAID5 1,024.00 GB 0.00 GB   1,024.00 GB
ScaleTestingDomain_CPG_29                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
CPG-SSD-AO                                      TestDomain         SSD        RAID5 1,024.00 GB 0.00 GB   1,024.00 GB
ScaleTestingDomain_CPG_10                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_5                        ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_27                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_26                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_25                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_13                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
FST_CPG1                                        TestDomain         FC         RAID5 1,024.00 GB 222.00 GB 802.00 GB
ScaleTestingDomain_CPG_6                        ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_12                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
FST_CPG2                                        TestDomain         FC         RAID5 1,024.00 GB 126.75 GB 897.25 GB
ScaleTestingDomain_CPG_35                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB
ScaleTestingDomain_CPG_24                       ScaleTestingDomain FC         RAID1 1,024.00 GB 143.00 GB 881.00 GB

PS C:\> TerminatingError(Send-HPOVRequest): "No appliance Hostname parameter provided and no valid appliance session(s) found."
PS C:\> TerminatingError(Send-HPOVRequest): "No appliance Hostname parameter provided and no valid appliance session(s) found."
Name  State Status WWPN                    Expected Network Actual Network Port Group
----  ----- ------ ----                    ---------------- -------------- ----------
0:1:1              20:00:00:02:AC:00:08:F7                  unknown        Auto
0:1:2              20:00:00:02:AC:00:08:F8                  unknown        Auto
0:1:3              20:00:00:02:AC:00:08:F9                  unknown        Auto
0:1:4              20:00:00:02:AC:00:08:FA                  unknown        Auto
1:1:1              20:00:00:02:AC:00:08:FB                  unknown        Auto
1:1:2              20:00:00:02:AC:00:08:FC                  unknown        Auto
1:1:3              20:00:00:02:AC:00:08:FD                  unknown        Auto
1:1:4              20:00:00:02:AC:00:08:FE                  unknown        Auto
0:2:1              20:00:00:02:AC:00:08:FF                                 Auto
0:2:2              20:00:00:02:AC:00:09:00                  unknown        Auto
0:2:3              20:00:00:02:AC:00:09:01                  unknown        Auto
0:2:4              20:00:00:02:AC:00:09:02                  unknown        Auto
1:2:1              20:00:00:02:AC:00:09:03                                 Auto
1:2:2              20:00:00:02:AC:00:09:04                  unknown        Auto
1:2:3              20:00:00:02:AC:00:09:05                  unknown        Auto
1:2:4              20:00:00:02:AC:00:09:06                  unknown        Auto
0:3:1              20:00:00:02:AC:00:09:07                  unknown        Auto
0:3:2              20:00:00:02:AC:00:09:08                  unknown        Auto
0:3:3              20:00:00:02:AC:00:09:09                  unknown        Auto
0:3:4              20:00:00:02:AC:00:09:0A                  unknown        Auto
1:3:1              20:00:00:02:AC:00:09:0B                  unknown        Auto
1:3:2              20:00:00:02:AC:00:09:0C                  unknown        Auto
1:3:3              20:00:00:02:AC:00:09:0D                  unknown        Auto
1:3:4              20:00:00:02:AC:00:09:0E                  unknown        Auto
0:4:1              20:00:00:02:AC:00:09:0F                  unknown        Auto
0:4:2              20:00:00:02:AC:00:09:10                  unknown        Auto
0:4:3              20:00:00:02:AC:00:09:11                  unknown        Auto
0:4:4              20:00:00:02:AC:00:09:12                  unknown        Auto
1:4:1              20:00:00:02:AC:00:09:13                  unknown        Auto
1:4:2              20:00:00:02:AC:00:09:14                  unknown        Auto
1:4:3              20:00:00:02:AC:00:09:15                  unknown        Auto
1:4:4              20:00:00:02:AC:00:09:16                  unknown        Auto

The property 'portName' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19993 char:20
+ ...                    $_ManagedPort.portName           = $_port.portName
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The property 'portName' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19993 char:20
+ ...                    $_ManagedPort.portName           = $_port.portName
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'actualNetworkUri' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19994 char:20
+ ...             $_ManagedPort.actualNetworkUri   = $_port.actualNetworkUr ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The property 'actualNetworkUri' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19994 char:20
+ ...             $_ManagedPort.actualNetworkUri   = $_port.actualNetworkUr ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'portWwn' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19995 char:20
+ ...                     $_ManagedPort.portWwn            = $_port.portWwn
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The property 'portWwn' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19995 char:20
+ ...                     $_ManagedPort.portWwn            = $_port.portWwn
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'expectedNetworkUri' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19996 char:20
+ ...             $_ManagedPort.expectedNetworkUri = $_port.actualNetworkUr ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The property 'expectedNetworkUri' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19996 char:20
+ ...             $_ManagedPort.expectedNetworkUri = $_port.actualNetworkUr ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'groupName' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19997 char:20
+                             $_ManagedPort.groupName          = "Auto"
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The property 'groupName' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19997 char:20
+                             $_ManagedPort.groupName          = "Auto"
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'name' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19998 char:20
+ ...                        $_ManagedPort.name               = $_port.name
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The property 'name' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19998 char:20
+ ...                        $_ManagedPort.name               = $_port.name
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'portName' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19993 char:20
+ ...                    $_ManagedPort.portName           = $_port.portName
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The property 'portName' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19993 char:20
+ ...                    $_ManagedPort.portName           = $_port.portName
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'actualNetworkUri' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19994 char:20
+ ...             $_ManagedPort.actualNetworkUri   = $_port.actualNetworkUr ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The property 'actualNetworkUri' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19994 char:20
+ ...             $_ManagedPort.actualNetworkUri   = $_port.actualNetworkUr ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'portWwn' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19995 char:20
+ ...                     $_ManagedPort.portWwn            = $_port.portWwn
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The property 'portWwn' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19995 char:20
+ ...                     $_ManagedPort.portWwn            = $_port.portWwn
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'expectedNetworkUri' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19996 char:20
+ ...             $_ManagedPort.expectedNetworkUri = $_port.actualNetworkUr ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The property 'expectedNetworkUri' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19996 char:20
+ ...             $_ManagedPort.expectedNetworkUri = $_port.actualNetworkUr ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'groupName' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19997 char:20
+                             $_ManagedPort.groupName          = "Auto"
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The property 'groupName' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19997 char:20
+                             $_ManagedPort.groupName          = "Auto"
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'name' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19998 char:20
+ ...                        $_ManagedPort.name               = $_port.name
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
The property 'name' cannot be found on this object. Verify that the property exists and can be set.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:19998 char:20
+ ...                        $_ManagedPort.name               = $_port.name
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

PS C:\> TerminatingError(Send-HPOVRequest): "JSON cannot be parsed. The JSON in the request is invalid. There is an error on line 1 near column 15,822."
>> TerminatingError(Add-HPOVStorageSystem): "JSON cannot be parsed. The JSON in the request is invalid. There is an error on line 1 near column 15,822."
Add-HPOVStorageSystem : JSON cannot be parsed. The JSON in the request is invalid. There is an error on line 1 near 
column 15,822.
At line:1 char:1
+ Add-HPOVStorageSystem -hostname 172.18.11.12 -username dcs -password  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Add-HPOVStorageSystem], 
InvalidOperationException
    + FullyQualifiedErrorId : InvalidAuthOperation,Add-HPOVStorageSystem
Add-HPOVStorageSystem : JSON cannot be parsed. The JSON in the request is invalid. There is an error on line 1 near
column 15,822.
At line:1 char:1
+ Add-HPOVStorageSystem -hostname 172.18.11.12 -username dcs -password  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Add-HPOVStorageSystem], InvalidOperationExc
   eption
    + FullyQualifiedErrorId : InvalidAuthOperation,Add-HPOVStorageSystem

--------------------------------------

**Comment by ChrisLynchHPE** [comment]
This is fixed, and will be in the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in the [2.0.279.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.279.0) release.
