### ISSUE TITLE
NEW-HPOVSERVERPROFILE: Unable to attach ephemeral volume(s) to Server Profile

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#71]
When attempting to attach an ephemeral volume to a new server profile volume is not being created and as a result the profile creation fails.

**Comment by ChrisLynchHPE** [comment]
This is fixed and will be in the next 2.00 update.

**Comment by ChrisLynchHPE** [comment]
This is fixed in the [2.0.279.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.279.0) release.
