### ISSUE TITLE
New-HPOVUpLinkSet - Missing paramaters in v2.0

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#72]
In the 1.20 library, New-HPOVUpLinkSet has a parameter called -LigName
In the 2.0 library, New-HPOVUpLinkSet has a parameter called -Resource with alias defined as -li or -lig
but no -ligname

As a result, calling New-HPOVUplinkset will fail if -ligName is used

**Comment by ChrisLynchHPE** [comment]
This is by design.  The Cmdlet no longer supports names.  It only supports objects with the various `Get-HPOVLogicalInterconnect` or `Get-HPOVLogicalInterconnectGroup`.
