### ISSUE TITLE
New-HPOVUpLinkSet - Resource parameter accepts object only - POSH 2.0

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/POSH-HPOneView#73]
The parameter -Resource in New-HPOVUpLinkSet accepts only object as input. The documentation is a tad confusing when it says: "Logical Interconnect Group Name to create the Uplink set for. "
It should not be a name ( [string]) but object.
Please correct the documentation

**Comment by ChrisLynchHPE** [comment]
This is by design.  It is an unfortunate change, but a necessary one.  We do try to maintain as much backwards compatibility so as to not break scripts.  I will look at the docs and update accordingly.

**Comment by DungKHoang** [comment]
Understood
Pls update the doc accordingly and close this issue


On Wed, Feb 24, 2016 at 8:59 AM, Chris Lynch <notifications@github.com>
wrote:

> This is by design. It is an unfortunate change, but a necessary one. We do
> try to maintain as much backwards compatibility so as to not break scripts.
> I will look at the docs and update accordingly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HewlettPackard/POSH-HPOneView/issues/73#issuecomment-188352922>
> .
>



-- 
Dung K Hoang

**Comment by ChrisLynchHPE** [comment]
This is fixed, and documentation will be uploaded to the Wiki soon.
