### ISSUE TITLE
REST API connection issues

### ISSUE THREAD

**Issue by 5truja** [HewlettPackard/POSH-HPOneView#74]
Hi,

url am I using is https://fqdn_of_my_one_view
(on some places I've found that I am supposed to use https://fqdn/rest/login-sessions but I only got ceratin reply using https://fqdn/#/rest
Using Postman to connect to oneview 2 REST API. I have created the following custom headers:
Header
Authorisation, value: (the one that is generated when entering credentials)
X-API-Version, value 200
Content-Type application/json

When I connect and choose the JSON and get the following: Malformed JSON: Unexpected 

I have status OK (200)
If I check HTML format I see the following:
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta charset="utf-8" />
        <title>OneView</title>
        
        <meta name="description" content="" />
        <link rel="icon" type="image/png" href="img/hp-piano/hp-icon.png?v=d6e951b680012372221345a6f8fe1cede2bbd0fb" />
        <link href="css/compiled/hp-piano.css?v=d6e951b680012372221345a6f8fe1cede2bbd0fb" rel="stylesheet" data-resizable="true">
        
        <script>
    var hp = {"supportedLocales":[{"pattern":"^en([-_][a-zA-Z]{2}){0,2}$","lang":"en"},{"pattern":"^ja([-_][a-zA-Z]{2}){0,2}$","lang":"ja"},{"pattern":"^zh([-_][a-zA-Z]{2}){0,2}$","lang":"zh"}],"defaultLanguage":"en"};
        // configure require.js to send query parameter which each request
        // either a timestamp (for devs) or the version number for normal use
        // this allows for normal caching but fetches a new copy when the UI version changes
        var buildNumber = "d6e951b680012372221345a6f8fe1cede2bbd0fb";
        var require = {
                urlArgs: (buildNumber[0] === "$") ? "" : "v=" + buildNumber,
                waitSeconds: 0
            };
    </script>
        <script type="text/javascript" src="/branding/js/branding.js?v=d6e951b680012372221345a6f8fe1cede2bbd0fb"></script>
        <script type="text/javascript" data-main="js/cic/shell-require.js" src="js/lib/require.js"></script>
  
    </head>
    <body>
        <div class="hp-logo"></div>
        <div class="hp-spinner">
            <div class="hp-spinner-image"></div>
            <p data-localize="core.loading">Loading ...</p>
  
        </div>
    </body>
</html>

**Comment by ChrisLynchHPE** [comment]
What are you trying to do? And why are you not using the CMDLETs provided by the PowerShell library? URI’s that start with /#/ are specific to the UI, not for external callers. Have you not looked at the REST API Documentation?

**Comment by 5truja** [comment]
Sorry. I am newbie regarding REST API. I did check doc, not enough, I will try CMDLETs.

Med v?nlig h?lsning,
Mladen Brekalo


24 feb. 2016 kl. 17:57 skrev Chris Lynch <notifications@github.com<mailto:notifications@github.com>>:


What are you trying to do? And why are you not using the CMDLETs provided by the PowerShell library? URI's that start with /#/ are specific to the UI, not for external callers. Have you not looked at the REST API Documentation?

-

**Comment by ChrisLynchHPE** [comment]
It's quite alright.  We all start somewhere.

The PowerShell (and Python) library is available so customers and partners don't have to create their own REST API calls.  We've parameterized them for you.  Of course, if a feature is missing, then you can extend it yourself with a custom script, using the native `Send-HPOVRequest` Cmdlet.  To setup a connection, use the `Connect-HPOVMgmt` Cmdlet, which would take care of the Auth request you were trying to make above.

**Comment by 5truja** [comment]
Thanks Chris.

Med v?nlig h?lsning,
Mladen Brekalo


24 feb. 2016 kl. 18:05 skrev Chris Lynch <notifications@github.com<mailto:notifications@github.com>>:


It's quite alright. We all start somewhere.

The PowerShell (and Python) library is available so customers and partners don't have to create their own REST API calls. We've parameterized them for you. Of course, if a feature is missing, then you can extend it yourself with a custom script, using the native Send-HPOVRequest Cmdlet. To setup a connection, use the Connect-HPOVMgmt Cmdlet, which would take care of the Auth request you were trying to make above.

-

**Comment by ChrisLynchHPE** [comment]
Closing.
