### ISSUE TITLE
New-HPOVServerProfile Firmware Installation Method support

### ISSUE THREAD

**Issue by aricbernard** [HewlettPackard/POSH-HPOneView#76]
OV 2.0 supports 3 firmware installation methods:
Firmware and OS Drivers using HP Smart Update Tools
Firmware only using HP Smart Update Tools
Firmware only

The New-HPOVServerProfile (nor any other cmdlet) offers the ability to modify this configuration.

**Comment by ChrisLynchHPE** [comment]
This will be added in the 2.0.279.0 release.

**Comment by ChrisLynchHPE** [comment]
This is added in the [2.0.279.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.279.0) release.
