### ISSUE TITLE
INVOKE-HPOVVCMMIGRATION problem

### ISSUE THREAD

**Issue by FredBertramHPE** [HewlettPackard/POSH-HPOneView#77]
Diff attached
[MigrateFixDiff.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/149159/MigrateFixDiff.txt)

**Comment by ChrisLynchHPE** [comment]
This is fixed, and will be in the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.296.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.296.0)

**Comment by FredBertramHPE** [comment]
296 is mistakenly setting "type" to MigratableVcDomainV300. Invalid for 2.00 API.

**Comment by ChrisLynchHPE** [comment]
Woops.  You are right.  Will fix.
