### ISSUE TITLE
Adding existing network to existing UplinkSet fails

### ISSUE THREAD

**Issue by 5truja** [HewlettPackard/POSH-HPOneView#78]
Hi,
Trying to add an existing network to the existing UplinkSet but it fails.
Please find the script below and this is error message:
Exception calling "Add" with "1" argument(s): "Collection was of a fixed size."
At C:\Users\adm127856\Produkt\Add_CreatedNetwork_to_UplinkSet.ps1:12 char:1
+ ($Lig.uplinkSets | ? name -eq 'SUS-B').networkUris.Add($NewNetwork.uri)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException

I was using the following script (modified with other names for LIG, UplinkSet and Network:

#Get the LIG Resource
$Lig = Get-HPOVLogicalInterconnectGroup 'My LIG Policy' -ApplianceConnection $ApplianceConnection

#Display the 'Prod Uplink Set 1_A' Uplink Set resource
$Lig.uplinkSets | ? name -eq 'Prod Uplink Set 1_A'

#Get MyNewVLAN_A network resource
$NewNetwork = Get-HPOVNetwork 'MyNewVLAN_A' -ApplianceConnection $ApplianceConnection

#Add it to the 'Prod Uplink Set 1_A'
($Lig.uplinkSets | ? name -eq 'Prod Uplink Set 1_A').networkUris.Add($NewNetwork.uri)

#Save the object
$resp = Send-HPOVRequest $lig.uri PUT $lig -Hostname $ApplianceConnection

**Comment by ChrisLynchHPE** [comment]
There is a slight issue with the example I posted.  The `networkUris` is type `[System.Array]`, which is a fixed size object.  So, instead of `.Add($variable)`, the `+=` PowerShell operation is needed.  So the script should look like this:

```powershell
#Get the LIG Resource
 $Lig = Get-HPOVLogicalInterconnectGroup 'My LIG Policy' -ApplianceConnection $ApplianceConnection

#Display the 'Prod Uplink Set 1_A' Uplink Set resource
 $Lig.uplinkSets | ? name -eq 'Prod Uplink Set 1_A'

#Get MyNewVLAN_A network resource
 $NewNetwork = Get-HPOVNetwork 'MyNewVLAN_A' -ApplianceConnection $ApplianceConnection

#Add it to the 'Prod Uplink Set 1_A'
 ($Lig.uplinkSets | ? name -eq 'Prod Uplink Set 1_A').networkUris += $NewNetwork.uri

#Save the object
 $resp = Send-HPOVRequest $lig.uri PUT $lig -Hostname $ApplianceConnection
```

**Comment by 5truja** [comment]
Hi Chris,

That works.
Thank you.

Kind regards

**Comment by ChrisLynchHPE** [comment]
Closing.
