### ISSUE TITLE
New-HPOVUplinkSet -lacptimer option 

### ISSUE THREAD

**Issue by kpetsev** [HewlettPackard/POSH-HPOneView#79]
Hi there, Creating several new UplinkSet with option “-lacptimer Long” create the set but with "short" LacpTimer. Seems the "lacpTimer" option is not processed correctly by the Cmdlet.

**Comment by ChrisLynchHPE** [comment]
The `lacpTimer` resource property isn't being applied due to an oversight.  This will be fixed in the next release.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.296.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.296.0)
