### ISSUE TITLE
Get-HPOVlicense does not work when you specify type

### ISSUE THREAD

**Issue by SSvilen** [HewlettPackard/POSH-HPOneView#8]
The following error occurs:

Get-HPOVLIcense -Type OneView

Send-HPOVRequest : The product HP OneView is not found in appliance to complete the requested operation. 
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.120\HPOneView.120.psm1:20097 char:10
+         $ret = Send-HPOVRequest ($script:licensesUri + $filter + $disSummary) GET
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Send-HPOVRequest
 
You cannot call a method on a null-valued expression.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.120\HPOneView.120.psm1:20099 char:28
+         $ret.members | % { $_.psobject.typenames.Insert(0,”HPOneView.Appliance.L ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Write-Verbose : Cannot bind argument to parameter 'Message' because it is null.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.120\HPOneView.120.psm1:20103 char:17
+         Write-Verbose $ret
+                       ~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Verbose], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.WriteVerboseCommand

**Comment by ChrisLynchHP** [comment]
Thanks for reporting this issue.  We forgot to add the 'HP OneView Advanced' filter string to the API query.

**Comment by SSvilen** [comment]
Can you please include also HP OneView Advanced w/o iLO?

**Comment by ChrisLynchHP** [comment]
Both were fixed.

Sent from my Windows Phone
________________________________

**Comment by ChrisLynchHP** [comment]
This was fixed in Release 1.20.0050.0.
