### ISSUE TITLE
unable to import-module HPOneView.120

### ISSUE THREAD

**Issue by david-olshefski** [HewlettPackard/POSH-HPOneView#80]
I just downloaded & installed the HPE OneView 1.20 POSH library.  When I run it, I get this error:

Import-Module : The 'ModuleVersion' member is not valid in the module manifest
file 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.120\HPOneVie
w.120.psd1': Cannot convert value " " to type "System.Version". Error:
"Version string portion was too short or too long."
At line:1 char:1
+ & import-module HPOneView.120
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Windows\syst...neView.1
   20.psd1:String) [Import-Module], ArgumentException
    + FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Com
   mands.ImportModuleCommand

So the import fails...how can I fix this? I am running Windows 7 [as a VMware fusion VM].

**Comment by ChrisLynchHPE** [comment]
This is a bug with the module build process.  I fixed the problem and am building an updated version.  Will post in the next hour or so.

**Comment by david-olshefski** [comment]
Thanks, that's awesome.

**Comment by ChrisLynchHPE** [comment]
The fix has been committed.  You can download the [1.20.310.0 Release]{https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v1.20.310.0}.
