### ISSUE TITLE
Error for STP creation with the local storage definition.

### ISSUE THREAD

**Issue by kpetsev** [HewlettPackard/POSH-HPOneView#81]
**Library Version:**
HPOneView.200 v 2.0.296.0

**Issue:**
Can't create SPT  with defined local storage configuration.  

**Used Command:**

$OVDCS ='x.x.x.x'     
$enclosuregroup = Get-HPOVEnclosureGroup "Encl_Group_Prod_1" -ApplianceConnection $OVDCS
$bl460cGen9 = Get-HPOVServerHardwareTypes -name "BL460c Gen9 1" -ApplianceConnection $OVDCS               
$LogicalDrive =  New-HPOVServerProfileLogicalDisk -Name ‘LogicalVolume’ -RAID 'RAID1' -NumberofDrives '2' -DriveType 'Auto' -Bootable $True
                                $params = @{
                                                name               = "ESXi_Prod_Cluster_10"
                                                description        = "ESXi_Prod_Cluster_10"
                                                serverHardwareType = $bl460cGen9
                                                enclosureGroup     = $enclosuregroup
                                                Firmware                = $Fasle
                                                baseline           = "843216_001_spp_2015_10_0-SPP2015200_2015_0921_6.iso"
                                                FirmwareMode = 'FirmwareOffline'                                                        
                                                BootMode = 'UEFIOptimized'
                                                ManageBoot = $True
                                                BootOrder = 'HardDisk'                                  
                                                LocalStorage = $True
                                                Initialize = $True
                                                ControllerMode = 'RAID'
                                                LogicalDisk = $LogicalDrive   
                                                PxeBootPolicy = 'Auto'
                                }
New-HPOVServerProfileTemplate @params -ApplianceConnection $OVDCS -verbose

**Return error:**
_errorCode          : UNRECOGNIZED_JSON_FIELD
data               :
details            : The field named importConfiguration near line 1, column 563 is not a valid field in this JSON object.
errorSource        :
nestedErrors       : {}
recommendedActions : {Check the valid fields for this JSON object and remove or correct the unrecognized field.}
message            : Unrecognized JSON field._

**Comment by ChrisLynchHPE** [comment]
Thanks.  This will be fixed in the 2.0.300.0 release.

**Comment by ChrisLynchHPE** [comment]
Fixed in the [2.0.310.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.310.0) release.
