### ISSUE TITLE
lldp port syntax

### ISSUE THREAD

**Issue by 5truja** [HewlettPackard/POSH-HPOneView#82]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
I have one command that works and shows lldp information on vconnect side and uplink side - ciscso port:
(Get-HPOVInterconnect 'hbg-1s-enc3, interconnect 2’).ports | ? { $_.name -eq ‘X3’ } | FL

I use the same command to check antother port
(Get-HPOVInterconnect 'hbg-1s-enc3, interconnect 1’).ports | ? { $_.name -eq ‘X2’ } | FL

### Actual Behavior
I get error message when either modifying or saving new file:
At C:\Users\useronev\Produkt\checkPortsI1X2.ps1:1 char:23
+ (Get-HPOVInterconnect 'hbg-1s-enc3, interconnect 1â?T).ports | ? { $_.name -e
q â ...
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
The string is missing the terminator: '.
At C:\Users\useronev\Produkt\checkPortsI1X2.ps1:1 char:95
+ ... â?~X2â?T } | FL
+                    ~
Missing closing ')' in expression.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

### Steps to reproduce
I modify that information or cut'n'paste identical (select all) to another file and all of sudden that very same command does not work

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`):
HPE OneView Appliance Version:  
Output from `$PSVersionTable` on your Windows Host:

**Comment by 5truja** [comment]
Here is the file.
Kind regards
[checkPorts1x2.zip](https://github.com/HewlettPackard/POSH-HPOneView/files/179270/checkPorts1x2.zip)

**Comment by ChrisLynchHPE** [comment]
You have an illegal character in your syntax.  Somehow the ', or Single Quote, is a different character that is causing PowerShell to throw the error.  Please use the following in your script:

```PowerShell
(Get-HPOVInterconnect 'hbg-1s-enc3, interconnect 2').ports | ? name -eq 'X2' | FL
```

**Comment by 5truja** [comment]
Strange since I am using very same editor as for all other working scripts. I was using cut and paste in all previous cases but I’ve never got illegal characters since all other scripts were working.

**Comment by ChrisLynchHPE** [comment]
I'm closing this.  Please re-open or open a new issue if you are still experiencing problems.
