### ISSUE TITLE
INVOKE-HPOVVCMMIGRATION problems

### ISSUE THREAD

**Issue by FredBertramHPE** [HewlettPackard/POSH-HPOneView#89]
### Expected Behavior
Start migration from VCM domain to HPE OneView management

### Actual Behavior
fails with Send-HPOVRequest : Invalid JSON type. The "type" field content, "MigratableVcDomainV200", included in this request is invalid.

Should be using "migratable-vc-domains" for type when communicating with 2.00 interface.

After editing in order to use "migratable-vc-domains", reloading the module and reinvoking the command, it fails with 
Send-HPOVRequest : The "type" field is missing from the JSON. The "type" field was not included in the JSON input of this request, so the request is invalid
At C:\POSH-HPOneView-2.00-300\POSH-HPOneView-2.00\HPOneView.200.psm1:17884 char:32
+                 $migrateTask = Send-HPOVRequest -method PUT -uri $vcMigrationRep ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationException
    + FullyQualifiedErrorId : InvalidAuthOperation,Send-HPOVRequest

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.300.0
HPE OneView Appliance Version:  2.00
Output from `$PSVersionTable` on your Windows Host:
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by ChrisLynchHPE** [comment]
Fixed in the [2.0.310.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.310.0) release.
