### ISSUE TITLE
New-HPOVServerProfileTemplate generating The requested HTTP method is not valid/supported

### ISSUE THREAD

**Issue by tknightblc** [HewlettPackard/POSH-HPOneView#90]
Using new library all of my HPOVServerProfileTemplate are generating The requested HTTP method is not valid/supported, worked with last library

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> Get-HPOVVersion
$PSVersionTable

PowerShell Library Version : 2.0.310.0
Library Path               : C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200

Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : BuildVersion
Value : 6.3.9600.16406

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> 
PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $bl460SHT

Name          Model                Form Factor Adapters                                        
----          -----                ----------- --------                                        
BL460c Gen9 1 ProLiant BL460c Gen9 HalfHeight  Flb 1 - HP FlexFabric 10Gb 2-port 536FLB Adapter

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $eg

Name          Logical Interconnect Group Used By
----          -------------------------- -------
ESX-Enclosure ESX-LIG                    Encl1  

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $conListA

id                  : 1
functionType        : Ethernet
name                : 
portId              : Auto
networkUri          : /rest/ethernet-networks/341d18c4-fb07-43ac-a46d-cfd0ff7fe1af
requestedMbps       : 1000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 2
functionType        : Ethernet
name                : 
portId              : Auto
networkUri          : /rest/ethernet-networks/229adda7-cedc-4c74-ab5d-03152be01a40
requestedMbps       : 1000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 3
functionType        : FibreChannel
name                : 
portId              : Auto
networkUri          : /rest/fc-networks/12e0d358-e587-4d5a-ab81-da5cec33a950
requestedMbps       : 4000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 4
functionType        : FibreChannel
name                : 
portId              : Auto
networkUri          : /rest/fc-networks/133e89d2-4a37-4144-b55d-cfa054227c53
requestedMbps       : 4000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 5
functionType        : Ethernet
name                : 
portId              : Auto
networkUri          : /rest/network-sets/3318e854-804f-4d2a-bd6b-c94a43885f3c
requestedMbps       : 3000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 6
functionType        : Ethernet
name                : 
portId              : Auto
networkUri          : /rest/network-sets/b6d7c640-6e88-4968-a975-2a6dd3572974
requestedMbps       : 3000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 7
functionType        : Ethernet
name                : 
portId              : Auto
networkUri          : /rest/ethernet-networks/719a645c-6331-4c9f-9240-ada5f0007b44
requestedMbps       : 2000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

id                  : 8
functionType        : Ethernet
name                : 
portId              : Auto
networkUri          : /rest/ethernet-networks/43234b10-4ade-439a-bad4-91aa60c8b5f3
requestedMbps       : 2000
boot                : @{priority=NotBootable; targets=System.Collections.ArrayList}
macType             : Virtual
mac                 : 
wwpnType            : Virtual
wwnn                : 
wwpn                : 
ApplianceConnection : @{Name=tk1-ov200-dcsdemo.advizex.net; ConnectionId=1}

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $Gen9BiosSettings

Name  : id
Value : PowerProfile

Name  : value
Value : MaxPerf

Name  : id
Value : AdminName

Name  : value
Value : Thomas Knight

Name  : id
Value : AdminPhone

Name  : value
Value : 585-451-6254

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> New-HPOVServerProfileTemplate -name "test11" -description "Template for ESX host-BL460 Gen9 with no SAN storage definitions" -firmware -baseline "HP Service Pack for ProLiant" -serverHardwareType $bl460SHT -enclosureGroup $eg -connections $conListA  –manageBoot -pxeBootPolicy Auto -bios -biossettings $Gen9BiosSettings -ApplianceConnection $Connection1 | Wait-HPOVTaskComplete

New-HPOVServerProfileTemplate : [Send-HPOVRequest]: The requested HTTP method is not valid/supported.  The request method POST is not supported or not applicable for the requested resource. URI: 
/rest/server-profiles/available-networks?serverHardwareTypeUri=/rest/server-hardware-types/FB3061E8-5DC3-4C32-9961-8C6EEC56786C&enclosureGroupUri=/rest/enclosure-groups/78dec4f7-c6c2-4def-a612-2c7891ed6a45
At line:1 char:1
+ New-HPOVServerProfileTemplate -name "test11" -description "Template for ESX host ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (POST:/rest/serv...12-2c7891ed6a45:String) [New-HPOVServerProfileTemplate], InvalidOperationException
    + FullyQualifiedErrorId : HTTP_METHOD_NOT_ALLOWED,New-HPOVServerProfileTemplate
 

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> 

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $error | % { Format-List -InputObject $_ * } 

PSMessageDetails      : 
Exception             : System.InvalidOperationException: [Send-HPOVRequest]: The requested HTTP method is not valid/supported.  The request method POST is not supported or not applicable for the requested 
                        resource. URI: /rest/server-profiles/available-networks?serverHardwareTypeUri=/rest/server-hardware-types/FB3061E8-5DC3-4C32-9961-8C6EEC56786C&enclosureGroupUri=/rest/enclosure-groups/78dec
                        4f7-c6c2-4def-a612-2c7891ed6a45
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : POST:/rest/server-profiles/available-networks?serverHardwareTypeUri=/rest/server-hardware-types/FB3061E8-5DC3-4C32-9961-8C6EEC56786C&enclosureGroupUri=/rest/enclosure-groups/78dec4f7-c6c2-4
                        def-a612-2c7891ed6a45
CategoryInfo          : InvalidOperation: (POST:/rest/serv...12-2c7891ed6a45:String) [], InvalidOperationException
FullyQualifiedErrorId : HTTP_METHOD_NOT_ALLOWED
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5564
                        at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (405) Method Not Allowed." ---> 
                        System.Net.WebException: The remote server returned an error: (405) Method Not Allowed.
                           at System.Net.HttpWebRequest.GetResponse()
                           at CallSite.Target(Closure , CallSite , HttpWebRequest )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : WebException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5085
                        at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.InvalidOperationException: [Send-HPOVRequest]: The requested HTTP method is not valid/supported.  The request method POST is not supported or not applicable for the requested 
                        resource. URI: /rest/server-profiles/available-networks?serverHardwareTypeUri=/rest/server-hardware-types/FB3061E8-5DC3-4C32-9961-8C6EEC56786C&enclosureGroupUri=/rest/enclosure-groups/78dec
                        4f7-c6c2-4def-a612-2c7891ed6a45
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : POST:/rest/server-profiles/available-networks?serverHardwareTypeUri=/rest/server-hardware-types/FB3061E8-5DC3-4C32-9961-8C6EEC56786C&enclosureGroupUri=/rest/enclosure-groups/78dec4f7-c6c2-4
                        def-a612-2c7891ed6a45
CategoryInfo          : InvalidOperation: (POST:/rest/serv...12-2c7891ed6a45:String) [], InvalidOperationException
FullyQualifiedErrorId : HTTP_METHOD_NOT_ALLOWED
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5564
                        at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (405) Method Not Allowed." ---> 
                        System.Net.WebException: The remote server returned an error: (405) Method Not Allowed.
                           at System.Net.HttpWebRequest.GetResponse()
                           at CallSite.Target(Closure , CallSite , HttpWebRequest )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : WebException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5085
                        at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.InvalidOperationException: [Send-HPOVRequest]: The requested HTTP method is not valid/supported.  The request method POST is not supported or not applicable for the requested 
                        resource. URI: /rest/server-profiles/available-networks?serverHardwareTypeUri=/rest/server-hardware-types/FB3061E8-5DC3-4C32-9961-8C6EEC56786C&enclosureGroupUri=/rest/enclosure-groups/78dec
                        4f7-c6c2-4def-a612-2c7891ed6a45
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : POST:/rest/server-profiles/available-networks?serverHardwareTypeUri=/rest/server-hardware-types/FB3061E8-5DC3-4C32-9961-8C6EEC56786C&enclosureGroupUri=/rest/enclosure-groups/78dec4f7-c6c2-4
                        def-a612-2c7891ed6a45
CategoryInfo          : InvalidOperation: (POST:/rest/serv...12-2c7891ed6a45:String) [], InvalidOperationException
FullyQualifiedErrorId : HTTP_METHOD_NOT_ALLOWED
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5564
                        at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (405) Method Not Allowed." ---> 
                        System.Net.WebException: The remote server returned an error: (405) Method Not Allowed.
                           at System.Net.HttpWebRequest.GetResponse()
                           at CallSite.Target(Closure , CallSite , HttpWebRequest )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : WebException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5085
                        at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.InvalidOperationException: [Send-HPOVRequest]: The requested HTTP method is not valid/supported.  The request method POST is not supported or not applicable for the requested 
                        resource. URI: /rest/server-profiles/available-networks?serverHardwareTypeUri=/rest/server-hardware-types/FB3061E8-5DC3-4C32-9961-8C6EEC56786C&enclosureGroupUri=/rest/enclosure-groups/78dec
                        4f7-c6c2-4def-a612-2c7891ed6a45
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : POST:/rest/server-profiles/available-networks?serverHardwareTypeUri=/rest/server-hardware-types/FB3061E8-5DC3-4C32-9961-8C6EEC56786C&enclosureGroupUri=/rest/enclosure-groups/78dec4f7-c6c2-4
                        def-a612-2c7891ed6a45
CategoryInfo          : InvalidOperation: (POST:/rest/serv...12-2c7891ed6a45:String) [], InvalidOperationException
FullyQualifiedErrorId : HTTP_METHOD_NOT_ALLOWED
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5564
                        at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (405) Method Not Allowed." ---> 
                        System.Net.WebException: The remote server returned an error: (405) Method Not Allowed.
                           at System.Net.HttpWebRequest.GetResponse()
                           at CallSite.Target(Closure , CallSite , HttpWebRequest )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : WebException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5085
                        at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $error | % { $_.ScriptStackTrace } 
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5564
at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
at <ScriptBlock>, <No file>: line 1
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5085
at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
at <ScriptBlock>, <No file>: line 1
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5564
at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
at <ScriptBlock>, <No file>: line 1
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5085
at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
at <ScriptBlock>, <No file>: line 1
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5564
at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
at <ScriptBlock>, <No file>: line 1
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5085
at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
at <ScriptBlock>, <No file>: line 1
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5564
at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
at <ScriptBlock>, <No file>: line 1
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 5085
at New-HPOVServerProfileTemplate<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 41477
at <ScriptBlock>, <No file>: line 1

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy>

**Comment by ChrisLynchHPE** [comment]
Sorry about that.  I found the issue, which was a re-use of an existing variable that was getting set to a different value for when the Template would be created.  The same issue exists in the `New-HPOVServerProfile` Cmdlet.  I have both fixed and will upload a quick, minor release to address this particular bug.

**Comment by tknightblc** [comment]
Thanks Chris!

**Comment by ChrisLynchHPE** [comment]
Fixed in [Release 2.0.312.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.312.0)
